### PR TITLE
build: correct paths in setup

### PR DESCRIPTION
**Pull request by imsodin**

### CODE REVIEW

**Comment by calmh** [comment]
@st-review rebuild

**Comment by calmh** [comment]
@st-review merge

build: Correct import paths for vet tools

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 694a7de59d75000a1a70250be6c054f809ba2b49. Thanks, @imsodin!

**Pull request closed without merging**
