### PR TITLE
gui: panel identicons

### PR DESCRIPTION
**Pull request by norgeous**
before:
untitled

after:
untitled

if you accept my last PR (looks like you have...) then I may need to adjust the notice on the dark theme to be 'readable' also.

sorry for random commits

### CODE REVIEW

**Comment by calmh** [comment]
Is nice. Should of course follow the "new" color scheme here on the dark scheme yes

**Comment by norgeous** [comment]
ill have a coffee then fix it

**Comment by calmh** [comment]
You're certainly keeping the builders busy :)

screen shot 2016-06-02 at 22 16 47

**Comment by calmh** [comment]
You've managed to pull in an alternate version of Majed's commit in your branch as well. Not sure how you did that :)

**Comment by norgeous** [comment]
i'm sorry for all the git noobishness, I am trying to learn...

**Comment by norgeous** [comment]
all fixed, see OP

**Comment by norgeous** [comment]
ill try again with a new PR and try to get it perfect.

**Comment by calmh** [comment]
You still have the stray commit in the middle. I'm guessing st-review will sort that out as it should be a no-op, but I'm also suspicious about it appearing in the diff at all. I suggest:

```
git checkout master
git pull syncthing
git checkout moreidenticons
git rebase master
git push --force
```

should take care of it, most likely.

**Comment by calmh** [comment]
Ah, ok :)

**Pull request closed without merging**
