### PR TITLE
Change 2014->2015

### PR DESCRIPTION
**Pull request by jpjp**
External libraries might need an update too.

### CODE REVIEW

**Comment by calmh** [comment]
Actually I think this should stay as `2014`, or possibly become `2014-2015`. http://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by cebe** [comment]
leaving it as 2014 is just fine, else you will need to remember to update it each year and as far as I understood from the stackoverflow answers it is kind of unclear what 2014-2015 actually means when I read it in e.g. 2017. you still have the copyright even if you have limited it to 2015 there. so it does not really make sense to add it.

**Comment by jpjp** [comment]
2014-2015: sounds good. wb btw :)

leaving it as 2014? then wouldn't it make sense to remove the year instead?

**Comment by plsng** [comment]
The Berne convention makes the copyright statement almost unnecessary anyway.

**Comment by calmh** [comment]
So I'll just unilaterally decide that ranges are unnecessary and the year should reflect the creation of the file. That seems to be compatible with any relevant laws and minimizes the upkeep required.

**Pull request closed without merging**
