### PR TITLE
fixed go get command for strelaysrv

### PR DESCRIPTION
**Pull request by Aranjedeath**
### Purpose

Small documentation fix.

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it please

cmd/strelaysrv: Correct go get command in README

Skip-check: authors, pr-build

**Comment by st-review** [comment]
@calmh: Build status is `failure` -- refusing to merge.

**Comment by st-review** [comment]
@calmh: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
@st-jenkins test this please

**Comment by calmh** [comment]
@st-review merge it please

cmd/strelaysrv: Correct go get command in README

Skip-check: authors

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@calmh: There's already a merge pending for this PR.

**Comment by calmh** [comment]
Bots are trolling me tonight...

**Comment by st-review** [comment]
:ok_hand: Merged as 7569b75d61cb7a1f964f09aafa1c87d86554f377. Thanks, @Aranjedeath!

**Comment by calmh** [comment]
Thanks for the fix!

**Pull request closed without merging**
