### PR TITLE
cmd/syncthing: Expand usage stats even more (ref #3628)

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Also add diffing functionality

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Don't merge yet

**Comment by AudriusButkevicius** [comment]
Now it's good to merge.

@imsodin wants to add usage stats for fs watcher, so I guess we should get his stuff merged before making an rc or a release.

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 059185b32569aaec3f95d4fe5bab829f8df1104e. Thanks, @AudriusButkevicius!

**Comment by calmh** [comment]
If the fs notifier thing is close to merging I'm willing to break the rc process a little bit - we can release several RCs while iterating. Tweaking the usage reporting between two RCs is fine as it's always on an never asked about (don't remember if we verified that's still the case with the usage reporting upgrades, I remember mentioning it).

**Comment by AudriusButkevicius** [comment]
The only problem with reiterating is the migration on ur reporting server can only be done once.

**Pull request closed without merging**
