### PR TITLE
[wip] For discussion, test of golang.org/x/net/trace

### PR DESCRIPTION
**Pull request by calmh**
Tried this on for size as it seems a little bit neat. Basically it's an always-on trace thing, accessible over the regular HTTP server. This could replace the current STTRACE system, giving us better user friendlyness (maybe the information is still unintelligible, but at least it's accessible without messing with env vars) and some other features (stats on how often things are called and how long they take). On the down side there's no easy way to capture a complete log of what's happened with this thing, so we may get reduced to screenshots... Which sucks... Unless we can figure something out. Maybe we can expose the full log as a txt on a URL for example.

screen shot 2015-09-22 at 16 07 51

screen shot 2015-09-22 at 16 08 12

(/debug/events and /debug/requests)

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Sorry, some background in what this is and what it does?

**Comment by calmh** [comment]
I thought I had that in the first few sentences :)

It's a package for debug tracing. You create trace "events" for short lived things (such as scanning a folder) and get the log output for those under /debug/requests (it's geared towards HTTP servers, hence the terminology) together with data on how many such per second, histogram over their duration and whether they reported an error or not. There's an example of the logs in the first screenshot, showing three calls to scanner.Walk.

Then there's "event logs" for longer lived things (such as permanently running services). These show up with their log into under /debug/events.

So in effect, it's like running with `STTRACE=all` and having the info always available over HTTP, limited by only seeing the last *x* events and *x* log entries. I think it's kind of neat to have it always available, but I'm not sure if that's enough to compensate for not having the full log of everything instantly available.

I don't know the performance impact of running with it always on; I'd expect some of the heavier things we have (`STTRACE=protocol` for example) may not be suitable for this.

**Comment by calmh** [comment]
Another advantage is being able to directly dig out just the traces for what you're interested in, like beacon.Broadcast in the example above. But it's nothing a grep couldn't do anyway.

**Comment by AudriusButkevicius** [comment]
Yeah but the problem is that you'd have to go through the code add annotations for this to work, which is a fair bit of work.  Places where we mostly have issues (scanner/model) should probably take priority, but the question is, can we actually get anything useful out of this, as well as, what sort of performance/memory footprint does this have?

**Comment by calmh** [comment]
I was thinking of doing a straight up swap of all `l.Debugln` stuff to this, if it seems like it has advantages. But I'm not sure. :)

**Comment by AudriusButkevicius** [comment]
Well, what sort of history does it preservd?

**Comment by dcarosone** [comment]
If syncthing crashes, does it take the logs with it?

**Comment by AudriusButkevicius** [comment]
Why? Perhaps it's not a bad idea afterall, but as a supplement rather than a replacement

**Comment by calmh** [comment]
I think my other trace stuff gets close to the point I wanted to reach with this, without the disadvantages and while being more transparent about how it works. That can probably be extended to do whatever this did that we still want.

**Pull request closed without merging**
