### PR TITLE
lib/model: Add minumum interval for progress emitter (fixes #3517)

### LINKED ISSUE #3517: lib/model: Progress emitter runs way too often
Every few microseconds:

```
[SYNO4] 2016/08/16 19:40:35.303094 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303101 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303126 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303140 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303164 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303173 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303191 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303200 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303220 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303229 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303255 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303263 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303289 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303297 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303319 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303328 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303346 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303353 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303374 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303383 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303403 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303412 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303432 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303437 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303453 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303459 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303473 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303481 sharedpullerstate.go:261: DEBUG: sharedPullerState ysmva-c3fqq foo pullNeeded done -> 0
[SYNO4] 2016/08/16 19:40:35.303506 progressemitter.go:103: DEBUG: progress emitter: emitting map[string]map[string]*model.pullerProgress{"ysmva-c3fqq":map[string]*model.pullerProgress{"foo":(*model.pullerProgress)(0xc82044f600)}}
[SYNO4] 2016/08/16 19:40:35.303548 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303603 rwfolder.go:1326: DEBUG: rwFolder/ysmva-c3fqq@0xc8200a4f00 closing foo
[SYNO4] 2016/08/16 19:40:35.303684 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303707 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303716 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303777 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303784 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303863 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303872 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303888 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303895 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303911 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303920 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303936 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303944 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303959 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303967 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.303986 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.303993 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.304010 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.304017 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.304039 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 1
[SYNO4] 2016/08/16 19:40:35.304051 progressemitter.go:82: DEBUG: progress emitter: nothing new
[SYNO4] 2016/08/16 19:40:35.304062 progressemitter.go:221: DEBUG: progress emitter: deregistering ysmva-c3fqq foo
[SYNO4] 2016/08/16 19:40:35.304077 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 0
[SYNO4] 2016/08/16 19:40:35.304089 progressemitter.go:103: DEBUG: progress emitter: emitting map[string]map[string]*model.pullerProgress{}
```

I have this in my config, for a reason I don't know:

`<progressUpdateIntervalS>0</progressUpdateIntervalS>`

Possibly a migration gone wrong somewhere along the way, since this is my production config that's been live since like v0.10 or something. Nonetheless, we should set a lower bound and handle this better.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
As per subject.

### CODE REVIEW

**Comment by calmh** [comment]
Hah. I had a literally byte for byte identical diff that I was just going to open a pull request for, with the same commit message, and had a moment that I though I had lost my mind when I saw your updates on the "feed"...

**Comment by calmh** [comment]
@st-review merge the shit out of this one

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 6ec4fbc82bae3fd0c70253fd6805c9ef3ef2a119. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
