### PR TITLE
Add systemd files to the deb package

### PR DESCRIPTION
**Pull request by hadogenes**
Systemd services in debian folders:
`/lib/systemd/system` - [Debian Wiki](https://wiki.debian.org/systemd/Packaging#systemd_unit_files_naming_and_installation)
`/usr/lib/systemd/user` - not defined special path for debian, so [Freedesktop](http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20Load%20Path))
Ref #1807 and #1821

### CODE REVIEW

**Comment by calmh** [comment]
Is this different from #1821?

**Comment by hadogenes** [comment]
in this pr system instance is in `/lib/systemd/system/syncthing@.service` (debian path),
but the #1821 is in `/usr/lib/systemd/system/syncthing@.service` (freedektop path)

**Comment by calmh** [comment]
Okay. So 1821 is just plain wrong for Debian?

**Comment by hadogenes** [comment]
yes, there isn't `/usr/lib/systemd/system` on debian

**Comment by calmh** [comment]
Ok, closed. So asking for opinions in this one as well. If we ship stuff for systemd, we should ship stuff for every other init system in use on a Debian system. Do we want to do that? Or do something else?

**Comment by hadogenes** [comment]
Debian now (from Jessie - current stable) by default use systemd, I don't think many people will change to some other init system.
I don't think there should be other init script, because other init systems can run only one syncthing instance per system (systemd can run syncthing per user).

**Comment by calmh** [comment]
Well, I have 25 or so Ubuntu systems running, none of which use systemd... :p

**Comment by hadogenes** [comment]
How do you run by init script 25 syncthing instance, by some loop?
Ubuntu declared that will go to systemd (I thing from 15.04)

**Comment by wweich** [comment]
Yes, in a loop.
Does systemd start the user instances on system start or on user login?
I use multiple instances on my server which all should be started on system startup without user login.
The current LTS versions from Ubuntu (12.04 + 14.04) are still using upstart (I think).
So for the next years, Ubuntu will still need other init script than systemd.

**Comment by calmh** [comment]
My point is just that there are multiple valid init systems we should support. Personally I use runit where I run syncthing on those boxes, to start it as whatever user needed, on boot. But that's besides the point. Do I want systemd files installed on my 14.04 boxes? Maybe it doesn't hurt. Do you want upstart stuff on your 15.04?

**Comment by hadogenes** [comment]
@wweich On systemd you could start syncthing@<UID>.service on system start or via loginctl enable-linger <username> start whole systemd user instance ([Arch Wiki](https://wiki.archlinux.org/index.php/Systemd/User#Automatic_start-up_of_systemd_user_instances)).
@calmh I'm not sure if some /etc/init.d script should start multiple instances of some program, but if yes I could write one for debian

**Comment by rumpelsepp** [comment]
@wweich See my comment here as well: https://forum.syncthing.net/t/starting-syncthing-from-systemd-take-2/2849/7?u=rumpelsepp

**Comment by hadogenes** [comment]
Fortunately the deb packages are used only on debian (or derivatives such as Ubuntu), so we can use debian path in deb.

**Comment by rumpelsepp** [comment]
Oh, sorry. You are right with the paths. I just wanted to point to my explanation of the `start syncthing@<UID>.service` thing from your previous post. :)

**Comment by frankthetank7254** [comment]
I may not understand all of this, but from my point of view, It makes sense to include the systemd files in the package. Yes there are many other init systems, and it might not make sense to support all of them, but when the latest Debian and Ubuntu are using systemd by default, it is weird to not include the files.

**Comment by calmh** [comment]
Merged in a11aa29

**Pull request closed without merging**
