### PR TITLE
Add Grey Theme

### PR DESCRIPTION
**Pull request by fti7**
### Purpose
Adding an Grey Theme to the Syncthing GUI
Its based on "Dark Theme" but the elements are brighter/grey

### Screenshots
st1

### CODE REVIEW

**Comment by calmh** [comment]
Is this really different enough from the dark theme that we want to maintain both into the eternity? Should this in fact supersede the dark theme?

screen shot 2016-09-17 at 22 29 28

**Comment by fti7** [comment]
I dont know how many users are using the Dark Theme (Maybe something for the Usage Report ;-)) )
But you are right, the colors are just slightly different.

But i have the same issues... its garishly black and i switched back to the Default Theme every time i tried the Dark one :-(
Different people have different preferences...

Except of one Change at the borders, there are only Color Replacements. So Maintenance should be possible without much hassle as long there are no bigger Changes on the Layout.

**Comment by hdcool** [comment]
I really dig the idea of getting rid of the dark theme and replacing it with this.

**Comment by xor-gate** [comment]
I am using the dark theme, but as you mention it is "really" dark. A more lighter alternative would be nice. Probably most people who switch between bright and dark would not be bothered to have a more "brighter dark"/gray theme (as I speak for myself). Maintaining two dark-ish themes should not be necessary.

**Comment by fti7** [comment]
@calmh done. I dont know why the authors check failed this time

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
It's a Github special annoyance... The test checks the merge of your PR and `master`, and Github synthesises that merge commit, and then it uses your noreply-address which isn't in the system. Never mind.

**Comment by calmh** [comment]
@st-review merge it please

gui: Slightly lighten the dark theme

Skip-check: authors

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 6fe2fa5ff054efc0ac49a3145cd5643f91ba46ca. Thanks, @fti7!

**Comment by camsteffen** [comment]
I think we lightened things a little too much. The text doesn't contrast enough, especially the blue or purple text on light grey. Is it just me?

**Comment by fti7** [comment]
Same here, at least for the Disconnected "Purple" stuff.
I will check that this weekend and do a slight color adjustment

**Comment by fti7** [comment]
Ok, now with a little bit more brightness for the "Disconnected" and "Scanning" State
At least with my Monitor Settings its a nice Contrast now

discon
scan

**Comment by fti7** [comment]
@AudriusButkevicius could you please merge this change? Or should i better create a new PR?

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Patiently waited 30m0s for the build status to turn green, but enough is enough.

**Comment by calmh** [comment]
@st-jenkins add to white list

**Comment by calmh** [comment]
Systems are confused by this PR. I merged it manually, thanks @fti7.

**Pull request closed without merging**
