### PR TITLE
lib/fs: Unflake watch tests (fixes #4687)

### LINKED ISSUE #4687: basicfs_watch_tests are flaky
Hello!

I am getting failing builds on mips64el for 0.14.43.

```
--- FAIL: TestWatchIgnore (2.50s)
	basicfs_watch_test.go:231: Timed out before receiving all expected events
=== RUN   TestWatchRename
--- FAIL: TestWatchRename (2.50s)
	basicfs_watch_test.go:231: Timed out before receiving all expected events
=== RUN   TestWatchOutside
--- PASS: TestWatchOutside (0.00s)
=== RUN   TestWatchSubpath
--- PASS: TestWatchSubpath (0.00s)
=== RUN   TestWatchOverflow
--- FAIL: TestWatchOverflow (2.50s)
	basicfs_watch_test.go:231: Timed out before receiving all expected events
```

Any idea what might cause this? Are they time-based tests?

Maybe they should be a little bit more forgiving?

Debian builds syncthing and runs tests on all kind of architectures, and our machines sometimes have heavy load.

[Full log](https://buildd.debian.org/status/fetch.php?pkg=syncthing&arch=mips64el&ver=0.14.43%2Bds1-1&stamp=1516323710&raw=0) (link may die, sorry)

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This removes a number of timing related things, leaving just the total test timeout now bumped to one minute. Normally we get the filesystem events within a second or so, so this doesn't affect the test time in the successfull case. If we don't actually get the events we expect within a minute I think we are legitimately in "failed" territory.

### Testing

I've run this in a loop on the Mac builder (which often fails with the code in `master`) and it's been fine for a few minutes. Leaving it up to the build server to see if this passes on linux etc...

### CODE REVIEW

**Comment by calmh** [comment]
I've rerun it on the Windows & Linux builders a couple of times and it doesn't seem more broken than before at least.

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 0fe3ae7c227686ac209cffb3622ff7d4ed8543ab. Thanks, @calmh!

**Pull request closed without merging**
