### PR TITLE
gui: change protocol from http to https for some links

### PR DESCRIPTION
**Pull request by norgeous**
change http://docs.syncthing.net/ to https://docs.syncthing.net/

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge this please

gui: Docs links should be HTTPS

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2876/head:pr-2876
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at 95247f7 cmd/syncthing: Basic smoke test of all API endpoints
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 95247f7 cmd/syncthing: Basic smoke test of all API endpoints
$ git clean -fxd
$ git merge --squash --no-commit pr-2876
Updating 95247f7..ca79f37
Fast-forward
Squash commit -- not updating HEAD
 gui/default/index.html | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
$ git commit -F -
GUI files changed; recompiling assets
.git/hooks/pre-commit: line 6: go: command not found

```

**Comment by calmh** [comment]
@st-review merge this please

gui: Docs links should be HTTPS

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2876/head:pr-2876
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at 95247f7 cmd/syncthing: Basic smoke test of all API endpoints
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 95247f7 cmd/syncthing: Basic smoke test of all API endpoints
$ git clean -fxd
$ git merge --squash --no-commit pr-2876
Updating 95247f7..ca79f37
Fast-forward
Squash commit -- not updating HEAD
 gui/default/index.html | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
$ git commit -F -
GUI files changed; recompiling assets
GOPATH is /
go run script/genassets.go gui > lib/auto/gui.files.go
[master 3da4c16] gui: Docs links should be HTTPS
 Author: norgeous <daniel@harte.me>
 2 files changed, 3 insertions(+), 3 deletions(-)
$ git rev-parse HEAD
3da4c162b6b56ab2a957ab98409071065ec7233a
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 4 of 4 required status checks are expected        
To git@github.com:syncthing/syncthing.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:syncthing/syncthing.git'

```

**Comment by calmh** [comment]
Trololol sorry about this. I'll mend the bot.

**Comment by calmh** [comment]
@st-review merge this please

gui: Docs links should be HTTPS

**Comment by st-review** [comment]
OK, merged as bc508aee7b8742ee596f1e909f69930eca58b55c. Thanks, @norgeous!

**Comment by calmh** [comment]
Thanks @norgeous :)

**Pull request closed without merging**
