### PR TITLE
gui: Circular progress bars

### PR DESCRIPTION
**Pull request by norgeous**
It's just for scanning folders right now, but functional.
I will implement for syncing and remote devices, if liked.

current proposal:
untitled
untitled

depreciated:
untitled

### CODE REVIEW

**Comment by calmh** [comment]
This does not immediately strike me as an improvement. Actual bars are easier to read at a glance?

**Comment by AudriusButkevicius** [comment]
I personally prefer the old ones.

**Comment by norgeous** [comment]
> Actual bars are easier to read at a glance?

The current progress bars are very non-standard in terms of design. The very first time I used Syncthing, I found the progress bars confusing because of where they are placed. After a while of using the application I became used to them... I would imagine most people also find them initially confusing.

The circular bar I present here is a draft and could indeed do with some fine tuning; colour adjustment, line thickness, etc. Hopefully this could make it more appealing.

I have used it for a couple of scans now and would argue it is as readable, if not more so because of the similarity to an analogue clock (again thinking of new users).

**Comment by AudriusButkevicius** [comment]
It's personally easier for me to understand progress when looking at a line and comparing progress width  relative to line length, versus a circle and counting the quarters etc, as the area in which the proportions are displayed is much more dense. 

Yeah agree, the line bar is a bit unusual, but perhaps we should try to improve that?

@norgeous, given you've made multiple useful contributions and seem to be keen on helping, I just wanted to check if you've seen the now stalled pull request/new UI mocks by @gillisig. I think everyone agrees that work on the current web UI is somewhat beating a dead horse, as it was made by UI/UX  incapable individuals and in general is not the most though through thing.

If you are feeling adventurous and have too much time on your hands, you could potentially pick up where he left off, or get inspired by it. There is also a bounty attached to the ticket (which sadly isn't much) and in return I could promise some reasonable non-UI (or little UI) feature/bugfix you are lacking in Syncthing.

**Comment by calmh** [comment]
> it was made by UI/UX incapable individuals

Hey! I resemble that remark :(

**Comment by AudriusButkevicius** [comment]
I tried using that elsewhere, and the lack of UI elements and having to invent your own is over 9000

**Comment by calmh** [comment]
OK, good to know :)

**Comment by norgeous** [comment]
> multiple useful contributions

I'm glad you merged some!

> I just wanted to check if you've seen the now stalled pull request/new UI mocks by @gillisig.
> you could potentially pick up where he left off, or get inspired by it.

Yes, I have seen this and some other one also (on the forum maybe?). The problem for me is that I'm really only contributing to learn how to use git on an actual project with multiple contributors. I feel that fully redoing the GUI is too much of a commitment (why gilli stalled?), but making the current GUI _more like_ those designs is in scope for me right now.

I think the current GUI works really well especially because it's already responsive. You should make sure that any new GUI is also responsive, which to me, wasn't apparent in the new designs / GUI drafts I saw. 

> I think everyone agrees that work on the current web UI is somewhat beating a dead horse

I really do believe some small, apparently insignificant changes to the current GUI can make it even more user friendly.

So what should I do? Close the PR? I am happy to work with you to obtain a loading bar that is better

> Yeah agree, the line bar is a bit unusual, but perhaps we should try to improve that?

But if you are strictly against the idea of changing it, then I guess I should close. I would love to hear the community's thoughts on this.

Here is the latest version with the 'track' colour tweaked.
untitled

**Comment by norgeous** [comment]
> material design frameworks

I think the current choice of bootstrap v3 is good. I might attempt to redo the GUI using the [flexbox edition](http://v4-alpha.getbootstrap.com/getting-started/flexbox/) of v4 once it's [released](https://github.com/twbs/bootstrap/releases) - taking their time though... but this would probabily make soooo many bugs...

**Comment by AudriusButkevicius** [comment]
So I can't find who was the original author of the linear bars, but I think we should get that person on board.

The latest version looks fine to me, and I guess is less confusing that the bars, but I guess we still need more votes than one.

**Comment by canton7** [comment]
I've long dreamed if a folder indicator which says how much of the folder has been synced with other devices, btsync-style. Making the progress indicators small and round would be one very small step towards this :P

**Comment by norgeous** [comment]
some other immediately possible options:

thinner line
untitled untitled

fatter line
untitled untitled

it could be any shape either, although that sounds a bit stupid - it could be used. Circle is best IMO.

**Comment by norgeous** [comment]
also relevant:
https://www.youtube.com/watch?v=M2dhD9zR6hk
https://www.youtube.com/watch?v=hf_pq5EDh7w

**Comment by uok** [comment]
Many :moon: ago I implemented this line indicator to get a fast overview of sync status (and also be able to compare between different folders). The round ones look fancy, but I strongly agree with @AudriusButkevicius that the lines are much faster to read, which is also proven by studies (human brain is better at distances than angles). The same way you should never use pie charts but bar charts if you want to represent data in a good way.

**Comment by norgeous** [comment]
I will combine this and coloured identicons PR into a theme and try to pull again at a later date. No point keeping this open...

**Pull request closed without merging**
