### PR TITLE
New GUI 

### PR DESCRIPTION
**Pull request by gillisig**
In order to try to force myself to finish the new GUI, I'm making this pull request now. It is still very much WIP. This GUI has been discussed [here](https://github.com/syncthing/syncthing/issues/1381) and [here](https://github.com/syncthing/syncthing/issues/1381)

#Here is a non-exhaustive list of TODOs
- [ ] Move notifications into notification dropdown
- [ ] Make mobile version of table - something like this: http://codepen.io/geoffreyrose/pen/azdJNO
- [ ] Add identicon which shows status color (green: In sync, yellow: syncing red: out of sync) to device column and add syncing percentage to tooltip.
- [ ] Link plus button in action column to a little device modal to add and remove devices to this folder (example: https://invis.io/PN4RLWGXH)
- [ ] Make edit folder/device screens be more like this: https://invis.io/3M4RLYRJP
- [ ] Add advanced button to edit folder/device screens hides/shows advances sections and fields.
- [ ] Make local device data in header fold into a "drawer" on mobile that expands when clicked on local device name

I'll add more items to the list as I remember them.

I appreciate any help available. I am not that familiar with AngularJS so I would especially appreciate help with the parts relating to Angular, like moving notifications to the dropdown and more.

It currently looks like this on the surface: 
screen shot 2015-11-02 at 09 39 53

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
:heart:

**Comment by calmh** [comment]
Ooh, neat!

**Comment by lkwg82** [comment]
Do you need help?

**Comment by gillisig** [comment]
@lkwg82 yes absolutely, feel free to checkout my repo and make pull-request. It would especially if you have angular experience since I'm not that experienced with it.

**Comment by lkwg82** [comment]
@calmh what dou you think about the GUI build system. It is grunt again. Some time ago I proposed it for the Website. What is your current opinion in this?

**Comment by AudriusButkevicius** [comment]
You can just use STGUIASSETS and edit files directly, why do you need grunt?

**Comment by calmh** [comment]
Indeed I'm unconvinced of the need of a build system here. Yes, loading the GUI would be more efficient with minification and concatenation and stuff, but in 99% of cases this is from localhost and is a matter of milliseconds anyway.

**Comment by lkwg82** [comment]
IMHO: Minification and concatination justifies in an almost always local setup with a single-page app not the additional complexity.

So there is only left using sass. I like sass too, no question. But is there any reasonable tooling for sass without grunt? Is the css that complex to cut complexity with sass substantially? (I guess no.)

These questions are needed to be answered to prepare the planning of additional steps.

- cleanup (maybe to use no grunt and sass)
- solving merge conflicts
- identify missing UI elements

**Comment by lkwg82** [comment]
I'd like to close this PR as stalled.

**Comment by calmh** [comment]
For now

**Pull request closed without merging**
