### PR TITLE
lib/model: Decrease max temp filename length (fixes #3338, fixes #3355)

### LINKED ISSUE #3338: EPIC: Syncthing 0.13 doesn't sync _some_ files
### Version Information

Syncthing Version: v0.13.7
OS Version: Ubuntu 14.04 (also affects Windows, MacOS, etc)

### Steps to reproduce the problem

This bug can be reproduced in different environments. Please don't get an impression that only Linux users are affected.

Here is an example how to reproduce an issue:

1. Install Ununtu 14.04 LTS, enable home directory encryption using EncFS. EncFS has a serious limit on maximum file name length which will help us to reproduce an issue.
2. Install Syncthing
3. Create a file with long enough name (close to FS limits) in Sync directory, for instance: `/home/eax/Sync/books/by_topic/papers-redbook/0032 - ARIES- A Transaction Recovery Method Supporting Fine-Granularity Locking and Partial Rollbacks Using Write-Ahead Logging.pdf`
4. Sync with second machine that doesn't use EncFS
5. Delete Syncthing, clear Sync directory
6. Re-Install Syncthing, try to sync with second machine

### What you expected to happen

All files sync successfully.

### What actually happened

Syncthing doesn't sync some files. In log there are multiple error messages like this:

```
[TQISY] 10:29:46 INFO: Puller: final: open /home/eax/Sync/books/by_topic/papers-redbook/.syncthing.032 - ARIES- A Transaction Recovery Method Supporting Fine-Granularity Locking and Partial Rollbacks Using Write-Ahead Logging.pdf.tmp: file name too long 
```

### Suggestion

Temp file name is longer than original file name and thus doesn't satisfy filesystem limits. Perhaps instead of `.syncthing.(full file name).tmp` you could use `.syncthing.(sha256 of file name).tmp`.

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Because dammit

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
No, this is bs, 140-160 sure, but this is like 48.

Also, the guy still hasn't bothered to explain the case where it's short enough but still fails, so I am against putting a workaround for a thing we cannot explain.

**Comment by calmh** [comment]
I changed it to 128. I'm tired fo fighting this issue and we've had it with other users before.

**Comment by calmh** [comment]
@st-review merge it and lets never speak of this again

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by AudriusButkevicius** [comment]
So I don't like adding workarounds for things that we can't explain, especially when the unexplainable goes against whats documented, and I'd say that the ball is in the users court to answer the questions before we wedge in yet another workaround.

**Comment by AudriusButkevicius** [comment]
But again, it's your project, so just go with whatever you feel like.

**Comment by calmh** [comment]
In my mind encfs is just a weird incorrectly documented hacky piece of ... something, and we'll never get a real answer to what's going on. But reducing the limit will most likely fix the problem and reduce my pain level.

**Comment by st-review** [comment]
:ok_hand: Merged as a165838cbddcc1445619202fa4d01f7b9b996e56. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
Well I am perfectly fine for users to suffer of they use a piece of something. As a minimum I'd expect a bug report woth encfs or a documentation change to make it a less piece of something, rather than closing our eyes and taking the easy route. Yet again, it's the users of the piece of something that should do this, and once the bug is acked/docs changed, then we could wedge in a workaround.

Sure, we have workarounds for many things already, but either we notify the people at fault, or we simply have no way of doing so (samba..)

**Pull request closed without merging**
