### PR TITLE
all: Define proper struct types for event data.

### PR DESCRIPTION
**Pull request by acolomb**
### Purpose

Replace usage of `map[string]string` and `map[string]interface{}` with appropriate named types.  Add JSON annotations to all of them, as well as to the `FolderCompletion struct`, replacing its `Map()` method.  Use correct type assertions when accessing the event data internally.

As discussed in #8295.

This is best reviewed by having the Event API docs open for reference.  Some missing stuff there was noted along the way, see https://github.com/syncthing/docs/pull/754.

### Testing

Because of the considerable changes to `verboseservice.go`, this should always be run with `--verbose` when testing. 

The unit test suite passes, but no new tests have been added yet.  I'd welcome suggestions for how to test that the events have all expected fields present.  As the definitions are scattered all over, it won't be easy to have some "generate every possible event JSON object once now" method.  And what exactly would we test against?

The integration test suite should be unaffected by this, as the Event API doesn't change externally.  More verification needed on that end.

### CODE REVIEW

**Comment by acolomb** [comment]
Note there are still some loose ends here.  `folder_summary.go` and `main.go` need some more event type conditions and the `watchaggregator` has not adopted `ItemStartedEventData` and `ItemFinishedEventData` yet.  Doing so would require a cyclic package import though, so I don't have a good solution yet.

Anyway, I'd like some early feedback on whether this aligns with your visions of cleanly defined type-safe event data.

One more feature I want to try out is @calmh's suggestion to make structs for the whole events, not just the data part.  I have some ideas how that could work cleanly without breaking the API.

**Comment by calmh** [comment]
I think that having the event data structs declared by the package triggering the event might be *conceptually* cleanest, but will almost certainly result in dependency cycle issues. The easiest alternative is of course to declare all the types in the event package. (This is also a common solution to this type of problem, won't surprise anyone.)

The other option would be to use interfaces. Instead of a `type MyEventData struct { Foo string }` the producer package will declare a `type MyEventData struct { foo string }; func (d* MyEventData) Foo() String { return d.foo }` and the consumer package will use a local interface declaration `type FooEvent interface { Foo() string }` and doesn't really need to import or care about the original declaration. 

I think a quick experiment would reveal whether the interface approach becomes annoying amounts of boilerplate or has any advantages.

I'm leaning towards just declaring all the event data structs in the event package and leaving it at that.

**Comment by greatroar** [comment]
I was just about to post the interface suggestion. Putting everything in the event package means having to update two packages every time something changes in the log formatting.

**Comment by calmh** [comment]
For logging (verbose service) purposes the event data things could implement Stringer as well.

**Comment by greatroar** [comment]
Yes, I was just trying my hand at that (except I used a custom Verbose method). It's mostly repetitive work, but it looks like Failure, ItemStarted and ItemFinished are the only events that need to live in lib/events.

**Comment by acolomb** [comment]
I too would prefer collecting them in the events package actually.  For one it cleanly solves dependency issues.  And since this is an external API, having it summarized in one place (which is already the case for event *types*) seems logical.  We could even switch to protobuf later, as was done for the configuration.

I though about something like the interface method, for common things such as `Folder() string` and `Device() protocol.DeviceID` which are often used to filter events and could be made reusable.  But other than that, I think adding a separate method for every field gets tedious and ends up being a *lot* of boilerplate code.

I also like the idea of implementing `Stringer` right along the type definitions, as it gives the whole events package a lot more intrinsic "reference" documentation.  As witnessed in some of my recent docs PRs and stuff like the `Pending...Changed` missing at all from verboseservice, keeping these up to date is hard.  And even finding the "definition" for the purpose of documenting the API is hard when it's scattered all over.

> It's a lot of repetitive work, but it looks like Failure, ItemStarted and ItemFinished are the only events that need to live in lib/events.

Defining some events in a central registry and others where they are produced seems confusing.  The repetitive work for the `Stringer` is mostly just cut-n-pasting code from `verboseservice.go` to `events.go`.

**Comment by acolomb** [comment]
Any ideas how to handle `FolderCompletion`?  It's defined in `lib/model`, but part of the `FolderCompletionEventData`, hence another dependency cycle :-(

**Comment by imsodin** [comment]
Another way to break dependency cycles is to move types into a sub-package, e.g. `lib/model/types`.  
If we go the "all types in events" route (which then also means `FolderCompletion` and other included types in events), and someone is already investing the time to create all those types, I would encourage to put them into protobuf right away. Shouldn't be much more work if any more than creating structs manually, and gives us the additional benefit that event consumers could use those protobuf messages (which e.g. for a new UI would be great).

**Comment by greatroar** [comment]
> Defining some events in a central registry and others where they are produced seems confusing.

It is kind of weird, but some types need to be known in multiple places and they have to live somewhere. I'll abandon my attempt for now.

**Comment by acolomb** [comment]
> Another way to break dependency cycles is to move types into a sub-package, e.g. `lib/model/types`.

This is starting to feel really messy, and I haven't even finished tackling the `Pending...ChangedEventData` refactoring, where several internal model types would need to be moved.  Just to give you an idea, I've arranged the commits by order of uglyness.  See `eventdata.go` for stuff that hasn't been moved yet (commented out).

Guess I'll try the interface route next.  Let's see how far we can get with that.  Though I really like the idea of moving to protobuf definitions for the Event API.  Any other ideas how to handle all those internal types welcome.  I think some of the obstacles here may just be pointing toward how the `lib/model` package became quite a monstrosity?

**Comment by acolomb** [comment]
> The other option would be to use interfaces. Instead of a `type MyEventData struct { Foo string }` the producer package will declare a `type MyEventData struct { foo string }; func (d* MyEventData) Foo() String { return d.foo }` and the consumer package will use a local interface declaration `type fooEvent interface { Foo() string }` and doesn't really need to import or care about the original declaration.

Am I understand that correctly, the consumer package will then use a type assertion `event.(fooEvent)` after getting one from a subscription?  Won't we end up with the same potential for panics as with the current `map[string]interface{}` approach?

**Comment by calmh** [comment]
Something like that, yes, but there's no need to panic. You only get a panic if you do a "hard" type assertion:

```
intf := subscription.Read() // returns events.EventInterface or somethign
ev := intf.(*events.FooEventData) // will panic if the underlying type is wrong
```

but you can also

```
if ev, ok := intf.(*events.FooEventData); ok {
  // ev is *events.FooEventData
} else {
  // it wasn't
}
```

or, if you listen to multiple events:

```
switch ev := intf.(type) {
case *events.FooEventData:
  // ev is *events.FooEventData
case *events.BarEventData:
  // ev is *events.BarEventData
default:
  // no idea what event this is
}
```

**Comment by calmh** [comment]
I see now your question wasn't really about that case, but the type assertion stuff applies anyway.

**Comment by AudriusButkevicius** [comment]
I suggest that these should be generated from proto, in case they ever need to go on the wire.

**Comment by acolomb** [comment]
> I suggest that these should be generated from proto, in case they ever need to go on the wire.

That's certainly the end goal here, but I first tried without to solve the package dependency issues.  When we do switch to proto, it should certainly live in one package, right?  And therefore all needed (previously internal) types must be defined there as well.

**Comment by AudriusButkevicius** [comment]
Tbh, I think its fair game to move all events into proto/lib/events and wherever they are initialized use them from the generated package. There is zero reason why other packages should define their own events.

**Comment by acolomb** [comment]
> Tbh, I think its fair game to move all events into proto/lib/events and wherever they are initialized use them from the generated package. There is zero reason why other packages should define their own events.

It's just not that easy if you look at the actual data content.  Some packages serialize their own internal types into the event data.  All those (such as `FolderCompletion` and `pullerProgress`) need to be rebuilt exactly within proto to keep compatibility.  So my plan here is roughly:

1. Untangle types and avoid dependency cycles when centralized.
2. Add some unit tests to generate every possible event type's serialization once.
3. Convert to protobuf.
4. Verify that the serialization format hasn't changed using the unit tests.

Regarding point 2, I actually don't have a good idea yet on how to capture the status quo for comparison.  And how to write such tests without hard-coding the expected values.  Steps 3 and 4 are a considerable effort in itself, so I'm focusing on the first right now.  Will probably open a new PR once we are past the protobuf conversion, to keep a better overview and a manageable discussion thread.

**Comment by AudriusButkevicius** [comment]
I think it's fine to move whatever the packages embed internally to a proto package.

**Comment by acolomb** [comment]
> I think it's fine to move whatever the packages embed internally to a proto package.

Do you mean that any code using these previously internal types should then depend on the generated `events` package declarations, or rather some new lower-level type declaration package?

**Comment by acolomb** [comment]
After some experimentation, I see two main hurdles right now where I don't see a clear solution when going protobuf:

1. The `ConfigSaved` event has a `config.Configuration` in the Data field.  Thus the events package needs to import config, which imports db for the `db.FileSet`, which imports events for throwing `Failure` type events.  Breaking the cycle would be easiest in the config package, but I haven't found a solution yet.
2. The `Failure` event type has a simple string message as data, except for the special case `ur.FailureData`.  I'd try to solve this by printing the `FailureData` object to a string first, but on the consumer side this doesn't work.

I'd welcome any thoughts on those points, otherwise I'm still experimenting with the whole story.

**Comment by imsodin** [comment]
1. A simple solution is adding an interface for`*db.FileSet` in config, something like
```golang
interface MtimeOptionBuilder {
    MtimeOption() fs.Option
}
```
Alternatively refactor `fs.NewFilestem` to a builder type, and make `FolderConfiguration.Filesystem` return such a builder with options set, and then the caller can add the MtimeOption -> no db in config.

2. By not working on consumer side, do you mean that someone receiving the event data as a string can't deseriliase that to a `FailureData` object?  
The clean but annoying option is two wrap all usages of string into a `FailureData` object with just a description. A cheaper variant would be using the json serialisation of `FailureData` as the event data - then the consumer can try to deserialize to that and if it fails just treat it as a plain string. Not very nice, but should work.

**Comment by st-review** [comment]
:robot: beep boop

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

To permanently exempt this PR from bot nagging, add the `slow-pr` label.

**Pull request closed without merging**
