### PR TITLE
fix(model): don't sync symbolic links on Android (fixes #9725)

### LINKED ISSUE #9725: Ignoring symbolic links when syncing on android as well
### Feature description

I wish to be able to set a device so that symbolic links are not synchronized onto that.

### Problem or use case

I'm unable to sync symlinks to my android phone so the syncing gets stuck at 99% and will never move. This annoys me and masks other issues that might cause the syncing to fail. 

### Alternatives or workarounds

I have not considered workarounds

### PR DESCRIPTION
**Pull request by KapilSareen**
### Purpose

Fixes issue #9725 by ensuring that symbolic (symlink) files are ignored in the event subscription process, preventing unwanted behavior caused by handling symlink files in scenarios where they aren't necessary.
### Testing

Manual testing was performed by creating both symlinked and regular files in the monitored directories. Observed that:

- Regular files are processed as expected.
- Symlinked files are ignored and do not trigger any event subscriptions.

### CODE REVIEW

**Comment by KapilSareen** [comment]
Hi @imsodin, can you review this?

**Comment by tomasz1986** [comment]
The two changes seems unrelated to one another… I would suggest to move the GUI code to a different PR, and keep this one focused on the symlink issue only.

**Comment by KapilSareen** [comment]
Okay sure I'll do that in some time

**Comment by imsodin** [comment]
I do not understand what you are trying to do here? Looks like you are fitering events pertaining to symlinks in the event API http request handler - I don't see why you'd want to do that.

It definitely doesn't fix #9725, that's about having an option to ignore symlinks when pulling. You are changing the API layer here - whatever it is you are trying to achieve, it can't influence the actual synchronisation.

**Comment by KapilSareen** [comment]
I'm focusing on ignoring all changes related to symlinks since I don't see a practical use case for synchronizing them. Do you have any other suggestions in mind?

**Comment by imsodin** [comment]
> I'm currently choosing to unsubscribe to the changes related to symlinks as I don't find a practical use case for syncing them.

That does not answer my confusion. Ignoring symlinks in events does not change syncing.

>  Or do you have any other idea for implementing this?

Yes, as mentioned (albeit admittedly very briefly) I do think it can be addressed in the same way it is currently for windows, just that it's newly controlled by a config (which is true by default on windows and probably android, and false everywhere else). See:
https://github.com/syncthing/syncthing/blob/main/lib/model/folder_sendrecv.go#L401

**Comment by KapilSareen** [comment]
Hi, just to clarify is this the correct approach you were suggesting?
Also, do you want this for Android to be configurable or just hardcoded? If yes, how do you want it to be controlled, like if you want to ignore symlinks?

**Comment by calmh** [comment]
Honestly I feel that it might be better to resolve this by flags on the ignore patterns, but that's a larger / more complex change. In the meantime, if we want to add Android to the same class as Windows in terms of symlink handling (hard coded) that seems fine too. I don't think we should add a one-off option for symlink disabling.

**Comment by KapilSareen** [comment]
So is this fine or do you have something in mind that needs to be implemented as of now?

**Comment by calmh** [comment]
The change to folder_sendrecv.go looks good to me. The other changes should be cleaned up.

**Review by imsodin — APPROVED** [review]

**Comment by lildata** [comment]
Hi,

I noticed this change had devastating consequences when using syncthing in termux.

The reason is the termux package (https://github.com/termux/termux-packages/blob/master/packages/syncthing/build.sh) seems to be the `android` build 

```
INFO: syncthing v1.29.3 "Gold Grasshopper" (go1.24.1 android-arm64) builder@24fe6cf991b2 2025-03-12 13:18:33 UTC [noupgrade]
```

So it seems that when upgrading to 1.28.1 and beyond all the symlinks silently stopped syncing and broke a lot of things for some of us.

I am not sure what was exactly caused the problem described in https://github.com/syncthing/syncthing/issues/9725

> I'm unable to sync symlinks to my android phone so the syncing gets stuck at 99% and will never move. This annoys me and masks other issues that might cause the syncing to fail.

but AFAIK running syncthing in termux must be the common way people use syncthing on Android now that the App is gone ? 
And symlinks are one of the core file types of any *nix system used by many of us.

Please, would it be possible to reverse that change and make it a configuration option?

**Comment by tomasz1986** [comment]
> but AFAIK running syncthing in termux must be the common way people use syncthing on Android now that the App is gone ? And symlinks are one of the core file types of any *nix system used by many of us.

Running Syncthing in Termux is probably very niche, with the recommended solution being https://github.com/Catfriend1/syncthing-android. The reason for the change was that symbolic links are not supported on the user storage (which includes both the `/storage/emulated/0` partition and SD cards).

It is true, however, that when talking specifically about Termux and its internal folders, symlinks are indeed supported there.

**Comment by lildata** [comment]
> Unfortunately, at least basing on our testing, it is not possible to reliably detect filesystems on Android.

I see, I am not surprised...

Please consider this, because my guess is it is breaking things for a lot of people.
Myself it took me weeks or months after upgrade to find out a lot of my problems were coming from this change.

**Pull request merged**
