### PR TITLE
Copy configuration struct when sending Changed() events

### PR DESCRIPTION
**Pull request by calmh**
Avoid data race

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins run integration tests please

**Comment by calmh** [comment]
Apparently this was not good enough, hang on with this one... :)

**Comment by calmh** [comment]
@st-jenkins run integration tests, please, again

**Comment by calmh** [comment]
That's green. The "pending" `integration` check above is `pr-integration` that I renamed halfway through - Jenkins kan now report integration separately from normal build! Yay!

**Comment by AudriusButkevicius** [comment]
What was the issue with the original pr?

**Comment by calmh** [comment]
I did the Copy() in wrapper.Serve() which is outside of any lock and so still triggers the race detector when the data is used from another goroutine. By doing the copy when we do the channel send, we get a fresh, private, copy of the info and it gets passed through the channel so it's goroutine clean...

**Comment by AudriusButkevicius** [comment]
Also, why not copy after receiving in the dispatcher?

**Comment by AudriusButkevicius** [comment]
Oh I see.

**Comment by calmh** [comment]
Yes :)

**Comment by AudriusButkevicius** [comment]
Sorry on the phone, stuff is slow.

**Pull request merged**
