### PR TITLE
lib/ignores: Don't add text from includes to lines

### PR DESCRIPTION
**Pull request by imsodin**
Otherwise all the lines from includes are present in the web UI instead of
just the #include ... line. This problem was introduced in #3996.

### CODE REVIEW

**Comment by imsodin** [comment]
@st-jenkins test this please

Mac failure:
```
--- FAIL: TestBufferOverflow (16.54s)
	events_test.go:117: Logging took too long, 16.536353673s avg 129.190263ms expected < 15ms
```
Ignore it or increase the threshould to 20ms?

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@imsodin would you mind also filing the corresponding bug that this can fix, so it ends up in the release notes?

**Comment by imsodin** [comment]
@calmh Meaning I should also create a bug report when I detect something like this instead of just a PR?

**Comment by calmh** [comment]
Ideally, yes. I mean, I don't myself a lot of the time, but for something that should be noted in the release it's nice to do so.

**Comment by imsodin** [comment]
Done: #4249 
I wasn't really too keen on attention on this :P

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as b75c9f2bbb7cbfc7ff05d250f8598acc9016691b. Thanks, @imsodin!

**Pull request closed without merging**
