### PR TITLE
cmd/syncthing: Report if weak hash is enabled

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
UR changes to follow at some point.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by AudriusButkevicius** [comment]
@st-review dont

**Comment by st-review** [comment]
I'm sorry, @AudriusButkevicius. I'm afraid I don't know what you mean. I know how to `don't`, `lgtm`, `merge`, `prevent`, `rebuild`, `squash`, `stop`.

**Comment by AudriusButkevicius** [comment]
@st-review stop

**Comment by st-review** [comment]
@AudriusButkevicius: Preventing merge for the time being. Push a new revision to reset!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as c5f90d64bc23993e7f4ce69e517c6290e8ba4d90. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
