### PR TITLE
lib/ignore: Only handle lines prefixed with #include specially (fixes #4680)

### LINKED ISSUE #4680: Ignore pattern beginning with "#" does not match subpaths
See: https://forum.syncthing.net/t/ignore-patterns-that-start-with/11173

E.g. `#snapshots` does not match `#snapshots/foo`.

### PR DESCRIPTION
**Pull request by imsodin**
see #4680

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as a1761795fe0ce1667352aab7cfc44d5216118c61. Thanks, @imsodin!

**Pull request closed without merging**
