### PR TITLE
lib/ignore: Add directory separator to glob.Compile call

### PR DESCRIPTION
**Pull request by imsodin**
The current implementation of [gobwas/glob](https://github.com/gobwas/glob) in lib/ignore does not account for directory separators ('/'). Thus the distinction between '\*' and '\*\*' is meaningless. Currently both the patterns 'a\*b' and 'a\*\*b' match the path 'a/b'.

I confirmed the current behavior looking at the last file received entry in the GUI. But as I am only familiar with syncthing-inotify and it uses lib/ignore for its filtering as well, I tested this PR with debug information from syncthing-inotify. The test setup is trivial, just put something like the strings mentioned into .stignore.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins add to white list

**Comment by calmh** [comment]
LGTM but could we get a unit test for this as well to catch regressions in the future? Somewhere in lib/ignore/ignore_test.go should be appropriate

**Comment by imsodin** [comment]
Like this?

**Comment by AudriusButkevicius** [comment]
I wonder if the pattern separators are normalised somewhere along the way, so that this gets fixed on windows.

**Comment by imsodin** [comment]
@AudriusButkevicius By normalised do you mean converted to slashs? If yes, this happens [here](https://github.com/syncthing/syncthing/blob/master/lib/ignore/ignore.go#L341).

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
How about this:

```go
func TestIssue3674(t *testing.T) {
	stignore := `
	a*b
	a**c
	`

	testcases := []struct {
		file    string
		matches bool
	}{
		{"ab", true},
		{"asdfb", true},
		{"ac", true},
		{"asdfc", true},
		{"as/db", false},
		{"as/dc", true},
	}

	pats := New(true)
	err := pats.Parse(bytes.NewBufferString(stignore), ".stignore")
	if err != nil {
		t.Fatal(err)
	}

	for _, tc := range testcases {
		res := pats.Match(tc.file).IsIgnored()
		if res != tc.matches {
			t.Errorf("Matches(%q) == %v, expected %v", tc.file, res, tc.matches)
		}
	}
}
```

Which fails now, and should hopefully pass with your patch:

```bash
jb@unu:~/s/g/s/s/l/ignore $ go test -v -run TestIssue3674
=== RUN   TestIssue3674
--- FAIL: TestIssue3674 (0.00s)
	ignore_test.go:768: Matches("as/db") == true, expected false
FAIL
FAIL	github.com/syncthing/syncthing/lib/ignore	0.006s
```

**Comment by imsodin** [comment]
Changed it to calmh's test function and yes, it does pass.

**Comment by calmh** [comment]
👍

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
wat

**Comment by calmh** [comment]
@st-review merge it then

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 7c37301c910dd3cf54a44a7ac677aef52f402e6d. Thanks, @imsodin!

**Pull request closed without merging**
