### PR TITLE
Matcher is always there

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
Dammit, I thought that we always have a matcher.
Cannot see a scenario where we don't.

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
waaaaaaaaaaaat

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
(Probably just needs a rebase on your integration test fix now)

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Pull request merged**
