### PR TITLE
add badge for freenode

### PR DESCRIPTION
**Pull request by wildcard**
Added a badge to emphasise the discussion is available on freenode

### CODE REVIEW

**Comment by calmh** [comment]
There's already a link a little further down in the readme; I don't think it deserves a build badge necessarily. If anything it's a bit hidden under "getting started" so that but could gain a header "getting in touch" and also a link to the forum?

**Comment by wildcard** [comment]
@calmh I agree with you :+1:

**Comment by wildcard** [comment]
You want me to close the PR?

**Comment by calmh** [comment]
No worries, I'll clarify the README a little.

**Comment by wildcard** [comment]
That would be great :)

קובי קדוש,
נשלח מה-iPhone שלי

‫ב-3 בינו׳ 2016, בשעה 14:03, ‏‏Jakob Borg ‏<notifications@github.com> כתב/ה:‬

**Pull request closed without merging**
