### PR TITLE
lib/protocol: Serialize the all zeroes device ID to the empty string

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Gets us `introducedBy=""` instead of `introducedBy="AAAinfinitelymanyAs"` in the config.

(`omitempty` does not apply here, as it is checked before serializing and a `[32]byte` is never "empty")

### Testing

Dem unit tests

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
@AudriusButkevicius this test is suspiciously randomly flaky...

```
--- FAIL: TestClusterConfig (0.00s)
	model_test.go:468: Incorrect device ID 4759525a5a51422d49524e5056345a2d543754433532572d4551594a3354542d46445157364d572d44464c4d5534322d5353535536454d2d46424b32564159 != 414952364c505a2d374b34505454562d555851534d55552d435051355957482d4f4544464949512d4a5547373737472d325951585852352d59443641575152
	model_test.go:471: Device1 should be flagged as Introducer
	model_test.go:474: Incorrect device ID 414952364c505a2d374b34505454562d555851534d55552d435051355957482d4f4544464949512d4a5547373737472d325951585852352d59443641575152 != 4759525a5a51422d49524e5056345a2d543754433532572d4551594a3354542d46445157364d572d44464c4d5534322d5353535536454d2d46424b32564159
	model_test.go:477: Device2 should not be flagged as Introducer
```

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 95c738ea2890974909189ea9f8ba65ee3f67bf43. Thanks, @calmh!

**Pull request closed without merging**
