### PR TITLE
Exchange temporary indexes

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
I got another pull request ready for github.com/syncthing/protocol, but you can see changes to it here.

Sadly this does not pass integration tests on Jenkins (though it does pass on my own machine).
http://build.syncthing.net/job/syncthing-integration/244/console
I get a ping timeout somehow, maybe it's some sort of deadlock/lock contention.

Need to figure that one out.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
http://build.syncthing.net/job/syncthing-integration/244/console

**Comment by AudriusButkevicius** [comment]
Currently running fine:
http://build.syncthing.net/job/syncthing-integration/244/console

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
Notes to self:
1. Forgot to check for featues when sending initial index.
2. Deadlock logs in the phone.

**Comment by AudriusButkevicius** [comment]
3. Remove redundant comments

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by calmh** [comment]
(I've seen this, but actually reading and understanding it will take some time. I'll get to it during the week. :)

**Comment by AudriusButkevicius** [comment]
Still needs to pass the tests

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
What the: http://build.syncthing.net/job/syncthing-pr-integration/6/console

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
Need to add ability to disable advertising temp indexes.

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
So, I guess I'd like to have at least a preliminary review of this, before I try to fix the issues I've pointed out, as it might make it easier to fix them due to some changes required by the review.

**Comment by calmh** [comment]
Yah, sorry, ditto on the busy/lazy part and it's a daunting diff. Looking at it now. :)

**Comment by calmh** [comment]
So the :+1: are mostly so that I don't read the same commit again. I think in general it's reasonable, with the above nits, and some general concerns;

 - I'm slightly worried about the "race condition" of announcing temp files, the file no longer being temp, then requests coming in. Could we / should we modify things so there's only one kind of request, that always includes a block hash and is responded to with temporary or normal blocks, whatever we happen to have lying around?
 - I don't like using reflect in normal code, as commented.
 - Creating and returning maps is fairly expensive (in terms of the amount of garbage created etc), so maybe there are places we could return a slice of some customer (key, value) struct instead (i.e. the map for available devices, that just holds a device ID and a flag)
 - There are quite a few places where we iterate over maps and lists to find stuff, which I'm worried may be a performance issue. Perhaps it isn't, and I'll take a look again, but it's something to keep in mind. This may be the opposite of the previous point above, so it's a trade off of course. :)

**Comment by AudriusButkevicius** [comment]
Round 2, fight!.

Concerns from IRC:
```
<[0]Jmr> calmh, tempindexes
<[0]Jmr> you have a fair point that a single temp index might be quite large
<[0]Jmr> hence batching would be beneficial
<[0]Jmr> but I guess that means I need an extra bit to indicate when it's an addition to the batch
<[0]Jmr> or when it's batch 0 and should reset everything
<[0]Jmr> which means an extra flag
<[0]Jmr> because protocol package has a state machine around Index{,Update} which does not respect flags
<[0]Jmr> hence if I were to fire off Index with Temp flag set, before Index is fired off without any flags, it would move to the new state.
<[0]Jmr> and allow index updates flags 0 to arrive before index with flags 0 has arrived
```

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
Right, ready for another bashing.

**Comment by michaelforge** [comment]
Just out of curiosity: what exactly this pull must doing? Something related to more faster index exchange?

**Comment by AudriusButkevicius** [comment]
Currently seeding only starts when a device has the whole file.
This allows to seed before you have the whole file.

**Comment by calmh** [comment]
Possibly impopular opinion coming up... 

I keep thinking it's a lot of mechanics here (the flags etc) to maintain compatibility with something that's anyway not a fixed standard. How about introducing the TemporaryIndex message as a new message type (identical layout to an Index message), with semantics that devices MAY send it and MUST accept it but MAY ignore it. Then we change the request message to be just folder, hash and size and drop the filename part completely. We already have the block map, and this way we can treat each request identically - either we have the block or we don't, never mind if it's in a temporary or real file (we must know this though on the receiving side so we know where to read it from).

**Comment by AudriusButkevicius** [comment]
Actually I prefer that to what I am doing now, as I can solve the batching issue too.
I guess I do like having the 'feature' concept there as it allows to deal with stuff when it's locked down.

The block map only gets updated when the whole file is finished downloading (unless we start writing tempfile content into the block map), so I guess this whole emitter tracker bullcrap is still needed.

**Comment by AudriusButkevicius** [comment]
Also, now looking at the PR it looks like I pushed the wrong thing or haven't fully fixed it up, as it's a a bit borked.

**Comment by AudriusButkevicius** [comment]
Right, looks less broken now.
Let's decide what we are throwing away, and what we're keeping.

**Comment by calmh** [comment]
Replaced by the "take two" PR

**Pull request closed without merging**
