### PR TITLE
Implement signal handling

### PR DESCRIPTION
**Pull request by calmh**
With this change, the behavior is as follows:

 - SIGTERM / SIGINT: Exit cleanly (exit code 0)
 - SIGHUP: Restart

This is the case both when hitting the monitor process or the inner
process, or if running with NORESTART (but then we won't restart,
obviously, just exit with code exitRestarting).

It enables "pkill -HUP syncthing" to do the right thing to restart all
Syncthings on package upgrade, for example.

### CODE REVIEW

**Comment by calmh** [comment]
@canton7 any consequences for the systemd stuff?

**Comment by rumpelsepp** [comment]
Yeah, I think so; that's even quite nice. I will file an appropriate PR for the service files today.

**Comment by AudriusButkevicius** [comment]
The only thing I could argue about is the hexadecimal signal codes. I think most of them have constants in the os or syscall packages. Even if they don't, using ints is more obvious, as you might do kill -TERM or kill -15, but not kill -0xf.

**Comment by rumpelsepp** [comment]
I have found that in the docs: http://www.cons.org/cracauer/sigint.html

> Note that if a process has a signal handler installed and exits by calling _exit(2) in response to a signal, the information about the signal is lost. Programs should instead perform cleanup and kill themselves with the same signal instead. See Proper handling of SIGINT/SIGQUIT — How to be a proper program.

Opinions?

**Comment by calmh** [comment]
I can change that. We had 0xf in there since before, but I agree that 15 is more human readable. Afaik the ones I created myself didn't have ready made constants

**Comment by AudriusButkevicius** [comment]
Sure, lets get rid of the hex.

**Comment by calmh** [comment]
@rumpelsepp Unless there are strong rationales for it (that page is tl;dr right now;) I just plain disagree about the exit code. I think the exit code should reflect how/why we're exiting in a useful way, but wether the restart was requested by command, REST POST or signal doesn't matter from my point of view.

**Comment by rumpelsepp** [comment]
Yeah; for further reference the link is here in the issue. So let's skip that tl;dr for the time being. :)

**Pull request merged**
