### PR TITLE
Multiarch for Docker

### LINKED ISSUE #5436: MultiArch for Docker
I'd like to feature-request Docker image releases of the same [binary release variety](https://github.com/syncthing/syncthing/releases). There will soon be a stable [docker manifest command](https://docs.docker.com/edge/engine/reference/commandline/manifest/) that allows the creation of image lists that allow automatic distribution of platform and architecture specific image variants. [All official docker images now use manifests](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/) and I think that would be a great addition to syncthing, which currently only serves the default linux/amd64 variant. I know that in #2591 linuxserver mentioned their release of such variants, but an official release is always more appealing.

### PR DESCRIPTION
**Pull request by dargmuesli**
Successor of #5446, plus working test deployment on a Rock64. Closes #5436.
Now this should finally work. You can test that yourself by setting up a copy of your build rules for the `docker_multiarch` branch or merge it directly if [it LGTY](https://cloud.docker.com/repository/docker/dargmuesli/syncthing) :)

### CODE REVIEW

**Comment by Dargmuesli** [comment]
Just noticed that syncthing displays `unknown-dev` as version in my custom tagged image. Do you know why that could be?

**Comment by calmh** [comment]
You have push permissions as far as I can tell, since you have write permissions on the repository. My intention by doing that was that you could do work on a branch like this, we might test that on the docker hub, and it could be reviewed by an ongoing PR to merge the `docker_multiarch` branch into `master`. Only `master` is a protected branch that cannot be pushed to without PRs.

**Comment by Dargmuesli** [comment]
Oh, my bad! I used a https instead of ssh remote. Sorry for that.

**Comment by Dargmuesli** [comment]
screenshot_2019-01-30 docker hub

**Comment by calmh** [comment]
If we didn't use docker hub but instead built and pushed the containers ourselves, would this be easier? We could use a real script of some kind (in Go, for example).

**Comment by calmh** [comment]
Part of the equation is that we already maintain an existing, complex build server setup. Adding a docker build/push step doesn't make it much worse, and would have caught and fixed #5495 earlier, for example.

Regardless, adapting this to that after the fact is easy if we want to do so.

**Comment by Dargmuesli** [comment]
Hey guys, what's your current status on this? :)

**Comment by calmh** [comment]
It's large, complex, and difficult to test (comparatively). We'll get there, but at  the moment there is a lack of time on my side, sorry

**Comment by AudriusButkevicius** [comment]
Sorry, this is slightly beyond me, so I can't give it s sensible review.

**Comment by Dargmuesli** [comment]
Ok, tell me if I can help somehow.

Btw, what exactly do you mean with testing? Do you test your current build servers somehow? As I mentioned, DockerHub should send build failure mails.

**Comment by Dargmuesli** [comment]
I've solved the merge conflict. Again, I want to offer my help to resolve whatever blocks a merge into master. Feel free to tell me the requirements and what you're unsure about and if I can help with that.

**Comment by calmh** [comment]
So this has been stale for a while because I was unsure what to do with it. The truth is that I'm not comfortable in taking on and maintaining this.

It's complicated, subtle (with the qemu interactions), tricky to test, and depends on specifics of the Docker Hub build setup that we don't have to care about today. I really appreciate all the effort you've put into this, but given how all this works today it's something that I think we should opt out of supporting. It's not that you've done a bad job, but that the way this is handled on Docker Hub is ugly and not well thought through, imho. Maybe that changes in the future and we can publish multi architecture images with less hoop jumping.

**Comment by dargmuesli** [comment]
😔

**Comment by dargmuesli** [comment]
If you really wish to get as official as possible, let me direct you to [docker-library/official-images] (https://github.com/docker-library/official-images). I'm pretty sure that syncthing qualifies for admission. I can't tell whether this would solve any of your mentioned issues (at least the qemu one for sure), as I think that those are general build pipeline issues. E.g. I still don't have a clue how build scripts could be tested (never seen before).
Please give it a try.

**Comment by dargmuesli** [comment]
I stopped updating my fork.
Anyone interested can find a Travis CI configuration that builds a multiarch Docker image using the new [buildx](https://github.com/docker/buildx/) Docker feature at [flipdot/drinks-touch:/.travis.yml](https://github.com/flipdot/drinks-touch/blob/master/.travis.yml).
This is unlikely to work on Docker Hub yet though as their builders are not very up 2 date and pretty restricted. @calmh ping me if you want me to help with anything related to that.
Happy coding :)

**Pull request closed without merging**
