### PR TITLE
gui: Update translation strings

### PR DESCRIPTION
**Pull request by imsodin**
In #3996 I introduce new strings to be translated, but I don't want unrelated strings to be in that PR -> this PR.

### CODE REVIEW

**Comment by calmh** [comment]
This should be in the same PR that uses them. It's not unrelated.

**Comment by imsodin** [comment]
The strings in this PR are about versioning, I didn't manipulate them at all in #3996, they come up when running `go run build.go translate` on master.

**Comment by calmh** [comment]
Oh. Dammit.

**Comment by calmh** [comment]
@st-review: merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 1b08176583624311af16ff051663fffa2b6af1b7. Thanks, @imsodin!

**Pull request closed without merging**
