### PR TITLE
lib/model: Meaningful error messages for paused folders

### PR DESCRIPTION
**Pull request by imsodin**
Just for clarification of logs like this: https://forum.syncthing.net/t/syncthing-inotify-crashes/9195/9

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Capitalization issues.

**Comment by calmh** [comment]
While you're at it, since these are obviously duplicated, could you add them to the error list at https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L110 instead? And delete the comment above, those are already not limited to CheckFolderHealth. :)

**Comment by AudriusButkevicius** [comment]
Can you get rid of the comment above the error list too? Or draw a line where errors returned by check folder health ends?

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 22903df2c10b4224bc50f545f3223636d96f7d71. Thanks, @imsodin!

**Pull request closed without merging**
