### PR TITLE
Update lang-ru.json

### PR DESCRIPTION
**Pull request by TrueGrom**
spelling mistake

### CODE REVIEW

**Comment by 101100** [comment]
@TrueGrom Translations are managed at [Transifex](https://www.transifex.com/projects/p/syncthing/).

**Comment by TemaSM** [comment]
I'm updated this string on Transifex, please  save it!

**Comment by 101100** [comment]
The translations are automatically picked up when a new version is released.

**Comment by TemaSM** [comment]
Okay, so i think, we can close this issue

**Pull request closed without merging**
