### PR TITLE
lib/sha256: Remove it

### PR DESCRIPTION
**Pull request by Gusted**
### Purpose

Remove the `lib/sha256` package, because it's no longer necessary. Go's standard library now has the same performance and is on par with `sha256-simd` since [Since Go 1.21](https://github.com/golang/go/commit/1a64574f42b95594cf9c8a12e9ca13d75585429c). Therefore using `sha256-simd` has no benefits anymore.

ARM already has optimized sha256 assembly code since https://github.com/golang/go/commit/7b8a7f8272fd1941a199af1adb334bd9996e8909, `sha256-simd` published their results before that optimized assembly was implemented, https://github.com/minio/sha256-simd/commit/f941fedda826b68a196de2e0a9183e273ec0cb91. The assembly looks very similar and the benchmarks in the Go commit match that of `sha256-simd`.

This patch removes all of the related code of `lib/sha256` and makes `crypto/sha256` the 'default'.

Benchmark of `sha256-simd` and `crypto/sha256`:
<details>

```
cpu: AMD Ryzen 5 3600X 6-Core Processor
                │  simd.txt   │               go.txt                │
                │   sec/op    │    sec/op     vs base               │
Hash/8Bytes-12    63.25n ± 1%    73.38n ± 1%  +16.02% (p=0.002 n=6)
Hash/64Bytes-12   98.73n ± 1%   105.30n ± 1%   +6.65% (p=0.002 n=6)
Hash/1K-12        567.2n ± 1%    572.8n ± 1%   +0.99% (p=0.002 n=6)
Hash/8K-12        4.062µ ± 1%    4.062µ ± 1%        ~ (p=0.396 n=6)
Hash/1M-12        512.1µ ± 0%    510.6µ ± 1%        ~ (p=0.485 n=6)
Hash/5M-12        2.556m ± 1%    2.564m ± 0%        ~ (p=0.093 n=6)
Hash/10M-12       5.112m ± 0%    5.127m ± 0%        ~ (p=0.093 n=6)
geomean           13.82µ         14.27µ        +3.28%

                │   simd.txt   │               go.txt                │
                │     B/s      │     B/s       vs base               │
Hash/8Bytes-12    120.6Mi ± 1%   104.0Mi ± 1%  -13.81% (p=0.002 n=6)
Hash/64Bytes-12   618.2Mi ± 1%   579.8Mi ± 1%   -6.22% (p=0.002 n=6)
Hash/1K-12        1.682Gi ± 1%   1.665Gi ± 1%   -0.98% (p=0.002 n=6)
Hash/8K-12        1.878Gi ± 1%   1.878Gi ± 1%        ~ (p=0.310 n=6)
Hash/1M-12        1.907Gi ± 0%   1.913Gi ± 1%        ~ (p=0.485 n=6)
Hash/5M-12        1.911Gi ± 1%   1.904Gi ± 0%        ~ (p=0.093 n=6)
Hash/10M-12       1.910Gi ± 0%   1.905Gi ± 0%        ~ (p=0.093 n=6)
geomean           1.066Gi        1.032Gi        -3.18%
```

</details>

### Testing

Compiled and tested on Linux.

### Documentation

https://github.com/syncthing/docs/pull/874

### CODE REVIEW

**Review by calmh — APPROVED** [review]
Nice

**Comment by imsodin** [comment]
That go ticket only talks about one intel instructions, while sha256-simd talks about multiple and also ARM specific things. Are we sure we aren't losing optimisations for some hardware by dropping this?

**Review by imsodin — CHANGES_REQUESTED** [review]
Actually I'll make this blocking. I don't have much prior knowledge on sha256 hardware optimization, so it's very possible I am just entirely wrong, I'd just like some acknowledgement that this does indeed cover all improvements made by sha256-simd, not just one (to a reasonable extent of certainty of course, something being missed is always possible).

Examples of what I picked up (again, just dumb pattern matching, I haven't looked into what any of this means exactly):

https://github.com/minio/sha256-simd?tab=readme-ov-file#arm-sha-extensions

**Comment by calmh** [comment]
At least on macOS ARM64 it's the same.

```
[I6KAH] 2024/08/10 11:36:30 INFO: Single thread SHA256 performance is 2504 MB/s using crypto/sha256 (2494 MB/s using minio/sha256-simd).
```

**Comment by AudriusButkevicius** [comment]
Go version for amd64 doesn't seem to use native instructions, where as minio does.
This is only likely be visible on more modern cpus.

**Review by imsodin — APPROVED** [review]
Thanks for testing Jakob, was about to try to run sha256-simd benchs myself on arm :) 

Also just found this quote by the author of sha256-simd, in answer to Audrius saying the package is obsolte:

> Correct, it is obsolete.

https://github.com/minio/sha256-simd/issues/72#issuecomment-2166514572

**Comment by AudriusButkevicius** [comment]
lemme just verify quickly on my machine

**Comment by imsodin** [comment]
Ah yeah, I just missed Audrius' message before approving myself. I should have just retracted my request for changes review, that would have represented my intent better :)

**Comment by AudriusButkevicius** [comment]
```
[2ERMY] 2024/08/10 12:37:04 INFO: Single thread SHA256 performance is 1740 MB/s using crypto/sha256 (1740 MB/s using minio/sha256-simd).
```
so we're good

**Review by AudriusButkevicius — APPROVED** [review]

**Comment by yonas** [comment]
@Gusted Would it be possible for you to add [BLAKE-3](https://www.infoq.com/news/2020/01/blake3-fast-crypto-hash/) to your comparison?

**Pull request merged**
