### PR TITLE
Change “Last File Received” to “Latest Change.”

### LINKED ISSUE #3769: Last File Received	Deleted: foo
Cosmetic:

I noticed the following message in the gui:

`Last File Received     	Deleted: foo`

So I’d would change the message `Last File Received` to `Latest transaction`

### PR DESCRIPTION
**Pull request by hboetes**
Change wording from “Last File Received” to the more appropriate “Latest Change.”
Closes #3769

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins test this please

**Comment by calmh** [comment]
@st-review merge it

gui: Tweak wording (fixes #3769)

Skip-check: authors

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as f6a2b6252a4f260497dd743aa49d682754468b49. Thanks, @hboetes!

**Pull request closed without merging**
