### PR TITLE
gui: Fix comparison operator in expression (ref #3035)

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Make the GUI not blow up

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge whenever dude

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
:no_entry: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by st-review** [comment]
:no_entry: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by calmh** [comment]
Wat

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 591959261c1ea8d1652878cf7e2eb4eda509665b. Thanks, @calmh!

**Comment by calmh** [comment]
WAAAT

**Comment by calmh** [comment]
Ah

**Comment by calmh** [comment]
The two simultaneous merge attempts stomped on each other, one doing "merge" at the same time as the other one doing "reset --hard" and so on. Maybe it shouldn't attempt more than one at the same time for a given repo :)

**Pull request closed without merging**
