### PR TITLE
gui: Folder picker modal [wip]

### PR DESCRIPTION
**Pull request by norgeous**
# totally not ready yet, but functional

untitled
- no plugins such as jstree
- windows only for now

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So apart from looking nothing like a tree, looks good and surprisingly very simple.
I guess its not very mobile and screen reader friendly so we should probably still keep the edit box for those who want to use that.

What's the rationale for not using jstree?

Reason I am asking is because folder ignores and other things which we will potentially need in the future require much more advanced features, such as checkboxes, different icons between folders files and custom "All" nodes, being able to get the top selected checkbox for every subtree, being able to prepopulate part of the subtree, such as:
```
 -a
  -? 
- b
  - c
    - d
- e 
  - f
    - ?
```
and getting the rest via AJAX

So I am not sure rolling out your own makes much sense, as it will either be tremendous effort to get all the features we potentially need implemented, or will make it somewhat redundant when we will have to use something else anyway in some other part of the UI.

**Comment by AudriusButkevicius** [comment]
The code of the old ignore UI is here:

https://github.com/AudriusButkevicius/syncthing/commit/80c4725ef0eecdfd2c797098f49063fd9d5a00c4

As you can see it's not trivial.

**Comment by norgeous** [comment]
Thanks for your feedback! Useful as always! But unfortunately I don't think I really fully understand what you you are saying. Hopefully you can elaborate?

Maybe I should explain some hopefully relevant things I have included, as I did foresee that this component may need to be reusable...

I have not used jstree, but I wouldn't really consider this as a 'own-rolled' - I have just reused the existing bootstrap and angular features

currently behind the scenes...

- load `https://127.0.0.1:8384/rest/system/browse?` with response:
```json
["C:\\","F:\\","G:\\","T:\\"]
```

- this response is parsed into `$scope.tree` as
```js
[
  {
    "isroot": true,
    "path": "C:\\",
    "label": "C:\\"
  },
  {
    "isroot": true,
    "path": "F:\\",
    "label": "F:\\"
  },
  {
    "isroot": true,
    "path": "G:\\",
    "label": "G:\\"
  },
  {
    "isroot": true,
    "path": "T:\\",
    "label": "T:\\"
  }
]
```

- Upon clicking an expander (for `C:\`, in this example) ajaxes in another response from `https://127.0.0.1:8384/rest/system/browse?current=C:%5C` and parses it into `$scope.tree` as follows:
```js
[
  {
    "isroot": true,
    "path": "C:\\",
    "label": "C:\\",
    "tree": [
      {
        "isroot": false,
        "path": "C:\\$RECYCLE.BIN\\",
        "label": "$RECYCLE.BIN"
      },
      {
        "isroot":false,
        "path": "C:\\Program Files\\",
        "label": "Program Files"
      },
      {
        "isroot": false,
        "path": "C:\\Program Files (x86)\\",
        "label": "Program Files (x86)"
      },
      {
        "isroot":false,
        "path": "C:\\ProgramData\\",
        "label": "ProgramData"
      },
      {
        "isroot": false,
        "path": "C:\\Recovery\\",
        "label": "Recovery"
      },
      {
        "isroot":false,
        "path": "C:\\System Volume Information\\",
        "label": "System Volume Information"
      },
      {
        "isroot": false,
        "path": "C:\\Users\\",
        "label": "Users"
      },
      {
        "isroot":false,
        "path": "C:\\Windows\\",
        "label": "Windows"
      },
      {
        "isroot": false,
        "path": "C:\\tools\\",
        "label": "tools"
      }
    ]
  },
  {
    "isroot": true,
    "path": "F:\\",
    "label": "F:\\"
  },
  {
    "isroot":true,
    "path": "G:\\",
    "label": "G:\\"
  },
  {
    "isroot":true,
    "path": "T:\\",
    "label": "T:\\"
  }
]
```
My point is that the per folder display template is 'dumb' (as it needs this preparsed info). And although it's currently tied to `/rest/system/browse` - with the controller parsing each ajax request into this more advanced data structure above, this could easily be changed by moving to a different endpoint that already provides the parsing (prepopulated tree?). The data structure `$scope.tree` I have set up above would also easily support interchangeable 'advanced features' (per directory checkboxes, icons, highlight for directories already in use, etc) as each object property can be easily accessed from the template.

I think that overall the code I have presented can be made to encompass every needed feature without to much effort... It's a simple use of `ng-repeat` used iteratively, so it should be fairly easy for others to understand and extend. 

If the `/rest/db/selections` endpoint is or can be made active again (not listed in https://docs.syncthing.net/dev/rest.html), then I am happy to adjust the code to use this alternate endpoint and whatever format it spits out instead.

**Comment by AudriusButkevicius** [comment]
Sure, but the things I am sure we will need in the short term:

1. Having parts of subtrees provided ahead of time, other part being preloaded later via AJAX,
2. When we need to list files, having the ability to differentiate an empty folder versus an unexpanded folder (in terms of AJAX call not being made yet)
3. Checkboxes.
4. Custom icons for each node/leaf.
5. Ability to get top of all fully selected subtrees (via checkboxes, where a subtree can be a single leaf).
6. Abilities to programmatically expand/select certain parts of the tree.
7. Ability to search the tree and highlight/expand down to the nodes that contain the string

I'll leave it to you to decide whether you want to implement all of this, or just reuse jstree potentially just reskinning it/redoing the templates with ng-repeat.

**Comment by norgeous** [comment]
Yep good info thanks again! Yeah, I think custom coding it with bs/angular inside the controller is the most lightweight and easily debugged. Are there any examples of json responses (for the above 1-7) to base this on?

**Comment by AudriusButkevicius** [comment]
Well the responses can be crafted to look whatever way we want, as long as the tree supports the features.

**Comment by AudriusButkevicius** [comment]
Is this dead, should we close it?

**Comment by lkwg82** [comment]
Seems so, maybe wait for response till the 2nd week of the new year in case of long christmas holidays.

**Pull request closed without merging**
