### PR TITLE
Push model data instead of pull (fixes #1434)

### LINKED ISSUE #1434: Syncthing GUI can inundate Syncthing with pending requests
Hi,

As mentioned in #867, I'm seeing issues where GUI starts sending polls to Syncthing before the previous polls have completed. This snowballs, resulting in the Syncthing having to process lots of duplicate requests. Everything does recover, but it takes a fair while.

Now, Syncthing is running on a low-power device here - an ODROID-C1 - but the GUI could still play more nicely.

I've yet to find a nice way of capturing a single screenshot which contains all the information I want to convey. So, I'll describe what happens for now:

1. Load the GUI. A bunch of requests go out, and typically 'connections' or 'report' can take up to a minute to respond.
2. In the meantime, the GUI has requested the 'model' resource for all folders, and all connections for all devices on all models. This adds up to quite a lot of pending connections!
3. 'system', 'connections', and 'errors' then start stacking up - I can get quite a few simultaneous sets of these 3 before the original holdup clears.

Suggestions:
 - Don't schedule one poll before the previous poll has finished. 
 - Consider limiting the total number of pending requests.

Thanks!

### PR DESCRIPTION
**Pull request by calmh**
Have a look over this one... I don't think it's really ready for merging yet. There's one annoying effect of this, in that the updates lag behind other events like the folder state changes, so we get things like

screen shot 2015-03-27 at 09 19 28

for 10-20 seconds; we're actually done (so the folder state has changed to idle), but haven't received the model update that confirms it yet.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So looks good, but perhaps we should have some sort of way of defining dependencies.
Such as when folder status changes, we should do a recalculation without waiting for the timer to kick in.

Or perhaps we should dispatch folder state updates through the same mechanism and lag for the whole thing.

**Comment by calmh** [comment]
> when folder status changes, we should do a recalculation without waiting for the timer to kick in

Yes. I'll get on this. I think it's the cleaner way.

**Comment by AudriusButkevicius** [comment]
We can actually listen for the FolderStatus events in this new service...

**Comment by calmh** [comment]
@AudriusButkevicius please take another look

**Comment by AudriusButkevicius** [comment]
So apart for that one comment, LGTM.

**Comment by calmh** [comment]
(There may be some inherent raciness there, I'm thinking about it.)

**Comment by calmh** [comment]
@st-jenkins test this please, and get your shit together. random failure suck.

**Comment by AudriusButkevicius** [comment]
Needs an update in the wiki.

**Pull request merged**
