### PR TITLE
gui: Improve Latest Change translation string for better multilanguage support

### PR DESCRIPTION
**Pull request by tomasz1986**
Currently, the "Latest Change" translation string is hard-coded to use
the English-like word order of V ("deleted") + N ("file"). As such, it
is incompatible with languages that require to use a different word
order, e.g. Korean or Japanese. In other words, a proper translation of
the string to those languages is currently impossible.

This commit changes the translation string, so that it includes the file
variable, and thanks to this, it can be easily adopted to languages with
different word order than English.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### CODE REVIEW

**Comment by tomasz1986** [comment]
I understand that this will trigger a re-translation, but as explained in the PR description, I'd argue that this is necessary. In languages like Korean or Japanese, the predicate in a sentence must be placed at the end, and there is no way around it. In this particular case, a proper translation to Korean should be `{{file}} 삭제됨` and `{{file}} 업데이트됨`, however the current hard-coded order of the strings makes this impossible.

**Review by calmh — APPROVED** [review]

**Comment by bugith** [comment]
Shouldn't it be "{{file}}" supprimé and "{{file}}" modifié? I see this in 1.20.0-rc.2 : 
image

**Comment by tomasz1986** [comment]
I'm not 100% what you mean by "supprimé" and "modifié", but the problem right now is that the new non-English language strings haven't been imported from Transifex yet, so the string is present in the English language file only. This is why you're seeing the variable like that.

Thinking about it, wouldn't it be better if the translate script always added new strings to all language files instead of just the English one?

**Comment by bugith** [comment]
Sorry Tomasz (deleted and modified). That's not the problem. When I saw "Deleted {%file%}" I thought the translation string required the quotes around the variables. Not sure, just a guess because some string show the variables quoted when others do not. Whatever, don't worry, I understood "...strings haven't been imported from Transifex yet..."

About your "Thinking about it..." I can't say because when a string is not translated it defaults to english in the GUI isn't it, instead of showing blank. So I can't say... or "thinking about it" myself, maybe adding new strings to all language would have the bad side effect of preventing Transifex to count/display untranslated ones.
Have a good day man and thanks for great ST job.

**Comment by tomasz1986** [comment]
> Not sure, just a guess because some string show the variables quoted when others do not.

Yeah, there are some inconsistencies regarding quotes, but in this case there were no quotes before, so no change's been made in this regard. This commit simply makes the whole string translatable in opposition to the previous partial translation, which didn't work with languages using different word order than English.

> it defaults to english in the GUI isn't it, instead of showing blank

The problem here is that it actually doesn't seem to be the case. The string, translated or not, needs to be present in the specific language file, or otherwise you're presented with what you've just seen, i.e. `Deleted {%file%}` instead of `Deleted somefile.txt`, etc. You should be able to verify this yourself simply by switching the GUI language, e.g. if you switch to English, you can see the proper filename, and then if you switch to something else again, you can only see `{%file%}` in its place. Of course, I'm referring only to the situation at the very moment until Transifex strings are imported.

**Pull request merged**
