### PR TITLE
all: Correct typos in code and docs

### PR DESCRIPTION
**Pull request by HairyFotr**
### Purpose

Correcting typos in code and documentation.

### Authorship

This is my first commit, my name is available in my GitHub profile.

### CODE REVIEW

**Comment by calmh** [comment]
Thanks. The man pages are auto generated from the docs repo so it would be neat if you would like to make the same sweep there.

**Comment by calmh** [comment]
@st-review merge it

all: Correct various typos

Skip-check: authors

**Comment by st-review** [comment]
:ok_hand: Merged as c56c48a7772bb1ef644d96fee1e5e44d8703bbf1. Thanks, @HairyFotr!

**Comment by HairyFotr** [comment]
OK, I'll make a sweep of docs and a few other syncthing projects in a day or two.

**Pull request closed without merging**
