### PR TITLE
all: Disable a few flaky tests

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Gnnh

### CODE REVIEW

**Comment by imsodin** [comment]
I guess your no fan of disabling those on slow build platforms only? They only ever fail on that one.

**Comment by calmh** [comment]
It's apparently like whackamole anyway

**Comment by calmh** [comment]
But no, not really. Tests depending on how fast the builder is is not great, regardless if just one of the builders is below the threshold at the moment. As all the fs tests use the same testScenario rig I guess all of them are about equally susceptible to this?

**Comment by calmh** [comment]
fwiw the Go 1.10 test caching will make this issue moot as the tests won't be rerun nearly as often, assuming we make them compatible

**Comment by calmh** [comment]
ok fuckit

**Pull request closed without merging**
