### PR TITLE
gui: Downgrade Angular 1.5.3 -> 1.2.9 (fixes #2961)

### LINKED ISSUE #2961: gui: Connection error dialog not visible
Just the backdrop.

Chrome on Windows.

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

I haven't been able to figure out the problem, despite a lot of experimenting with this... I tried the latest 1.4.x and 1.3.x as well, and this is the most modern variant that works for us.

### Testing

This now works in my browser...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Doea google not answer the question? Usually there are full of posts about issues like this on SO. Also does the order adjustment trick not work?

**Comment by calmh** [comment]
No, none of that helps at all for me. I even tried a larger reorganization today and moving the modal directive to it's own module added as an explicit dependency of everything, but no dice. Please do give it a try if you feel like it though.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 4b07535e86a4c09f5a268d021047220febac5a35. Thanks, @calmh!

**Pull request closed without merging**
