### PR TITLE
README.md in addition to README-FIRST.txt

### PR DESCRIPTION
**Pull request by maximal**
For better visibility in GitHub web pages.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Having one file is enough, I'd just scrap readme first.

**Comment by calmh** [comment]
I renamed the file instead. Thanks for suggesting this.

**Comment by maximal** [comment]
I would use Markdown there though.
You can add some formatting in future.

**Comment by AudriusButkevicius** [comment]
Yeah like a "Don't modify files here" in the largest possible font in red with many bang signs.

**Comment by maximal** [comment]
!!

**Comment by AudriusButkevicius** [comment]
An idea for bot, auto close PRs referring to files in there.

**Comment by calmh** [comment]
It's not that big of a problem, we can answer them manually for now I think.

**Pull request closed without merging**
