### PR TITLE
Add trailing folder seperator to allow symlinks as folder path (fixes #1361)

### LINKED ISSUE #1361: The path in the gui is not the path in my config file (trailing slash issue)
I noticed that the config file contains something like this:

    <folder path="~/yep/">

but the gui shows a path of:

    ~/yep

### PR DESCRIPTION
**Pull request by eipiminus1**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-jenkins add to whitelist

**Comment by eipiminus1** [comment]
AppVeyor shows that tests don't work on windows.

**Comment by AudriusButkevicius** [comment]
So whats the plan?

**Comment by calmh** [comment]
`filepath.FromSlashes("e:/")` and so on on those tests should work on both Windows & Unixes.

**Comment by eipiminus1** [comment]
Actually I believe there are two problems. First is the Win/Unix file seperator which can easily be fixed by using filepath.Separator.
Then there is the `e:\` thing which I'm not sure I fully understand despite going over https://github.com/syncthing/syncthing/issues/1262. Nevertheless I think I found a way to make everybody happy (at least tested on Arch Linux and Win7).
Commit follows. If it works, should I would open another PR with clean commit history?

**Comment by calmh** [comment]
LGTM. Can you let us know a working email and a name you'd like to be called in the AUTHORS file?

**Comment by calmh** [comment]
Oh, and ideally squash this to a single commit. Something like the following should do:

```
git checkout master
git pull
git checkout issue1361
git rebase -i master
# "pick" one commit, "fixup" the others
git push --force
```

**Comment by eipiminus1** [comment]
Sorry for the delay.

I rebased and fixuped the commit.

@calmh thanks for the commands. It saved me quite some time.
regarding the `AUTHORS` file I would go with "Yannic A." and eipiminus1@users.noreply.github.com.

**Comment by calmh** [comment]
noreply.github.com is not a working email address though. We keep those around because we may need to get in touch with authors.

**Comment by eipiminus1** [comment]
Thats a point. Would eipiminusone+github@gmail.com work then?

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Pull request merged**
