### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by boone**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
You should potentially add yourself to authors.

**Comment by boone** [comment]
@AudriusButkevicius thanks. I'm new to the Synching codebase. Is adding to authors common for such a minor PR?

**Comment by AudriusButkevicius** [comment]
Well, I am fence sitting as it's just comments, so I don't think there is any IP that you own with that commit, but I guess calmh's scripts will scream about you missing in the list of people who made commits.

**Comment by calmh** [comment]
Generally we don't add authors for just typo fixes, but that breaks the build so there's a list of whitelisted commits. I've added this there. Also, I prefer if a maintainer does the adding, as it needs to be done correctly in AUTHORS, NICKS and script/authors.go needs to be run. :)

Thanks for the fixes!

**Pull request merged**
