### PR TITLE
Make links to usage report clickable

### PR DESCRIPTION
**Pull request by uok**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Yeah I am not sure this would work.
Have you tried compiling the assets and seeing what it looks like?

**Comment by uok** [comment]
Do you mean because of the `'`? 
These all seem to work 
  - `translate-value-url='<a href="http://example.com">http://example.com</a>'`
  - `translate-value-url="<a href='http://example.com'>http://example.com</a>"` 
  - `translate-value-url="<a href=&quot;http://example.com&quot;>http://example.com</a>"`

Any preferences?

I changed Syncthing with STGUIASSETS to use the gui folder of git branch. I can see and click the link and Firebug also shows a correct link. I always test to my best knowledge before a PR.

**Comment by uok** [comment]
I checked on stackoverflow and it seems using `&quot;` is recommended. Rebased.

**Comment by AudriusButkevicius** [comment]
I'll run some tests on this to make sure it still works.

**Comment by AudriusButkevicius** [comment]
:+1:

**Pull request merged**
