### PR TITLE
GUI: Fixes Darktheme interface (fixes #5583)

### LINKED ISSUE #5583: White tab in black Interface ?
Hi !
I don't know if it's a normal or not:

White tab color in Dark and Black theme (see screen below)

thx for your work ! this app is very helpfull for a lots of thing !

### Version Information

Syncthing Version: v1.1.0
All version, all browser

image

### PR DESCRIPTION
**Pull request by boomsquared**
###
darkteme
 ## Purpose
 Fixes dark theme interface (fixes #5583)

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Seems like the colours picked do not fit the scheme?

**Comment by AudriusButkevicius** [comment]
Can haz new screenshot? The same issue exists for the black theme too in case you are bored.

**Comment by boomsquared** [comment]
Screen Shot 2562-10-01 at 22 45 30


Should I open a new pull request for the black theme?

**Comment by AudriusButkevicius** [comment]
Looks great.

I assume the black one looks similar?

**Comment by AudriusButkevicius** [comment]
Closing this in favor of the other one

**Pull request closed without merging**
