### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by nbraud**
### Purpose

Fixes typos in messages and manpages

### Testing

Code still compiles and passes tests.
Fix included in the next Debian version for the package.

### CODE REVIEW

**Comment by aviau** [comment]
> Fix included in the next Debian version for the package.

Which I am uploading right now <3

**Comment by aviau** [comment]
@nbraud AFAIK the manpages are maintained in the [docs repository](https://github.com/syncthing/docs).

**Comment by nbraud** [comment]
@aviau Actually, you already authored the doc fix, so I removed it.

**Comment by aviau** [comment]
So now that you have authored a line, my understanding is that you should be in the AUTHORS file. Can you add your name there?

**Comment by aviau** [comment]
So, my understanding is that I should now say:

```
@bot_name merge

lib: fixed typos
```

But I'll wait for somebody to confirm that.

**Comment by aviau** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@aviau: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
Actually no, fixing a typo is also not a copyright able work by itself. (Also these are strings that no user will normally see.)

**Comment by aviau** [comment]
@st-review merge it please

lib: Fix typos in connections/service.go and model/model.go

Skip-check: authors

**Comment by st-review** [comment]
:ok_hand: Merged as 8e39e2889d58401b136e13cb6db9dedc2cf04b4e. Thanks, @nbraud!

**Pull request closed without merging**
