### PR TITLE
lib/db: support Pebble as database backend

### PR DESCRIPTION
**Pull request by calmh**
This is a quick experiment to support Pebble as an alternative database backend. It has an API and a behaviour that is very close to leveldb so the change is quite easy.

### CODE REVIEW

**Comment by calmh** [comment]
Apparently. The mips build was a trivial fix, I fixed it.

**Comment by bt90** [comment]
> Apparently. The mips build was a trivial fix, I fixed it.

https://github.com/cockroachdb/pebble/pull/3005

The first stable release with this fix is only 3 weeks old: https://github.com/cockroachdb/pebble/releases/tag/v1.1.2

Looks like we can have nice things after all @imsodin https://github.com/syncthing/syncthing/pull/8250#issuecomment-1087801664

**Comment by calmh** [comment]
I can say though that without any real tuning, the behaviour was not exactly drop-in-replacement when I tried now for the discovery servers. Memory usage was hilarious and performance ... not great. Doing some reading it seems it's optimised for a custom memory allocator using C malloc/free, which is not available when building CGO_ENABLED=0, which we almost always do.

**Comment by bt90** [comment]
https://github.com/cockroachdb/pebble/issues/1754#issuecomment-1156441165

A bit old but this might still be the case.

**Comment by bt90** [comment]
On a scale of "meh" to "hell no," what is our stance on CGO?

**Comment by calmh** [comment]
It's more that to build with CGO enabled you need a native C toolkit, and we build for like 47 operating systems.

**Comment by imsodin** [comment]
@calmh What's your wish for this: Do you want to get it merged relatively quickly for easier testing, or are you ok with the PR for a bit?  
Basically asking to decide if I do a token/rubber-stamp review now and check it out/review more later on main, or review here. Besides just understanding the code, I intedn to compare to my earlier attempt in the hopes of finding pitfalls or anything that way.

Regarding 32bit support:

From what I see that "support" isn't exactly very supported, at least not upstream. One could follow a link/issue/PR chain starting at the one @bt90 posted tagging me. The gist is:

I did initial work to make it build on 32bit (long while ago), asked for feedback, didn't get any. After some push by other people maintainers gave some input, imo best summarized by these two statements:

> We're not opposed to 32-bit support as long as it doesn't add any additional maintenance burden.

> I’d like to provide some additional context around 32-bit support. While Pebble will (for the most part) work in standalone setups (i.e. when not part of a CockroachDB deployment), it is developed and tested (almost exclusively) with CockroachDB in mind. Given that CockroachDB currently does not target 32-bit architectures, there has historically been no need for such support in Pebble. Our roadmap is currently driven by Cockroach features. https://github.com/cockroachdb/cockroach/issues/8179 in case anyone is interested.

Then people from go-ethereum kept pushing and finished my wip changes and drove them through. Looks like they are currently supporting both goleveldb and pebble as their DB. And there's quite a bit of noise around performance of the db on their side, but it seems to be working well now (no wonder performance matters there, it's blockchain, reducing the computing waste to just the inherent waste is kinda their main thing, besides trying to get square peg into a round hole in a vain search for an application of their tech).

I have no clue what systems people run go-ethereum nodes on, i.e. if those systems cover a similar range as ours. If they do and pebble adoption is high, support by go-ethereum might mean it's actually functional enough on a dev set relevant to us (which to me seems to be every turing compute system that exists :P ) - I am not entirely convinced though. And generally an upstream not caring about the use-case isn't great. Go-ethereum likely has no appetite of main maintainership if anything breaks upstream, otherwise I'd expect they'd have picked up goleveldb. Then again goleveldb is basically abandonware, so it's likely still an improvement.

**Comment by bt90** [comment]
IMHO the main concern is if we're able to use pebble without CGO and with reasonable memory/CPU usage.

**Comment by imsodin** [comment]
Ah right I missed that comment you linked (https://github.com/cockroachdb/pebble/issues/1754#issuecomment-1156441165):

> If you plan to use Pebble in production setting, you definitely want to run with CGO enabled.

If this is authoritative, then afaik that's indeed a nogo. And the commenter is the main contributor to pebble (by far), so I think we can treat it as authoritative. Unless we consider having multiple backends, depending on the platform/cgo feasibility.

**Comment by calmh** [comment]
Yeah it's unfortunate. I ran this for a week at home and didn't see any adverse effects, but I also tried it on the discovery servers and it blew up spectacularly so there are definitely aspects for larger installations. I think close for now, but the leveldb situation remains a background problem.

**Pull request closed without merging**
