### PR TITLE
Added systemd files to the deb build

### PR DESCRIPTION
**Pull request by Moeplhausen**
I don't really know about  Debian packaging. Anyway, I'd like to have the systemd files into the .deb and here is a mini patch to do that.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by Moeplhausen** [comment]
Sorry for that git mess. I better stop trying to fix that now :S

**Comment by calmh** [comment]
:D

**Comment by hadogenes** [comment]
Why this is closed?
The files aren't in deb packages.

BTW On debian there the systemd files are in /lib/systemd not in /usr/lib/systemd

**Comment by calmh** [comment]
I think @Moeplhausen just fumbled it a bit; I expect there'll be a new one with the right files in the right places and whatnot.

**Comment by rumpelsepp** [comment]
> BTW On debian the "system" systemd files are in /lib/systemd not in /usr/lib/systemd, the "user" files are in /usr/lib/systemd

Pretty sure, that the "user" files are not in `/usr/lib/systemd`, see http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20Load%20Path

The admin can overwrite files provided by packages in `/etc/systemd`. I have a debian VM somewhere and I will have a look.

**Comment by hadogenes** [comment]
No, you are right, by "system" I mean /lib/systemd/system and "user" /usr/lib/systemd/user

**Pull request closed without merging**
