### PR TITLE
lib/connections: More fine grained locking (fixes #3066)

### LINKED ISSUE #3066: Deadlock when connecting
```
goroutine 67 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0xc82041bb2c)
        /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*RWMutex).RLock(0xc82041bb20)
        /usr/local/go/src/sync/rwmutex.go:37 +0x58
github.com/syncthing/syncthing/lib/connections.(*Service).CommitConfiguration(0xc821aa3a40, 0xd, 0xc82002b800, 0x3, 0x4, 0xc820064000, 0x3, 0x4, 0x1, 0xc8204c5bc0, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/service.go:405 +0x2d4
github.com/syncthing/syncthing/lib/config.(*Wrapper).replaceLocked(0xc8200c3600, 0xd, 0xc821ec0600, 0x3, 0x3, 0xc821948b40, 0x3, 0x3, 0x1, 0xc8204c5bc0, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/config/wrapper.go:153 +0x734
github.com/syncthing/syncthing/lib/config.(*Wrapper).SetDevice(0xc8200c3600, 0x22d33fe030900e17, 0xe217936a7da3cc8c, 0x554dd932a7e97d0a, 0x1c494e2220a0eadf, 0xc822f7ce88, 0x4, 0xc8201acb40, 0x1, 0x4, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/config/wrapper.go:202 +0x31d
github.com/syncthing/syncthing/lib/model.(*Model).AddConnection(0xc8200883c0, 0xc820310000, 0x864210, 0xc, 0xa, 0x17145f0, 0xc822f7cf10, 0xc822f7ce88, 0x4, 0xc822f7ce90, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:1053 +0xfe5
github.com/syncthing/syncthing/lib/connections.(*Service).handle(0xc821aa3a40)
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/service.go:226 +0x1d53
github.com/syncthing/syncthing/lib/connections.(*Service).(github.com/syncthing/syncthing/lib/connections.handle)-fm()
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/service.go:102 +0x20
github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0xc8216f9750)
        /Users/jb/src/github.com/syncthing/syncthing/lib/connections/structs.go:73 +0x19
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0xc820855520, 0x1, 0x1709950, 0xc8216f9750)
        /Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/suture.go:556 +0x5e
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService
        /Users/jb/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/suture.go:559 +0x51
```

Or, with words,

1. Connection service calls AddConnection while holding the connection service lock
1. AddConnection updates the device name and calls config.SetDevice
1. config.SetDevice calls CommitConfiguration everywhere
1. Connection service CommitConfiguration wants the lock

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This fixes the deadlock by reducing where we hold the various locks. To
start with it splits up the existing "mut" into a "listenersMut" and a
"curConMut" as these are the two things being protected and I can see no
relation between them that requires a shared lock. It also moves all
model calls outside of the lock, as I see no reason to hold the lock
while calling the model (and it's risky, as proven).

### Testing

Things connect, now.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So this potentially brings back the connected to already connected issue, if we don't lock around AddConnection and ConnectedTo

**Comment by calmh** [comment]
How does that happen, again?

**Comment by AudriusButkevicius** [comment]
T1 checks connectionType map, no value
T2 does model.AddConnection
T2 sets connectionType map
T1 checks model.ConnectedTo and prints message

**Comment by calmh** [comment]
So if one connection comes in at the same time as we're dialing, one will get hit by "already connected" which is fine?

**Comment by AudriusButkevicius** [comment]
I am as always on my phone so hard to have a proper discussion, though what you are saying sounds like true.

I think the caching discovery mux absorbs the frequent lookups?

**Comment by calmh** [comment]
Some of them, but I think it still lets through a global discovery query per five or ten minutes or something. But that's an easy optimization for another commit. :)

**Comment by AudriusButkevicius** [comment]
So whats the plan? Are we pushing this and following it up or whats the plan.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by calmh** [comment]
From my POV yes as it fixes the problem I see, and I don't think I see the other problem if it's here. :)

**Comment by st-review** [comment]
:ok_hand: Merged as 31f64186ae03999b2709782a523f7e7e7f510dbe. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
Well the other problem is definately there, as thats what I tried to fix by using wider scope for the locks.

**Comment by calmh** [comment]
I remember that issue being about us not switching connections properly. I'll see if I can find it later.

**Pull request closed without merging**
