### PR TITLE
lib/model: Refactor Index/IndexUpdate

### PR DESCRIPTION
**Pull request by imsodin**
The only behaviour this PR changes is the debug logging format (contents are the same). The rest is just less lines for the same thing.

### CODE REVIEW

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 93b5180e62854ecd45a0063f85cdeac64372a429. Thanks, @imsodin!

**Comment by AudriusButkevicius** [comment]
Tbh we should drop one of the messages.

**Pull request closed without merging**
