### PR TITLE
Encrypted devices (WIP)

### PR DESCRIPTION
**Pull request by Lennix**

### CODE REVIEW

**Comment by calmh** [comment]
High level things that hit me (apart from stuff already mentioned in [the forum thread](https://forum.syncthing.net/t/encrypted-nodes-please-test/5295), looking more at implementation details here):

- It'd be ideal if the encrypted side didn't need to know it was encrypted. In fact, what happens if we don't tell it and there's a mismatch between the two sides in their assumption about the encryptedness?

- There's too much code duplication here between the rw and enc folder types. You don't necessarily need to fix that, but before merging this I think we need to do some refactoring to break out common parts into something more sensible, so be prepared for that to happen. :) It's been on the todo list for a while but this makes it more urgent.

- Do symlinks survive the passage? Are they encrypted?

**Comment by calmh** [comment]
File name encryption seems mostly sane; possibly we need to add some hierarchy to it but that's trivial. However, I can check if you have a given file or not by comparing the filename hashes. This is more difficult as I don't know the directory prefix, but may still be an issue?

- PBKDF per crypto operation is unnecessarily expensive; some other way here would be nice - use an IV and stash it somewhere?

- This doesn't encrypt the file content hashes, which means I can check if you have a given file by comparing the hashes with an unencrypted copy of that file.

- This doesn't hide file modification times and so on. Do we need this? I don't see a reason we *need* to expose it, and the less data we give an attacker the better?

- Do we want data verification on the encrypted devices? Spontaneously, I do, but I can't say it's super essential...

**Comment by calmh** [comment]
Discussion in https://forum.syncthing.net/t/encrypted-nodes-please-test/5295 until we get into nitty gritty code review :)

**Comment by calmh** [comment]
I'm guessing this is rather stalled?

**Comment by eschnepel** [comment]
I would really appreciate this feature once it is available.

**Comment by calmh** [comment]
Closing as stalled, reopen as required :)

**Pull request closed without merging**
