### PR TITLE
Enable -logfile on all platforms (fixes #2004)

### LINKED ISSUE #2004: Documentation of log-file options
If I understand correctly, Syncthing writes out log messages on stdout. So, the nature of logging and the location of log file, if any, depends on the how Syncthing was started. Would it be possible to document simple ways of logging (something similar to http://docs.syncthing.net/users/autostart.html would be great)?

I think on windows logfile is saved in configuration directory. Is it too much work to have an option to have the same behavior on all OS?

BTW, I use following on linux to log to syslog. Works great!

```
/home/bin/syncthing-linux-amd64/syncthing 2>&1 | logger -t [SYNCTHING]
```

### PR DESCRIPTION
**Pull request by Zillode**
(optional)

### CODE REVIEW

**Comment by calmh** [comment]
Is there a cleaner way to do this that doesn't flip the logFile variable between the empty string and dash back and forth?

**Comment by Zillode** [comment]
@AudriusButkevicius ?

**Comment by AudriusButkevicius** [comment]
You should default the log to -, then where the no-console option is added, change that to locations[logFile] for windows, and then cut down on the ifs.

**Comment by calmh** [comment]
There's some annoyance here as we need to set the defaults before parsing options, but the default is dependent on the home dir which is set by parsing the options.

**Comment by calmh** [comment]
How about just skipping the Windows specialness and always defaulting to a log file?

https://github.com/calmh/syncthing/commit/c5ae8a3114d4c4f09176645a88276da4982c52db

**Comment by AudriusButkevicius** [comment]
I suggest no, because on Linux the daemon usually runs unattended on machines with long uptime, hence it could grow out of hand.
I suggest we keep stdout as standard for Linux.

**Comment by calmh** [comment]
That's also an argument against enabling the flag at all on non-Windows, to be honest. It's the slippery slope towards having to implement log rotation and so on that I'd rather avoid. :)

**Comment by AudriusButkevicius** [comment]
So I like having the flag on Linux, just not enabled by default.

**Comment by calmh** [comment]
Then again, on Linuxes this doesn't actually buy us anything? As it's essentially equivalent to `syncthing > mylogfile` or `syncthing | tee mylogfile`...

**Comment by Zillode** [comment]
I prefer `""` compared to `"<default>"`. Tee works as well, but only if you know it;)

So we can drop this, as I proposed this as an optional pr anyway, however I think it is a useful feature even on linux.

**Comment by calmh** [comment]
OK, so how about https://github.com/calmh/syncthing/commit/94884bc494e521f6b525ab7073e6448ebe2823a3 ?

It removes one if clause and retains the desired behavior.

**Comment by Zillode** [comment]
:+1:

**Comment by calmh** [comment]
#2206

**Pull request closed without merging**
