### PR TITLE
New debug logging infrastructure

### PR DESCRIPTION
**Pull request by calmh**
Todays plane hacking...

This implements a new debug/trace infrastructure based on a slightly hacked up logger. Instead of the traditional "if debug { ... }" I've rewritten the logger to have no-op Debugln and Debugf, unless debugging has been enabled for a given "facility". The "facility" is just a string, typically a package name. (Audrius pushed for this a while back and I was opposed; I think the advantages overweigh this time, and doing it with the current "if debug" stuff isn't practical as it requires locking and package-global variables and so on anyway, and ends up being what this is....)

This will be slightly slower than before; but not that much as it's mostly a function call that returns immediately. For the cases where it matters (the Debugln takes a hex.Dump() of something for example, and it's not in a very occasional "if err != nil" branch) there is an l.ShouldDebug(facility) that is fast enough to be used like the old "if debug".

The point of all this is that we can now toggle debugging for the various packages on and off at runtime. There's a new method /rest/system/debug that can be POSTed a set of facilities to enable and disable debug for, or GET from to get a list of facilities with descriptions and their current debug status.

Similarly a /rest/system/log?since=... can grab the latest log entries, up to 250 of them (hardcoded constant in main.go) plus the initial few.

Not implemented in this commit (but planned) is a simple debug GUI available on /debug that shows the current log in an easily pasteable format and has checkboxes to enable the various debug facilities.

The debug instructions to a user then becomes "visit this URL, check these boxes, reproduce your problem, copy and paste the log". The actual log viewer on the hypothetical /debug URL can poll regularly for new log entries and this bypass the 250 line limit.

The existing STTRACE=foo variable is still obeyed and just sets the start state of the system.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
It's a bit large, but I've skimmed through it and it looks fine.

**Comment by AudriusButkevicius** [comment]
I am happy to merge, and we'll fix it later if its broken

**Comment by Zillode** [comment]
:+1:

**Comment by dcarosone** [comment]
One tip to consider, something I really like from the log facility I use in
perl, and have seen in some other frameworks:

Have a log call which takes the message content as a closure which will
return the text when called.

Very useful where logging might not be enabled, and generating the text
could be expensive, as the closure need never be called. Once you develop
the habit of using it, you tend to wrap more debug stuff into the closure
to produce better messages, because you can.

**Comment by calmh** [comment]
@dcarosone This is somewhat similar to that, as `Debugf("foo %v", bar)` will never format that string or inspect `bar` unless debugging is enabled.

**Pull request merged**
