### PR TITLE
gui: Allow to translate and fix incorrect Versions date filter ranges

### PR DESCRIPTION
**Pull request by tomasz1986**
Translate the previously English-only ranges used in Versions date
filter. In the process, fix the currently incorrect range calculation.

For instance, let us say it is 08:05. Selecting "today" should set the
range to start at 00:00 and end at 08:05. However, what really happens
is that both start and end are set to 08:05, and as a result "today" is
never shown to the user. The case is the same for "yesterday", which in
contrary to "today" is shown, but its range is fixed at 08:05 on the
previous day.

This commit fixes the above by always calculating "today" starting at
00:00 up to the current moment, and calculating "yestarday" from 00:00
to 23:59:59 on the previous day.

When it comes to "last x days", the commit fixes the calculation so that
it actually covers the whole day, which is done by moving the start date
to 00:00 on the first day.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

#### Before

- Today missing.
- Yesterday fixed at specific time.

  image

- Last 7 Days and Last 30 Days not starting at 00:00.

  image
  image

#### After

- Today actually shown and calculated from 00:00.

  image

- Yesterday covering the whole previous day.

  image

- Last 7 Days and Last 30 Days starting at 00:00 on the first day.

  image
  image

### CODE REVIEW

**Comment by acolomb** [comment]
How would one see things happen if after 23:59:59,but before midnight? I think you are filtering out that one second per day? 24:00:00 or in that case 0 on the next day would make more sense.

**Comment by tomasz1986** [comment]
Hmm, but then a file modified exactly at 00:00:00 would be included in both "yesterday" and "today"…

As far as I understand the smallest unit is second here, so it's either 23:59:59 or 00:00:00, and nothing in between.

**Comment by acolomb** [comment]
It depends on the comparison operator used and on the resolution of the value to be compared.  If that is only seconds, you might be right.  But still, `00:00:00 <= x < 23:59:59` would lose that one second.  `00:00:00 <= x < 1d+00:00:00` would work regardless of resolution.  `00:00:00 <= x <= 23:59:59` only works when the thing being compared is truncated to seconds in advance.  So what I suggested is as robust as possible, but what matters is the comparison operator.

This is all very unlikely stuff, but robust code works for every corner case, no matter how small.  Stuff happening during that one second is still more likely than exactly at 00:00:00 anyhow.

**Comment by tomasz1986** [comment]
What should we do about "Last Month" though? Right now, it also ends at 23:59:59 of the last day.

**Comment by acolomb** [comment]
Yes, I'd do it consistently.

**Comment by tomasz1986** [comment]
> Yes, I'd do it consistently.

Done. I've also removed the superfluous `.endOf('month')` from "This month".

**Review by acolomb — APPROVED** [review]

**Pull request merged**
