### PR TITLE
gui: Make warning titles more readable in Dark Theme

### PR DESCRIPTION
**Pull request by norgeous**
before:
untitled

after:
untitled

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 8709fec517cc1b3f5232ef6ff44ff6a49695d565. Thanks, @norgeous!

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/3253/head:pr-3253
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   48245ef..8709fec  master     -> orig/master
$ git reset --hard
HEAD is now at 8709fec gui: Make warning titles more readable in Dark Theme
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 8709fec gui: Make warning titles more readable in Dark Theme
$ git clean -fxd
Skipping repository syncthing/syncthing
Skipping repository syncthing/syncthing-android
Skipping repository syncthing/docs
Skipping repository syncthing/discosrv
Skipping repository syncthing/syncthing-gtk
Skipping repository syncthing/syncthing-inotify
$ git merge --squash --no-commit pr-3253
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Comment by calmh** [comment]
⚡

**Pull request closed without merging**
