### PR TITLE
docs: Correct Docker README (#5480)

### PR DESCRIPTION
**Pull request by Dargmuesli**
Plus some formatting.
If you rather wish to add a `VOLUME` tag to the Dockerfile, feel free to close this alternative solution.

### CODE REVIEW

**Comment by jordanpotter** [comment]
Thoughts on actually making `/var/syncthing/config` a mount point in the `Dockerfile` instead? :thinking:

**Comment by Dargmuesli** [comment]
I'm not sure if volumes inside volumes work without issues. I suspect that that they don't, leading to #5480.

**Comment by AudriusButkevicius** [comment]
How is your comment relevant tto this PR tho?

**Comment by Dargmuesli** [comment]
Which comment are you referring to?

**Comment by jordanpotter** [comment]
I think he was referring to my comment? If so, I was asking about an alternative solution also related to https://github.com/syncthing/syncthing/issues/5480

@Dargmuesli really good point. My thinking was the following:

As a consumer of the Docker image and a user of data volumes semi-religiously, I would want to create a data volume for `/var/syncthing/config` to store all the configuration files. I'm not sure why I would want a data volume for `/var/syncthing`, which also stores the default sync folder.

**Comment by Dargmuesli** [comment]
True. I just `exec`ed into my container and found that `/var/syncthing/` only contains the `config` folder. Can someone confirm that `/var/syncthing/` really doesn't contain anything else?

**Comment by jordanpotter** [comment]
Looks like it also contains the default sync folder. From inside a fresh container:
```
# find /var/syncthing/
/var/syncthing/
/var/syncthing/config
/var/syncthing/config/https-cert.pem
/var/syncthing/config/https-key.pem
/var/syncthing/config/key.pem
/var/syncthing/config/index-v0.14.0.db
/var/syncthing/config/index-v0.14.0.db/MANIFEST-000017
/var/syncthing/config/index-v0.14.0.db/LOCK
/var/syncthing/config/index-v0.14.0.db/CURRENT
/var/syncthing/config/index-v0.14.0.db/000015.ldb
/var/syncthing/config/index-v0.14.0.db/000016.log
/var/syncthing/config/index-v0.14.0.db/000014.ldb
/var/syncthing/config/index-v0.14.0.db/LOG
/var/syncthing/config/config.xml
/var/syncthing/config/cert.pem
/var/syncthing/Sync
/var/syncthing/Sync/.stfolder
```

**Comment by jordanpotter** [comment]
What if the mount points were instead `/var/syncthing/config` and `/var/syncthing/Sync`? That way the configuration could be in a separate volume from the data.

**Comment by AudriusButkevicius** [comment]
And break every existing user in the world.

**Comment by AudriusButkevicius** [comment]
Why can't you just mend the config in the same mount point?
Anyways, this is severly off topic and not related to this PR so should be moved elsewhere (forum ideally).

**Comment by jordanpotter** [comment]
> And break every existing user in the world.

That's not completely accurate. The official Docker `syncthing/syncthing` repo has tags available for this reason.

> Why can't you just mend the config in the same mount point?

I feel the spirit of Separation of Concerns would say config and data should be separate. But I 100% see your point.

> Anyways, this is severly off topic and not related to this PR so should be moved elsewhere (forum ideally).

Sounds good! I'll start a conversation there. Thank you :+1:

**Pull request merged**
