### PR TITLE
lib/ignore: Replace lib/fnmatch with github.com/gobwas/glob

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This globbing library is literally *ten times* faster than my fnmatch implementation:

```
benchmark                  old ns/op     new ns/op     delta
BenchmarkMatch-8           13842         1200          -91.33%
BenchmarkMatchCached-8     139           147           +5.76%
    
benchmark                  old allocs     new allocs     delta
BenchmarkMatch-8           0              0              +0.00%
BenchmarkMatchCached-8     0              0              +0.00%
    
benchmark                  old bytes     new bytes     delta
BenchmarkMatch-8           12            0             -100.00%
BenchmarkMatchCached-8     0             0             +0.00%
```

### Testing

Our ignore implementation is actually fairly well covered by unit tests so this doesn't worry me so much.

### Documentation

This is API breakage as we no longer return the compiled patterns as regexps (there are no regexps). Instead we return the original patterns, but expanded as we've done while parsing them and explicitly indicating case insensitiveness (which in my case comes by default as this is on Mac). Example new format:

```
{
  "ignore": [
    "/Backups"
  ],
  "patterns": [
    "(?i)/Backups",
    "(?i)/Backups/**"
  ]
}
```

### CODE REVIEW

**Comment by calmh** [comment]
Hm, there's a little bit more work to do here around Windows file path separators.

**Comment by calmh** [comment]
So frankly I get a little confused when looking at our current implementation. We look for things like strings starting with "/**" - don't we support using "\" in patterns on Windows? Shouldn't we?

**Comment by AudriusButkevicius** [comment]
I think the ignores are always supposed to be linux separators

**Comment by AudriusButkevicius** [comment]
The only problem I see with this is that inotify uses this, and whoever else wants to use this, has to implement the grammar themselves (unless they use go and can use the same library)

**Comment by calmh** [comment]
I think that at the very least we should support both, on Windows. `//` will need to be a comment no matter what, but both `foo\bar\**` and `foo/bar/**` *should* be valid patterns.

**Comment by calmh** [comment]
I think the grammar has always been "glob patterns" which doesn't change. That we exposed the regexps were an unfortunate implementation detail that I added for debugging purposes, and that then got used... :/

**Comment by AudriusButkevicius** [comment]
So the definition of glob patterns is not very defined. I think this library supports c{ow,at} type of globs which others languages might not have.

**Comment by canton7** [comment]
If you change the format of "patterns" away from regexes, I'll probably crash as .NET tries to compile invalid regexes. If you change the key to something like "glob_patterns", I'll be a lot happier :smile: 

Not sure how much you care about inotify implementations not telling Syncthing about changes to ignored files: if you're planning on integrating that into Syncthing for 0.13 then of course it doesn't matter...

**Comment by calmh** [comment]
It also exposes a bug in our previous implementation, IMHO. We expect `**/efile` to match `efile` at the top level, which this library does not...

**Comment by calmh** [comment]
> Not sure how much you care about inotify implementations not telling Syncthing about changes to ignored files

It's pretty much an optimization. We should ignore them anyway and do nothing. We might have a bug though where we do a full scan when asked to scan just an ignored file; need to double check that.

**Comment by calmh** [comment]
I added a test to verify that we understand both `a/b` and `a\b` on Windows (we're supposed to not handle escapes on Windows, which should mean we understand both kinds of slashes as path separators).

**Comment by calmh** [comment]
Can someone with a Windows box run 

```
cd lib/ignore
go test -run None -bench . -benchmem
```

on both `master` and this branch? I wonder how painful the slashification is on Windows.

**Comment by canton7** [comment]
Master:

```
$ go test -run None -bench . -benchmem
PASS
BenchmarkMatch     30000             50419 ns/op               1 B/op          0 allocs/op
BenchmarkMatchCached     5000000               244 ns/op               0 B/op          0 allocs/op
ok      github.com/syncthing/syncthing/lib/ignore       3.585s
```

calmh/glob:
```
$ go test -run None -bench . -benchmem
PASS
BenchmarkMatch    500000              3057 ns/op               0 B/op          0 allocs/op
BenchmarkMatchCached     5000000               242 ns/op               0 B/op          0 allocs/op
ok      github.com/syncthing/syncthing/lib/ignore       3.071s
```

**Comment by calmh** [comment]
Ok so enormously faster on Windows too. To me that nails it - it's worth the pain of no longer exposing regexps.

**Comment by AudriusButkevicius** [comment]
So my browser refuses to switch to the code tab for 60 files. Did you rename the key as canton7 asked?

**Comment by calmh** [comment]
No, I haven't. I will!

As for the diff, all the interesting things are on ignore.go, the rest is just a dependency shuffle.

**Comment by calmh** [comment]
```diff
--- a/cmd/syncthing/gui.go
+++ b/cmd/syncthing/gui.go
@@ -933,8 +933,8 @@ func (s *apiService) getDBIgnores(w http.ResponseWriter, r *http.Request) {
        }
 
        sendJSON(w, map[string][]string{
                "ignore":   ignores,
-               "patterns": patterns,
+               "parsed": patterns,
        })
 }
 ```

**Comment by calmh** [comment]
Does github... duplicate every line break in the commit message? Wtf?

**Pull request merged**
