### PR TITLE
Improve protocol tests, close handling

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by calmh** [comment]
doubleyou tee eff...

**Comment by calmh** [comment]
Nooo... This was still broken. Although I can't for the life of me understand why.

**Comment by AudriusButkevicius** [comment]
So the build seems to have passed, the mac one just had no outcome.

**Comment by calmh** [comment]
Mac one spuriously failed the message type test... There's something weird going on here, as my change yesterday shouldn't have affected any of the tests anyway. Confusing.

**Comment by calmh** [comment]
Could be there is a race of some kind in those tests, connection becoming closed for another reason than the one being tested, say the ioutil.Pipe thing returning eof or something.

**Pull request merged**
