### PR TITLE
add gh actions to build and publish multiarch images to dockerhub

### PR DESCRIPTION
**Pull request by Migelo**
### Purpose

As discussed in  #8691 I started updating the build system to automatically build syncthing and related programs and publish them to dockerhub.

### Testing

I used the working gh actions from my [docker-syncthing-relay repo](https://github.com/Migelo/docker-syncthing-relay).
You can also check my fork and the finished action where all arches successfully finished building [here](https://github.com/Migelo/syncthing/actions/runs/4479225264).

Or the latest one where I only build for `amd64` so we can iterate more quickly on this PR.

### Todo

1. How to implement automatic tagging of docker images with the correct version. The commented out portion of my changes are how I deal with automatic versioning by setting it manually in `Dockerfile` and then greping it from there and into gh actions.
2. The repo owner has to add their `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` under `Settings->Security->Secrets and variables->Actions`

### CODE REVIEW

**Comment by imsodin** [comment]
Isn't docker hub killing the free tier, or was that a storm in a teacup? If it isn't, maybe that's a good reason to move to e.g. ghcr while adding this anyway. I guess @calmh you own the docker syncthing org - did you get any news on that?

**Comment by imsodin** [comment]
>  In any case, I'm happy to update this PR to include a push to gh registry.

I should have made this clearer before, sorry: Please don't change anything in this PR (yet).

> From my understanding syncthing aren't offering a paid version of their software neither do they offer paid support so it should be ok?

My understanding is that doesn't matter, everyone gets to pay. Resp. there's a track for open source software, but apparently it's cumbersome/slow. Referring to stuff like this:
https://news.ycombinator.com/item?id=35154025
https://github.com/docker/hub-feedback/issues/2314
Then again I don't have first hand knowledge and can't easily find anything definitive. So maybe there's no issue at all, just wanted to check whether @calmh is already aware of issues, resp. got such an email from docker about cost/cancellation.

**Comment by calmh** [comment]
It's on my radar to sort out and apply for the open source thing, though the form was annoying and I got side tracked.

**Comment by Migelo** [comment]
You don't have to worry about it anymore. They walked back the whole thing: https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

**Comment by Migelo** [comment]
If there is still interest in merging this, I am happy to work on it.

**Comment by calmh** [comment]
There is, it just needs some tweaks to how Syncthing is built. Currently there's a Dockerfile.buildx that we use for the multi arch builds, which expects binaries to already be present. We compile the binaries prior to the docker step:

```
for arch in amd64 arm arm64 ; do
	go run build.go -goos linux -goarch $arch -no-upgrade build syncthing
	mv syncthing syncthing-linux-$arch
done
```

**Comment by Migelo** [comment]
I am not sure what I should do here, could you please give me some pointers please? All the checks seem to pass so idk where to start.

**Comment by Migelo** [comment]
Aha, I see

```
COPY ./syncthing-linux-$TARGETARCH /bin/syncthing
```
this file has to be present and is what you were referring to, right?

**Comment by calmh** [comment]
Thanks for this @Migelo I've incorporated your changes into the build setup, and marked you as co-author of the commit in question.

**Pull request closed without merging**
