### PR TITLE
Disable missing syscall on android-amd64, support AVD 12+ and Chromebook arch x86_64

### PR DESCRIPTION
**Pull request by Catfriend1**
### Purpose

Without this PR, "libsyncthing.so" (SyncthingNative) crashes with "bad syscall error".
ref: https://github.com/Catfriend1/syncthing-android/issues/583#issuecomment-1341022101

Affected: Both Syncthing(Android) and Syncthing-Fork (for Android). The missing syscall is called by "unix.EpollWait" from the god module "github.com/syncthing/notify". "unix.EpollWait" is part of "golang.org/x/sys". Upgrading "golang.org/x/sys" to the most recent version 0.3.0 doesn't solve the problem. So I've made this PR. 

Issue: https://github.com/syncthing/syncthing-android/issues/1703

### Testing

Verified on Android AVD 13. The disabled syscall (unix.epollwait) which isn't available on android-amd64 arch allows SyncthingNative to run without the file watcher. Platforms using this arch are for example: Android emulator >= 12, Google Chromebook. The arch is also labeled "x86_64" in app/src/jniLibs.

### Screenshots

image

### Documentation

ref: https://github.com/Catfriend1/syncthing-android/issues/583

Please go light on me, I don't know much about the go stuff and appreciate any help on this. My main goal isn't dealing with the affected go lib or syscall stuff but I really need my Android emulator be able to execute the Syncthing Android app to continue my work on newer API levels and Android releases 12+.

## Authorship

Catfriend1

### CODE REVIEW

**Comment by calmh** [comment]
Could you give #8710 a spin, which I think is a cleaner way to disable the watcher on android/amd64?

**Comment by bt90** [comment]
Can we check if epollWait is implemented without triggering a crash? That would be the cleanest approach IMHO.

**Comment by Catfriend1** [comment]
> Can we check if epollWait is implemented without triggering a crash? That would be the cleanest approach IMHO.

I don't know if this is possible in Go. I've tracked the crash down this way:

basicfs_watch.go > gomod/notify > gomod/x/sys (provides unix.epollwait)

Another dirty workaround I've tried out yesterday is blanking the function "loop" in gomod/notify as that's the place where unix.epollwait is called. But without it, there would be no watching and that's why we are currently discussing disabling the basicfs_watch capability on this rarely used platform.

**Comment by Catfriend1** [comment]
Superseded by #8710

**Pull request closed without merging**
