### PR TITLE
Added test for conflict detection with scans from single device.

### PR DESCRIPTION
**Pull request by Zillode**
This is unit test for a major bug which shows that ST simply overwrites data without generating a conflict. The missing conflict detection manifests itself when modifications are made to both devices on a single file at the same time. When one of those devices discovers a change during a scan and exchanges it index before the other node scanned.

It seems the puller does not check whether the file has been updated since the last scan interval. This means modified content is simply overwritten.

### CODE REVIEW

**Comment by Zillode** [comment]
@st-jenkins run integration tests on windows

**Comment by Zillode** [comment]
@st-jenkins run integration tests for linux

**Comment by Zillode** [comment]
```
--- FAIL: TestConflictSingleScan (15.68s)
	conflict_test.go:256: Expected 1 conflicted files instead of 0
```

**Comment by fsateler** [comment]
I have just been bitten by the bug this test detects. This is quite an ugly, as it causes data loss.

**Comment by Zillode** [comment]
Please use [syncthing-inotify](https://github.com/syncthing/syncthing-inotify) or help with a patch:)

**Pull request closed without merging**
