### PR TITLE
fix language menu for small screen devices

### PR DESCRIPTION
**Pull request by ralder**
pr-bugfix

### CODE REVIEW

**Comment by calmh** [comment]
What's the fix - screenshot?

**Comment by ralder** [comment]
fix-menu
and also moved menu "Help" into "Actions" for small screens

**Comment by uok** [comment]
Thanks, looks great!
Is it possible to rename "actions" to "menu" with icon "glyphicon-menu-hamburger" ?

**Comment by calmh** [comment]
Does "Menu" say something more than "Actions"?

**Comment by calmh** [comment]
:+1:

**Pull request merged**
