### PR TITLE
gui: Hide "allowed networks" if empty

### PR DESCRIPTION
**Pull request by uok**
### Purpose

Hide line for "allowed networks" (advanced config) in device panel if it is empty.

### Testing

yep

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Hold on. Empty string is false'ish, no? Why is this needed then? This also breaks for null/undefined values.

**Comment by uok** [comment]
I was expecting if advanced config is not (never was in my case) set that the line isn't displayed.  That's why I created this PR. I'm open to suggestions for possible values to check for

**Comment by calmh** [comment]
FWIW, I have the problem too:

screen shot 2018-06-05 at 19 53 50

I think it stems from the fact that this is an array, and an empty array in Javascript is trueish... I can't vouch for the fix; it might work because Angular stringifies the empty array to the empty string.

**Comment by AudriusButkevicius** [comment]
It seems stringification is done afterwards, so you probably need what we had there already && arr.length > 1

**Comment by uok** [comment]
I checked config.xml: entry "<allowedNetwork>...</allowedNetwork>` only exists if it is set. So in my case (and probably 99% of all users) there is no entry at all.
A few lines down in index.html I found a similar check for folders array so I updated the PR to use this method.

**Pull request merged**
