### PR TITLE
Fix STGUIAPIKEY and STGUIADDR overrides (fixes #2335)

### LINKED ISSUE #2335: STGUIAPIKEY and friends is broken
I broke this in 36ac757 as we no longer use the "overridden" config, but the actual on disk config.

### PR DESCRIPTION
**Pull request by calmh**
Also removes STGUIAUTH and corresponding --gui-authentication as this
seems fundamentally insecure and I'm unsure of the actual use case for
it?

I recommend the [white space insensitive diff](https://github.com/syncthing/syncthing/pull/2336/files?w=1) on this one.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
We should mention the removal of that option in the release notes.

**Comment by calmh** [comment]
Yep

**Comment by calmh** [comment]
@st-jenkins run integration tests please

**Pull request merged**
