### PR TITLE
lib/fs: Unwrap mtimeFile, get fd the "correct" way (ref #6875)

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
So the crux of the problem is the fact they are wrapped in mtimefs.

I thought about doing an interface assertion instead, but some of the implementations call Stat() which again might return basicFileInfo or mtimeFileInfo, so I am not sure I can  do an assertion on a function with yet another generic interface return value?

This also addresses stuff discussed in golang/go#24331

Let's see if this passes the tests.

### CODE REVIEW

**Comment by calmh** [comment]
I fixed the freebsd builder so it's happy now.

We could have an unexported `interface { unwrap() FileInfo }` that FileInfo implementations can implement if they wrap a lower level implementation. Then we'd loop on `unwrap()` as long as the return is still assertable to that interface and finally check if it's basic or not.

It's not just the mtime one, there's also the new windows junction stuff, but maybe that only wraps junctions specifically?

**Comment by calmh** [comment]
Or possibly we implement the SyscallFd stuff

**Comment by AudriusButkevicius** [comment]
image

**Comment by AudriusButkevicius** [comment]
image

**Comment by AudriusButkevicius** [comment]
image

**Pull request merged**
