### PR TITLE
Default sync dir can now be set by envvar on first startup.

### PR DESCRIPTION
**Pull request by nrm21**
Fixes: https://github.com/syncthing/syncthing/issues/1515

### CODE REVIEW

**Comment by calmh** [comment]
While I see the attraction, I'm not super convinced of this approach. The default sync directory is just one of the many defaults. What if I don't want to use global discovery, or if I need to use a custom relay server? (I.e. should we add stuff for things like that as well?)

One argument against my line of reasoning is that our default here results in an mkdir, which may be unwanted (and maybe break?). In that case I wonder if it wouldn't be cleaner with something like `STNODEFAULTFOLDER=1` which prevents us from creating a default folder at all?

**Comment by AudriusButkevicius** [comment]
I think this is to aid automatic deployments, but given you still need to post a config to add devices etc, I am not convinced this helps much, as you'll still have to perform the non-easy steps to make it work.

**Comment by calmh** [comment]
Well, I can see an argument for "just start and don't create folders in weird places that I didn't ask for please", but being able to tweak random defaults from the outside is more shady imho.

**Comment by nrm21** [comment]
Ok so you want me to try to change it to a STNODEFAULTFOLDER=1 functionality instead?

**Comment by calmh** [comment]
Does that fulfil your use case? The other way to do it would be as a `-generate ... -no-folder` kind of thing, I guess I'm not sure how it's being used.

**Comment by nrm21** [comment]
To be perfectly honest, none of it fulfills my use case that I care.

I saw a feature request in the list that someone wanted and was tagged as easy.  I read it and thought "I could do that!  And someone wants it!".  So I did it.  :)

Personally though, most of the things left that I really want this program to do are features way to large and beyond my skillset (Example: syncing true P2P style by starting to resend blocks before finishing a large file like BitTorrnt Sync does).  And besides I know you and Audrius almost have that finished anyway.
https://github.com/syncthing/syncthing/pull/2252

So for now I'm just trying to help out how I can while using it to learn Go.  Most of the other "REALLY needed stuff"... are already kinda done well more or less.  For a file-sync-across-the-internet type program

**Comment by calmh** [comment]
:) Go with `STNODEFAULTFOLDER=1`. Your contribution is welcome, and an excellent first look into go.

**Comment by nrm21** [comment]
Ok then.  I'll prob just create another PR when that's done.

**Pull request closed without merging**
