### PR TITLE
Custom login fix

### PR DESCRIPTION
**Pull request by MpoyiMmg**
### Purpose

New HTML page with login form
New backend API request to process the login and hand out a cookie or  bearer token (see https://github.com/syncthing/syncthing/blob/master/lib/api/api_auth.go and the api code where that gets called)
Redirect unauthenticated requests to the login form (in the auth middleware probably)
We need a "logout" method to invalidate the session and send the user back to the login screen

### Testing

I tested the authentication with the new login interface.  To access the login form, click on action then login.

### Screenshots
Capture d'écran Deepin_zone de sélection _20200404221341

## Authorship

Gael MUTANDA
mpoyigaelmmg@gmail.com

### CODE REVIEW

**Comment by calmh** [comment]
Looks like a good start.

**Comment by MpoyiMmg** [comment]
Thank you! Are there any improvements to be made?

Le jeu. 16 avr. 2020 à 08:24, Jakob Borg <notifications@github.com> a
écrit :

**Comment by tomasz1986** [comment]
> I tested the authentication with the new login interface. To access the login form, click on action then login.

Does the new code work in all Web browsers, including IE11 and mobile (Android, iOS) browsers?

**Comment by MpoyiMmg** [comment]
By the way, there was a mistake with that sweater request! I fixed all the
problems and everything works fine now and I have to redo the sweater
request with what works

**Pull request closed without merging**
