### PR TITLE
lib/fs: Unit test to remove read only Windows files (#3744)

### PR DESCRIPTION
**Pull request by AlexandreAlvesDB**
Unit test for the issue #3744

### CODE REVIEW

**Comment by AlexandreAlvesDB** [comment]
The syscall functions are specific to Windows so when It tries to test for other OS, it fails even if in the first line we check if It's windows and return if not

**Comment by AlexandreAlvesDB** [comment]
Now it's just working as intended

**Comment by calmh** [comment]
Indeed, this fails as it should since it's not fixed in this branch. I've incorporated it into my fix branch (you'll get co-author creds there) and tweaked it a little so will close this one. Thanks!

**Comment by AlexandreAlvesDB** [comment]
> Indeed, this fails as it should since it's not fixed in this branch. I've incorporated it into my fix branch (you'll get co-author creds there) and tweaked it a little so will close this one. Thanks!

Perfect, you're welcome ! 👍

**Pull request closed without merging**
