### PR TITLE
gui: show remaining bytes in remote devices panel (#4227)

### PR DESCRIPTION
**Pull request by liusy182**
### Purpose

Show remaining bytes in remote devices panel (#4227)

### Testing

When 2 devices are in syncing state, the remote devices panel should show "Syncing (`X`%, `Y` MiB)" Where `X` is the completion percentage and `Y` is the remaining bytes to be synced on that remote device.

### Screenshots

sync

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
In principle fine, but please reinstate the space befor the parenthesis on line 567, so here is a space between “Syncing” and “(...”

**Comment by calmh** [comment]
@st-review lgtm 

gui: Show remaining bytes in remote device panel (fixes #4227)

**Comment by st-review** [comment]
:ok_hand: Merged as 322bedbb04943c8e139c6eda0b57c9824a4c6947. Thanks, @liusy182!

**Comment by calmh** [comment]
Thanks!

**Pull request closed without merging**
