### PR TITLE
cmd/syncthing: Compile as GUI application, attach or allocate console instead (ref #8046, ref #8248)

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Does what I said it should do.

### Testing

Tested launching from an explorer window. Allocates console as expected.

Tested launching from cmd, has a weird side-effect where the console input is attached to both cmd.exe and syncthing, and you're returned back to the shell.

This is a bit wonky in the `syncthing cli -` case where you input commands, as it looks like you're typing on the cmd prompt, but I think it gets sent to both?!

Strangely Ctrl+C etc still gets passed to the process.

Also seems to work fine in cygwin. Something a bit strange does happen when running as STMONITORED=yes (which I used to do for development, as Ctrl+C in cygwin didn't work well), but with this change, Ctrl+C works fine from cygwin with monitor process.

`./bin/syncthing | cat` still works, so I assume wrappers et all will still work, maybe? please? untested?

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Ironically the biggest challenge was getting a working Go environment after so much time.

**Comment by bt90** [comment]
Could you test it with the new Windows terminal?

https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701

**Comment by calmh** [comment]
It's kind of ugly in the terminal, for example running with `--help` prints about a screenful of info as it should, but from powershell's point of view it still thinks the prompt is at the top of the window so typing continues up there and overwrites the output from Syncthing... If this is what inheriting the console from the parent means then I wonder if it isn't better to just skip that and open output in a separate window, like if the binary is double-clicked. Perhaps in that case we'd need a "press enter to close" thing to prevent the window from immediately disappearing?

Otherwise I like this approach. I could see our default changing, so that if you launch it without a parent console (i.e. double-clicked in explorer) we dont' start one either, but if there is a parent we allocate one (to show output when launched from a terminal)...

**Comment by AudriusButkevicius** [comment]
I'm fairly Bruce Lee on this (flow like water etc).

Tell me what you want this to look like and I'll make it happen.

 I tried to attach to the terminal existing process for purposes of launching from cmd.exe feeling like you still hand control, but which madman would do that nowadays anyway. I guess I do that in dev from cygwin but maybe I need to be re-educated.

**Comment by calmh** [comment]
So in terms of regressions to avoid, I would like it if running `--help` from a terminal (either kind) does something non-awful. Whether that means an attach-to-parent of some kind that works or opening the output in a separate window that must be explicitly closed, I don't really care.

As for nothing visibly happen when you double click it, I agree. I think this is the only reasonable behaviour though when starting of opening browser is disabled (which isn't the default). However if started and already running it's maybe reasonable to open the browser, regardless of config?

**Comment by calmh** [comment]
Oh and don't let my musings derail the PR. For now, `--no-console` working and `--help` not being terrible is all I ask. :) The rest are possible future extensions.

**Comment by AudriusButkevicius** [comment]
That already works for me?

image
image

**Comment by calmh** [comment]
Here's powershell. I'm using `serve --help` because the output is longer and the effect more disturbing...


https://user-images.githubusercontent.com/125426/215265204-c1694d45-f99f-416e-b296-5e47347dd6a6.mp4

**Comment by AudriusButkevicius** [comment]
I'll try to look into this.
This seems to work fine in cmd.

**Comment by Martchus** [comment]
Does the command prompt really show up correctly in cmd as well? (Or only when you press enter again?) I have this problem with cmd and the problem @calmh has shown in PowerShell with my own GUI apps that are using the same approach (as they also have some CLI parameters after all).

I also noticed the problem that redirections don't work. Considering you state that `./bin/syncthing | cat` still works I presume that you have worked around this issue. However, for a better test I suggest you invoke `./bin/syncthing > foo` and check the contents of `foo`.

**Comment by st-review** [comment]
:robot: beep boop

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

To permanently exempt this PR from bot nagging, add the `slow-pr` label.

**Pull request closed without merging**
