### PR TITLE
issue_template: Add note about using forum for support

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Reduce the number of support requests entering the tracker.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge this please.

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2867/head:pr-2867
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   a492cfb..31362df  master     -> orig/master
$ git reset --hard
HEAD is now at 31362df gui: Better accessibility for folder & device panels (fixes #2288)
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 31362df gui: Better accessibility for folder & device panels (fixes #2288)
$ git clean -fxd
$ git merge --squash --no-commit pr-2867
Updating 31362df..38ce465
Fast-forward
Squash commit -- not updating HEAD
 ISSUE_TEMPLATE.md | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)
$ git commit -F -
[master 82a0d04] issue_template: Add note about using forum for support
 Author: Jakob Borg <jakob@nym.se>
 1 file changed, 6 insertions(+), 1 deletion(-)
$ git rev-parse HEAD
82a0d041e1a73dc3d419f107f8321fef207f1656
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "pr-build" is pending        
To git@github.com:syncthing/syncthing.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:syncthing/syncthing.git'

```

**Comment by calmh** [comment]
@st-review merge it yo

**Comment by st-review** [comment]
OK, merged as a28f890e83daf919c7cd9a939fe1c50c7db2063f. Thanks, @calmh!

**Comment by calmh** [comment]
@AudriusButkevicius too quick on the trigger :)

(It's a bit annoying not to be able to push to master directly for things like this, but I think it's a quality win in the long run...)

**Comment by AudriusButkevicius** [comment]
Yeah, just need to get used to it.

**Pull request closed without merging**
