### PR TITLE
Changes to ignored files should not result in out of sync (reproduces #1701)

### PR DESCRIPTION
**Pull request by Zillode**
I cleaned up the previous PR too much which meant the bug wasn't triggered. This reproduces #1701 with the following findings:

`leveldb.go:889: DEBUG: need folder="default" device=7777777-777777N-7777777-777777N-7777777-777777N-7777777-77777Q4 name="testfile.txt" need=false have=false haveV=[] globalV=[{5157751870738175669 1}]`

`{Name:"testfile.txt", Size:14, Flags:"0664", Modified:time.Time{sec:63567486913, nsec:0, loc:(*time.Location)(0x9d1e80)}, Localversion:891, Version:[]string{"5157751870738175669:1"}}}, Total:1, Page:1, Perpage:65536}`

### CODE REVIEW

**Comment by Zillode** [comment]
(updated issue nr, should have been #1701)

**Comment by Zillode** [comment]
@st-jenkins run integration tests please

**Comment by Zillode** [comment]
[This error should not happen?](http://build.syncthing.net/job/syncthing-pr-integration/96/console)
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
Yeah, seems the test is not very reliable, and should check for errors.

**Comment by Zillode** [comment]
(needs more devices)

**Pull request closed without merging**
