### PR TITLE
lib/fs: Put the caseFS as the outermost layer

### PR DESCRIPTION
**Pull request by imsodin**
Reasoning in comments. The main motivation is to avoid all the case checks when walking the filesystem.

### CODE REVIEW

**Review by calmh — APPROVED** [review]
Well it _sounds_ reasonable

**Comment by imsodin** [comment]
I share that cursive feeling. I was pondering adding something like "I was wrong before, and I am right now - trust me" to the commit message...

**Comment by calmh** [comment]
Yeah we'll see, won't we 🤨

**Comment by andreymal** [comment]
Reverted in v1.27.12.

It seems it also broke my Syncthing instances: when one device deleted a file, another device displayed an error:

```
[TIPS2] INFO: Puller (folder "mystorage" (-), item "i-want-to-delete-this-file.txt"): syncing: delete file: file modified but not rescanned; will try again later
[TIPS2] INFO: "mystorage" (-): Failed to sync 1 items
```

and the deleted file was restored.

I was planning to send a bug report, but this seems to be fixed in v1.27.12, so I'm just leaving this note here

**Pull request merged**
