### PR TITLE
Update quic to 0.22.0 to support RFC9000, enable batch reads

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by bt90** [comment]
Should fix https://github.com/syncthing/syncthing/issues/7824

Looks like v0.22.0 and v0.19.3 both support draft-29 which means that this isn't a breaking change.

**Comment by imsodin** [comment]
We need to ensure that the upgrade doesn't lead to this panic: https://sentry.syncthing.net/share/issue/50e74f85038240cb833cd4fa5fade3c2/ That comes from arch, which upgraded quic without doing any changes in Syncthing. I haven't yet checked what exactly causes the panic and whether the changes to pfilter already address them.

**Comment by yan12125** [comment]
> We need to ensure that the upgrade doesn't lead to this panic:

That looks like my report :)

Still investigating, though

**Comment by yan12125** [comment]
No idea what's going on... I use Go 1.16.6 on Arch Linux. The current main branch (37d0ba16603a71f15b5ebdc8485d3bc0de65615c) runs fine, while this PR (9ce6ebeb789f1961d0c1787278b58920c0ed0715) results in a panic :(

**Comment by AudriusButkevicius** [comment]
Is it the same panic?

**Comment by yan12125** [comment]
Yep, this is what I got from the terminal:
```
$ ./bin/syncthing serve --no-browser --no-restart --logflags=0
[start] INFO: syncthing v1.18.1-rc.3.dev.6.g9ce6ebeb "Fermium Flea" (go1.16.6 linux-amd64) yen@PC951-Home 2021-08-01 14:28:23 UTC [purego]
[start] INFO: Automatic upgrade is always enabled for candidate releases.
[start] INFO: Using large-database tuning
[EDHIV] INFO: My ID: EDHIVUD-NSLB6QO-QRXLIVM-MZH3EMT-EE3B63I-7YMJ34P-TAEX2AV-2Y5DJQ6
[EDHIV] INFO: Single thread SHA256 performance is 200 MB/s using crypto/sha256 (200 MB/s using minio/sha256-simd).
[EDHIV] INFO: Hashing performance is 180.84 MB/s
[EDHIV] INFO: Starting deadlock detector with 20m0s timeout
[EDHIV] INFO: Overall send rate is unlimited, receive rate is unlimited
[EDHIV] INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
[EDHIV] INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
2021/08/02 00:26:57 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
panic: interface conversion: *connections.oobConnWrapper is not net.Conn: missing method Read
[monitor] WARNING: Panic detected, writing to "/home/yen/.config/syncthing/panic-20210802-002657.log"
[monitor] WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] INFO: Reporting crash found in panic-20210802-002657.log (report ID d7ca267e) ...
```
And the panic log: [panic-20210802-002657.reported.log](https://github.com/syncthing/syncthing/files/6912986/panic-20210802-002657.reported.log)

**Comment by AudriusButkevicius** [comment]
Can you try with the latest commit?

**Comment by yan12125** [comment]
It works! Also, I can confirm syncthing with this patch can still connect to the current syncthing (1.18.0). From WireShark, I see QUIC Version Negotiation packets and draft-29 is used in the end.

**Comment by AudriusButkevicius** [comment]
Raised https://github.com/golang/go/issues/47491 for the panic.
Seems like a poor API to ask for X, and then expect X to be Y, without checking it's actually Y.

**Review by imsodin — APPROVED** [review]

**Comment by AudriusButkevicius** [comment]
@calmh happy?

**Comment by calmh** [comment]
Sure. I mean if it doesn't crash and stuff. :)

**Pull request merged**
