### PR TITLE
lib/scanner: Don't scan if input path is below symlink (fixes #6090)

### LINKED ISSUE #6090: Pull-scan loop due to symlink traversal
Version: v1.3.0 - debian package as downloaded from https://apt.syncthing.net/ 
syncthing v1.3.0 "Fermium Flea" (go1.13.1 linux-amd64) deb@build.syncthing.net 2019-10-01 05:34:58 UTC
OS Version: Debian 9.11
Browser Version: N/A

I've pasted a very short extract of the logs below (redacted, but still relevant) which indicates that somehow (look at the timestamps) the backoff timer doesn't seem to work.  I've got alerted to this issue by my monitoring system as my logfiles grew to many gigabytes, filling the log partition,  as far as I can tell syncthing is not misbehaving in any other way

```
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Folder workfolder isn't making sync progress - retrying in 1h4m0.029033154s.
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later 
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Folder workfolder isn't making sync progress - retrying in 1h4m0.023025062s.
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later 
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Folder workfolder isn't making sync progress - retrying in 1h4m0.02256079s.
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later 
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Folder workfolder isn't making sync progress - retrying in 1h4m0.026129808s.
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later 
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.md"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/credentials-simcard-tech.old.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/howto-reset.txt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/testmachine/tech-sms-test-documentation.odt"): delete file: file modified but not rescanned; will try again later
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Folder workfolder isn't making sync progress - retrying in 1h4m0.025634811s.
Oct 17 10:19:59 hyena syncthing[15805]: [2WOFS] INFO: Puller (folder workfolder, item "git/projectA/smsgw/info-failover.txt"): delete file: file modified but not rescanned; will try again later



```

### PR DESCRIPTION
**Pull request by imsodin**
### Purpose

If the path to be scanned is below a symlink, the scanner goes ahead walking that path, as it never by itself needed to traverse the symlink. Now it checks before walking that the path given is not traversing any symlinks.

### Testing

Get no results when scanning a path behind a symlink.

### CODE REVIEW

**Comment by calmh** [comment]
It still works when the folder root itself is a symlink though, right?

**Comment by imsodin** [comment]
Yes it does, that's checked by an existing unit test. I added an additional scenario: Scanning a path point directly to a symlink (i.e. below root) should return just the symlink.

**Comment by calmh** [comment]
Symlink test fails on Windows; maybe just the test itself not functioning there?

**Comment by imsodin** [comment]
Test was expecting one symlink to be returned, which doesn't hold on windows where we do not support symlinks.

**Pull request merged**
