### PR TITLE
removed appveyor build icon

### PR DESCRIPTION
**Pull request by lkwg82**
### Purpose

cleanup Readme.md

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:no_entry: Merge failed:

```
$ git fetch -f origin refs/pull/3003/head:pr-3003
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   ccfcdf7..4aa6ecb  master     -> orig/master
$ git reset --hard
HEAD is now at 4aa6ecb lib/model: Do not use WRONLY (ref #2584)
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 4aa6ecb lib/model: Do not use WRONLY (ref #2584)
$ git clean -fxd
Skipping repository syncthing/syncthing
$ git merge --squash --no-commit pr-3003
Updating 4aa6ecb..6cbb957
Fast-forward
Squash commit -- not updating HEAD
 README.md | 1 -
 1 file changed, 1 deletion(-)
$ git commit -F -
******************************************************
* Commit message does not match the expected format: *
*                                                    *
*   some/tag: A longer description (fixes #1234)     *
*                                                    *
******************************************************

```

**Comment by AudriusButkevicius** [comment]
@st-review merge

readme: Remove Appveyor icon

**Comment by st-review** [comment]
:ok_hand: Merged as 80f2a9a6bf9ad11601504bee123ceb385d79f4c6. Thanks, @lkwg82!

**Pull request closed without merging**
