### PR TITLE
lib/fs: Handle DST changes on FAT on Android (fixes #9227)

### LINKED ISSUE #9227: Handle daylight savings time changes with FAT filesystems
FAT filesystems store timestamps in reference to whatever the computer considers local time. This means that when time changes due to daylight savings the timestamps all shift by one hour in some direction, causing files to be rehashed and resynced (at least metadata wise).

Discussion: https://forum.syncthing.net/t/unwanted-full-rescan-resync-sd-card-syncthing-android-after-timezone-daylight-saving-change/21064/16

It's of course also possible for "local time" to be UTC or another zone that doesn't shift, or the filesystem can be mounted with `tz=UTC` to store timestamps in UTC. But this is not the most common setup on Windows or Android where FAT is more common.

One solution to all this, implemented by OwnCloud and possibly other sync programs, is to ignore timestamp changes of precisely one hour. We could do the same. We even have a good place to do it -- the mtimefs. We already virtualize the timestamp on top of what's actually on the filesystem, we would more or less just need to accept differences of precisely one hour where we check for equality.

In theory this means some changes might not get picked up, but it will be rare in practice. On filesystems with better than second timestamp precision it would be essentially impossible to trigger by mistake.

### PR DESCRIPTION
**Pull request by calmh**
Here, you guys can argue about this. I'll go diving in the meantime.

### CODE REVIEW

**Comment by Catfriend1** [comment]
@calmh I cannot determine if this is ready to work "as is" . Do you think there's a chance as I expect you did not test it on Android because that's not your main OS to work on. 

If you're fine with it, I could throw it into a Syncthing-Fork prerelease and grab feedback from users if it works. 

What is the best way to simulate DST changes? Is it sufficient if the user disables "automatically retrieve time from provider" and disables NTP by going into airplane mode?

The fork has a "recent changes" UI , showing what has scanned (so was detected as changed). I would need a user with enough knowledge to test this fairly and not just run the app and "oh it is syncing".

**Comment by calmh** [comment]
Indeed I have not even compiled for Android, only simulated what I hope are similar conditions.

I added a log line, needs `STTRACE=fs` to fire.

**Comment by Catfriend1** [comment]
@calmh Perfect, thank you.

**Comment by Catfriend1** [comment]
Editing...

I'm just giving this a shot on the android emulator...

```
	 Invoking git fetch ...
	 Invoking git describe ...
	 Cleaning go-build cache
	 Building syncthing version v1.27.0-13-g32d74f4d4
	 
	 *** Building for arm
	 Notice: Next generation GUI will not be built; see --with-next-gen-gui.
```

**Comment by er-pa** [comment]
> it is just happening in older Android versions (I'm currently too lazy to setup new AVDs for every version before 14)

Most likely, yes.

My guess is that it mostly (or only) affects devices running Android < 11 ór a kernel version below 5.4; as that's when the old FS was deprecated (SDCardFS).

Android Emulators running a recent version (Just tested a Pixel 7 - API 33) use EXT4 combined with a FUSE-implementation. As this seems to be a FAT-specific issue, it most likely isn't relevant anymore for devices running Android >= 11 ánd kernel >= 5.4.

**Comment by tomasz1986** [comment]
I think you should be able to reproduce this easily on a real device with an external SD card inserted. Those are always formatted as FAT, including the newest versions of Android (unless you mount them as "internal storage").

In the original issue (https://forum.syncthing.net/t/unwanted-full-rescan-resync-sd-card-syncthing-android-after-timezone-daylight-saving-change/21064), the problem happened specifically with files located on an SD card.

**Comment by Catfriend1** [comment]
@tomasz1986 the problem here is, I do not own a device with sdcard slot :-(. Maybe my emulator was Fuse based.

**Pull request closed without merging**
