### PR TITLE
Add explicit v4 and v6 listeners

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Allows non-dualstack binding, read with ?w=1

### Testing

None

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge this please 

lib/connections: Allow "tcp4" and "tcp6" addresses

**Comment by st-review** [comment]
OK, merged as 690837dbe52ed14267ea44c230ebb8f4e8369e97. Thanks, @AudriusButkevicius!

**Comment by calmh** [comment]
Also needs some GUI and docs tweaks I think.

**Comment by AudriusButkevicius** [comment]
I think we can survive without GUI updates (as it's already a lot of clutter and fairly niche), and @ProactiveServices was nice enough to update the docs.

**Pull request closed without merging**
