### PR TITLE
gui: add a lock icon to the folder title for easy overview (fixes #2703)

### LINKED ISSUE #2703: Add Icons for Master Folder
I think that there is not enough information. I want to know exactly what are the MASTER folder for other devices. Otherwise, I see a monotonous list and nothing is clear.
Image
http://i.imgur.com/bUKpEMu.jpg

### PR DESCRIPTION
**Pull request by kralo**
(to indicate it is a master directory)

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Can you fix the alignment please, and I am happy to merge.
Also an entry in NICKS

**Comment by uok** [comment]
Good idea - please implement it like this (ng-if used twice):

- regular folder = folder icon
- master folder = lock icon

I think this is better then two icons

**Comment by calmh** [comment]
Echoing uok, also ob-screenshot-for-gui-tweaks

**Comment by kralo** [comment]
ok, sorry, I didn't know I was spamming the issue with my rebases. It currently looks like this 
auswahl_003

**Pull request merged**
