### PR TITLE
lib: Move more stuff into util package, rejiggle UPnP

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

This is again a chunk of code that lives in connection refactor, which doesn't have much todo with connections, hence making a separate PR.

Essentially moves some functions into util, adds a few methods on IGD (Get{External,Local}IPAdrress) adds a timeout to dial and changes the return type of one of the functions.

### Testing

Tests pass

### CODE REVIEW

**Comment by calmh** [comment]
It would be really neat if this would add tests for the simple stuff that gets promoted to exported functions in `util`, and maybe the IGD thing should be a commit on it's own. I don't see the relation between them...

**Comment by AudriusButkevicius** [comment]
Why does it matter, the bot with squash it anyway?

**Comment by AudriusButkevicius** [comment]
There.

**Comment by calmh** [comment]
Indeed, so I was thinking to separate PRs as the one doesn't relate to the other. But never mind, :heart: for the tests. :)

**Comment by calmh** [comment]
@st-review merge this please

lib/upnp: Refactor out methods to util with tests, refactor IGD

**Comment by st-review** [comment]
OK, merged as 1d1789128691cb4c966487991d20107f2d4b2ea0. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
