### PR TITLE
LoginWithFullFeatures

### PR DESCRIPTION
**Pull request by trezero**

### CODE REVIEW

**Comment by canton7** [comment]
.. What is this? Dash?

**Comment by trezero** [comment]
Sorry, this was something I was playing with, didnt mean to create a pull request

**Comment by canton7** [comment]
Looks like you're rebanding Syncthing, and redistributing it? Make sure you adhere to the terms of the MPL v2: all source files covered by the MPL must be made freely available :wink:

**Comment by AudriusButkevicius** [comment]
That's very important given you are heading towards commercialization (strings such as Free - Receive Only mode).

**Comment by canton7** [comment]
[You also removed the copyright notice](https://github.com/syncthing/syncthing/pull/2712/files#diff-794a84ca89d4301465159ed62f9cb356L11), which you may not do (under section 3.4 of the MPL).

**Comment by trezero** [comment]
This is just something I'm playing around with at the moment. This is not meant for release. We are planning to make sure we follow all of the terms of the MPL.

**Comment by rumpelsepp** [comment]
When you are planning to be MPL compliant, then please do not remove any copyright strings in first place. Instead **add** your copyright strings.

**Pull request closed without merging**
