### PR TITLE
Reschedule the next scan interval (fixes #1591)

### LINKED ISSUE #1591: Provide /post/rescaninterval
Enable external programs to set the rescan interval for a folder
See https://discourse.syncthing.net/t/default-rescan-interval/2191/5

### PR DESCRIPTION
**Pull request by Zillode**

### CODE REVIEW

**Comment by calmh** [comment]
This looks good, although i'm suspicious that it may be a race condition to access the timers from more than one goroutine. Can you add a short test for this, and we should get a thumbs up or down from the race detector?

**Comment by Zillode** [comment]
Seems to be safe (http://play.golang.org/p/jRAHrGuCJB)
@st-jenkins please run integration tests

- Not sure about the REST API: should it expose seconds or nanoseconds?

**Comment by Zillode** [comment]
Seems to be safe (http://play.golang.org/p/jRAHrGuCJB)
@st-jenkins please run integration tests

- Not sure about the REST API: should it expose seconds or nanoseconds?

**Comment by calmh** [comment]
Famous last words. ;)

```
WARNING: DATA RACE
Write by goroutine 69:
  time.(*Timer).Reset()
      /usr/local/go/src/time/sleep.go:89 +0xef
  github.com/syncthing/syncthing/internal/model.(*rwFolder).DelayScan()
      /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:1171 +0x5c
  github.com/syncthing/syncthing/internal/model.(*Model).DelayScan()
      /go/src/github.com/syncthing/syncthing/internal/model/model.go:1333 +0x184
  main.(*apiSvc).postDBScan()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:795 +0x342
  main.*apiSvc.(main.postDBScan)·fm()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:158 +0x52
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:1541 +0x20c
  main.func·002()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:230 +0x184
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  main.func·005()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:283 +0x234
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:1541 +0x20c
  main.func·009()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_csrf.go:32 +0x183
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  main.func·006()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:290 +0xe3
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  main.func·008()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_auth.go:30 +0x198
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1703 +0x1f6
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1204 +0x1087

Previous write by goroutine 72:
  time.(*Timer).Reset()
      /usr/local/go/src/time/sleep.go:89 +0xef
  github.com/syncthing/syncthing/internal/model.(*rwFolder).DelayScan()
      /go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:1171 +0x5c
  github.com/syncthing/syncthing/internal/model.(*Model).DelayScan()
      /go/src/github.com/syncthing/syncthing/internal/model/model.go:1333 +0x184
  main.(*apiSvc).postDBScan()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:795 +0x342
  main.*apiSvc.(main.postDBScan)·fm()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:158 +0x52
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:1541 +0x20c
  main.func·002()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:230 +0x184
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  main.func·005()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:283 +0x234
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  net/http.(*ServeMux).ServeHTTP()
      /usr/local/go/src/net/http/server.go:1541 +0x20c
  main.func·009()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_csrf.go:32 +0x183
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  main.func·006()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:290 +0xe3
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  main.func·008()
      /go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_auth.go:30 +0x198
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1265 +0x4e
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1703 +0x1f6
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1204 +0x1087
```

**Comment by calmh** [comment]
Seconds seem appropriate.

**Comment by Zillode** [comment]
@st-jenkins please run integration tests

**Comment by Zillode** [comment]
(--- PASS: TestDelayScan)

**Pull request merged**
