### PR TITLE
debian: Rename debian directory to debtpl (fixes #3099)

### LINKED ISSUE #3099: Please move the debian folder
Hello,

Can you please move the debian folder away? I am packaging syncthing for Debian and it interferes with my work.

See our [upstream guide](https://wiki.debian.org/UpstreamGuide)
> Some projects include a rough /debian directory among source files to ease bleeding-edge package compilation and installation on debian (and derived) systems. While this is a good effort, it is better to leave it out of the final tarball as it can interfere with debian's own packaging effort.

So, in other news, Syncthing is coming to Debian. :tada:

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

To keep it out of the way for actual, real, Debian packagers

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge beep boop

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@calmh: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
buzzkill

**Comment by canton7** [comment]
What does "debtpl" even *mean*?

**Comment by calmh** [comment]
debian templates

**Comment by calmh** [comment]
@st-review merge it please, at your earliest convenience, should you deem the code worthy of such an honour

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 4669ce07664b10db7c0f2e50828f09d36db34899. Thanks, @calmh!

**Comment by lkwg82** [comment]
sry for being late, but would you mind to rename it to 'debian_templates'? It not obvious, what is meant by this name.

**Comment by calmh** [comment]
It's only referenced and used in one place, I think the slightly obscure name is fine for now.

**Pull request closed without merging**
