### PR TITLE
Collapse advanced settings in folder dialog

### PR DESCRIPTION
**Pull request by lkwg82**
### Purpose

Reduce information in folder dialog by collapsing advanced settings.

I worked on the folder labels and noticed, that 
- I needed to scroll to get to the save button (kind of weird).
- the advanced block in the middle I rarly use

### Testing

manual

### Screenshots

---

### CODE REVIEW

**Comment by calmh** [comment]
Maybe put the advanced settings below the shared devices then? Otherwise LGTM; we may at some point need to do something drastic like make this a tabbed interface or something...

**Comment by lkwg82** [comment]
Tiny steps. I hope for this particular PR #2425 which has a very nice UI.

**Comment by lkwg82** [comment]
Offtopic: 
What about a participation in the Google Summer of Code? Beside it would get some publicity and maybe some users and committers?

**Comment by calmh** [comment]
:+1:

**Comment by calmh** [comment]
@st-review merge this please

Collapse advanced settings in folder editor modal

**Comment by st-review** [comment]
OK, merged as 3abb80885e5664d5d08687321590867926afeda8.

**Comment by calmh** [comment]
Planned, I just haven't had time the last few weeks;

https://forum.syncthing.net/t/google-summer-of-code-2016-ideas/6679

**Comment by calmh** [comment]
> we may at some point need to do something drastic like make this a tabbed interface or something...

Yeah, I agree. I think we need to do that as well, but this seemed a simple hack along the way. And it has now separated out the stuff that would go on the "Advanced" tab. :)

**Comment by lkwg82** [comment]
Did I miss some workflow or branching or why is this change not in version 0.12.21?? :|

**Comment by AudriusButkevicius** [comment]
We've got incompatible protocol changes on head, so we selectively picked stuff for 0.12.21, and probably missed your changes.

**Comment by calmh** [comment]
Yes. v0.12 is mostly important bugfixes only at this point, we'll release a v0.13 beta soon enough to catch up on all these things and get it out in the wild.

**Comment by lkwg82** [comment]
mhm completly reasonable. But I dont like that there is the chance to miss something.  At this point I d like to have a branch or something transparent. BTW How do you track left over commits?

**Comment by calmh** [comment]
This is the master branch. It's where normally all releases are cut from and where all development happen. Builds of it are [here](https://build.syncthing.net/job/syncthing/) etc. It's just that currently we're in the (fairly rare) situation where we're preparing for a new "major" version (v0.13) and have accepted changes into the master branch that are protocol-incompatible with v0.12. Hence there is a `v0.12` branch that accepts bugfixes, and where I cut v0.12 releases. At some point soon we'll start making actual v0.13 releases from master, and the `v0.12` branch becomes obsolete.

**Comment by lkwg82** [comment]
Ah, I see. thx for clarification.

**Pull request closed without merging**
