### PR TITLE
lib/model: Drop incoming updates for ignored items

### PR DESCRIPTION
**Pull request by calmh**
Help me think this through, please, before merging.

Currently our ignore filters apply in a couple of places:

 - When scanning. We don't scan ignored files.
 - After scanning. Files in the index that are ignored are tagged "invalid" so they are ineligible to be promoted to "global".
 - When sending indexes to other devices. We don't send any entries that are ignored.
 - When processing the "need" list in the puller - ignored files are dropped.

Net effect is reasonable enough, we don't process or pull ignored files and we don't send any updates about them regardless. However we still *accept* updates for ignored files. That means that they show up as needed files when asking the database, and hence the GUI shows them and tags us as "out of sync".

With this change we pretend not to see updates from other devices if they match an ignore pattern. So they don't end up in the database and we are not out of sync due to them.

Is there a good reason this wasn't already the case? Are there are negative effects to this?

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
If I un-ignore a file, I'll have to reconnect to actually pick it up.

**Comment by calmh** [comment]
I was considering dropping the connection on change of ignore patterns. Or, possibly, making the invalid bit into an *actual* "this file is ignored" bit instead, so that we can accept and send updates as normal, and have the files be properly excluded in all circumstances.

**Comment by AudriusButkevicius** [comment]
So what are other cases for Invalid bit being set?

**Comment by calmh** [comment]
Currently, none. Originally I set it when it was detected that a file changed too often, and stopped scanning it for a while. But that was removed in like v0.2 or something.

**Comment by AudriusButkevicius** [comment]
What about invalid characters and so on?

**Comment by calmh** [comment]
Yeah I just thought of that. I think we do in fact set it for incoming updates with impossible file names. Don't think we ever set it on our own files, unless they're ignored.

**Comment by AudriusButkevicius** [comment]
So I think we still need to accept them to the index, but the Ignore bit would vary per device, so I am not sure how much it would make sense.

**Comment by calmh** [comment]
Do you think adds something we need? I can see that we should allow and tag-as-invalid files that cannot be synced, like invalid filenames, because those should show up as out of sync items and yet not be pulled. But ignored files?

**Comment by AudriusButkevicius** [comment]
Actually, no its fine. I wonder if its not wiser to add an ignore bit and advertise the files that have slipped into the global index as ignored instead, which would fix the completion I guess?

**Comment by calmh** [comment]
I think we should do that, long term. It needs to happen when we eventually shift to using delta indexes, as we then need to be able to "reprocess" the index data we already have an unignore files that should no longer be ignored, etc. Until that time though I think this is cleaner, as we already work by filtering out ignores when sending indexes etc.

**Comment by calmh** [comment]
Wrong button

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
:watch: Patiently waited 30m0s for the build status to turn green, but enough is enough. Let me know when things look good.

**Comment by calmh** [comment]
That's it, I'm turning off appveyor. It doesn't add much now that we have a Windows builder of our own and taking 40 minutes to get to the tests isn't awesome

**Comment by AudriusButkevicius** [comment]
:tada:

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as b81c8d2e1b5856d9493a62c816f26483f505adea. Thanks, @calmh!

**Pull request closed without merging**
