### PR TITLE
no file versioning caution

### PR DESCRIPTION
**Pull request by camsteffen**
Testing the waters with my first pull request... This adds a caution message to the GUI when No File Versioning is selected.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I don't think it's implied by default that it will be kep, so I don't see why we should add this.

**Comment by camsteffen** [comment]
I'm adding this with less technical users in mind who might not consider the risks of syncing.

**Comment by calmh** [comment]
Yeah, no, thanks for the proposal but I don't think the defaults warrant a caution here. If we thought it did, the correct cause of action would be to change our default to be the safe choice. However I don't think we should default to do versioning.

**Comment by camsteffen** [comment]
Ok, that's fine.

**Pull request closed without merging**
