### PR TITLE
File/Folder sync log to file (fixes #1683)

### LINKED ISSUE #1683: More detailed sync logs in the web gui
Hi there,

Something i wished for since im using syncthing, are data like:

which files did a node already sync and which not

right now i only know the last time the node was online and that it finished (?) at least one file.
thats not very much. 
last synced file is cute, but i dont see why it has a place in the gui when other more meaningful data doesnt.

i guess some of that information can be obtained through log files, but i hope its planned to move some  of the data like this into the gui

i tried to search for a similar thread but didnt find anything, sorry if that topic was already requested.

keep going with the good work.

### PR DESCRIPTION
**Pull request by nrm21**
This is a feature addition.  All it does is writes all incoming file/folder (not outgoing for now) changes to a log file written in the same directory as the executable.  The log file has a time stamp in the file name and so should rotate daily.

If there are problems with the code or something is lacking, please let me know and I will do my best to correct it.

This feature seems to (sort of) solve #1683 but I don't know how to link it yet.  Feel free to do that if you want.

### CODE REVIEW

**Comment by calmh** [comment]
As far as I can tell from a quick glance this just logs the device ID and number of items, which is already in the audit log?

**Comment by nrm21** [comment]
I'm sorry I don't see where the audit log is, is that the same as the debug log when I use STTRACE?  I'm on a Windows machine here.

Anyway the feature logs the device ID, number of items and the list of those item names.

Example:
-----------
AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA
10.11.12.13:56789-12.34.56.78:22000 (direct-dial) [2 object change(s) recieved]
Nov 30 10:07:46.504: [ default ] --> create folder "aaaa"
Nov 30 10:07:46.504: [ default ] --> create file "aaaa/eeee.txt"

**Comment by AudriusButkevicius** [comment]
So I think that -audit provides the same data (or could be modified to print ItemFinished events). Regardless there are two many moving parts here for what it actually does.

**Comment by canton7** [comment]
Start syncthing with `-audit` to create the audit log, as documented by `syncthing -help`

**Comment by calmh** [comment]
Yeah, so I think `-audit` should cover the same use case, and if it doesn't please do look into extending it until it does. But adding an extra logging function is probably unnecessary at this point.

**Comment by nrm21** [comment]
Ok so I will work to extending audit logs to at least include file and folder names.  I just grepped the audit log after transferring a few test files from one client to another, and I see nothing in the log even mentioning the file names.

**Comment by calmh** [comment]
:+1:

**Pull request closed without merging**
