### PR TITLE
Add oxford comma

### PR DESCRIPTION
**Pull request by DeflateAwning**

### CODE REVIEW

**Comment by tomasz1986** [comment]
Are you sure you can edit translations like that? Normally, if the English string gets modified (even if just slightly), it is treated as a new one, requiring translating everything from scratch. Translations themselves are handled at https://hosted.weblate.org/projects/syncthing.

**Comment by acolomb** [comment]
I think it should work with Weblate, as this actually adjusts all the keys in translations as well.  Weblate should pick up the changes in the translations.  Only the comments / history will be lost, as they live in their database instead of the JSON files.

Maybe time to just try it out?  We can always revert if things go wrong.  Although this change in itself is very minor so not worth much trouble.

**Comment by DeflateAwning** [comment]
Alternatively, I think the worst that happens is that the string needs to be re-translated. I thought that by replacing it in every location, there's a good chance it'd avoid the retranslation requirement.

**Comment by DeflateAwning** [comment]
Are there any changes required to make this mergable? Should I open a new PR with the same change, but not in any of the translation files?

**Comment by tomasz1986** [comment]
> Should I open a new PR with the same change, but not in any of the translation files?

That would likely be a no-go, as we normally don't do minor modifications like that which would force the translators to translate the whole string again from scratch. In other words, the only way to merge this is probably to do it in such a way that will not require any re-translation (as in this PR, however, as already mentioned, something like this hasn't been done before yet).

**Comment by DeflateAwning** [comment]
Speaking more generally about this projech, I actually have a very large number of problems with minor writing style/grammar problems within. It would be awesome if I could help clean some of these things up to polish the project and help instill trust. 

As far as the Oxford comma goes, the trend is definitely in the direction of using it. The rule is that its use should be consistent throughout a document/app/etc. As there is currently a mix in the Syncthing ecosystem, I would strongly encourage this upgrade.

Someone should look into the translation system's docs and see what the correct way to perform this sort of upgrade is. It can't be a novel problem, and retranslation shouldn't always be required.

**Comment by acolomb** [comment]
Well, I do have a thorough understanding of what *should* happen with the Weblate integration. My point was just that it's never been done before (the old system, Transifex didn't support it) and that I want to be watching closely when we first try.

One thing that will certainly happen is the loss of context in Weblate, such as suggestions and comments on the string. It will effectively be seen as a new string that happens to already have a translation in the repository. And it may get some kind of "automatically translated" label, would need to check if we still have that enabled. Nothing too serious in my opinion. 

So again, if there is a consensus on whether the comma is correct, I'll happily merge this and see what really happens. If it works out, you're welcome to propose further language optimizations. We'll need to decide case by case whether they are worth making waves.

**Comment by DeflateAwning** [comment]
My other comma PR (with other changes as well) was approved, FYI

https://github.com/syncthing/syncthing/pull/9136

**Review by acolomb — APPROVED** [review]
So I took the time to develop an opinion.  I'd personally prefer the new style proposed here.  Any other objections regarding the bikeshed's color?

**Comment by calmh** [comment]
The comma style is obviously and objectively superior. ;)

As for how to handle the translation strings, I defer to the localisation expertise of you guys.

**Comment by acolomb** [comment]
Looks fine, the existing translations were carried over:
https://hosted.weblate.org/translate/syncthing/gui/en/?checksum=88170e2a8fd58563#translations

**Comment by DeflateAwning** [comment]
This sets a record for comments-per-characters changed in a PR. Thank you everybody! :)

**Pull request merged**
