### PR TITLE
lib/protocol: Allow unknown message types

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This lets us add message types in the future, for authentication or
other purposes, without completely breaking old clients. I see this as
similar behavior to adding fields to messages - newer clients must
simple be aware that older ones may ignore the message and act
accordingly.

Related to, for example, #3379.

### Testing

None whatsoever. But it looks safe.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Not sure if it should warn. To be honest, the more advanced peer should be aware which messages other side support from versiom defined in hello?

**Comment by calmh** [comment]
It should, yes. Silent skip?

**Comment by AudriusButkevicius** [comment]
Magic cookie would be a field in hello message most likely.

**Comment by AudriusButkevicius** [comment]
I am not sure we should warn about this as this is something that is not necesserily actionable by the user. What do you expect the user to do when he sees this message?

**Comment by calmh** [comment]
Upgrade, probably, but I'm absolutely fine with not even warning. But I do think we'll save ourselves a headache down the road by allowing unknown messages. Other mechanisms I've considered are ranges on the message type (types <256 are mandatory, understand them or close the connection; >=256 are optional and can be skipped if you don't understand) or an explicit flag in Header (type=47, mandatory=true => skipping this message is not allowed).

**Comment by AudriusButkevicius** [comment]
So I am fine ignoring, just not sure about warning.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as e440d3002877a5fb7ae0ada5b5843b011b00c9bd. Thanks, @calmh!

**Pull request closed without merging**
