### PR TITLE
gui: Default theme (widescreen)

### PR DESCRIPTION
**Pull request by uok**
Additional default theme that uses 90% of screen width on large resolutions.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Pic?

**Comment by wweich** [comment]
Why not change the `container` to `container-fluid` in the default theme. `container-fluid` is always full width, with the same responsiveness.

**Comment by uok** [comment]
@AudriusButkevicius do you mean a screenshot? I don't have a widescreen monitor so a screenshot from theme widescreen would look exactly like theme regular
@wweich The idea was to have the default theme (centered gui with margins left/right) and widescreen theme (90% width). There is no need for editing html.

**Comment by AudriusButkevicius** [comment]
Why don't we use the fluid stuff?

**Comment by uok** [comment]
@wweich thanks for the screenshots and the info, I update the media query.
@AudriusButkevicius Then we would need to change the index.html file as well because right now you can only change colors/layouts of existing elements (CSS classes and HTML tags). In the future then somebody needs to update it every time a new element is added to the default index.html - I'm not sure this is worth the work.

**Comment by AudriusButkevicius** [comment]
As far as I understand the fluid stuff could be part of the default ui, as it should not change much.

**Pull request closed without merging**
