### PR TITLE
lib/connections, lib/model: Check addr before hello exchange

### PR DESCRIPTION
**Pull request by imsodin**
There's no point and arguably even bad to exchange hello messages and do all kinds of stuff when the connection comes from a blacklisted address -> check that first.

### CODE REVIEW

**Comment by calmh** [comment]
I'm not sure I agree. The device is known and accepted; we trust it. It's trying to connect from some place we don't want it to. It seems reasonable and polite to say "hi, I'm syncthing, I know you, but I'm not going to talk to you at the moment".

**Comment by imsodin** [comment]
I get that, but only the "hi, I'm devicename on syncthing version xyz" is actually happening, then we just go silent. I'd say that's worse than not sending a hello at all, thus not creating any useless work at all. If we'd actually send a message saying "I know you, but I don't like your current address" that might have some use, but currently we potentially block the single loop handling connections for up to 20s (timeout).

**Comment by calmh** [comment]
Clearly we should close the connection with an error. If we don't do that it's definitely a bug, but I think a different one with a different solution than you're proposing

**Comment by imsodin** [comment]
Ok fine, we'll have to agree to disagree on the fundamental point

What do you mean by closing the connection with an error - a BEP close message or is there the possibility to close the underlying connection such that it isn't just dropped and the other side is notified?

**Comment by imsodin** [comment]
I should have just rtfm. From BEP:

> [...] even in the case that a connection is rejected a Hello message must be sent before the connection is terminated.

I still think the check should happen in `lib/model` and the connection status reporting implemented added in #5727 should also apply here - I'll open another PR for that.

**Pull request closed without merging**
