### PR TITLE
fix(config): respect GUI address override in fresh default config (fixes #9783)

### LINKED ISSUE #9783: gui: Address override not respected in fresh default config
### What happened?

When generating a new `config.xml` file with default options, the GUI address is populated with a hard-coded default value of `127.0.0.1:8384`, except for a random free port if that default one is occupied.  This ignores any `STGUIADDRESS` override given via environment variable or command-line option, thus probing for the default port instead of the one specified via override.

When not probing for free ports (`--skip-port-probing`), the override should still be persisted rather than the default address.  Only when generating a fresh default `config.xml`, never on an existing one.

### Syncthing version

1.28.0

### Platform & operating system

Linux amd64

### Browser version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by acolomb**
### Purpose

When generating a new `config.xml` file with default options, the GUI address is populated with a hard-coded default value of `127.0.0.1:8384`, except for a random free port if that default one is occupied.  This is independent from the GUI configuration default address defined in the protobuf description.  More importantly, it ignores any `STGUIADDRESS` override given via environment variable or command-line option, thus probing for the default port instead of the one specified via override.

The `ProbeFreePorts()` function now respects the override, by reading the `GUIConfiguration.Address()` method instead of using hard-coded defaults.

When not calling `ProbeFreePorts()`, the override should still be persisted rather than the default address.  This happens only when generating a fresh default `config.xml`, never on an existing one.

### Testing

Unit tests added for the `DefaultConfig` method in `lib/syncthing`.

Manual testing: (need to interrupt each started instance to see the result, only for UNIX / bash)

```bash
(export TMPHOME=$(mktemp -d) ; STGUIADDRESS=0.0.0.0:8385 bin/syncthing --home=$TMPHOME --skip-port-probing --no-browser && grep address $TMPHOME/config.xml)
(export TMPHOME=$(mktemp -d) ; STGUIADDRESS=0.0.0.0:8385 bin/syncthing --home=$TMPHOME --no-browser && grep address $TMPHOME/config.xml)
(export TMPHOME=$(mktemp -d) ; bin/syncthing --home=$TMPHOME --skip-port-probing --no-browser && grep address $TMPHOME/config.xml)
(export TMPHOME=$(mktemp -d) ; bin/syncthing --home=$TMPHOME --no-browser && grep address $TMPHOME/config.xml)
```

### CODE REVIEW

**Comment by acolomb** [comment]
Not quite sure if this is the right approach, especially the second commit.  I tried to apply the override in `GUIConfiguration.prepare()`, but that is called on more occasions, and at that point the `RawAddress` is already initialized to its default value.  Thus we wouldn't know whether it's a fresh config or whether we're replacing a previously configured value with the override (which is probably not be desired).

**Comment by calmh** [comment]
I've always thought STGUIADDRESS was a runtime override of whatever was in the config, not something that should be persisted there. For generate, if we want to the possibility bake a custom value, it would make sense to have a `--gui-address` option perhaps?

**Comment by acolomb** [comment]
Yeah, I just noticed that the test vectors using `generate` are actually flawed, as the override is not taken into account at all there.  For the default invocation however, it does apply.

My main motivation was that when starting for the first time without `config.xml` and `STGUIADDRESS` set, a random port ends up in the config, although the one specified in `STGUIADDRESS` was actually free (only the default 8384 was taken).  That was rather unexpected and I think we should honor the `STGUIADDRESS` setting when persisting a fresh config for the first time.  Of course, once it exists, the override must be strictly temporary.

Adding `--gui-address` / `STGUIADDRESS` support to `syncthing generate` is a different issue IMHO, might add that soon.

**Comment by acolomb** [comment]
On second thought, we usually tell users to write their custom, minimal `config.xml` snippet before running `syncthing generate` if they want to set other default options except GUI user and password.  These need special handling (password hashing), while adding all the other options (like `--api-key`) will get tedious.  Therefore I think we can keep ignoring this deficiency for `syncthing generate`.

**Comment by acolomb** [comment]
Please advise if the added tests are acceptable.  Might just be complete nonsense, as I'm really not imaginative with unit testing.  Happy to learn and improve them!

**Comment by acolomb** [comment]
Well, it does handle port 8384 being taken already.  For sub-tests which expect it to be blocked, accept that it is.  Those which expect it to be free are simply skipped because we cannot achieve that condition.

So I agree that being independent from the actual network stack would be better.  I'm just totally lost about how to "mock out the prober".  Tried to add some directives for `counterfeiter`, but it fails with:

    Writing `ProbeFreePorts` to `mocks/config.go`... 
    cannot find package with target: ProbeFreePorts

I'd welcome a little jump-start on how to go about this.

**Comment by calmh** [comment]
Counterfeiter is a thing for creating mocks of whole interfaces, which is useful in some cases, but I think not here. In this case the active component in the end looks like it's the `func getFreePort(host string, ports ...int) (int, error)` which does the actual probing. So options might be to pass that function (or one with that signature) as a parameter to `(cfg *Configuration) ProbeFreePorts() error`, or just make it override-able in tests, like:

```
var getFreePort = defaultGetFreePort

func defaultGetFreePort(host string, ports ...int) (int, error) {
  ... currnet getFreePort implementation
```

then you can just

```
getFreePort = func(host string, ports ...int) (int, error) {
  return 42, nil
}
```

or whatever is the desired behavion from inside the test code.

**Comment by acolomb** [comment]
Alright, I tried both suggestions and definitely prefer the module-level variable (function reference).  We'd need to pass the mocked function through `DefaultConfig()` and `ProbeFreePorts()` in several places across packages, which seemed overly intrusive.  What's still smelly here is the exported `GetFreePort` variable, as the test which mocks it lives in a different package.  Let me know if you have a nicer solution to that.  Otherwise I'm content with the current state.

**Comment by calmh** [comment]
Yeah so doing this across packages is not great, imho. As an externally-invisible things inside a packages yes, but not this. Maybe we can just move the free port function to netutil or something and just pass the result to the places that need it.

**Comment by calmh** [comment]
The problem here is that (*Configuration).ProbeFreePorts() does unpredictable stuff, right? So let's not do that -- remove that method entirely, and have (*Configuration).New() take the listen ports as parameters. That puts the entire burden on the code that creates the config, where they could then choose to just pass `:8384` if that's the override in place, or call netutil.GetFreePort(...) (if that's where we move the function).

Or something else, whatever, but not this cross-package function overwriting :)

**Comment by acolomb** [comment]
Alright, I think I got it untangled and have a cleaner solution now.  Removing `ProbeFreePorts()` from `config` seemed unfortunate, since it effectively holds some defaults for the `listenAddresses` option and it explicitly enumerates options that concern an address for listening.  Moving that outside the package makes it more prone to forget adjusting when we ever add another type of listen port option.

So now I just pass the probing function reference to `ProbeFreePorts()`.  The implementation lives in `netutil` and the overridable reference for tests is in the `lib/syncthing` package, not exported as it ought to be.

Looks alright?

**Comment by calmh** [comment]
I mean, it's kind of OK, but I can't say I love it. Your first commit is fine -- the meat of the change. Then it's another 100-130 lines for the tests and it ends splitting the port probing functionality over three different packages, which feels like it adds a lot of mental complexity just for the tests. Honestly I'm still at

> If you wanted to test this fully (which I think may be overkill)

and I think the juice is not worth the squeeze for this test.

**Comment by acolomb** [comment]
Alright.  Your "may be overkill" was still motivating enough to try it :-D

Removed the unit test again.  We know it passed, so the change itself can be seen as tested for all relevant scenarios.

**Comment by acolomb** [comment]
Ping, is there a reason why this didn't get into the latest RC?

**Review by calmh — APPROVED** [review]

**Comment by PeterSurda** [comment]
Unfortunately it looks like this breaks listening on unix socket.

**Pull request merged**
