### PR TITLE
Defer restore versions

### LINKED ISSUE #4738: File restore doesn't work on one folder
It works on other directories but on one specific folder there's no tree displayed, the JS console says:

```
TypeError: $scope.restoreVersions.tree.filterNodes is not a function
    at syncthingController.js:1967
    at Object.$watchCollectionAction [as fn] (angular.js:11724)
    at Scope.$digest (angular.js:11827)
    at Scope.$apply (angular.js:12080)
    at done (angular.js:7862)
    at completeRequest (angular.js:8045)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:8001)
```

Syncthing Version: v0.14.44-rc.3
OS Version: Debian 9.3
Browser Version: Version 64.0.3282.119 (Official Build) beta (64-bit)

### PR DESCRIPTION
**Pull request by cromefire**
### Purpose

Fix from https://github.com/syncthing/syncthing/issues/4738#issuecomment-434463688
Fixes #4738

### Testing

Not tested yet, I will try to test it in my installation.

### CODE REVIEW

**Comment by cromefire** [comment]
@AudriusButkevicius
The is the PR you wanted, if there is any thing missing, feel free to request changes.

I will try testing this in my own installation once I have found the file

**Comment by cromefire** [comment]
Is it `$scope.$apply();`?

**Comment by AudriusButkevicius** [comment]
It's everything that is after `then(function() {` , literally, the whole function body.

**Comment by cromefire** [comment]
Better?

**Comment by AudriusButkevicius** [comment]
thanks

**Comment by cromefire** [comment]
I guess the files are embedded in the `syncthing` executable?

**Comment by AudriusButkevicius** [comment]
Yes

**Pull request merged**
