### PR TITLE
gui: Order folders and devices by display name (fixes #3310)

### LINKED ISSUE #3310: Folders should be sorted by label, not ID
Is it possible to sort the folder by label instead of by ID?

I'm using 0.13.7 on Linux (AMD64 & ARM), Windows and OS X.

### PR DESCRIPTION
**Pull request by norgeous**
redo of failed #3318

### CODE REVIEW

**Comment by xduugu** [comment]
There might be some issues with the current approach.

The folderList function already sorts the folders by id, which should be removed, if your solution is used: https://github.com/syncthing/syncthing/blob/master/gui/default/syncthing/app.js#L71

The devices on the other hand, should already be sorted by the deviceCompare function:
https://github.com/syncthing/syncthing/blob/master/gui/default/syncthing/app.js#L39

I fixed the folder list order some time ago, but was not sure about the code quality. I adjusted the folderCompare function to use the label as key and fall back to the id if it is empty. Maybe that is the right place to sort...

```
--- a/gui/default/syncthing/app.js
+++ b/gui/default/syncthing/app.js
@@ -77,10 +77,20 @@ function deviceCompare(a, b) {
 }
 
 function folderCompare(a, b) {
-    if (a.id < b.id) {
+    labelA = a.id
+    if (typeof a.label !== 'undefined' && a.label !== null && a.label.length > 0) {
+        labelA = a.label
+    }
+
+    labelB = b.id
+    if (typeof b.label !== 'undefined' && b.label !== null && b.label.length > 0) {
+        labelB = b.label
+    }
+
+    if (labelA < labelB) {
         return -1;
     }
-    return a.id > b.id;
+    return labelA > labelB;
 }
 
 function folderMap(l) {
```

**Comment by norgeous** [comment]
yes, thanks @xduugu! I didn't know about these functions, I believe your approach is the correct one.
With this PR, the order is only changed in the display.
In your version, the folders and devices will be sorted correctly in the `$scope` and subsequently everywhere else. Can you create a PR? This should be closed then?

**Comment by xduugu** [comment]
I've created a pull request at #3326.

**Comment by calmh** [comment]
Superseded

**Pull request closed without merging**
