### PR TITLE
ConnectionService is the address lister

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

This is a smaller extract of the connection refactor.
Gets rid of the AddrLister, and uses the connection service itself to satisfy that interface.

### Testing

Tests pass, haven't ran it yet.

### CODE REVIEW

**Comment by calmh** [comment]
LGTM. Ideas for future cleanup that strike me:

The upnpService could be a single method interface as far as the connection service cares

Looks like that constructor may want to take a ConnectionOptions strict or something instead of the 250 arguments.

**Comment by calmh** [comment]
@st-review merge this please 

lib/connections: Refactor address listing into connection service

**Comment by st-review** [comment]
OK, merged as 29913dd1e4857738261d8fa98de613ced03edd6a. Thanks, @AudriusButkevicius!

**Comment by AudriusButkevicius** [comment]
So it will be cleaner once I wedge in the second part of the refactor.

**Pull request closed without merging**
