### PR TITLE
Do not send group/others-writable bits from Windows.

### PR DESCRIPTION
**Pull request by kamadak**
There is no user/group/others in Windows' read-only attribute,
and all "w" bits are set in os.FileInfo if the file is not read-only.
Do not send these group/others-writable bits to other devices
in order to avoid unexpected world-writable files on other platforms.

### CODE REVIEW

**Comment by calmh** [comment]
Looks reasonable! :+1:

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
@st-jenkins run integration tests, please

**Comment by calmh** [comment]
We are currently in the process of changing the license from GPL to MPL. If you could please drop a :+1: on #1421 to indicate that you're on board with this that would be great.

**Comment by kamadak** [comment]
Thanks, I have no problem with MPL, so dropped a :+1: .

**Comment by calmh** [comment]
Integrations pass (http://build.syncthing.net/job/syncthing-pr-integration/32/).

@st-jenkins test this please

**Comment by calmh** [comment]
@st-jenkins test this please

**Pull request merged**
