### PR TITLE
cmd/strelaypoolsrv, lib/api: Factor out static asset serving

### PR DESCRIPTION
**Pull request by greatroar**
Much of the asset handling code shared by these modules now lives in lib/api/assets, with the following modifications.

* strelaypoolsrv had its mtime checking reversed: it reported StatusNotModified when modified.Add(time.Second).After(t).
* Generated ETags were "bare" decimal numbers, but [RFC 7232 §2.3](https://tools.ietf.org/html/rfc7232#section-2.3) requires them to be quoted strings. Since this changes invalidates all old ETags, I changed them to hex for compactness while I was at it.
* lib/api added charset=utf-8 for textual MIME types, but strelaypoolsrv  didn't. Both now do.

### CODE REVIEW

**Comment by imsodin** [comment]
Just an idea, haven't thought it through: Would it make sense to have this new code in `lib/api/assets` and `lib/auto` in a single package?

**Comment by greatroar** [comment]
I would have merged the two, but cmd/strelaypoolsrv has different assets (actually only one) than syncthing.

**Comment by AudriusButkevicius** [comment]
Perhaps this should be lib/assets and lib/auto. lib/api is a syncthing specific package for it's rest api, so it feels weird that we reach into that in the relay server.

**Comment by greatroar** [comment]
Your call. The Go module system doesn't care what the path is :)

**Comment by imsodin** [comment]
So `lib/api/assets` -> `lib/assets` and `lib/auto` -> `lib/api/auto`? (We're really good at bikeshedding :P )

**Comment by AudriusButkevicius** [comment]
Yeah, sounds good.

**Comment by greatroar** [comment]
Ok, did that.

**Pull request merged**
