### PR TITLE
gui: Icons and directory information in "This Device" summary consistent with folders (fixes #4100)

### LINKED ISSUE #4100: Device stats "items" should show the same kind of data as the folder stats
screen shot 2017-04-14 at 17 50 38

### PR DESCRIPTION
**Pull request by snugghash**
Resolves #4100.

### Summary
Changes [index.html](https://github.com/syncthing/syncthing/blob/master/gui/default/index.html) so that the `<td>` element is consistent with per-folder's HTML. Adds a tooltip, similar to folder. 

Adds `directories` attribute to the `localStateTotal` in [syncthingController.js](https://github.com/syncthing/syncthing/blob/master/gui/default/syncthing/syncthingController.js) which populates the template engine's variables. This value is obtained from `$scope.model[f].localDirectories`, which has the correct value. This is the same method as used for other attributes, thus requiring no further changes.

### Screenshots
Preliminary test of generated web UI:
syncthing issue 4100

### Documentation

Can remain the same, UX is more intuitive now.

### CODE REVIEW

**Comment by calmh** [comment]
Sweet 👍

**Comment by AudriusButkevicius** [comment]
Awesome.

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it

gui: Make icons and directory information in local device summary consistent with folders (fixes #4100)

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 3395992abd2a30cff9108a4df9f1832eb1751e64. Thanks, @snugghash!

**Pull request closed without merging**
