### PR TITLE
vendor: Update pfilter (fixes #4537)

### LINKED ISSUE #4537: Panic in "pfilter" package on 32 bit architectures
Panic at 2017-11-21T16:45:01+08:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4012cc]

goroutine 571 [running]:
sync/atomic.AddUint64(0x2059a13c, 0x1, 0x0, 0x5dc, 0xb8)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*PacketFilter).loop(0x2059a120)
	/usr/local/gopkg/src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/filter.go:132 +0x105
created by github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*PacketFilter).Start
	/usr/local/gopkg/src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/filter.go:90 +0x33

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@imsodin https://build.syncthing.net/viewLog.html?buildId=13240&buildTypeId=Syncthing_BuildMac

**Comment by AudriusButkevicius** [comment]
@st-review retest

**Comment by st-review** [comment]
I'm sorry, @AudriusButkevicius. I'm afraid I don't know what you mean. I know how to `don't`, `lgtm`, `merge`, `prevent`, `rebuild`, `squash`, `stop`.

**Comment by AudriusButkevicius** [comment]
@st-review rebuild

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 67c39b25121ee467879df392b18ff2a56a5449c2. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
