### PR TITLE
Small improvements for job queue

### PR DESCRIPTION
**Pull request by uok**
Small improvements for job queue (introduced in #629)
- change to link element to indicate click action with pointer
- add title attribute for better usability
- move icon next to file name

### CODE REVIEW

**Comment by calmh** [comment]
Hi! Looks like some stuff added and then reverted. Can you squash to a single clean commit?

**Comment by uok** [comment]
please help, I don't know how to do that

**Comment by AudriusButkevicius** [comment]
Sorry it took so long.

**Comment by uok** [comment]
No problem, I took me a while to learn `git rebase` anyways :grinning:

**Pull request merged**
