### PR TITLE
lib/protocol: Invalid files should always lose

### PR DESCRIPTION
**Pull request by imsodin**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
How does this solve the 'my files ain't downloading' issue?

**Comment by imsodin** [comment]
This doesn't solve any issue I am aware of, but it prevents an invalid file with concurrent version to be put ahead of a valid file in the global list: https://github.com/syncthing/syncthing/blob/master/lib/db/leveldb_transactions.go#L154

**Comment by imsodin** [comment]
@AudriusButkevicius Regarding your last comment: Is this PR good to go or is there something to discuss?

**Comment by AudriusButkevicius** [comment]
lgtm

**Pull request merged**
