### PR TITLE
gui: Sort folders by label, fall back to ids if required (fixes #3310)

### LINKED ISSUE #3310: Folders should be sorted by label, not ID
Is it possible to sort the folder by label instead of by ID?

I'm using 0.13.7 on Linux (AMD64 & ARM), Windows and OS X.

### PR DESCRIPTION
**Pull request by xduugu**
Sorts the folders by its labels and uses the folder ID if no label is set.

### CODE REVIEW

**Comment by calmh** [comment]
Needs `var` declarations and semicolons, otherwise looks good to me.

**Comment by calmh** [comment]
@st-jenkins add to white list

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by xduugu** [comment]
Adjusted the patch, thanks.

**Comment by calmh** [comment]
@st-review merge it, looks good

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 89a29946f96c63795ca5d3da062316c375604961. Thanks, @xduugu!

**Pull request closed without merging**
