### PR TITLE
lib/db: Don't whack blocks when putting truncated file

### PR DESCRIPTION
**Pull request by calmh**
As of the latest database checker we are again putting files without
blocks. I'm not 100% convinced that's a great idea, but we also do it
for ignored files apparently so it looks like we probably should support
it.

### CODE REVIEW

**Comment by calmh** [comment]
Actually no. Accepting random fileinfos with a hash is a problem and we shouldn't do it.

**Comment by calmh** [comment]
On the other hand, non-deleted/invalid without blocks are already dropped at the protocol level.

**Comment by imsodin** [comment]
Oh dammit, I am still not on top of the blockhashes...

The changes look good. If you'd rather not allow it, an alternative would be to use `procotol.checkFileInfoConsistency` in `putFile` and panic on error - then my mistakes will at least properly blow up early.

**Comment by calmh** [comment]
I think this is a fine compromise

**Comment by calmh** [comment]
A proper repair for this isn't super trivial and I'm hoping it won't be widespread enough yet that we need one :/

**Comment by imsodin** [comment]
Latest number of rc.2's is 1400, but it only concerns people with messed up sequence entries, so I hope were good...

**Pull request merged**
