### PR TITLE
lib/connections: Fix lan detection (fixes #4421)

### LINKED ISSUE #4421: Local network classification doesn't always work
Firstly, we check these once on startup, which is not ideal.
Secondly, they are only checked if rate limiting is enabled, yet if rate limiting is enabled post startup, lans are never resolved.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
...

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 62a4106a794bd88c6f0a86593ee0c4f4736a4d72. Thanks, @AudriusButkevicius!

**Comment by calmh** [comment]
Are you asking me or setting reminders for yourself? :D

screen shot 2017-11-06 at 15 06 54

**Comment by AudriusButkevicius** [comment]
Nah, it was supposed to be a branch reducing strain on discovery servers by not reannouncing many kcp addresses, but then I got bored and did something else.

**Pull request closed without merging**
