### PR TITLE
CSS code formatting in Dark theme

### PR DESCRIPTION
**Pull request by OCRenkist**
A few small improvements to the spacing consistency in the CSS itself.

### CODE REVIEW

**Comment by OCRenkist** [comment]
Hmm...that's odd. My `commit`s from another `branch` also appear here? Only `d283ad3` is part of the "CSS" `branch`.

**Comment by acolomb** [comment]
You need to take care where you create your new branch from.  Always base it on current `main` when you are going to make a PR.

By the way, you don't need to specially format `commit` and `branch` everytime.  Those are perfectly normal words for a conversation on GitHub :wink:

**Review by acolomb — CHANGES_REQUESTED** [review]
Content-wise, I'll be quite frank now, sorry in advance.  This is a complete waste of time.  No offense intended, but I hope you read my comments on https://github.com/syncthing/syncthing/pull/8166.

I'll be glad to see perfectly formatted code on your contributions, but please not such functional no-op changes on code that Just Works and isn't in terrible shape anyway.

**Comment by tomasz1986** [comment]
> please not such functional no-op changes on code that Just Works and isn't in terrible shape anyway.

I'd also add that the CSS for the black and dark themes follows almost the same format, so if there's a significant change in one of them, there's a high probability that it should also be applied to the other one.

**Comment by OCRenkist** [comment]
Thank you all for the feedback. Despite a background in Computer Science, this is only my second month using Git, and I may be (thus far) out of my depth attempting to contribute to Syncthing. This is the largest, most rapidly-in-development, and most mission-critical repository I have sought to contribute. Previously I've had more success introducing myself as a productive member of the open-source community, via contributing cosmetic (copyediting) improvements to documentation and code layouts, to smaller, less intensely-maintained projects.

I'm not quitting on y'all, but I am willing to a more conservative approach to contributing if that is preferred by the community. I'm just not really sure where to begin to make myself useful while I learn the codebase of Syncthing and brush up on `Go` syntax, which despite my background in `C++` does have some differences to consider.

The theory behind my style of commits (and pull requests) thus far has been based on the idea of atomicity, which suggests the best way to change things is in granular fashion so that some changes can be reverted or accepted without affecting others. (For example, I would do a separate commit for moving the open-block curly braces onto a separate line, as that is a more controversial point of style and I might be told to revert it while something like providing consistency for spacing between operators in CSS definitions might be accepted.)

Did I actually make a mistake on the branching, or is that just how the GitHub web GUI displays my commits?

**Comment by tomasz1986** [comment]
> Did I actually make a mistake on the branching, or is that just how the GitHub web GUI displays my commits?

It seems that you've created a new branch on top of the one used in https://github.com/syncthing/syncthing/pull/8166 instead of using `main` as the start.

When it comes to purely cosmetic fixes though, as far as I understand, you just don't do them unless they're a by-product of actual code fixes. This means that if you're implementing real bug fixes and such, and in the process you decide to improve the related formatting as well, that's fine, but changing formatting for the sake of formatting is not.

**Comment by calmh** [comment]
Yeah, no, we don't do formatting-only changes unless there are specific circumstances.

**Pull request closed without merging**
