### PR TITLE
Update lang-de.json

### PR DESCRIPTION
**Pull request by agowa338**
### Purpose

Opposite meaning, translation error...

### CODE REVIEW

**Comment by uok** [comment]
thanks for contributing, please close this issue and make the corrections on [transifex](https://www.transifex.com/syncthing/syncthing/)

**Comment by wweich** [comment]
I don't think that your translation is correct.
You say: When set as master, every other node is write protected.
But that is not the case. The other nodes can still change files and push that changes to every other node. But the master node won't accept those changes.
So from Sycnthing's point of view, the master node is the one who is write protected (protected agains changes from other nodes).

**Comment by agowa338** [comment]
> The other nodes can still change files and push that changes to every other node
Sorry to say this, but where is the sense with this?
Wouldn't it be more intuitive to have the master node providing the files and all other nodes only accept the files matching the ones from master?

**Comment by wweich** [comment]
This is useful if you don't want other nodes to change files on this machine. If other nodes do change something and want to send it to a master, the master will block that and give you a button to override the changes.

Syncthing currently has no master-slave architecture, but only "master-normal" (no slaves). The other nodes don't know that this one is master.
There was a discussion how the setting could be named better, but we didn't really come up with a better name and description.

**Comment by agowa338** [comment]
Actually I think I have a better name: "Protected Node" or "Protected Client"
Even though I think this "feature" is a design bug...

**Pull request closed without merging**
