### PR TITLE
cmd/syncthing: Enable KCP by default

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Merge only if you are happy that it works.

Also, use upstream library, as my changes have been merged.

### CODE REVIEW

**Comment by calmh** [comment]
On phone, didn’t read. How about enabling it when the candidate or beta flags are set?

**Comment by AudriusButkevicius** [comment]
Whats the worst that can happen if we enable it across the board?

**Comment by calmh** [comment]
I dunno really, I guess we'll see during the RC anyway regardless

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by AudriusButkevicius** [comment]
Let's make this the most buggy RC ever.

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review rerun tests

**Comment by st-review** [comment]
I'm sorry, @AudriusButkevicius. I'm afraid I don't know what you mean. I know how to `don't`, `lgtm`, `merge`, `prevent`, `rebuild`, `squash`, `stop`.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review rebuild

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
a night with the bots

**Comment by AudriusButkevicius** [comment]
@st-review rebuild

**Comment by AudriusButkevicius** [comment]
@st-review rebuild

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Patiently waited 30m0s for the build status to turn green, but enough is enough.

**Comment by imsodin** [comment]
@st-review merge

**Comment by st-review** [comment]
@imsodin: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by imsodin** [comment]
Meh, bot doesn't listen to me either. I think it needs to hear from its master @calmh

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: There's already a merge pending for this PR.

**Comment by AudriusButkevicius** [comment]
Screw robots.

**Comment by st-review** [comment]
@imsodin: Merge failed:

```
$ git fetch -f origin refs/pull/4427/head:pr-4427
From https://github.com/syncthing/syncthing
 * [new ref]           refs/pull/4427/head -> pr-4427
$ git fetch -f origin master:orig/master
From https://github.com/syncthing/syncthing
   694a7de5..fb7264a6  master     -> orig/master
   889814a1..fb7264a6  master     -> origin/master
$ git reset --hard
HEAD is now at 889814a1 gui: Add uncamel filter
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git reset --hard orig/master
HEAD is now at fb7264a6 cmd/syncthing: Enable KCP by default
$ git clean -fxd
$ git merge --squash --no-commit pr-4427
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

```

**Comment by calmh** [comment]
Zomg

**Pull request merged**
