### PR TITLE
WIP: Consider tempfile when checking for free space (fixes #2598)

### LINKED ISSUE #2598: Syncing large files requires double the disk space on resume
After restarting an in-progress sync of a large file (87 GB) I get an “insufficient disk space” error.

    2015-12-19 11:50:42: Folder "HAL": insufficient disk space in /Users/jan/Sync/HAL/ for HAL2 HD Julien 2015-11-08 (10.11.1).dmg: have 15773.03 MiB, need 86914.60 MiB

This is using the current release v0.12.8 (from syncthing-0.12.8.dmg).

That looks reasonable at first, but doesn’t account for the fact, that the space required is already reserved by the hidden temp file for the backup image.

I expected syncthing to continue where it left off. Why does it require the additional space?

Anything I can do differently apart from making more space, which currently isn’t an option?

The only workaround I have found is to delete the folder and recreate it on the machine that downloads the image. This is contrary to the idea of syncing, of course. ;)

### PR DESCRIPTION
**Pull request by andersonvom**
Checks the existing blocks that can be reused when downloading a file so
that it only requires the space corresponding to the missing blocks.
This will prevent syncthing from claiming the folder doesn't have enough
space when resuming download of large files after they have been
partially downloaded.

### CODE REVIEW

**Comment by andersonvom** [comment]
I'm wondering if this will alleviate the problem of running out of space when resuming downloads of large files. I still want to add tests if this seems like the right way to approach the problem.

**Comment by AudriusButkevicius** [comment]
To me this looks fine.

**Comment by andersonvom** [comment]
I'm also wondering if we should consider the size of all existing blocks for that, even the ones that are not reusable, but that would depend on what happens to a block that needs to be redownloaded (e.g. if it gets erased before downloading it again, then we know its space is also available).

**Comment by calmh** [comment]
This is closer to the truth, but as you note there are still corner cases. We'll never be able to do this correctly in all cases so I'm fine with that being the case.

**Comment by calmh** [comment]
Should have un-WIP:ed that before merging, but ah well

**Pull request merged**
