### PR TITLE
gui: Fix missing word in sendOwnership explanation in GUI

### PR DESCRIPTION
**Pull request by tomasz1986**
For consistency with syncOwnership explanation right above this one, the sentence should talk about "sending ownership information", and not just "sending ownership".

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### CODE REVIEW

**Comment by tomasz1986** [comment]
I've found this when working on the translation in Transifex. The `syncOwnership` explanation reads

```
Enables sending ownership information to other devices
```

so I think this one should too, instead of

```
Enables sending ownership to other devices
```

This is probably the last moment to change this without breaking existing translations.

**Review by acolomb — APPROVED** [review]
Can we somehow accelerate pushing to Transifex this one time, so it gets picked up before many translations are done?

**Review by acolomb — APPROVED** [review]

**Comment by tomasz1986** [comment]
I think Transifex pulls new strings often, maybe even everyday, so the fixed lines should be there very quickly. I'd suggest to merge this PR as soon as possible, if there are objections, of course.

I've just updated the language file as well, so that the script should automatically remove the obsolete string.

**Comment by acolomb** [comment]
Assuming no objections.  Let's leave enough time for translators to notice.

**Pull request merged**
