### PR TITLE
Fix STGUIASSETS search paths & order (fixes #2827)

### LINKED ISSUE #2827: STGUIASSETS should work when pointed to gui dir
In my mind, the bug is that STGUIASSETS should no longer point to the same hierachy that we compile in, and that the behavior is different when overriding vs when not. It used to be very simple (assuming $PATH has been requested):

1. $STGUIASSETS/$PATH
2. Compiled in asset $PATH

Now we're instead looking for

1. $STGUIASSETS/$PATH
2. Compiled in asset $THEME/$PATH
3. Compiled in asset default/$PATH

I think it would be cleaner if we instead looked for

1. $STGUIASSETS/$THEME/$PATH
2. Compiled in asset $THEME/$PATH
3. $STGUIASSETS/default/$PATH
4. Compiled in asset default/$PATH

Then we'd get back the old behavior of just being able to override the whole hierarchy and then hack on the dark theme or whatever as @lkwg82 also mentions. A (small) complication is that the theme selector would need to pick up themes present both in the compiled in assets and in the potential overridden assetsDir.

From a development point of view, I think pointing STGUIASSETS at the gui dir in the source checkout should result in it working exactly as normal, except that anything in there can be overridden regardless of theme etc. It's just that I haven't noticed this is not the case because I haven't done nay GUI dev work lately :)

(https://github.com/syncthing/docs/pull/132)

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Fix STGUIASSETS processing to be as I expect it to be; that is, you point it at `gui` in the source distribution, and whatever you have in there overrides what is compiled in. ~~What is *not* fixed here is that if you add a new theme, it won't show up in the theme selector. You need to actually manually configure that theme name for the moment; next PR...~~

### Testing

A unit test is added to verify the correct assets are served.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Doesn't pick up themes from tge asset dir though.

**Comment by calmh** [comment]
I thought I said that :)

> What is not fixed here is that if you add a new theme, it won't show up in the theme selector. You need to actually manually configure that theme name for the moment; next PR...

Or are you trying to say this is not worth doing without also fixing that?

**Comment by calmh** [comment]
Actually, I'll add it. Hang on.

**Comment by calmh** [comment]
@st-jenkins retest this

**Comment by AudriusButkevicius** [comment]
Whats up with the status checks

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
I'm not sure... Build server is wonky, or reporting to github is wonky...

**Comment by AudriusButkevicius** [comment]
@st-review merge this please

Fix STGUIASSETS search paths & order (fixes #2827)

**Comment by st-review** [comment]
OK, merged as 032365d57cb2fb7de734aabc28d3587de5fbd636. Thanks, @calmh!

**Pull request closed without merging**
