### PR TITLE
lib/config, lib/connections: Configurable protocol priority (ref #8626)

### PR DESCRIPTION
**Pull request by calmh**
This makes the various protocol priorities configurable among the other options. With this, it's possible to prefer QUIC over TCP for WAN connections, for example. Both sides need to be similarly configured for this to work properly.

The default priority order remains the same as previously (TCP, QUIC, Relay, with LAN better than WAN).

To make this happen I made each dialer & listener more priority aware, and moved the check for whether a connection is LAN or not into the dialer / listener -- this is the new "lanChecker" type that's passed around.

### CODE REVIEW

**Comment by bt90** [comment]
Somewhat orthogonal to your PR but IMHO mandatory if we want users to be able to properly replace TCP with QUIC: #7403

**Comment by bt90** [comment]
I'm not that happy with the priority approach to be honest. This puts the burden on the user to get the configuration right on all devices and prevents a hassle free upgrade path to prioritizing QUIC(**if** we want to do that).

It would be better if the user could express that certain connection types have the same priority while being able to manipulate the order in which they are dialed. In essence we would sort by connection quality and for the same quality by dialing priority.

With this approach QUIC WAN and TCP WAN would have the connection quality but we'd still keep TCP with a higher dialing priority. This avoids connection flip-flops if one device is missing the configuration.

**Comment by calmh** [comment]
I don't think that approach really fits, though. For one, we dial a whole bunch of addresses concurrently, IIRC. Also some method/addresses may require "warmup" (i.e., TCP punchthrough, in the rare cases when it works, requires connection attempts to have happened in both directions, I think).

However I think we could accomplish what you want by adding a further config: an "upgrade threshold". Say, for example, that I configured priorities as:

- TCP LAN: 10
- QUIC LAN: 15
- TCP WAN: 30
- QUIC WAN: 35

and set the upgrade threshold to 10. Then we'd prioritise TCP when trying to get a connection, but if we already have a QUIC WAN connection and are considering a TCP WAN connection, then 35-30 = 5 which is less than the threshold of 10 so no upgrade is attempted...

**Comment by bt90** [comment]
The threshold approach sounds good :+1:

**Review by er-pa — APPROVED** [review]
Looks reasonable to me

**Review by imsodin — APPROVED** [review]
Looks good to me too. Just one thing that crossed my mind, definitely no blocker (plus the usual: likely missing some point, yada-yada...): 

Do we really want to make LAN vs WAN prio configurable?  
While senseless, one could configure LAN with worse prio than WAN as is. Maybe lets define that `prio(type, lan) == prio(type, wan) - 10` instead. As far as I see the all use-cases brought up, including the threshold mechanism would still work fine with that. And it's a bit less config/moving pieces.

**Comment by calmh** [comment]
> Do we really want to make LAN vs WAN prio configurable?

We do, or I do, because a use case for this is to use TCP locally but QUIC over WAN. That's not achievable with just an offset.

**Comment by imsodin** [comment]
Ah yes. there it is :) 

We might want to emit a warning on config validation when `prio(type, lan) > prio(type, wan)`, as we assume lan is always lower in the lowest prio function (and it also is most likely a user mistake).

**Comment by calmh** [comment]
I added a thing to ensure that LAN is always preferred over WAN, for each individual protocol. It's still possible to say that we prefer TCP over WAN to QUIC over LAN, for example, and I think this is as it should be.

**Pull request merged**
