### PR TITLE
If rename works we are happy (fixes #1767)

### LINKED ISSUE #1767: FAIL: TestInWritableDirWindowsRename
http://build.syncthing.net/job/syncthing-windows-integration/115/console

```
--- FAIL: TestInWritableDirWindowsRename (0.02s)
	osutil_test.go:147: Expected error testdata/windows/ro/readonly
	osutil_test.go:147: Expected error testdata/windows/ro
	osutil_test.go:147: Expected error testdata/windows
	osutil_test.go:158: Unexpected error testdata/windows/ro/readonly: GetFileAttributesEx testdata\windows\ro: The system cannot find the path specified.
	osutil_test.go:162: Unexpected error testdata/windows/ro/readonly: GetFileAttributesEx testdata/windows/ro/readonlynew: The system cannot find the path specified.
	osutil_test.go:158: Unexpected error testdata/windows/ro: GetFileAttributesEx testdata\windows: The system cannot find the file specified.
	osutil_test.go:162: Unexpected error testdata/windows/ro: GetFileAttributesEx testdata/windows/ronew: The system cannot find the path specified.
	osutil_test.go:158: Unexpected error testdata/windows: remove testdata/windowsnew: The directory is not empty.
FAIL
FAIL	github.com/syncthing/syncthing/internal/osutil	0.192s
```

### PR DESCRIPTION
**Pull request by Zillode**

### CODE REVIEW

**Comment by Zillode** [comment]
@st-jenkins run integration tests for windows

**Comment by calmh** [comment]
Actually, I'd change the `t.Errorf` in the loop into a `t.Skipf("seem like this test doesn't work here"); return` to better document that the test is not in fact testing what we think it's testing...

**Comment by Zillode** [comment]
@st-jenkins run integration tests for windows

**Comment by Zillode** [comment]
@st-jenkins run integration tests for windows

**Pull request merged**
