### PR TITLE
gui: Early return 'danger' over 'warning'

### LINKED ISSUE #3242: gui: Unshared folder with error should show stopped
screenshot at 2016-06-02 06 20 17

### PR DESCRIPTION
**Pull request by norgeous**
as above

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So this only changes the class, which only changes the colors I think.

**Comment by norgeous** [comment]
Yes you are right... I got confused, the bug I opened #3242 is not present in the latest development version (Closing...). However this code change does enable early return and brings `folderClass` inline with `folderStatus`. Renaming this PR...

**Comment by AudriusButkevicius** [comment]
@st-review merge

gui: Early return 'danger' over 'warning'

**Comment by st-review** [comment]
:ok_hand: Merged as d317f197be8489491b43fb9a4b7c1548bdd8bf84. Thanks, @norgeous!

**Pull request closed without merging**
