### PR TITLE
lib/model: Honor umask when creating folder directories on Unix (fixes #2519)

### LINKED ISSUE #2519: Should honor umask when creating shared folder
SyncThing 0.12.4, sync from Windows to Linux (Ubuntu), "Ignore Permissions" checked when adding a new folder (synched from Windows, if that matters) on Linux side, with umask set to 0022 in /etc/init/syncthing.conf for Upstart.

The umask setting is honored for the folder content, but not for the folder itself, which is always created with permissions 0700 instead of 0755.

### PR DESCRIPTION
**Pull request by calmh**
Doesn't change the behavior on Windows.

### CODE REVIEW

**Comment by calmh** [comment]
(No power at home so no solaris builder at the moment...)

**Comment by AudriusButkevicius** [comment]
You must be really living off the grid to have power cuts in the 21st century in a country with no hurricanes...

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by AudriusButkevicius** [comment]
Well, no power = no merge

**Comment by calmh** [comment]
Yeah, no, this is an intentional electrician-induced power cut as they're doing work on the wiring in the house. Still annoying, but laptop and 4G makes it bearable for a short while.

**Comment by AudriusButkevicius** [comment]
Right, hopefully we don't forget this somehow.

**Comment by calmh** [comment]
I disabled/un-required the Solaris builder. We don't need to run all PRs on it, and for the other jobs (Linux & Windows) there are redundant builders so my house is not a single point of failure. :)

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: There's already a merge pending for this PR.

**Comment by st-review** [comment]
@AudriusButkevicius: Patiently waited 30m0s for the build status to turn green, but enough is enough.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as bdb56d91b9a33eafd31a11e9a07fa4fb3e9fa243. Thanks, @calmh!

**Pull request closed without merging**
