### PR TITLE
vendor: Fix kcp deadlock 

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Ref #4459

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 9c60bb8336211c96eeae207d3613b8b523615030. Thanks, @AudriusButkevicius!

**Comment by AudriusButkevicius** [comment]
@calmh rc2 worthy? blocks dials :)

**Comment by calmh** [comment]
Hah. Nice one. Yeah.

**Comment by AudriusButkevicius** [comment]
Clearly Well tested™

**Comment by alyandon** [comment]
Totally stealing "Clearly Well tested™" for code reviews.  Hope you don't mind!

**Pull request closed without merging**
