### PR TITLE
add some contrib files

### PR DESCRIPTION
**Pull request by 13werwolf13**
I took the liberty of adding a little contrib, maintainers have to solve these problems on their own and everyone spends time trying to get a result that already exists somewhere.

### CODE REVIEW

**Comment by 13werwolf13** [comment]
examples of rpm spec which show how the given files are used

```spec
#
# spec file for package strelaysrv
#
# Copyright (c) 2021 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#

Name:           strelaysrv
Version:        1.26.0
Release:        0
Summary:        Syncthing relay server
License:        GPL-3.0
URL:            https://github.com/syncthing/syncthing
Source:         %{name}-%{version}.tar.gz
Source1:        vendor.tar.gz
Source2:        contrib.tar.gz
Requires:       coreutils
%if 0%{?sle_version} == 150500 && 0%{?is_opensuse}
BuildRequires:  go1.20
%endif
BuildRequires:  golang-packaging
BuildRequires:  systemd-rpm-macros
BuildRequires:  sysuser-tools
Provides:       user(strelaysrv)
%{sysusers_requires}

%description
strelaysrv - Syncthing relay server

%prep
%setup

%build
go build -mod vendor ./cmd/strelaysrv/
%sysusers_generate_pre %{_sysusersdir}/system-user-strelaysrv.conf strelaysrv

%install
install -Dm 755  strelaysrv %{buildroot}%{_bindir}/strelaysrv
install -Dm 644  contrib/systemd/strelaysrv.service %{buildroot}%{_unitdir}/strelaysrv.service
install -Dm 644  contrib/systemd/strelaysrv.tmpfiles %{buildroot}%{_tmpfilesdir}/strelaysrv.conf
install -Dm 644  contrib/systemd/strelaysrv.sysusers %{buildroot}%{_sysusersdir}/system-user-strelaysrv.conf
install -Dm 644  contrib/systemd/strelaysrv.env %{buildroot}%{_sysconfdir}/strelaysrv.conf

%files
%license LICENSE
%doc cmd/strelaysrv/README.md
%config(noreplace) %{_sysconfdir}/strelaysrv.conf
%{_bindir}/strelaysrv
%{_unitdir}/strelaysrv.service
%{_tmpfilesdir}/strelaysrv.conf
%{_sysusersdir}/system-user-strelaysrv.conf

%pre -f strelaysrv.pre
%service_add_pre strelaysrv.service

%post
%service_add_post strelaysrv.service
%sysusers_create %{_sysusersdir}/system-user-strelaysrv.conf
%tmpfiles_create %{_tmpfilesdir}/strelaysrv.conf

%preun
%service_del_preun strelaysrv.service

%postun
%service_del_postun strelaysrv.service

%changelog

```

```spec
#
# spec file for package stdiscosrv
#
# Copyright (c) 2021 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#

Name:           stdiscosrv
Version:        1.26.0
Release:        0
Summary:        Syncthing discovery server
License:        GPL-3.0
URL:            https://github.com/syncthing/syncthing
Source:         %{name}-%{version}.tar.gz
Source1:        vendor.tar.gz
Source2:        contrib.tar.gz
Patch:          go.mod.patch
Requires:       coreutils
BuildRequires:  golang-packaging
BuildRequires:  go >= 1.19
BuildRequires:  systemd-rpm-macros
BuildRequires:  sysuser-tools
Provides:       user(stdiscosrv)
%{sysusers_requires}

%description
stdiscosrv - Syncthing discovery server

%prep
%setup

%build
go build -mod vendor ./cmd/stdiscosrv/
%sysusers_generate_pre %{_sysusersdir}/system-user-stdiscosrv.conf stdiscosrv

%install
install -Dm 755  stdiscosrv %{buildroot}%{_bindir}/stdiscosrv
install -Dm 644  contrib/systemd/stdiscosrv.service %{buildroot}%{_unitdir}/stdiscosrv.service
install -Dm 644  contrib/systemd/stdiscosrv.tmpfiles %{buildroot}%{_tmpfilesdir}/stdiscosrv.conf
install -Dm 644  contrib/systemd/stdiscosrv.sysusers %{buildroot}%{_sysusersdir}/system-user-stdiscosrv.conf
install -Dm 644  contrib/systemd/stdiscosrv.env %{buildroot}%{_sysconfdir}/stdiscosrv.conf

%files
%license LICENSE
%doc cmd/stdiscosrv/README.md
%config(noreplace) %{_sysconfdir}/stdiscosrv.conf
%{_bindir}/stdiscosrv
%{_unitdir}/stdiscosrv.service
%{_tmpfilesdir}/stdiscosrv.conf
%{_sysusersdir}/system-user-stdiscosrv.conf

%pre -f stdiscosrv.pre
%service_add_pre stdiscosrv.service

%post
%service_add_post stdiscosrv.service
%sysusers_create %{_sysusersdir}/system-user-stdiscosrv.conf
%tmpfiles_create %{_tmpfilesdir}/stdiscosrv.conf

%preun
%service_del_preun stdiscosrv.service

%postun
%service_del_postun stdiscosrv.service

%changelog

```

**Comment by calmh** [comment]
That's nice, though I don't see why you need to move the Docker files, and there are existing systemd templates under `etc/linux-systemd`...

**Comment by 13werwolf13** [comment]
> I don't see why you need to move the Docker files

I thought a little order wouldn't hurt

> and there are existing systemd templates under etc/linux-systemd...

Apparently I'm not very attentive...
i see syncthing-resume.service, syncthing@.service but not stdiscosrv & strelaysrv
And besides the service files, there is something else that I should do, cancel this mr or modify it?

**Comment by reneleonhardt** [comment]
Did you actually test the GitHub build after all those movements? For example with https://github.com/nektos/act
You didn't change the Dockerfile paths in the build workflows for starters ;)

**Comment by 13werwolf13** [comment]
Well, I was convinced that my idea, although it could be useful, obviously changes too much in the established traditions of a particular project. I'm closing this mr.

**Comment by reneleonhardt** [comment]
@13werwolf13 I hope it didn't sound negatively, I want to contribute to many projects too, but most of the time contributions are not accepted, even if they are smaller than your one and more important like fixing bugs and closing security CVEs for corporate projects... 🤷‍♂️
Sometimes it helps to open an "issue" first, some projects agree to discuss improvements openly.

**Pull request closed without merging**
