### PR TITLE
Remove TestGithubRelease

### PR DESCRIPTION
**Pull request by nbraud**
### Purpose

This removes `TestGithubRelease` and its associated test data, as per #3362.

### Testing

The modified source has been built and tests have been run without issues.

### Authorship

I'm fine with my name (Nicolas Braud-Santoni) or my nickname (nicoo) being added to the AUTHORS file.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins test this please

**Comment by calmh** [comment]
Thanks! No authorship needed as zero lines authored, but we'll do that on your next PR :)

**Comment by calmh** [comment]
@st-review merge it please

lib/upgrade: Remove TestGithubRelease (fixes #3362)

Skip-check: authors

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as a9ee4bb9f18d45bc22ff24f45067b0e156fbfef1. Thanks, @nbraud!

**Comment by nbraud** [comment]
@calmh OK, and thanks a lot for the quick merge  :-)

**Pull request closed without merging**
