### PR TITLE
Add relay and discovery Dockerfiles

### PR DESCRIPTION
**Pull request by jyundt**
### Purpose
Add Dockerfiles for discovery and relay servers. Both files are mostly copy/pasta-ed from the existing syncthing Dockerfile. I slightly modified the entrypoint to allow for reuse between all three images.

This is a follow-up to #6014. 

### Testing

I've been running containers based on these Dockerfiles:

- https://hub.docker.com/r/jyundt/strelaysrv
- https://hub.docker.com/r/jyundt/stdiscosrv

### CODE REVIEW

**Comment by jyundt** [comment]
> Does the discosrv require host networking? It depends on being able to see the source address of the announcing device and I’d expect the Docker proxy obscures this

Based on my testing: no, host networking isn't required.

However, I have the discovery server behind an Ingress router [(ingress-nginx)](https://kubernetes.github.io/ingress-nginx/) with the following annotations:

```
annotations:
  nginx.ingress.kubernetes.io/server-snippet: |
    ssl_verify_client optional_no_ca;
  nginx.ingress.kubernetes.io/configuration-snippet: |
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-SSL-Cert $ssl_client_cert;
```

I also had to add the other misc relay/disco ports (22000, 22067, 22070, 19200) to the `tcp-services` config map as well.

**Comment by calmh** [comment]
Right, so the discovery server picks up x-forwarded-for and makes this work, but I don't think that will be the case in general when someone tries to deploy this, so it requires notes or some workaround I think.

**Comment by jyundt** [comment]
Can you provide more details about the deployment scenario you'd like me to test / document?

I ran the discovery container in docker (no kubernetes), pointed a few clients to it and I _think_ it's working as expected.

I ran the following on a server:

```
$ docker run --rm -p 8443:8443 jyundt/stdiscosrv "-debug"
stdiscosrv v1.3.0+63-g59e83a58-add-relay-disco-dockerfiles "Fermium Flea" (go1.13.4 linux-amd64) docker@syncthing.net 2019-11-09 16:14:37 UTC
Failed to load keypair. Generating one, this might take a while...
Server device ID is 57OEPHJ-344DNTM-SZVYPM6-3VZWPWH-3HGWX4H-MJPQKRZ-6OOIQXF-M35KBQ2
```

And then pointed some clients to: `https://$myserver:8443/?id=57OEPHJ-344DNTM-SZVYPM6-3VZWPWH-3HGWX4H-MJPQKRZ-6OOIQXF-M35KBQ2`

However, in ^this config I am getting some `http: TLS handshake error` errors that I didn't encounter when running in k8s / with an ingress router:

```78629a0f5f3f164f GET /?device=HH4N4UC-EGQOB5S-EMCQ3PA-#######-#######-#######-#######-#######
380704bb7b4d7c03 POST /
57e9d1860d1d68d8 GET /?device=P42J27W-AWBSYRR-GQLLGQL-#######-#######-#######-#######-#######
1408d2ac22c4d294 GET /?device=RJ4WSBH-LB74VTJ-GIKRFLM-#######-#######-#######-#######-#######
268447a4189deb99 GET /?device=VTFCKKH-5MMDF5N-56YRCYZ-#######-#######-#######-#######-#######
68255aaf95e94627 GET /?device=WPLPF7N-KGEAOTB-7ZWEMXC-#######-#######-#######-#######-#######
http: TLS handshake error from 127.0.0.1:33911: EOF
http: TLS handshake error from 127.0.0.1:45105: EOF
30b95ff183c471d4 GET /?device=HH4N4UC-EGQOB5S-EMCQ3PA-#######-#######-#######-#######-#######
3c04951aa42655d9 GET /?device=P42J27W-AWBSYRR-GQLLGQL-#######-#######-#######-#######-#######
25845c95d4491d1b GET /?device=RJ4WSBH-LB74VTJ-GIKRFLM-#######-#######-#######-#######-#######
1bf98be2a9d78d73 GET /?device=VTFCKKH-5MMDF5N-56YRCYZ-#######-#######-#######-#######-#######
2e3108dabb158644 GET /?device=WPLPF7N-KGEAOTB-7ZWEMXC-#######-#######-#######-#######-#######
6e661e92759805f5 POST /
2606cd2b57d29245 GET /?device=HH4N4UC-EGQOB5S-EMCQ3PA-#######-#######-#######-#######-#######
1a714cf86b83d0e2 GET /?device=P42J27W-AWBSYRR-GQLLGQL-#######-#######-#######-#######-#######
592e17f7b068d9db GET /?device=RJ4WSBH-LB74VTJ-GIKRFLM-#######-#######-#######-#######-#######
039f6f78a15d523b GET /?device=WPLPF7N-KGEAOTB-7ZWEMXC-#######-#######-#######-#######-#######
4dba7b0f9da1d7eb GET /?device=3BL666K-27RHZMZ-PMLFSSW-#######-#######-#######-#######-#######
http: TLS handshake error from 127.0.0.1:39101: EOF
```

Were you thinking about a deployment scenario that is kubernetes / no ingress router?

**Comment by AudriusButkevicius** [comment]
Can you hit it from a remote machine?
`http: TLS handshake error from 127.0.0.1:33911: EOF` shows local address, which is not clear if it's because of docker proxy or because of local routing rules.

**Comment by jyundt** [comment]
> Can you hit it from a remote machine?
> `http: TLS handshake error from 127.0.0.1:33911: EOF` shows local address, which is not clear if it's because of docker proxy or because of local routing rules.

Yes, I was hitting it from remote machines.

Upon further inspection I think this was the Docker healthcheck:
```
HEALTHCHECK --interval=1m --timeout=10s \
  CMD nc -z localhost 8443 || exit 1
```

**Comment by AudriusButkevicius** [comment]
I think that's fine, but what I care whether remote IP address reported by the network stack is actually remote. It seems it is never in the logs, so you either need to modify the source code to add printing of it, or run stdiscosrv against postgres and check what gets recorded in the db.

**Comment by jyundt** [comment]
I built a new discovery container with this quick-and-dirty patch:

```
$ git diff
diff --git a/cmd/stdiscosrv/apisrv.go b/cmd/stdiscosrv/apisrv.go
index a848ebc9..104d4925 100644
--- a/cmd/stdiscosrv/apisrv.go
+++ b/cmd/stdiscosrv/apisrv.go
@@ -129,7 +129,7 @@ func (s *apiSrv) handler(w http.ResponseWriter, req *http.Request) {
        ctx := context.WithValue(topCtx, idKey, reqID)
 
        if debug {
-               log.Println(reqID, req.Method, req.URL)
+               log.Println(reqID, req.RemoteAddr, req.Method, req.URL)
        }
 
        var remoteIP net.IP
$
```


The remote IP address looks fine (I think):

```
# docker run --rm -p 8443:8443 stdiscosrv_localhost:latest -debug
stdiscosrv v1.3.1+39-g59e83a58-dirty-add-relay-disco-dockerfiles "Fermium Flea" (go1.13.1 linux-amd64) docker@syncthing.net 2019-11-09 16:14:37 UTC
Failed to load keypair. Generating one, this might take a while...
Server device ID is NJK62PX-JJZTHIU-UW57OIR-I3JRK4W-LEHO7C6-QCQUQQA-XWHZP4Y-YCRODQI
78629a0f5f3f164f 192.168.67.137:37006 GET /?device=HH4N4UC-EGQOB5S-EMCQ3PA-#######################################
380704bb7b4d7c03 192.168.67.137:37004 POST /
57e9d1860d1d68d8 192.168.67.137:37008 GET /?device=P42J27W-AWBSYRR-GQLLGQL-#######################################
1408d2ac22c4d294 192.168.67.137:37010 GET /?device=RJ4WSBH-LB74VTJ-GIKRFLM-#######################################
268447a4189deb99 192.168.67.137:37012 GET /?device=VTFCKKH-5MMDF5N-56YRCYZ-#######################################
68255aaf95e94627 192.168.67.137:37014 GET /?device=WPLPF7N-KGEAOTB-7ZWEMXC-#######################################
http: TLS handshake error from 127.0.0.1:45695: EOF
30b95ff183c471d4 192.168.67.121:44821 GET /?device=HH4N4UC-EGQOB5S-EMCQ3PA-#######################################
3c04951aa42655d9 192.168.67.121:44823 POST /
25845c95d4491d1b 192.168.67.121:44831 GET /?device=P42J27W-AWBSYRR-GQLLGQL-#######################################
1bf98be2a9d78d73 192.168.67.121:44833 GET /?device=RJ4WSBH-LB74VTJ-GIKRFLM-#######################################
2e3108dabb158644 192.168.67.121:44835 GET /?device=WPLPF7N-KGEAOTB-7ZWEMXC-#######################################
6e661e92759805f5 192.168.67.121:44837 GET /?device=3BL666K-27RHZMZ-PMLFSSW-#######################################
http: TLS handshake error from 127.0.0.1:34657: EOF
2584c47f2cdf5b8a 192.168.67.137:37048 GET /?device=HH4N4UC-EGQOB5S-EMCQ3PA-#######################################
6054502fc5d6d268 192.168.67.137:37050 GET /?device=P42J27W-AWBSYRR-GQLLGQL-#######################################
6ec34c367674cb74 192.168.67.137:37052 GET /?device=RJ4WSBH-LB74VTJ-GIKRFLM-#######################################
430c8b35bb9457d8 192.168.67.137:37054 GET /?device=WPLPF7N-KGEAOTB-7ZWEMXC-#######################################
http: TLS handshake error from 127.0.0.1:44819: EOF
```


Should I add additional debugging elsewhere to double check this remote IP?

**Comment by AudriusButkevicius** [comment]
No, this looks good. I am happy with this.

I'll leave for @calmh to merge given we've answered the question.

**Pull request merged**
