### PR TITLE
lib/connections: Add UTP support (fixes #804)

### LINKED ISSUE #804: Consider using reliable UDP for block transfers
This is a long-shot, over-engineering and is not required, but a interesting topic nonetheless which could be a unique selling point to Syncthing.

Some interesting ideas can be found [here](http://stackoverflow.com/questions/107668/what-do-you-use-when-you-need-reliable-udp)

I seems that the easiest one to adopt would be [UDT](http://udt.sourceforge.net/) with bindings already available for most languages.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
PR for review/testing.

I know we will use our own fork.

### CODE REVIEW

**Comment by calmh** [comment]
I created https://reviews.syncthing.net/cru/CR-14 for this as I'm sure there'll be some back and forth. Although maybe most of it may be on the vendored stuff anyway, we'll see.

**Comment by calmh** [comment]
Test failures are just config defaults around the stun stuff

**Comment by calmh** [comment]
First impression is that this seems to work rather well. A couple of integration tests with `s/tcp:/utp:/` in the config:

```
jb@syno:~/s/g/s/s/test $ go test -v -tags "integration benchmark" -run ManyFiles
=== RUN   TestBenchmarkTransferManyFiles
2016/05/26 14:45:43 Cleaning...
2016/05/26 14:45:43 Generating files...
2016/05/26 14:45:53 Total 154.2 MiB in 50000 files
2016/05/26 14:45:53 Starting instance 1...
2016/05/26 14:45:58 Starting instance 2...
2016/05/26 14:45:59 {9 2016-05-26 14:45:59.075155089 +0200 CEST StateChanged map[folder:default from:idle to:scanning]}
2016/05/26 14:45:59 {12 2016-05-26 14:45:59.075386267 +0200 CEST StateChanged map[duration:0.00023089600000000002 folder:default from:scanning to:idle]}
2016/05/26 14:45:59 {17 2016-05-26 14:45:59.146684244 +0200 CEST StateChanged map[duration:0.071297752 folder:default from:idle to:syncing]}
2016/05/26 14:46:28 {100737 2016-05-26 14:46:27.909864445 +0200 CEST StateChanged map[duration:28.763178832 folder:default from:syncing to:idle]}
2016/05/26 14:46:28 Verifying...
2016/05/26 14:46:29 Result: Wall time: 28.763180201s
2016/05/26 14:46:29 Result: 5.4 MiB/s synced
2016/05/26 14:46:29 Receiver: Utime: 40.631256s
2016/05/26 14:46:29 Receiver: Stime: 22.472824s
2016/05/26 14:46:29 Receiver: MaxRSS: 90052 KiB
2016/05/26 14:46:29 Sender: Utime: 42.37251s
2016/05/26 14:46:29 Sender: Stime: 8.316362s
2016/05/26 14:46:29 Sender: MaxRSS: 83440 KiB
--- PASS: TestBenchmarkTransferManyFiles (46.79s)
PASS
ok  	github.com/syncthing/syncthing/test	46.807s
jb@syno:~/s/g/s/s/test $ go test -v -tags "integration benchmark" -run LargeFile2G
=== RUN   TestBenchmarkTransferLargeFile2G
2016/05/26 14:46:45 Cleaning...
2016/05/26 14:47:00 Generating files...
2016/05/26 14:47:07 Total 2048.0 MiB in 1 files
2016/05/26 14:47:07 Starting instance 1...
2016/05/26 14:47:19 Starting instance 2...
2016/05/26 14:47:20 {11 2016-05-26 14:47:19.913855676 +0200 CEST StateChanged map[from:idle to:scanning folder:default]}
2016/05/26 14:47:20 {12 2016-05-26 14:47:19.913997622 +0200 CEST StateChanged map[duration:0.00014171800000000001 folder:default from:scanning to:idle]}
2016/05/26 14:47:20 {17 2016-05-26 14:47:19.996501759 +0200 CEST StateChanged map[duration:0.082503792 folder:default from:idle to:syncing]}
2016/05/26 14:47:56 {43 2016-05-26 14:47:56.260290556 +0200 CEST StateChanged map[folder:default from:syncing to:idle duration:36.26378843]}
2016/05/26 14:47:56 Verifying...
2016/05/26 14:48:00 Result: Wall time: 36.263788797s
2016/05/26 14:48:00 Result: 56.5 MiB/s synced
2016/05/26 14:48:00 Receiver: Utime: 48.709398s
2016/05/26 14:48:00 Receiver: Stime: 20.428559s
2016/05/26 14:48:00 Receiver: MaxRSS: 51184 KiB
2016/05/26 14:48:00 Sender: Utime: 44.024839s
2016/05/26 14:48:00 Sender: Stime: 21.932s
2016/05/26 14:48:00 Sender: MaxRSS: 39944 KiB
--- PASS: TestBenchmarkTransferLargeFile2G (74.71s)
PASS
ok  	github.com/syncthing/syncthing/test	74.719s
jb@syno:~/s/g/s/s/test $ 
```

(That's close enough to the TCP numbers in the first case and about a fifth of the TCP speed in the second but still good enough.)

We should update the `Address` field in the GUI to show more clearly the connection type - currently it's just in the tooltip. No need for the client/server distinction there, but maybe it would be nice to show the actual url á la `utp://127.0.0.1:22001`.

**Comment by AudriusButkevicius** [comment]
What about memory stats?

**Comment by calmh** [comment]
No significant difference in memory utilization. Here are the full benchmarks for comparison:

### UTP

```
jb@syno:~/s/g/s/s/test $ go test -v -tags "integration benchmark" -run ManyFiles
...
2016/05/26 15:20:53 Result: Wall time: 28.019343614s
2016/05/26 15:20:53 Result: 5.5 MiB/s synced
2016/05/26 15:20:53 Receiver: Utime: 39.441504s
2016/05/26 15:20:53 Receiver: Stime: 22.506826s
2016/05/26 15:20:53 Receiver: MaxRSS: 90796 KiB
2016/05/26 15:20:53 Sender: Utime: 41.650274s
2016/05/26 15:20:53 Sender: Stime: 8.294506s
2016/05/26 15:20:53 Sender: MaxRSS: 85184 KiB
--- PASS: TestBenchmarkTransferManyFiles (61.38s)
PASS
ok  	github.com/syncthing/syncthing/test	61.397s
jb@syno:~/s/g/s/s/test $ go test -v -tags "integration benchmark" -run LargeFile2G
...
2016/05/26 15:23:51 Result: Wall time: 40.490043341s
2016/05/26 15:23:51 Result: 50.6 MiB/s synced
2016/05/26 15:23:51 Receiver: Utime: 55.030133s
2016/05/26 15:23:51 Receiver: Stime: 24.811183s
2016/05/26 15:23:51 Receiver: MaxRSS: 53944 KiB
2016/05/26 15:23:51 Sender: Utime: 47.310353s
2016/05/26 15:23:51 Sender: Stime: 29.755932s
2016/05/26 15:23:51 Sender: MaxRSS: 39424 KiB
--- PASS: TestBenchmarkTransferLargeFile2G (80.89s)
PASS
ok  	github.com/syncthing/syncthing/test	80.905s
```

### TCP

```
jb@syno:~/s/g/s/s/test $ go test -v -tags "integration benchmark" -run ManyFiles
...
2016/05/26 15:24:49 Result: Wall time: 25.883400474s
2016/05/26 15:24:49 Result: 6.0 MiB/s synced
2016/05/26 15:24:49 Receiver: Utime: 34.311382s
2016/05/26 15:24:49 Receiver: Stime: 19.899173s
2016/05/26 15:24:49 Receiver: MaxRSS: 90588 KiB
2016/05/26 15:24:49 Sender: Utime: 38.349314s
2016/05/26 15:24:49 Sender: Stime: 5.961613s
2016/05/26 15:24:49 Sender: MaxRSS: 84000 KiB
--- PASS: TestBenchmarkTransferManyFiles (43.00s)
PASS
ok  	github.com/syncthing/syncthing/test	43.019s
jb@syno:~/s/g/s/s/test $ go test -v -tags "integration benchmark" -run LargeFile2G
...
2016/05/26 15:25:38 Result: Wall time: 6.876926392s
2016/05/26 15:25:38 Result: 297.8 MiB/s synced
2016/05/26 15:25:38 Receiver: Utime: 26.257437s
2016/05/26 15:25:38 Receiver: Stime: 3.490791s
2016/05/26 15:25:38 Receiver: MaxRSS: 47636 KiB
2016/05/26 15:25:38 Sender: Utime: 13.978795s
2016/05/26 15:25:38 Sender: Stime: 3.149591s
2016/05/26 15:25:38 Sender: MaxRSS: 37520 KiB
--- PASS: TestBenchmarkTransferLargeFile2G (43.72s)
PASS
ok  	github.com/syncthing/syncthing/test	43.728s
jb@syno:~/s/g/s/s/test $ 
```

There is of course a significant CPU and pure transfer performance hit in the "largefile" case (where we are otherwise fast), but I expected that.

**Comment by AudriusButkevicius** [comment]
Wow the cpu hit is so big.

**Comment by calmh** [comment]
Yes... The increase in `Stime`, and a large part of the `Utime` as well, are just because we're doing a system call and userspace-kernel-userspace context switch for every packet, while with TCP it's large copies into the kernel. The rest is probably just optimization. The kernel TCP stack is rather optimized at this point, the uTP code does something similar but worse... :)

**Comment by calmh** [comment]
```
[ANTOJ] 2016/05/26 19:46:08.181331 utp_listen.go:153: DEBUG: utp://0.0.0.0:22020 stun discovery on stun.ekiga.net:3478: Received data format mismatch. (&{%!s(uint16=1) 213.114.37.239 %!s(uint16=22020)})
```

**Comment by calmh** [comment]
I'm not currently getting it to connect through two NAT devices, the above error may be related. Both sides appear to trying to connect to the "original" port 22020 of the other.

**Comment by AudriusButkevicius** [comment]
What NAT type does it report when it starts?

**Comment by AudriusButkevicius** [comment]
I guess it doesn't report, as it errors out.
Does it error out twice?

**Comment by calmh** [comment]
There is weirdness here. I did the following patch:

```diff
 lib/connections/utp_listen.go | 20 ++++++++++++++++----
 test/h1/config.xml            |  9 +++++----
 2 files changed, 21 insertions(+), 8 deletions(-)

diff --git a/lib/connections/utp_listen.go b/lib/connections/utp_listen.go
index 18dfcfd..7ced651 100644
--- a/lib/connections/utp_listen.go
+++ b/lib/connections/utp_listen.go
@@ -50,7 +50,16 @@ func (t *utpListener) Serve() {
 
 	network := strings.Replace(t.uri.Scheme, "utp", "udp", -1)
 
-	listener, err := utp.NewSocket(network, t.uri.Host)
+	pc, err := net.ListenPacket(network, t.uri.Host)
+	if err != nil {
+		t.mut.Lock()
+		t.err = err
+		t.mut.Unlock()
+		l.Infoln("listen (BEP/utp):", err)
+		return
+	}
+
+	listener, err := utp.NewSocketFromPacketConn(pc)
 	if err != nil {
 		t.mut.Lock()
 		t.err = err
@@ -63,11 +72,13 @@ func (t *utpListener) Serve() {
 	l.Infof("UTP listener (%v) starting", listener.Addr())
 	defer l.Infof("UTP listener (%v) shutting down", listener.Addr())
 
-	go t.stunRenewal(listener)
+	go t.stunRenewal(pc)
 
 	for {
 		listener.SetDeadline(time.Now().Add(time.Second))
+		l.Debugln("utp calling accept")
 		conn, err := listener.Accept()
+		l.Debugln("utp accept returned")
 		select {
 		case <-t.stop:
 			if err == nil {
@@ -80,6 +91,7 @@ func (t *utpListener) Serve() {
 			if err, ok := err.(*net.OpError); !ok || !err.Timeout() {
 				l.Warnln("Accepting connection (BEP/utp):", err)
 			}
+			l.Debugln("utp ping")
 			continue
 		}
 
@@ -134,7 +146,7 @@ func (t *utpListener) Factory() listenerFactory {
 	return t.factory
 }
 
-func (t *utpListener) stunRenewal(listener *utp.Socket) {
+func (t *utpListener) stunRenewal(listener net.PacketConn) {
 	oldType := stun.NAT_UNKNOWN
 	for {
 		client := stun.NewClientWithConnection(listener)
@@ -150,7 +162,7 @@ func (t *utpListener) stunRenewal(listener *utp.Socket) {
 
 			natType, extAddr, err = client.Discover()
 			if err != nil || extAddr == nil {
-				l.Debugf("%s stun discovery on %s: %s (%s)", t.uri, addr, err, extAddr)
+				l.Debugf("%s stun discovery on %v: %v (%v)", t.uri, addr, err, extAddr)
 				continue
 			}
 ```

and get the following output:

```
jb@syno:~/s/g/s/s/test $ STTRACE=connections syncthing -home h1 | egrep -i 'utp|stun'
[I6KAH] 2016/05/27 12:53:56.648788 service.go:395: DEBUG: Starting listener utp://0.0.0.0:22020
[I6KAH] 2016/05/27 12:53:56.649386 utp_listen.go:72: INFO: UTP listener ([::]:22020) starting
[I6KAH] 2016/05/27 12:53:56.649415 utp_listen.go:79: DEBUG: utp calling accept
[I6KAH] 2016/05/27 12:53:56.755608 utp_listen.go:165: DEBUG: utp://0.0.0.0:22020 stun discovery on stun.ekiga.net:3478: read udp [::]:22020: use of closed network connection (<nil>)
[I6KAH] 2016/05/27 12:53:56.756726 utp_listen.go:165: DEBUG: utp://0.0.0.0:22020 stun discovery on stun1.voiceeclipse.net:3478: write udp [::]:22020->64.24.35.201:3478: use of closed network connection (<nil>)
^C
```

I don't know why the connection is considered closed; netstat confirmed it was, though... The deadline thing seems to not work, because the utpconn.Accept never returns.

**Comment by AudriusButkevicius** [comment]
I wonder if its some regression in the rebase. I'll poke at it tonight if I get a chance.

**Comment by calmh** [comment]
I added a UDP port forward to allow the connection, but there seems to be something else ungood in the UTP library itself as well:

```
[ANTOJ] 13:29:57 INFO: Established secure connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 at [::]:22020-194.126.249.11:58174 (UTP (Server))
[ANTOJ] 13:29:57 INFO: Device ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 client is "syncthing v0.13.4+5-g6ece4ae" named "acro-syncer.nym.se"
[ANTOJ] 13:29:58 INFO: Connected to already connected device (ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6)
[ANTOJ] 13:30:12 INFO: Connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 closed: timed out waiting for ack
[ANTOJ] 13:30:55 INFO: Established secure connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 at [::]:22020-194.126.249.11:47187 (UTP (Server))
[ANTOJ] 13:30:55 INFO: Device ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 client is "syncthing v0.13.4+5-g6ece4ae" named "acro-syncer.nym.se"
[ANTOJ] 13:31:10 INFO: Connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 closed: timed out waiting for ack
[ANTOJ] 13:31:55 INFO: Established secure connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 at [::]:22020-194.126.249.11:61876 (UTP (Server))
[ANTOJ] 13:31:55 INFO: Device ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 client is "syncthing v0.13.4+5-g6ece4ae" named "acro-syncer.nym.se"
[ANTOJ] 13:32:10 INFO: Connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 closed: timed out waiting for ack
```

```
[ACROT] 13:29:10 INFO: Connection to ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH closed: timed out waiting for ack
[ACROT] 13:29:57 INFO: Established secure connection to ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH at [::]:58174-213.114.37.239:22020 (UTP (Client))
[ACROT] 13:29:57 INFO: Device ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH client is "syncthing v0.13.4+5-g6ece4ae" named "anto-syncer"
[ACROT] 13:29:58 INFO: Connected to already connected device (ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH)
[ACROT] 13:30:12 INFO: Connection to ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH closed: peer reset
[ACROT] 13:30:55 INFO: Established secure connection to ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH at [::]:47187-213.114.37.239:22020 (UTP (Client))
[ACROT] 13:30:55 INFO: Device ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH client is "syncthing v0.13.4+5-g6ece4ae" named "anto-syncer"
[ACROT] 13:31:10 INFO: Connection to ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH closed: peer reset
[ACROT] 13:31:55 INFO: Established secure connection to ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH at [::]:61876-213.114.37.239:22020 (UTP (Client))
[ACROT] 13:31:55 INFO: Device ANTOJMC-IVBQICL-TOPD4BJ-GFU2AVM-UV5TLXJ-OJG5ATZ-GEBWSDY-XVJEZAH client is "syncthing v0.13.4+5-g6ece4ae" named "anto-syncer"
```

**Comment by AudriusButkevicius** [comment]
So I am sure it worked fairly well for some older version.

**Comment by AudriusButkevicius** [comment]
So just tested this branch works fine for me:

Client, behind NAT, has server address set to an invalid address.
```
[BKD5O] 20:53:30 INFO: syncthing v0.13.0-beta.2+125-g84bd0fd-utp "Copper Cockroach" (go1.6 windows-amd64) AUDRIUS\Audrius@Audrius 2016-05-27 19:35:35 UTC
[BKD5O] 20:53:30 INFO: My ID: BKD5O67-ZEX75J2-G33Y3O4-TGZHBZC-ON7BMJA-FTG56IO-DMCX6ZF-HCCZ2QM
[BKD5O] 20:53:30 INFO: Single thread hash performance is ~142 MB/s
[BKD5O] 20:53:30 INFO: Starting deadlock detector with 20m0s timeout
[BKD5O] 20:53:30 INFO: Ready to synchronize tPruK-4jm3c (readwrite)
[BKD5O] 20:53:30 INFO: Using discovery server https://discovery-v4-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[BKD5O] 20:53:30 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[BKD5O] 20:53:30 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[BKD5O] 20:53:30 INFO: Using discovery server https://discovery-v6-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[BKD5O] 20:53:30 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[BKD5O] 20:53:30 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[BKD5O] 20:53:30 INFO: UTP listener ([::]:22020) starting
[BKD5O] 20:53:30 INFO: Completed initial scan (rw) of folder tPruK-4jm3c
[BKD5O] 20:53:30 INFO: Device BKD5O67-ZEX75J2-G33Y3O4-TGZHBZC-ON7BMJA-FTG56IO-DMCX6ZF-HCCZ2QM is "PIRATAS VARDU BATAS" at [dynamic]
[BKD5O] 20:53:30 INFO: Device F72F5AO-37T2W7K-BC43BAN-ZDMWZF6-KR7SSHD-O6YQ7GM-CR2XWJG-UOTCTA5 is "Ocean" at [tcp://10.0.0.1]
[BKD5O] 20:53:30 INFO: No automatic upgrades; v0.13.0-beta.2+125-g84bd0fd-utp is not a release version.
[BKD5O] 20:53:30 INFO: Starting usage reporting
[BKD5O] 20:53:30 INFO: GUI and API listening on [::]:8384
[BKD5O] 20:53:30 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[BKD5O] 20:53:30 INFO: utp://0.0.0.0:22020 detected NAT type: Full cone NAT, external address: utp://195.99.88.219:54649
[BKD5O] 20:53:58 INFO: Established secure connection to F72F5AO-37T2W7K-BC43BAN-ZDMWZF6-KR7SSHD-O6YQ7GM-CR2XWJG-UOTCTA5 at [::]:22020-178.62.69.157:39468 (UTP (Server))
[BKD5O] 20:53:58 INFO: Device F72F5AO-37T2W7K-BC43BAN-ZDMWZF6-KR7SSHD-O6YQ7GM-CR2XWJG-UOTCTA5 client is "syncthing v0.12.4+486-g84bd0fd" named "audrius"
```


Server (on the public internet)
```
[monitor] 15:53:35 INFO: Starting syncthing
[F72F5] 15:53:36 INFO: syncthing v0.12.4+486-g84bd0fd "Copper Cockroach" (go1.6.2 linux-amd64) root@audrius 2016-05-27 19:35:35 UTC
[F72F5] 15:53:36 INFO: My ID: F72F5AO-37T2W7K-BC43BAN-ZDMWZF6-KR7SSHD-O6YQ7GM-CR2XWJG-UOTCTA5
[F72F5] 15:53:36 INFO: Single thread hash performance is ~61 MB/s
[F72F5] 15:53:36 INFO: Starting deadlock detector with 20m0s timeout
[F72F5] 15:53:36 INFO: Ready to synchronize tPruK-4jm3c (readwrite)
[F72F5] 15:53:36 INFO: Using discovery server https://discovery-v4-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[F72F5] 15:53:36 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[F72F5] 15:53:36 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[F72F5] 15:53:36 INFO: Using discovery server https://discovery-v6-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[F72F5] 15:53:36 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[F72F5] 15:53:36 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[F72F5] 15:53:36 INFO: UTP listener ([::]:22020) starting
[F72F5] 15:53:36 INFO: Completed initial scan (rw) of folder tPruK-4jm3c
[F72F5] 15:53:36 INFO: TCP listener ([::]:22000) starting
[F72F5] 15:53:36 INFO: Device BKD5O67-ZEX75J2-G33Y3O4-TGZHBZC-ON7BMJA-FTG56IO-DMCX6ZF-HCCZ2QM is "home" at [dynamic]
[F72F5] 15:53:36 INFO: Device F72F5AO-37T2W7K-BC43BAN-ZDMWZF6-KR7SSHD-O6YQ7GM-CR2XWJG-UOTCTA5 is "audrius" at [dynamic]
[F72F5] 15:53:36 INFO: No automatic upgrades; v0.12.4+486-g84bd0fd is not a release version.
[F72F5] 15:53:36 INFO: GUI and API listening on [::]:8384
[F72F5] 15:53:36 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[F72F5] 15:53:36 INFO: utp://0.0.0.0:22020 detected NAT type: Not behind a NAT, external address: utp://178.62.69.157:22020
[F72F5] 15:54:00 INFO: Established secure connection to BKD5O67-ZEX75J2-G33Y3O4-TGZHBZC-ON7BMJA-FTG56IO-DMCX6ZF-HCCZ2QM at [::]:39468-195.99.88.219:54649 (UTP (Client))
[F72F5] 15:54:00 INFO: Device BKD5O67-ZEX75J2-G33Y3O4-TGZHBZC-ON7BMJA-FTG56IO-DMCX6ZF-HCCZ2QM client is "syncthing v0.13.0-beta.2+125-g84bd0fd-utp" named "PIRATAS VARDU BATAS"
```

**Comment by AudriusButkevicius** [comment]
Aaaand I am suddenly in the same boat as you

https://github.com/anacrolix/utp/issues/14

**Comment by calmh** [comment]
Yeah so I guess I was using a newer+patched utp lib, so maybe I broke it or it broke by itself after the version you vendored

**Comment by AudriusButkevicius** [comment]
No, it's intermittent even with latest version, due to potentially getting no packets from stun servers. I seem to have more reliable udp than you.

**Comment by AudriusButkevicius** [comment]
Updated UTP package with the fix to deadlines, see if you can get it to work now.

**Comment by calmh** [comment]
I'll test it. But thinking more about it I'm not sure how the stun stuff would work, except when run before the uTP layers starts. Once uTP runs, surely it swallows any packets coming in on the socket in order to be able to read them and attempt to match to an uTP connection?

**Comment by AudriusButkevicius** [comment]
No, it actually passes through packets it does not recognize as UTP.

**Comment by calmh** [comment]
RFC 5626 (which is really about SIP, but talks about using STUN for NAT keepalive) recommends 24-29 seconds. https://tools.ietf.org/html/rfc5626#section-4.4.2

**Comment by AudriusButkevicius** [comment]
So maybe we just send a packet to google every 24 seconds?

**Comment by calmh** [comment]
So for 100k devices (which is roughly the magnitude we have) that's 4k packets/s we're pointing at someone. It's not completely insignificant. I think the correct solution is to have a stun.syncthing.net and let that be a round robin dns thing to either our own infrastructure or a pool of public addresses or in the future maybe a mix.

**Comment by calmh** [comment]
There should be prior art here. What do the various torrent clients out there do for example?

**Comment by AudriusButkevicius** [comment]
It seems they send keep alives every 20 or so seconds.
It doesn't say where to though :D

**Comment by AudriusButkevicius** [comment]
SIP sends it to the SIP server, torrent sends it to one of the peers or DHT.

**Comment by bigbear2nd** [comment]
For it would be nice to see the magnitude we have when we can see the impact on stun.syncthing.net, I guess the privacy focused users might be interested in being able to customize this. :smiley:

**Comment by AudriusButkevicius** [comment]
Stun is somewhat magical and requires two public ips on the same machine, so I do not anticipate many people running it themsleves.

**Comment by AudriusButkevicius** [comment]
@calmh so whats the verdict here?

**Comment by calmh** [comment]
I haven't had time to resume testing. Not sure about the STUN thing. Once we have a peer, we could use them. But that gets complex as well.

**Comment by calmh** [comment]
Current status, with a port forward, is that they connect and start exchanging indexes, then disconnect.

```
[ANTOJ] 09:18:39 INFO: Established secure connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 at [::]:22020-194.126.249.11:46839 (UTP (Server))
[ANTOJ] 09:18:39 INFO: Device ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 client is "syncthing v0.13.4+12-ge26846f" named "acro-syncer.nym.se"
[ANTOJ] 09:18:54 INFO: Connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 closed: timed out waiting for ack
[ANTOJ] 09:18:57 INFO: Established secure connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 at [::]:22020-194.126.249.11:50779 (UTP (Server))
[ANTOJ] 09:18:57 INFO: Device ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 client is "syncthing v0.13.4+12-ge26846f" named "acro-syncer.nym.se"
[ANTOJ] 09:19:13 INFO: Connection to ACROTSH-MDLAN5I-OOQT4JI-RDGB3SN-K4AJMQ2-3Q5RWUQ-2GPULFP-2IYHVA6 closed: timed out waiting for ack
```

The other side says "peer reset". This is on my quite slow ADSL connection which is probably relevant. v0.13.4+12-ge26846f is unmodified from this PR.

**Comment by AudriusButkevicius** [comment]
Hmmm. And does the punch through work if you remove the port forward?
Can you measure udp throughput and drop rate?

It worked fine on my ADSL link, but I am lucky to be next to the exchange, so I get around 17Mb/s, yet in my case it was idle.

**Comment by AudriusButkevicius** [comment]
So how do we put this to bed?

**Comment by calmh** [comment]
I think this requires an engineering effort on the uTP code. This is all from memory and without looking at either the code nor the spec, but if I remember correctly there is a thing in the protocol that sends essentially "ping" messages at a quite high frequency (is in every few RTT) and when a certain number has been dropped the above happens. I think that in my case the uplink buffers get full and this can obviously drop packets and increase delay to sometimes several seconds. Probably that causes the connection drop, and I'm quite sure I'm not alone in that situation. It should be able to handle it. I don't know if this is a bug in the code or in the spec but I'm guessing other implementations may be more lenient as bittorrent in general tends to work at home.

**Comment by Scratch-net** [comment]
So, no uTP in the near future?

**Comment by calmh** [comment]
I expect there to be a second attempt with `s/utp/kcp/` at some point soon.

**Comment by AudriusButkevicius** [comment]
Yes, thats the plan.

**Comment by lkwg82** [comment]
It this PR starving or waiting for sth (except having time ;) ) ?

**Comment by AudriusButkevicius** [comment]
It's an old alternative to something that's starving.

**Comment by calmh** [comment]
Lets primarily focus on kcp now as that seems promising

**Pull request closed without merging**
