### PR TITLE
systemd: Remove exit code 2, due to #2578

### PR DESCRIPTION
**Pull request by rumpelsepp**
PR #2578 enables us to remove the exit code 2 from the list of
success status codes, because SIGINT will be handled properly.
I have also converted STNORESTART to --no-restart for the sake
of consistency.

### CODE REVIEW

**Comment by rumpelsepp** [comment]
Why fails the windows build here? Bug?

**Comment by calmh** [comment]
Yeah some windows file locking flakyness with the ignore test

**Comment by calmh** [comment]
Zero is always a default success exit status I guess, so it does not need to be in the list?

**Comment by rumpelsepp** [comment]
> Zero is always a default success exit status I guess, so it does not need to be in the list?

Zero is not in the list? To what are you refering to?

**Comment by calmh** [comment]
I mean that we do exit zero in a bunch of successful cases, but it's not mentioned in SuccessExitStatus, so I gess that's not necessary because it's regarded as successful by default?

**Comment by rumpelsepp** [comment]
Ah, sry for me being still a bit tired... Yeah zero is regarded as success by default.

**Pull request merged**
