### PR TITLE
Guide / example on how to run Syncthing on Windows as Service

### PR DESCRIPTION
**Pull request by lepipele**
### Purpose

It would be beneficial to have definite guide on how to run Syncthing as a Service on Windows machines. There have previously been requests for this:

 - https://github.com/syncthing/syncthing/pull/1407
 - https://github.com/syncthing/syncthing/issues/906

### Testing

I've installed Syncthing as a Service on Windows Service in my company right before writing this guide

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
The docs site I believe already explains it.

**Comment by lepipele** [comment]
Yeah,

https://docs.syncthing.net/users/autostart.html?highlight=service#run-as-a-service-independent-of-user-login

It would be great if that was linked more prominently...

**Comment by AudriusButkevicius** [comment]
Prominently where? I expect users who want to find something to refer to the docs first.

**Comment by AudriusButkevicius** [comment]
I am not saying what you did is wrong, yet I am questioning what you expect to be prominent.

**Pull request closed without merging**
