### PR TITLE
Add full path in failed files modal

### PR DESCRIPTION
**Pull request by nov1n**
### Purpose

Display the full file path in the failed files modal such that a user may copy the path in order to investigate.

### Testing

Tested on Chrome and Firefox on Windows and Ubuntu.

### Screenshots

image

### CODE REVIEW

**Comment by calmh** [comment]
So this makes sense (except we can remove the now useless tooltip), but what happens with long paths?

**Comment by nov1n** [comment]
The tooltip wraps but the actual text does not: 

image

We can make this horizontally scrollable but I think this is a bad user experience. Wrapping filepaths with `word-wrap:break-word` looks like this which may be acceptable: 

image

**Comment by calmh** [comment]
Yeah I wonder if that isn't the best alternative. Although, it would be nice if it could layout the table a bit better so the right column isn't so wide. CSS trickery probably required. I think static column widths are required to be able to use ellipsis breaking (IIRC) or something like that.

**Comment by nov1n** [comment]
@calmh I updated the PR andI swapped out the table-condensed for a new table-dynamic class which solves the problems.

The columns dynamically scale:
image

Long lines wrap if there is no space left:
image

**Comment by AudriusButkevicius** [comment]
Can you add yourself to authors/nicks/aliases whatever?

Otherwise, this looks good to me.

**Comment by calmh** [comment]
Let me sort out the authorness, I want that as a separate commit.

**Comment by calmh** [comment]
Done.

@st-jenkins retest this please

**Comment by calmh** [comment]
I think the table should still be `table-condensed` even if dynamic, but I'm not going to fight over it.

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Merge failed:

```
$ git fetch -f origin refs/pull/4023/head:pr-4023
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   88dfd63..c6dd777  master     -> orig/master
   1caa683..c6dd777  master     -> origin/master
$ git reset --hard
HEAD is now at 1caa683 lib/scanner: Stopped outputting rescan debug message if file doesn't exist locally (fixes #1350)
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git reset --hard orig/master
HEAD is now at c6dd777 authors: Add nov1n
$ git clean -fxd
$ git merge --squash --no-commit pr-4023
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
Commit message subject:

    Add full path in failed files modal

doesn't look like "tag: One sentence description". Specifically, it doesn't
match this pattern:

    ^[\w/,\. ]+: \w

```

**Comment by AudriusButkevicius** [comment]
@st-review merge

gui: Show full failed item path

**Comment by st-review** [comment]
:ok_hand: Merged as ed771f5c6428b7c3a215943b97415b76db8aa498. Thanks, @nov1n!

**Pull request closed without merging**
