### PR TITLE
gui: add bootstrap tooltip to existing tooltip on folders

### PR DESCRIPTION
**Pull request by norgeous**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge this please

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2877/head:pr-2877
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   e573122..95247f7  master     -> orig/master
$ git reset --hard
HEAD is now at 95247f7 cmd/syncthing: Basic smoke test of all API endpoints
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 95247f7 cmd/syncthing: Basic smoke test of all API endpoints
$ git clean -fxd
$ git merge --squash --no-commit pr-2877
Updating 95247f7..0abae33
Fast-forward
Squash commit -- not updating HEAD
 gui/default/index.html | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
$ git commit -F -
GUI files changed; recompiling assets
.git/hooks/pre-commit: line 6: go: command not found

```

**Comment by calmh** [comment]
@st-review merge this please

gui: Add bootstrap tooltip to existing tooltip on folders

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2877/head:pr-2877
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   95247f7..bc508ae  master     -> orig/master
$ git reset --hard
HEAD is now at bc508ae gui: Docs links should be HTTPS
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at bc508ae gui: Docs links should be HTTPS
$ git clean -fxd
$ git merge --squash --no-commit pr-2877
Automatic merge went well; stopped before committing as requested
Auto-merging gui/default/index.html
Squash commit -- not updating HEAD
$ git commit -F -
[master ee3e7b8] gui: Add bootstrap tooltip to existing tooltip on folders
 Author: norgeous <daniel@harte.me>
 1 file changed, 1 insertion(+), 1 deletion(-)
$ git rev-parse HEAD
ee3e7b8e8f367de8a6bd4b276f21c41c0b573eca
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 4 of 4 required status checks are expected        
To git@github.com:syncthing/syncthing.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:syncthing/syncthing.git'

```

**Comment by calmh** [comment]
@st-review merge this please

gui: Add bootstrap tooltip to existing tooltip on folders

**Comment by st-review** [comment]
OK, merged as 82e80a479a75788394c20d197af441086bd75599. Thanks, @norgeous!

**Pull request closed without merging**
