### PR TITLE
Guessing version from directory name is not viable in Go (ref #1449)

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Why?

**Comment by AudriusButkevicius** [comment]
Github will still upload the sources, we want it or not, hence there is no harm in keeping this, just incase someone decides to build from githubs sources?

**Comment by calmh** [comment]
But it doesn't work. All our `import "github.com/syncthing/syncthing/internal/...` stuff would need to be `import "github.com/syncthing/syncthing-0.10.26/internal/...`for the stuff to be buildable in a directory with a version number on it.

**Comment by AudriusButkevicius** [comment]
ghrr, damn github.

**Pull request merged**
