### PR TITLE
Issue #1472: Suppress 'Last File Received' if a node is folder master

### PR DESCRIPTION
**Pull request by sciurius**
master.

### CODE REVIEW

**Comment by sciurius** [comment]
Sorry, the request escaped before I could fix it, and I'm still finding out how to rollback... :(

**Comment by sciurius** [comment]
As for remark #1: Yes it should be !folder.ReadOnly.

As for remark #2: After a rebuild git notifies me that there are two files modified: 
        modified:   gui/index.html
        modified:   internal/auto/gui.files.go
The latter is a generated file, but apparently is has been checked in into git.

**Comment by AudriusButkevicius** [comment]
The generated file is checked in, but your editor created a temp file in the directory which the generator uses to compile static assets.

**Comment by AudriusButkevicius** [comment]
You should do your edits, and then do:
```
git add -u
git commit --amend --no-edit
git push origin master -f
```

Which will update the commit.

**Comment by sciurius** [comment]
Thanks for being patient with me. I see now what I did wrong. Stay tuned.

**Comment by sciurius** [comment]
It looks okay to me now. Sorry for the inconvenience.

**Comment by Zillode** [comment]
@sciurius : could you +1 on https://github.com/syncthing/syncthing/pull/1421 (if you agree)?

**Comment by AudriusButkevicius** [comment]
Also, can either you add yourself to NICKS/AUTHORS/List of people who contributed in index.html, or give me the relevant details so I could do so?

**Comment by sciurius** [comment]
I added myself to AUTHORS and NICKS and gui/index.html .

**Comment by AudriusButkevicius** [comment]
Can you squash the commits, and rebase please? It's not merge'able anymore.

**Comment by calmh** [comment]
I think you're deep in the git rabbit hole now, with squashes and merge commits on top of each other. :) Let me sort this out for you...

**Comment by sciurius** [comment]
I can close the PR and issue a new, clean one if you want.

**Comment by calmh** [comment]
Merged. :)

**Pull request closed without merging**
