### PR TITLE
Show Device ID QR code in "Edit Device" popup

### PR DESCRIPTION
**Pull request by ironmig**
As suggested by #1494. @blakev said he wrote a patch to do this, but had trouble building and never submitted a pull request AFAIK. I'm not great with css/boostrap, so feel free to rewrite how the qr button is displayed in the edit device modal. I tested this and it works fine. Closing the device edit modal to open the idqr modal is a little awkward, but I'm not sure how else to do it. I would appreciate feedback, this is my first time contributing to syncthing!

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Hi,

Could by you any chance provide screenshots, for those too lazy/not clever enough to build the code?

Thanks.

**Comment by ironmig** [comment]
Screenshot of device edit screen:

screenshot from 2015-12-29 17-18-25
screenshot from 2015-12-29 17-18-53

**Comment by calmh** [comment]
This would be a nice addition, but I'm not sure I agree with the implementation UI-wise. The QR code symbol is small and non-obvious and doesn't align well, especially as the window gets narrower. Is there somewhere else we could place a more obvious "show QR code for this device" control, perhaps besides the Pause and Edit buttons, or make it a real button in the edit dialog?

**Comment by uok** [comment]
maybe add link next to the "Device ID" label in the edit modal, e.g.

**Device ID** (<a href="#">show QR code for this device</a>)

also please use "Device ID" instead of "Device identification" as the heading in the QR modal so that existing translations can be used

**Comment by ironmig** [comment]
@uok Isn't 'Device Identification' the correct heading? My diff doesn't show the heading changing.

**Comment by ironmig** [comment]
Updated with potential alternative UI. It also now only shows the button if the ID is valid.
screenshot from 2015-12-30 17-30-27
screenshot from 2015-12-30 17-29-57
screenshot from 2015-12-30 17-28-38

**Comment by calmh** [comment]
Looks better. I'd like one final tweak if it's OK with the rest of you - place the button between Save and Close, and shorten it to `Show QR`. The reason I'd like that is to avoid the risk for an accidental Remove in the last screenshot, as we don't provide an undo for that (it's not fatal, but at the very least annoying). Grouping it beside the close button and having it be the same color both minimizes accidental klicks and associates it with the "close" behavior that it shares. That sound reasonable?

**Comment by uok** [comment]
my vote is for a text link / button at the top (maybe even in header, floated right?) to better inform the user about this helpful feature

**Comment by ironmig** [comment]
Updated with UI change suggested by @calmh. 
screenshot from 2015-12-31 13-49-41

**Comment by calmh** [comment]
Thanks, merged in ffc4a60.

**Pull request closed without merging**
