### PR TITLE
Add no-translate attribute for suppressing translation extraction

### PR DESCRIPTION
**Pull request by emlun**
### Purpose

PR [#9175][1] currently adds the following element:

```html
<label>RP ID</label><!-- RP ID is the name of the WebAuthn setting, should not be translated -->
```

This is in a table of WebAuthn credentials that have been made ineligible because they are bound to a different RP ID than the one currently configured in Syncthing. "RP ID" is the technical term, and it probably should not be translated since it relates to the "Webauthn Rp Id" setting in advanced settings.

`go run build.go translate` prints a warning because this text is not translated:

```
$ go run build.go translate
2024/08/21 21:58:14 Untranslated text node (settingsModalView.html):
2024/08/21 21:58:14     RP ID
```

But it shouldn't be either, so there should be a way to silence the warning for when this is intentional.

This introduces a `no-translate` attribute that can be added to do just that. This replaces the current special case for `id="contributor-list"` and `id="copyright-notices"`, and deletes the latter attribute since it is not referenced anywhere else.

An explanation can be added as the attribute value - for example: `no-translate="Don't translate list of contributors"`. This value is printed if `go run build.go translate` is run with the `TRANSLATEDEBUG` environment variable set to non-empty:

```
$ TRANSLATEDEBUG=true go run build.go translate
2024/08/21 22:20:09 Ignoring no-translate <div> in aboutModalView.html: Don't translate list of contributors
2024/08/21 22:20:09 Ignoring no-translate <ul> in aboutModalView.html: Don't translate list of copyright notices
```

[1]: https://github.com/syncthing/syncthing/pull/9175

### Testing

Manually tested that the resulting translation extraction does not change `lang-en.json` on this branch, that adding an element with `no-translate` also does not change `lang-en.json`, and that the attribute value (if any) is printed if run with `TRANSLATEDEBUG` set.

### CODE REVIEW

**Comment by acolomb** [comment]
This is a noble cause, but for the case at hand ("RP ID"), I don't think we should make the decision here.  We can mark the string as untranslatable and / or add a glossary term for it on Weblate.  I think even just the latter should suffice, because there may be valid reasons (different script?) to provide a translated string, even though it is a fixed term.

**Comment by calmh** [comment]
I agree; let this pass through the translators untouched, or perhaps actually translated in some cases, depending.

**Comment by emlun** [comment]
Fair enough. Do you want to keep the `no-translate` attribute independent of that, or kepp this on a special-case basis to not encourage introducing more "untranslatable" strings?

**Comment by acolomb** [comment]
I don't see a real need for it now.  Could keep it open or hopefully remember it later should thee requirement come up again.

**Pull request closed without merging**
