### PR TITLE
Compress only metadata by default (fixes #1374)

### LINKED ISSUE #1374: Disable compression by default
I know compression sounds always good, but after a few experiments (not with syncthing, used another syncing solution for this) you should really consider to turn it off by default.

Compression is only effective on uncompressed files (like textfiles, who are, most of the time, only a few kB in size).

In every other case (for music, videos or pictures who are usually bigger in size than textfiles), compression only adds more overhead, uses up cpu-time, but does not effective reduce the files size.

Also, with compression enabled, syncing can (due to the additional time it requires to compress the files) even take longer than without.

So please, consider to disable compression by default.

Edit: Did a short test: With compression (200MB data containing a few pictures (jpg), a few textfiles and a few videos (webm)) the sync lasted 220 seconds, without compression (same data) the sync only needed 165 seconds (I know this is not representative, results might vary depending on hardware, network interface, etc.).

### PR DESCRIPTION
**Pull request by calmh**
This introduces metadata compression as a concept (applying compression to messages that are not Response messages). It interprets the old compression default of `true` as the new default `metadata` and updates the GUI to a mode selector instead of a checkbox.

### CODE REVIEW

**Comment by calmh** [comment]
Looks reasonable. Would you mind putting a :+1: on #1421, as we are currently in the process of relicensing from GPL to MPL and this would be covered by that?

**Comment by AudriusButkevicius** [comment]
So looks good. We could add additional options (not sure how much value they add though):
1. Always on WAN
2. Metadata on WAN

**Comment by AudriusButkevicius** [comment]
Though we can add that later (or can we?). @st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by calmh** [comment]
Right, yes, we should be able to do that. Maybe separate out the lan detection stuff into a package with something simple like `func IsLocal(net.Addr) bool`, with some appropriate caching or whatever.

**Comment by calmh** [comment]
@st-jenkins run integration tests please

(Made some small cleanups)

**Pull request merged**
