### PR TITLE
gui: remove extra href on folder panel titles

### PR DESCRIPTION
**Pull request by norgeous**
untitled

I may be wrong, but after looking at this for a while I can't see the purpose of the extra `a href` wrapping the text part of the folder panel title.

If this IS being used for something, then please reject the pull req.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
It's used for expanding a accordion

**Comment by norgeous** [comment]
yes, it appears that way initially, but on closer inspection `line 230` the `div.panel-heading` is a elemental parent and it's actually this that the javascript accordion works with. This `div` in `line 230` also contains a `href`.

I still believe that the lines I have removed are extra. obviously I have tested the accordion still works with this version

**Comment by norgeous** [comment]
Clarification:

without this PR (https://github.com/syncthing/syncthing/blob/master/gui/default/index.html) there are 2 nested uses of `href="#folder-{{$index}}"` on folder panel titles. one on line 230 and then again line 235.

235 is a child of 230 so not needed.

i believe the child one must have been accidentally (re)added here https://github.com/syncthing/syncthing/commit/31362dfc17bc63c208e89eff0e0b12392f63f30c although I'm no expert at reading git history - you can see the same nesting of the href attributes.

It might make sense to leave it, if the application (or some derivative) uses deeplinking. 

Can anyone explain the difference between clicking on a folder's title bar and the text inside the bar itself? I have marked these two areas on the original screenshot with the end on the red line. For me both expand the accordion, but without this PR clicking the text also changes the address bar from `http://127.0.0.1:8384/` to `http://127.0.0.1:8384/#folder-0`.

**Comment by uok** [comment]
looks like you are right about the duplicate href, but there was #2862 with should provide better accessibility (see #2288) - maybe @wweich can help out here?

**Comment by norgeous** [comment]
Thanks uok! useful information. it's clear that the hitzone https://github.com/syncthing/syncthing/issues/651 should be the entire panel title https://github.com/syncthing/syncthing/commit/c6aefbc9a0559f49c17ddf23ae74a0c6ad7f76ad

maybe `<div class="panel-heading" ... >` should be `<a class="panel-heading" ... >`

**Comment by wweich** [comment]
AFAIK, the href on the div is needed for the JS to expand when the div is clicked.
And my understanding from the NVDA users was, that screen readers don't see that so they need an (additional) a, including the href.

**Comment by norgeous** [comment]
Thanks wweich! I have just downloaded NVDA to check how it works... yes it only reads aloud normal html `a href` links, and not `div href` style javascript links we want to use here. Converting the `panel-headings` from `div` to `a` and adding `display:block;` looks like it works. will commit it shortly with a fix for the devices list where this is also present.

**Comment by norgeous** [comment]
ok good, last 2 commits should be good, have removed the extra nested href and combined it all into one. should look and function exactly as before.
can anyone confirm this works with NVDA as expected?

**Comment by AudriusButkevicius** [comment]
I'll it to @wweich confirm that it's the right thing before merging.

**Comment by calmh** [comment]
@wweich should have the powers to merge it, if it looks good :)

**Comment by calmh** [comment]
Although a better commit message needs to be set at merge time, and @norgeous I think you need to clean up your git as every PR starts with sixteen merges ;)

**Comment by wweich** [comment]
LGTM, but honestly I just saw ticket #2288 as "please add `a href` to panel-headers" so I did it ;). I haven't done anything regarding accessibility before and can't tell, if this change breaks it or not.

**Comment by AudriusButkevicius** [comment]
@st-review merge

gui: Remove extra href on folder panel titles

**Comment by st-review** [comment]
:ok_hand: Merged as 37816e3818aab773f5d1239d016184a82fe661b3. Thanks, @norgeous!

**Pull request closed without merging**
