### PR TITLE
Fix autocomplete with '~' in add folder (Fix #1478)

### LINKED ISSUE #1478: Autocompletion does not work with "~"
When you use `~`, as suggested, for your home directory the autocompletion does not work.

```
$ syncthing --version
syncthing v0.10.27 (go1.4.2 linux-amd64 default) builduser@jara 2015-03-15 15:42:52 UTC
```

### PR DESCRIPTION
**Pull request by zukoo**

### CODE REVIEW

**Comment by calmh** [comment]
Hi! LGTM. Can you also add yourself to NICKS, use `Fix ~ completion in add folder (fixes #1478)` as commit message (follows standard formatting), and merge the two commits into one?

**Comment by zukoo** [comment]
Think it's good now

**Comment by AudriusButkevicius** [comment]
So this does automatic expanding, right?

**Comment by zukoo** [comment]
Yes, replacing ~ by the home dir

**Comment by AudriusButkevicius** [comment]
I would prefer doing the expansion serverside though, just in case your HOME changes, having `~` is a safer choice.

**Comment by AudriusButkevicius** [comment]
@calmh merged it b95a6ccf80ea7431ab4cb2b385bc57f39fb11230

**Comment by AudriusButkevicius** [comment]
Thanks for the contribution, btw.

**Comment by calmh** [comment]
Oh. That was unintentional. I merged it to master for testing, then did something else on master and pushed. :/ Ah well, all good.

**Comment by calmh** [comment]
I'll fix up the results.

**Pull request closed without merging**
