### PR TITLE
Update docs & translations

### PR DESCRIPTION
**Pull request by calmh**
Prerelease busywork

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it when it passes

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
:no_good: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
wat

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it now then

**Comment by st-review** [comment]
:ok_hand: Merged as 0155b6f84171724686694417cd8015bdffb31e22. Thanks, @calmh!

**Pull request closed without merging**
