### PR TITLE
cmd: Random fixes (fixes #3503, #3505, #3506, #3509, #3511)

### LINKED ISSUE #3503: Relaysrv: panic: send on closed channel
Today I noticed relasrv crashed few days ago:
```
...
2016/08/10 16:07:37 pool.go:52: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2016/08/10 16:55:38 pool.go:52: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
panic: send on closed channel

goroutine 380856 [running]:
panic(0x82f1ee0, 0x18a86140)
	/usr/local/go/src/runtime/panic.go:481 +0x326
main.protocolConnectionHandler(0xb755f678, 0x1ad81bf0, 0x18850180)
	/home/buildslave/workspace/relaysrv/src/github.com/syncthing/syncthing/cmd/relaysrv/listener.go:170 +0x1fbf
created by main.listener
	/home/buildslave/workspace/relaysrv/src/github.com/syncthing/syncthing/cmd/relaysrv/listener.go:52 +0x547
```

Started by

```
./relaysrv -global-rate=3000000 -ext-address=:443 -provided-by=chucic
2016/07/31 21:34:38 main.go:104: relaysrv v0.13.5 (go1.6.2 linux-386) unknown-user@lx-buildslave.syncthing.net 2016-06-03 11:03:24 UTC
2016/07/31 21:34:38 main.go:110: Connection limit 3276
2016/07/31 21:34:38 main.go:168: URI: relay://:443/?id=NCIJELL-_rest_of_ID_&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=3000000&statusAddr=:22070&providedBy=chucic
2016/07/31 21:34:38 main.go:171: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2016/07/31 21:34:38 main.go:172: !!  Joining default relay pools, this relay will be available for public use. !!
2016/07/31 21:34:38 main.go:173: !!      Use the -pools="" command line option to make the relay private.      !!
2016/07/31 21:34:38 main.go:174: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2016/07/31 21:34:39 pool.go:52: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
...
```

I don't know how to reproduce this.

### Version Information

Relay Server Version: v0.13.5
OS Version: Debian 7

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Many random fixes.

Haven't tested the timezone conversion, but I am a bit suspicious about it.
If the driver does not specify the timezone, Go defaults to UTC, yet the fact that we are getting weird times implies that the driver is using local timezone, in which case this should work.

### CODE REVIEW

**Comment by calmh** [comment]
Dude, no. While I love the fixing of many bugs this random fixes grab bag commit is crap. Split it up like a normal person. :D

**Comment by AudriusButkevicius** [comment]
Haven't realized that I am not normal.
Sadly, it's a lot of boring button smashing to split them up now, so I'd rather close this and forget it than split them up.

**Comment by calmh** [comment]
You know what, I'll sort it out for you. :)

**Comment by calmh** [comment]
Merged

**Pull request closed without merging**
