### PR TITLE
lib/versioner: base versions path to working dir (#4188)

### PR DESCRIPTION
**Pull request by liusy182**
### Purpose

base versions path to working dir (#4188)

### Testing

__base settings__: In folder, advanced settings, "File Versioning" dropdown, choose "Stagger file versioning" option.

#### - Scenario 1:
Leave field "Versions Path" empty and save.

Expect staggered files to be synced to `<<Folder Path>>/.stversions` folder where `<<Folder Path>>` is the "Folder Path" value displayed in the same dialog.

#### - Scenario 2:

Give a absolute path in "Versions Path" field, E.g. "`/tmp/testpath`" and save.

Expect staggered files to be synced to the given path. E.g. "`/tmp/testpath`"

#### - Scenario 3:

Give a relative path in "Versions Path" field, E.g. "`testpath`" and save.

Expect staggered files to be synced to the path relative to "Folder Path", E.g. `<<Folder Path>>/testpath`

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@liusy182 Thanks, looks good.

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it please

lib/versioner: Interpret versions path relative to folder path (fixes #4188)

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 03c678a810d318079cb43103628c1b55942f8b83. Thanks, @liusy182!

**Pull request closed without merging**
