### PR TITLE
Add env var to disable proxy fallback (fixes #3006)

### LINKED ISSUE #3006: Add proxy option that won't be bypassed
It is already possible to use Syncthing with Tor on Android with the following environment variable:
`all_proxy=socks5://localhost:9050 syncthing`

However, if Tor is not running, Syncthing will just connect to other devices directly. Instead, it should be so that no connections are made without the proxy. The idea is to have a setting "use tor", that forces the app to do all connections only over Tor.

Also, I couldn't find a way to make sure that Syncthing is using a proxy. The logs only show "INFO: Proxy settings detected". It would be good to have some info if the proxy is actually used, and maybe have the address logged, too.

Edit: This is for syncthing/syncthing-android#589

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Adding environment variable to disable falling back to direct dialer when proxy dial fails.

### Testing

None as usual.

### CODE REVIEW

**Comment by calmh** [comment]
Why not just have this as our one and only behavior?

**Comment by AudriusButkevicius** [comment]
So by default, I think the most important thing is to connect to someone, which I think doesn't really matter if it's done directly of via proxy, hence why I'd expect this to be the default behaviour.

Also, you can have cases where the env var is set, but the environment we are in has changed, and syncthing hasn't been restarted, which would make it painful.

**Comment by canton7** [comment]
Yeah, I think the "only use a proxy, never try and connect without a proxy" use-case only covers the Tor people - most proxy users are using one so they can establish a connection in some sort of restricted environment.

**Comment by calmh** [comment]
Okay

**Comment by calmh** [comment]
@st-review merge please

lib/dialer: Add env var to disable proxy fallback (fixes #3006)

**Comment by st-review** [comment]
:ok_hand: Merged as 2467678bd4f2aa0fecd18ba1bd3df4ae867c627a. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
