### PR TITLE
Update reset API to reflect new use cases.

### PR DESCRIPTION
**Pull request by Zillode**
```syncthing -reset``` clears the entire Syncthing DB and restart the program
```/rest/reset``` clears the entire Syncthing DB and restart the program
```/rest/reset&folder=default``` clears the indexes of the 'default' folder

In response to https://github.com/syncthing/syncthing/pull/1562

### CODE REVIEW

**Comment by calmh** [comment]
Looks reasonable to me.

**Comment by Zillode** [comment]
I was thinking, should I add a rescan after dropping the folder?

**Comment by calmh** [comment]
Probably a restart. Or to make sure an empty IndexMessage gets sent, which won't happen in this case I think. We need to get the old index info removed from remote devices.

**Comment by Zillode** [comment]
I opted for a restart

**Comment by calmh** [comment]
:+1: LGTM. @AudriusButkevicius you had some opinions on how this stuff should work?

**Pull request merged**
