### PR TITLE
build: Bump quic-go to 0.26.0 for go1.18 update

### PR DESCRIPTION
**Pull request by imsodin**
go1.18 is out and quic-go made a release mentioning updates for go1.18, so likely good to have that.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Did you test it? The pfilter does a lot of magic wrapping the types and what not, and seems there are a few PRs in the release tickling those parts.

**Comment by bt90** [comment]
https://github.com/lucas-clemente/quic-go/pull/3334 might affect us

**Review by calmh — APPROVED** [review]

**Comment by imsodin** [comment]
> Did you test it? The pfilter does a lot of magic wrapping the types and what not, and seems there are a few PRs in the release tickling those parts.

> [lucas-clemente/quic-go#3334](https://github.com/lucas-clemente/quic-go/pull/3334) might affect us

I didn't. There's a test in place now that establishes a quic conn and checks it can read/write a few bytes. That PR doesn't change anything that's exported, and on a quick glance the changes look unproblematic to me.

**Comment by calmh** [comment]
FWIW a `build.go update-deps` also pulls in some updated qtls stuff that seemed to have a couple of API changes required. Maybe we could do that at the same time?

**Review by calmh — APPROVED** [review]

**Comment by calmh** [comment]
Merging because I want this in the RC, when we do the RC...

**Comment by calmh** [comment]
And this works fine for me, talks to the previous version.

**Pull request merged**
