### PR TITLE
man: include stdiscosrv and strelaysrv manpages

### PR DESCRIPTION
**Pull request by aviau**

### CODE REVIEW

**Comment by calmh** [comment]
Cool. Make sure they're included in our packages as well, build.go around lines 109 and 127 or so and it's all good.

**Comment by calmh** [comment]
@st-review merge it

man: Include stdiscosrv and strelaysrv manpages

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as d7cb4d407ba18b150b350f1a90e89b648992cee3. Thanks, @aviau!

**Pull request closed without merging**
