### PR TITLE
authors: Clean up AUTHORS and NICKS files

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Git didn't really understand the multiple email addresses in the NICKS file the same way I expected it to, and this fixes that. It also makes AUTHORS the "master" file that everything else depends on, so it now includes all of name, nickname and email addresses.

As of this change, *all* that needs to happen to add a new author is to add them to the AUTHORS file in the correct format, including Github nickname. The rest (NICKS and the GUI credits) is taken care of at release time by `script/authors.go`.

### Testing

I've ran it, multiple times.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Why do we even need nicks?

**Comment by calmh** [comment]
It's symlinked as `.mailmap` which `git log` uses, meaning I get git logs like

screen shot 2016-06-02 at 10 14 53


which, besides being nice, is also what goes into the release notes via the changelog script.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as d67c0a1eda3a59214e8d7ab6fede0fbd6abcabda. Thanks, @calmh!

**Pull request closed without merging**
