### PR TITLE
cmd/syncthing: Add selectable sha256 package (fixes #3613, fixes #3614)

### LINKED ISSUE #3613: v0.14.7 crashes on Arm64
- what happened: Syncthing automatically updated from 14.6 to 14.7 on an Arm64 SOC and now syncthing won't start/crashes whenever I try to start version 14.7 (see log file below).

- what you expected to happen instead: I expected this update to start normally like all the other versions

- any steps to reproduce the problem: I downgraded to 14.6 and everything runs normally. I updated to 14.7 through the GUI and the same issue happens (see log file below). I rebooted and downgraded again to 14.6 and everything runs normally. I manually installed 14.7 from CLI and the same issue happens again. I have once again downgraded to 14.6 and will be running 14.6 until the issue can be resolved. Thanks for your help.

### Version Information
---------------------------

Syncthing Version: v0.14.7
OS Version: 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Board: Odroid C2
Processor: Arm64 -> Amlogic ARM® Cortex®-A53(ARMv8) 1.5Ghz quad core CPUs

Browser Version: n/a

Log Output
---------------------------
```
root@omv-c2: syncthing
[monitor] 07:13:16 INFO: Starting syncthing
SIGILL: illegal instruction
PC=0x368ebc m=0

goroutine 1 [running, locked to thread]:
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.blockArm(0x442003bbb8, 0x8, 0x8, 0x4420130000, 0x20000, 0x20000, 0xbb67ae856a09e667, 0xa54ff53a3c6ef372, 0x9b05688c510e527f, 0x5be0cd191f83d9ab, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256block_arm64.s:59 +0x5c fp=0x442003bb80 sp=0x442003bb80
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.blockArmGo(0x442003bd50, 0x4420130000, 0x20000, 0x20000)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256block_arm64.go:32 +0xd8 fp=0x442003bc20 sp=0x442003bb80
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.block(0x442003bd50, 0x4420130000, 0x20000, 0x20000)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:79 +0x108 fp=0x442003bc60 sp=0x442003bc20
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.(*digest).Write(0x442003bd50, 0x4420130000, 0x20000, 0x20000, 0x20000, 0x0, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:125 +0x1b8 fp=0x442003bcf0 sp=0x442003bc60
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.Sum256(0x4420130000, 0x20000, 0x20000, 0x0, 0x0, 0x0, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:100 +0xc4 fp=0x442003bdc0 sp=0x442003bcf0
github.com/syncthing/syncthing/lib/protocol.init()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/protocol/bep_extensions.go:25 +0xadc fp=0x442003be40 sp=0x442003bdc0
github.com/syncthing/syncthing/lib/config.init()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/config/wrapper.go:360 +0x88 fp=0x442003beb0 sp=0x442003be40
main.init()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/verboseservice.go:187 +0xb0 fp=0x442003bf40 sp=0x442003beb0
runtime.main()
	/usr/local/go/src/runtime/proc.go:172 +0x280 fp=0x442003bf90 sp=0x442003bf40
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:983 +0x4 fp=0x442003bf90 sp=0x442003bf90

r0      0x442003bbb8
r1      0x4420130040
r2      0x1ffc0
r3      0x881100
r4      0x8
r5      0x8
r6      0x442003bbb8
r7      0x4420130000
r8      0x10e
r9      0x10
r10     0x8776e0
r11     0x0
r12     0x8
r13     0x0
r14     0x0
r15     0x10
r16     0x442003bdb8
r17     0x87ae78
r18     0x0
r19     0x0
r20     0x0
r21     0x0
r22     0x0
r23     0x0
r24     0x0
r25     0x0
r26     0x87ad50
r27     0xb2dd19
r28     0x44200001a0
r29     0x0
lr      0x3684c8
sp      0x442003bb80
pc      0x368ebc
fault   0x0
```

### LINKED ISSUE #3614: v0.14.7 huge hash performance degradation
v0.14.6 reports this:
```
23:36:13 INFO: syncthing v0.14.6 "Dysprosium Dragonfly" (go1.7 linux-amd64) builduser@svetlemodry 2016-09-06 15:26:27 UTC
23:36:13 INFO: Single thread hash performance is ~186 MB/s
```

 v0.14.7 consistently reports:
```
23:35:03 INFO: syncthing v0.14.7 "Dysprosium Dragonfly" (go1.7.1 linux-amd64) builduser@svetlemodry 2016-09-21 18:31:42 UTC
23:35:03 INFO: Single thread hash performance is ~43 MB/s
```
I've tried to restart it few times and every time it was around ~40MB/s

OS: Archlinux
CPU:
```
Architecture:          x86_64                                                                                                                                                                
CPU op-mode(s):        32-bit, 64-bit                                                                                                                                                        
Byte Order:            Little Endian                                                                                                                                                         
CPU(s):                8                                                                                                                                                                     
On-line CPU(s) list:   0-7                                                                                                                                                                   
Thread(s) per core:    2                                                                                                                                                                     
Core(s) per socket:    4                                                                                                                                                                     
Socket(s):             1                                                                                                                                                                     
NUMA node(s):          1                                                                                                                                                                     
Vendor ID:             GenuineIntel                                                                                                                                                          
CPU family:            6                                                                                                                                                                     
Model:                 42                                                                                                                                                                    
Model name:            Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz                                                                                                                              
Stepping:              7                                                                                                                                                                     
CPU MHz:               1863.525                                                                                                                                                              
CPU max MHz:           5900.0000                                                                                                                                                             
CPU min MHz:           1600.0000                                                                                                                                                             
BogoMIPS:              6787.48                                                                                                                                                               
Virtualization:        VT-x                                                                                                                                                                  
L1d cache:             32K                                                                                                                                                                   
L1i cache:             32K                                                                                                                                                                   
L2 cache:              256K                                                                                                                                                                  
L3 cache:              8192K                                                                                                                                                                 
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
```

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This adds autodetection of the fastest hashing library on startup, thus handling the performance regression. It also adds an environment variable to control the selection, STHASHING=standard (Go standard library version, avoids SIGILL crash when the minio library has bugs on odd CPUs), STHASHING=minio (to force using the minio version) or unset for the default autodetection.

### Testing

Works for me...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
We could catch the sigill in monitor, and restart with alternative implementation and potentially set it in stone/config.

**Comment by AudriusButkevicius** [comment]
Also, because we are benching both implementations, perhaps it would be nice to print both hashing performances?

**Comment by calmh** [comment]
That's a good idea, didn't think of that, will look into it!

**Comment by scienmind** [comment]
Regarding the startup hash bench:

The bench itself is quite short, and as noted on the forum discussion about the new hash algo. is is short enough to not bump up the CPU up to its full speed (on relatively powerful CPUs). 

I tested it on few laptops - and unless either the PC is already under load or its on "Crazy Super Performance Power Plan", the clock speed won't bump up to max during the hash test, degrading the results. Ranging from 50MB/s (starting ST when PC is fully idle) up to 300+MB/s (when some CPU core is already busy before launching ST). 

The point is - it may lead to wrong hash algorithm selection, giving an advantage to whichever one will run last. So it may be a good idea to either make hash test longer, or do few iterations of hash benchs, alternating the algorithm used.

**Comment by calmh** [comment]
Good point. It runs three iterations, but first one also and then the other, and only for 75ms each. They should be interleaved.

**Comment by canton7** [comment]
How about running a longer test on first start, then saving the results? You'd need a good strategy for catching people changing their CPU, although I don't imagine that'd be a common occurrence.

**Comment by scienmind** [comment]
If by first start you mean "the first", when the ID and config are born, its not optimal:
If anyone (I do :) runs a portable version, they'd be effectively changing CPUs...

(one of my ST instances is a a portable SyncTrayzor on a portable HDD that travels across bunch of PCs...)

**Comment by calmh** [comment]
It doesn't need to be that exhaustive, nobody dies if we get it wrong. A few hundred milliseconds at startup should be sufficient if done correctly.

**Comment by calmh** [comment]
Mmkay, so this now does the relevant benchmarking and reporting:

```
jb@unu:~/s/g/s/s/test $ STHASHING=standard syncthing -home h1 | grep perfo
[I6KAH] 17:58:19 INFO: Single thread hash performance is 346 MB/s using crypto/sha256 (0.00 MB/s using minio/sha256-simd).
^C
jb@unu:~/s/g/s/s/test $ STHASHING=minio syncthing -home h1 | grep perfo
[I6KAH] 17:58:28 INFO: Single thread hash performance is 357 MB/s using minio/sha256-simd (351 MB/s using crypto/sha256).
^C
jb@unu:~/s/g/s/s/test $ syncthing -home h1 | grep perfo
[I6KAH] 17:58:37 INFO: Single thread hash performance is 362 MB/s using minio/sha256-simd (355 MB/s using crypto/sha256).
^C
```

It also detects and acts on SIGILL, but doesn't do anything permanently about it. Also doesn't work when not running with the monitor process, but hey...

```
jb@unu:~/s/g/s/syncthing $ syncthing -home h1 
[monitor] 18:09:27 INFO: Starting syncthing
[H73EW] 18:09:27 INFO: syncthing v0.14.7+4-ge2cacc3-dirty-sha256 "Dysprosium Dragonfly" (go1.7.1 darwin-amd64) jb@unu.kastelo.net 2016-09-23 15:59:14 UTC
[H73EW] 18:09:27 INFO: My ID: H73EWZC-BE7F57I-2KBRW7K-YZ56BFF-GREHSBC-65GOKDE-N3Q5YH7-65N5YAK
SIGILL: illegal instruction
[monitor] 18:09:27 WARNING: 
*******************************************************************************
* Crash due to illegal instruction detected. This is most likely due to a CPU *
* incompatibility with the high performance hashing package. Switching to the *
* standard hashing package instead. Please report this issue at:              *
*                                                                             *
*   https://github.com/syncthing/syncthing/issues                             *
*                                                                             *
* Include the details of your CPU.                                            *
*******************************************************************************

[monitor] 18:09:27 INFO: Syncthing exited: exit status 2
[monitor] 18:09:28 INFO: Starting syncthing
[H73EW] 18:09:28 INFO: syncthing v0.14.7+4-ge2cacc3-dirty-sha256 "Dysprosium Dragonfly" (go1.7.1 darwin-amd64) jb@unu.kastelo.net 2016-09-23 15:59:14 UTC
[H73EW] 18:09:28 INFO: My ID: H73EWZC-BE7F57I-2KBRW7K-YZ56BFF-GREHSBC-65GOKDE-N3Q5YH7-65N5YAK
[H73EW] 18:09:28 INFO: Single thread hash performance is 339 MB/s using crypto/sha256 (0.00 MB/s using minio/sha256-simd).
[H73EW] 18:09:28 INFO: Starting deadlock detector with 20m0s timeout
[H73EW] 18:09:28 INFO: Ready to synchronize czxwh-ckkfq (readwrite)
```

Tested the SIGILL handling by changing some random bytes in the sha256 package assembly.

**Comment by AudriusButkevicius** [comment]
So does it switch to standard as it crashes?

**Comment by calmh** [comment]
Yes. The stdout reader sets the environment variable and returns (instead of continuing to process the rest of the sigill crash). The main loop in the monitor waits for the stdout and stderr readers to complete, then attempts another launch, at which point the STHASHING=standard variable takes effect and the start up works. 

So it'll crash once on every monitor startup, with the message pointing to github. For those who notice we may get the bug report, for those who don't it should mostly just work. For those who run it under a service with -no-restart they'll come here to complain and we'll have to accept the bug report with CPU details and point towards setting STHASHING=standard.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as d328e0fb7583b20dba2de862acac89ea41d2ee0b. Thanks, @calmh!

**Pull request closed without merging**
