### PR TITLE
lib/model: Don't error on pulling deletion of invalid file (fixes #5791)

### LINKED ISSUE #5791: Puller complains about invalid filenames which are long gone
When I started using syncthing with my Home Folder, it contained some files with a colon in the filename. Linux client didn’t have any problems, but the windows client complained about invalid filenames. That’s perfectly fine and I just renamed the files and rescanned the folder.

But although the problematic files are gone now, the windows client still complains about those invalid filenames and says “out of sync” and lists the old filenames in the “out of sync” list.

I'm using syncthing 1.1.4 on both sides.

I tried to reproduce this today, and that’s what happened:

On linux I created a file with a colon in a directory which is ignored on the windows side:
[root@frogstar .syncthing-config]# echo "bla" > 'test:file'

Syncthing on linux picked up the file.

On windows I unignored the directory, and after waiting a bit, I queried the DB on windows:

```
bka@bka-pc:/mnt/c/Windows/System32$ curl -X GET -H "X-API-Key: xxx" 'http://localhost:8384/rest/db/file?folder=msrcl-kvcnd&file=.syncthing-config\test:file'
{
  "availability": [
    {
      "id": "EFZZSVQ-POIBRPK-WEQTLFL-CB6VS4T-MFI4LJF-XVPQMJU-MKZZKX5-PPFVXQT",
      "fromTemporary": false
    }
  ],
  "global": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2019-06-12T20:25:30.271290366+02:00",
    "modifiedBy": "EFZZSVQ",
    "mustRescan": false,
    "name": ".syncthing-config\\test:file",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 1234849,
    "size": 4,
    "type": 0,
    "version": [
      "EFZZSVQ:1"
    ]
  },
  "local": {
    "deleted": true,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2019-06-12T20:25:30.271290366+02:00",
    "modifiedBy": "Y2UU6DH",
    "mustRescan": false,
    "name": ".syncthing-config\\test:file",
    "noPermissions": false,
    "numBlocks": 0,
    "permissions": "0",
    "sequence": 2199918,
    "size": 0,
    "type": 0,
    "version": [
      "Y2UU6DH:1"
    ]
  }
}
```

I renamed the file on linux:

```
[root@frogstar .syncthing-config]# mv test\:file test_file
```

The file now got sync’ed to windows with the new name and again I queried the DB:

```
bka@bka-pc:/mnt/c/Windows/System32$ curl -X GET -H "X-API-Key: xxx" 'http://localhost:8384/rest/db/file?folder=msrcl-kvcnd&file=.syncthing-config\test:file'
{
  "availability": [
    {
      "id": "EFZZSVQ-POIBRPK-WEQTLFL-CB6VS4T-MFI4LJF-XVPQMJU-MKZZKX5-PPFVXQT",
      "fromTemporary": false
    }
  ],
  "global": {
    "deleted": true,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2019-06-12T20:25:30.271290366+02:00",
    "modifiedBy": "EFZZSVQ",
    "mustRescan": false,
    "name": ".syncthing-config\\test:file",
    "noPermissions": false,
    "numBlocks": 0,
    "permissions": "0",
    "sequence": 1248581,
    "size": 0,
    "type": 0,
    "version": [
      "EFZZSVQ:2"
    ]
  },
  "local": {
    "deleted": true,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2019-06-12T20:25:30.271290366+02:00",
    "modifiedBy": "Y2UU6DH",
    "mustRescan": false,
    "name": ".syncthing-config\\test:file",
    "noPermissions": false,
    "numBlocks": 0,
    "permissions": "0",
    "sequence": 2199918,
    "size": 0,
    "type": 0,
    "version": [
      "Y2UU6DH:1"
    ]
  }
}
```

And again the GUI shows one more out-of-sync item named “test:file”.

### PR DESCRIPTION
**Pull request by imsodin**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Should the error be in an else statement?

**Comment by calmh** [comment]
You ran this and tested it manually to ensure it didn't have any obvious issues right?

**Comment by imsodin** [comment]
No, due to windows and very small scope (converts invalid (ignored) db entry to a deleted db entry).

**Comment by calmh** [comment]
Looks to me like we didn't have/create a database entry at all before unless the file was ignored? Now we do, with an invalid file name and no invalid bit. I agree it should be fine, but I'm not 100% sure it's great without running it even once :)

**Comment by imsodin** [comment]
It's a bit less problematic: If the file isn't in the database in the first place, and the global file is deleted, we do not need/pull it -> no new deleted file. This only applies to files with invalid names, that  were not deleted, then ignored on windows, then deleted on the remote, then unignored on windows.

**Pull request merged**
