### PR TITLE
lib/connections: Fix connection switching

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

It seems that it would be impossible to drop down to relay after establishing a direct connection
Also, we should not drop the existing connection until after we've passed the validation steps,
and it seems it's being dropped in two places unnecesserily at the moment.

### Testing

None what so ever.

### CODE REVIEW

**Comment by calmh** [comment]
Lgtm but let me do some actual testing since I anyway intended to do that

**Comment by calmh** [comment]
I have a vague suspicion that something like the following can happen, but it's not confirmed at all:

- relay connection exists
- direct connection comes in
- we drop relay connection
- we add direct connection
- other side drops relay connection, we get some error, call close
- close is based on device id, we remove the direct connection for that device is that we added milliseconds ago
- index sending starts for the direct connection that we just added and closed

But needs investigation...

**Comment by AudriusButkevicius** [comment]
Totally possible

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as a4f052ad31fa160ad376598a920a5938699f58b9. Thanks, @AudriusButkevicius!

**Comment by calmh** [comment]
No testing yet but it looks safe. We should look again into the possible race condition described above or something similar.

**Pull request closed without merging**
