### PR TITLE
gui: Tweak the Restore Versions modal for better usability

### PR DESCRIPTION
**Pull request by tomasz1986**
Add various tweaks to the Restore Versions modal in order to make it
more usable in general. In the process, upgrade both fancytree and
daterangepicker to their newest versions.

The important changes in details are as follows.

1. Wrap the table in a container, which is user-resizable, by default
   occupying as much space as needed within the screen. This prevents
   the generation of a giant list pushing everything down the screen,
   and also keeps the filter, date picker, and buttons visible.
2. Apply various usability tweaks, including support for long filenames,
   ensuring proper functionality on all resolutions, widening the input
   fields to fit more text, etc.
3. Upgrade the theme to match the rest of the Web GUI, including using
   the same set of icons. Ensure that everything works correctly in all
   supported themes.
4. Upgrade fancytree from 2.28.1 to 2.38.0, and daterangepicker from
   3.0.0 to 3.1. In the process, remove all pre-defined fancytree themes
   and create our own in css/assets instead. This is because it takes
   much less code to write a theme from scratch for our use case than to
   override the complex pre-defined one.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

## Screenshots Before & After

<details>
<summary>Light Theme (desktop)</summary>

image
image
</details>

<details>
<summary>Light Theme (tablet)</summary>

</details>

<details>
<summary>Light Theme (phone)</summary>

</details>

<details>
<summary>Black Theme (desktop)</summary>

image
image
</details>

<details>
<summary>Black Theme (tablet)</summary>

</details>

<details>
<summary>Black Theme (phone)</summary>

</details>

<details>
<summary>Dark Theme (desktop)</summary>

image
image
</details>

<details>
<summary>Dark Theme (tablet)</summary>

</details>

<details>
<summary>Dark Theme (phone)</summary>

</details>

### CODE REVIEW

**Comment by tomasz1986** [comment]
I still want to add some minor fixes, but I'd like to comment on a few things first.

1. The PR is large due to upgrading both fancytree and daterangepicker. I thought that it would be a good idea to upgrade them, because our versions were a few years old. These two components are only used in the Restore Versions modal anyway, so doing so won't affect anything else. There are no actual changes when it comes to the latter apart from a version bump, but in the case of fancytree, I have completely replaced the theme with a custom one that I believe fits Syncthing's UI better.
2. The calendar is still broken (see https://github.com/syncthing/syncthing/pull/7390) and also doesn't support the black and dark themes. I've tried to fix it without digging deep down the code, but couldn't really do much, so for now I'm planning to deal with it later in a separate PR.
3. There are still major performance issues with large numbers of files (see https://github.com/syncthing/syncthing/issues/7393), but this also will have to be addressed separately. This is fortunately limited mainly to cases, where we have a few thousands of files in single folder.

**Comment by tomasz1986** [comment]
I'd say the commit is ready for review.

I've added a few more fixes, and also updated the screenshots to show the final version. I've simplified the container, removed some unneeded CSS, which resulted in getting rid of the inner border, and also gaining more horizontal space (which is critical here).

Also, as commented by @imsodin at https://github.com/syncthing/syncthing/pull/7395#discussion_r583587628, I've limited the container to be user-resizable only vertically. The reason is that if we allow horizontal resizing, then the user can drag the box as far as they can, and once that happens, it overflows the screen, and there is no way to go back, because the Web GUI disallows horizontal scrolling. Thus, I think it's just safer to keep the container in the modal. On a side note, the same probably should be applied to the Ignore Patterns textarea.

Just in case this PR is accepted, I'd like to ask, if possible, not to squash the two commits, and rather merge them separately. The reason is that there is a bug in the current version of fancytree that prevents folder child counters from being shown in IE11. I've reported the bug to the developer, but right now there's no fix, so I've applied a quick workaround myself. I think it would be better to keep this specific commit separate, so that if fancytree does get updated later, it will be easy to track the fix down, revert it, and then perform a clean upgrade.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Comment by calmh** [comment]
I'll take a look in the new year!

**Review by calmh — APPROVED** [review]
This seems fine to me and a significant improvement! Could I ask you to do a quick search for "restore" "GUI" type issues (they are legion) and see which of them are legitimately closed by this change?

**Comment by tomasz1986** [comment]
Thank you for the positive feedback 🙂.

I've gone through all open issues and tried to gather everything related to Versioning:

- [Configurable restore path](https://github.com/syncthing/syncthing/issues/4670)
- [Date selector dialog on restore versions partially hidden](https://github.com/syncthing/syncthing/issues/4755)
- [Selection of time in versions GUI not possible without editing the string inside the textfield](https://github.com/syncthing/syncthing/issues/5408)
- [Restoring versions reports an error but actually works](https://github.com/syncthing/syncthing/issues/6253)
- ["Restore Versions" GUI breaks when path exists as both directory and file](https://github.com/syncthing/syncthing/issues/7068)
- [Restore Versions modal extremely laggy and RAM-hungry with many items](https://github.com/syncthing/syncthing/issues/7393)
- [Trash Can File Versioning always throws errors on restore (even when succeeded)](https://github.com/syncthing/syncthing/issues/7965)
- [Restore Versions file filter should have an option to disable case sensitivity](https://github.com/syncthing/syncthing/issues/7973)

I don't think this PR fixes any of them, unfortunately :slightly_frowning_face:. The issues are mostly about functionality, while the PR is mainly a visual overhaul. One component that isn't addressed here, but should be later, is the calendar, as it lacks support for themes and has issues on small screens, but I'm planning to work on it separately later.

All in all, I think this PR is ready as it is now, with no "ref" or "fixes" next to it.

**Comment by calmh** [comment]
Then so be it! I thought it might have resolved some of the gui related ones but could pinpoint it. :) thanks for looking!

**Pull request merged**
