### PR TITLE
gui: Display ETA while syncing (fixes #899)

### LINKED ISSUE #899: ETA and bytes left for synchronization
Since current speed and bytes left are already here it would be great to use them to calculate an ETA for download/upload of each folder and also show the time left for the sync status of each device. After successful transfers this line is hidden.

Another helpful information would be to see the total remaining size (sum of all remaining transfers) of all connected folders for each device.

label: [enhancement]

### PR DESCRIPTION
**Pull request by uok**
Display ETA while syncing

- [x] ETA for device
- [ ] ETA for folder
- [ ] CSS styling (two lines for status - see [idea](https://github.com/syncthing/syncthing/pull/3928#issuecomment-274993674))

-wip, do not merge-

### CODE REVIEW

**Comment by uok** [comment]
@fti7 can you please share the CSS code for your [multiline idea](https://github.com/syncthing/syncthing/pull/3928#issuecomment-274993674)? thanks!

**Comment by wweich** [comment]
If a device is sending us files for more than one folder, that device's rate shouldn't be used in full for each folder.

**Comment by fti7** [comment]
> @fti7 can you please share the CSS code for your [multiline idea](https://github.com/syncthing/syncthing/pull/3928#issuecomment-274993674)? thanks!

Unfortunately that was just a Photoshop Mockup 😢 No CSS Code

**Comment by uok** [comment]
@wweich good point. How do you want to split it? I'm not a JS wizard so I'm thankful for code suggestions.

@fti7 ok, I'll see if I can come up with some CSS for two lines

**Comment by uok** [comment]
@wweich good point. How do you want to split it?

**Comment by uok** [comment]
I hope I can continue on this soon

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
