### PR TITLE
Enforce line endings when cloning (fixes #1766)

### LINKED ISSUE #1766: walk_test.go:119: Walk returned unexpected data [Windows]
http://build.syncthing.net/job/syncthing-windows-integration/115/console

```
walk_test.go:119: Walk returned unexpected data
Expected: {
  afile (4 bytes): b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  dir1 (128 bytes): 
  dir1\dfile (5 bytes): 49ae93732fcf8d63fe1cce759664982dbd5b23161f007dba8561862adc96d063
  dir2 (128 bytes): 
  dir2\cfile (4 bytes): bf07a7fbb825fc0aae7bf4a1177b2b31fcf8a3feeaf7092761e18c859ee52a9c
  excludes (37 bytes): df90b52f0c55dba7a7a940affe482571563b1ac57bd5be4d8a0291e7de928e06
  further-excludes (5 bytes): 7eb0a548094fa6295f7fd9200d69973e5f5ec5c04f2a86d998080ac43ecf89f1
}
Actual: {
  afile (5 bytes): bf874c7dd3a83cf370fdc17e496e341de06cd596b5c66dbf3c9bb7f6c139e3ee
  dir1 (128 bytes): 
  dir1\dfile (6 bytes): c49b743f4d02c3430336150519173d8e13ab74607eaf3563809aabb1bf3cfb14
  dir2 (128 bytes): 
  dir2\cfile (5 bytes): d30392e66c636a063769cbb1db08cd3455a424650d4494db6379d73ea799582b
  excludes (39 bytes): 819bd11a8fda79a853aec5413ced11b9f9a24b71a9a2ef9d0bc8b473e020576d
  further-excludes (6 bytes): 621a748519ed11d9ef567fb24c1400a58de35047cecff24c7ce5d1b6683abe95
}
```

### PR DESCRIPTION
**Pull request by Zillode**

### CODE REVIEW

**Comment by Zillode** [comment]
@st-jenkins run integration tests for windows

**Comment by Zillode** [comment]
still broken: 	walk_test.go:119: Walk returned unexpected data

**Comment by Zillode** [comment]
@st-jenkins run integration tests for windows

**Comment by Zillode** [comment]
This patch does work, Jenkins was incorrectly configured (was building master instead of PR SHA)

**Comment by calmh** [comment]
`sync_test.go` seems permanently broken now, although probably not due to this change...

**Pull request merged**
