### PR TITLE
Adding missing contributor

### PR DESCRIPTION
**Pull request by marclaporte**
We have several lists. Perhaps they should all be merged...

### CODE REVIEW

**Comment by calmh** [comment]
Yeah, three places, used for different things though and need to be in kinda different formats. I agree it's a bit annoying, the thought has struck me to have a master list and script it... As it is, there's script that checks for presence in AUTHORS so that isn't missed. The reason you *are* missed anyway is that we haven't added to AUTHORS for non-code commits, i.e. typo fixes. (For the same reason all of the translators are not listed...) This isn't something I feel strongly about, so contributions beyond a single typo fix can certainly be recognized. :) Tweak this one to include all the three places and I'll merge it.

**Comment by marclaporte** [comment]
Done. Thanks!

**Comment by AudriusButkevicius** [comment]
Can you please squash the commits? Thanks.

**Comment by calmh** [comment]
squash-merged

**Comment by marclaporte** [comment]
Thanks Jakob!

**Pull request closed without merging**
