### PR TITLE
gui: css cleanup

### PR DESCRIPTION
**Pull request by norgeous**
move some css around to better reflect new css structure of #2883 
also some css formatting fixed

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Can you change the copright date to 2016?

**Comment by norgeous** [comment]
ok, i updated the copyright for ```gui/default/assets/css/theme.css``` to 2016

should the copyright for ```gui/default/assets/css/overrides.css``` remain as 2014?

i'm not sure how this works...

**Comment by AudriusButkevicius** [comment]
That file was probably created in 2014, so it's fine.

**Comment by AudriusButkevicius** [comment]
So this is fine, but can you do me a favor, and actually remove the colurs from .folder-advanced from both default and dark themes?

Because this breaks for every other theme around.

**Comment by norgeous** [comment]
ok i have just removed the rules refering to ```.folder-advanced```

couldn't find where it was used then realised its for a newer feature not yet in the release version...

looks good.

**Comment by AudriusButkevicius** [comment]
@st-review merge this please 

gui: Clean up CSS

**Comment by st-review** [comment]
OK, merged as 46c07bb207d0d6577477012bbd0c69f3dcb39060. Thanks, @norgeous!

**Pull request closed without merging**
