### PR TITLE
Update wording to save space

### PR DESCRIPTION
**Pull request by uok**
Update wording to save space (related https://github.com/syncthing/syncthing/pull/3973)
Pause All Folders -> Pause All
Resume All Folders -> Resume All

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/3982/head:pr-3982
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   96fba1b..89f8be4  master     -> orig/master
$ git reset --hard
HEAD is now at 89f8be4 lib/model: Use ignore patterns in remote completion calculation
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 89f8be4 lib/model: Use ignore patterns in remote completion calculation
$ git clean -fxd
$ git merge --squash --no-commit pr-3982
Updating 89f8be4..b298142
Fast-forward
Squash commit -- not updating HEAD
 gui/default/index.html | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
$ git commit -F -
Commit message subject:

    Update wording to save space

doesn't look like "tag: One sentence description". Specifically, it doesn't
match this pattern:

    ^[\w/,\. ]+: \w

```

**Comment by calmh** [comment]
@st-review merge it

gui: Update button wording

**Comment by st-review** [comment]
:ok_hand: Merged as fb6d453c74d8420af847460e42e05779e90311b6. Thanks, @uok!

**Pull request closed without merging**
