### PR TITLE
Return status code 307 instead of 302 when redirecting from HTTP to HTTPS

### PR DESCRIPTION
**Pull request by calmh**
```
jb@syno:~/s/g/s/syncthing $ curl -X POST -i http://localhost:8385/rest/system/config
HTTP/1.1 307 Temporary Redirect
Location: https://localhost:8385/rest/system/config
Date: Fri, 29 Jan 2016 10:09:16 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

### CODE REVIEW

**Comment by calmh** [comment]
Or maybe we should even return 308?

**Comment by canton7** [comment]
Agreed with 308.

**Comment by AudriusButkevicius** [comment]
Why is this an issue?

**Comment by canton7** [comment]
It seems that thing which make HTTP requests (browsers, API libraries, etc) will switch from `POST` to `GET` if they see a `302`. This can happen if a client requests an API endpoint over HTTP when Syncthing is configured to only allow HTTPS.

**Comment by AudriusButkevicius** [comment]
I understand the conceptual problem, but what is the actual problem that someone has reported?
I bet there is a metric ton of things which do not support 307/8.

**Comment by canton7** [comment]
It popped up when I was trying to let Syncthing choose between HTTP and HTTPS based on its settings, but still make API requests to it.

I've fallen back to just making all API requests over HTTPS.

**Comment by calmh** [comment]
I think IE 6 is the most modern browser to *not* support 307, from what I can gather on the web. This *should* have the advantage of being able to do things like enable TLS in the browser, hit save, disable it again and hit save, and it works. Currently the second POST would get hit by a 302 redirect and get transformed to a GET, doing nothing.

**Pull request merged**
