### PR TITLE
script: Improve changelog layout

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Pull issue information from Github to show both the resolved issue subject and the commit subject. Also show reviewer, when different from author.

Example:

    * #3201: api: /rest/system/browse behaves strangely on Windows

      lib/osutil: Fix globbing at root (by @AudriusButkevicius, reviewed by
      @calmh)

    * #3174: Ignore patterns with non-ASCII characters causes out of memory
      crash

      vendor: Update github.com/gobwas/glob (by @calmh)

### CODE REVIEW

**Comment by calmh** [comment]
(Everyone please feel free to touch up issue subjects so they make some rough sort of sense in the future.)

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as a775dd2b79ce6ed84a0223dc0e7f0d0a6a570de3. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
You can also adjust the merge bot to refuse merging in issue title does not match something.

**Pull request closed without merging**
