### PR TITLE
Make QR Code visible on small screens (fixes #1602)

### LINKED ISSUE #1602: QR Code not fully visible on small Android screen
And when touch screen is used to move QR code to be fully visible, it's the background page which moves, and not the overlay with the QR code.

This was using the web interface (Bootstrap) on an older small Android phone. On a modern phablet, it works well.

2015-04-07-syncthing-qrcode-small-screen

### PR DESCRIPTION
**Pull request by bigbear2nd**
Added another line in the menu on small devices. Maybe not the most elegant solution.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Don't you need hidden-xs on the old button?

**Comment by bigbear2nd** [comment]
On small devices, there are two different options, then: 
One can show the ID and one can show the QR-code.

I am so unable to squash commits. Is everybody using the command line of this?

**Comment by bigbear2nd** [comment]
Sorry, I have to do this again..

**Comment by AudriusButkevicius** [comment]
Yeah, sadly it's very limited what you can do though the UI.
Embrace the command line!

**Pull request closed without merging**
