### PR TITLE
User fewer hasher routines when there are many folders.

### PR DESCRIPTION
**Pull request by calmh**
https://forum.syncthing.net/t/2564

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I guess the bigger problem is the random seeks reading 128kb each from different files trying to multiplex?

**Comment by calmh** [comment]
(Tests need fixing.)

Yeah, so it seems. I keep claiming that's not a big deal as *real operating systems* will recognize the multiple sequential streams for what they are and do the appropriate readahead, and *real hardware* doesn't have a seek penalty. And indeed the complaints come from Windows boxes running on spinning rust, which is neither. So maybe that's the reality we need to adjust for. :/

**Comment by calmh** [comment]
I guess we could spin up a "global" pool of hashers of set size, say `runtime.GOMAXPROCS`, once and for all so that we won't exceed it even with many folders. For the case where the number of folders is equal to or less than the number of cores, this should have the same effect though.

**Comment by calmh** [comment]
I've been toying with the idea of a rate limiter for disk I/O as well. Either in bytes/s or operations/s.

**Pull request merged**
