### PR TITLE
lib/upnp: Add a NAT service which provides mappings

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Refactors existing UPnP code into a NAT service.

Improvements:
1. Returns a mapping object rather than just a port, which allows subscribing to external addresses changing
2. Acquires a mapping for each of the listen addresses rather than the first one.
3. Acquires a mapping for each of the IGDs available, adding multiple gateway support
4. Allows plugging in other providers of NAT traversal (NATPMP to follow)

### Testing

Ran some manual tests with 1 minute lease times and STTRACE=discovery,nat, unplugging network cable, plugging it back in, etc.

### CODE REVIEW

**Comment by calmh** [comment]
Neat!

https://reviews.syncthing.net/cru/CR-10

**Comment by calmh** [comment]
Appears to work with a quick two second test against miniupnpd at least.

```
[7DDRT] 2016/04/10 20:46:24.386859 service.go:107: INFO: Detected 1 NAT device
[7DDRT] 2016/04/10 20:46:24.386918 service.go:235: DEBUG: Acquiring TCP 0.0.0.0:22200 mapping on c9c13192-b5dd-4bb4-827e-585ab9082cd7
[7DDRT] 2016/04/10 20:46:24.504006 service.go:243: DEBUG: Acquired TCP 0.0.0.0:22200 -> 213.114.37.239:51744 mapping on c9c13192-b5dd-4bb4-827e-585ab9082cd7
[7DDRT] 2016/04/10 20:46:24.504032 structs.go:32: INFO: New NAT port mapping: external TCP address 213.114.37.239:51744 to local address 0.0.0.0:22200.
[7DDRT] 2016/04/10 20:46:24.504086 verboseservice.go:49: VERBOSE: External port mapping changed; protocol: TCP, local: 0.0.0.0:22200, added: [213.114.37.239:51744], removed: []
```

**Comment by AudriusButkevicius** [comment]
Don't merge yet.

**Comment by AudriusButkevicius** [comment]
Check out last commit, if happy, feel free to merge.

**Comment by calmh** [comment]
@st-review merge this please

lib/nat: Add a nat package and service to track mappings on multiple IGDs

**Comment by st-review** [comment]
OK, merged as 19b4f3bfb4e6afb0a3efb879a3e22dc9463600b6. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
