### PR TITLE
all: "Mac OS X" is now called "macOS"

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This changes the string we show in the web GUI, a note in the README, the directory name for the launchd stuff, and prepares the upgrade system for a future change. The upgrade system learns to recognize releases named "...-macos-..." in addition to the current "...-macosx-..." so that we could at some point in the future start naming our releases like that.

### Testing

Nyet

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I am like 99% sure this will fk up auto-upgrades. I can't tell you why, but something like this always does.

**Comment by calmh** [comment]
I approve of your skepticism

On 21 Jan 2018, at 00:34, Audrius Butkevicius <notifications@github.com<mailto:notifications@github.com>> wrote:


I am like 99% sure this will fk up auto-upgrades. I can't tell you why, but something like this always does.

**Comment by imsodin** [comment]
I assumed the two comments above were serious at the core, but with a joking nature - the silence since and not addressing the tests makes me doubt that a bit. Is this PR meant to happen, just benched for now or dead? x)

**Comment by calmh** [comment]
I’m going to either add a test to prove this is safe, or explain why I think the existing tests cover it, once I’ve had time to do so. :)

**Comment by calmh** [comment]
And, of course, fix the tests.

**Comment by calmh** [comment]
I think the existing TestSelectedRelease covers this quite well, and added a specific one for Mac to verify that both asset name variants are OK and can be selected.

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/4694/head:pr-4694
From https://github.com/syncthing/syncthing
 * [new ref]         refs/pull/4694/head -> pr-4694
$ git fetch -f origin master:orig/master
From https://github.com/syncthing/syncthing
   885e3f1..20e05cd  master     -> orig/master
   a505231..20e05cd  master     -> origin/master
$ git reset --hard
HEAD is now at a505231 lib/scanner: Support walking a symlink root (ref #4353)
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git reset --hard orig/master
HEAD is now at 20e05cd authors: Update PrototypeNM1
$ git clean -fxd
$ git merge --squash --no-commit pr-4694
Automatic merge went well; stopped before committing as requested
Auto-merging etc/macos-launchd/README.md
Squash commit -- not updating HEAD
$ git commit -F -
Commit message subject:

    all: "Mac OS X" is now called "macOS"

doesn't look like "tag: One sentence description". Specifically, it doesn't
match this pattern:

    ^[\w/,\. ]+: \w

```

**Comment by calmh** [comment]
orly

**Comment by calmh** [comment]
@st-review merge

all: Mac OS X is now called macOS

**Comment by st-review** [comment]
:ok_hand: Merged as 050f9f809181f39d258eb1e665e00d3090a9a96b. Thanks, @calmh!

**Pull request closed without merging**
