### PR TITLE
gui: Pretty theme names

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Prettier names for new themes

### Testing

Compiled and looked at it

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge this

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2893/head:pr-2893
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   eaa805b..46c07bb  master     -> orig/master
$ git reset --hard
HEAD is now at 46c07bb gui: Clean up CSS
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 46c07bb gui: Clean up CSS
$ git clean -fxd
$ git merge --squash --no-commit pr-2893
Auto-merging lib/auto/gui.files.go
CONFLICT (content): Merge conflict in lib/auto/gui.files.go
Squash commit -- not updating HEAD
Automatic merge failed; fix conflicts and then commit the result.

```

**Comment by calmh** [comment]
Meh. Robot, you should add value here and handle the merge conflict on that thing automatically...

**Comment by calmh** [comment]
@st-review merge this, and handle the auto thing now please

**Comment by st-review** [comment]
OK, merged as 4b6c2d0d3d2245a42e02546a603f28154ab07413. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
