### PR TITLE
lib/osutil: Disable setting priority on Windows (fixes #4676)

### LINKED ISSUE #4676: Panic: fatal error: unexpected signal during runtime execution
I have 3x computers synced using syncthing:
Windows 7 32bit - work, installed manually
Windows 10 64bit - home, installed via just-install
Void Linux 64bit - server, run via docker linuxserver/syncthing

On startup, work computer produces the attached panic log. This panic happens every start I start syncthing and I felt reporting the issue was better than re-installing the application in the hopes it would resolve but I'm willing to try.

Yesterday I added a number of sqlite databases (baikal, selfoss, etc) from the 'server' install, but my Windows 10 install gives me no issues.

Attached a redacted panic log.

### Version Information

Syncthing Version: v0.14.44-rc.1
OS Version: Windows 7 32bit

[panic-20180117-091638.log](https://github.com/syncthing/syncthing/files/1638379/panic-20180117-091638.log)

### PR DESCRIPTION
**Pull request by calmh**
Presumably fixing the crash, leaving us to improve this calmly.

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 582539a1e60ac325cea1cc801552f9a4390e4e13. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
I guess this is so urgent as you want a new RC?

**Comment by calmh** [comment]
Yeah printing one currently

**Comment by calmh** [comment]
Can try to get a fixed version into an rc3, but lets not crash in the meantime

**Comment by AudriusButkevicius** [comment]
I hopefully can test this, yet not until friday I suspect.

**Comment by calmh** [comment]
I can see a couple of things that might go wrong. I'm blindly assuming that kernel32.dll is available (and we do that in other places) and that SetPriorityClass is found. That may not be the case. The process handle in the crash backtrace is 0xffffffff which is odd, yet that is one call where we do check the error. And of course I might have misunderstood something else.

**Comment by AudriusButkevicius** [comment]
I suspect it crashes due to an exception/fault/whatever it's called raised during the syscall, and the exception is raised because something is not found or not valid.

**Pull request closed without merging**
