### PR TITLE
Fix deleting folders on WinXP (fixes #2522)

### LINKED ISSUE #2522: Out of sync: failed to remove dirs, files on winxp (busy error)
Hi All! Thanks for the great Sync thing!

But I am experiencing an "Out of sync" problem on my Win XP box after upgrade from 0.11.25 to 0.12.4 (please see the log below). Other boxes (Linux, Win7, Win7, Android) in the domain has upgraded fine. What can cause this "Busy" error? There is no any other activity with these files.

[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 rwfolder.go:257: DEBUG: rwFolder/default@0x1f446f00 changed 3
[3JIVD] 2015/11/26 15:55:34.515625 rwfolder.go:287: INFO: Folder "default" isn't making progress. Pausing puller for 1m0s.
[3JIVD] 2015/11/26 15:55:34.515625 rwfolder.go:288: DEBUG: rwFolder/default@0x1f446f00 next pull in 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:144: DEBUG: log 1517 FolderErrors map[folder:default errors:[{test remove \\?\H:\Sync\test: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.} {test-vdvp remove \\?\H:\Sync\test-vdvp: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.} {test2 remove \\?\H:\Sync\test2: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.}]]
[3JIVD] 2015/11/26 15:55:34.515625 events.go:144: DEBUG: log 1518 StateChanged map[duration:0.125 folder:default to:idle from:syncing]
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s

The localized error message above says "the file is busy".

### PR DESCRIPTION
**Pull request by buinsky**

### CODE REVIEW

**Comment by canton7** [comment]
Nice find :+1:

**Comment by AudriusButkevicius** [comment]
Great detecive work. Can you please add yourself to authors and remove the trailing semicolon.

**Comment by canton7** [comment]
Sorry to be a pain, but could you please change the subject to `Fix deleting folders on WinXP (fixes #2522)` to match the [Contributing Guidelines](http://docs.syncthing.net/dev/contributing.html)? Thanks!

**Comment by buinsky** [comment]
@AudriusButkevicius @canton7
Done.

**Comment by AudriusButkevicius** [comment]
Lets wait for the build to finish, and I'll merge this.

**Comment by canton7** [comment]
:+1:

**Comment by AudriusButkevicius** [comment]
Build reporting is borked, but I am happy with this. Thank you very much for your fix.

**Comment by calmh** [comment]
Neat. @AudriusButkevicius, @canton7, please note that adding to AUTHORS is not enough; we also need NICKS and the authors list in the GUI, which is why I usually want to do it myself. :)

**Pull request merged**
