### PR TITLE
Improve event handling a little bit.

### PR DESCRIPTION
**Pull request by calmh**
The first commit is smaller when viewed without whitespace changes...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So it we decide to get rid of the details, we might as well get rid of the ToTruncated as that's the only place where it's used.

Is there reason for getting rid of it the CamelCase incorrectness, or in general you feel it's not useful?

We could also include action in the ItemStarted, and the type in ItemFinished, though not sure how useful it is.

**Comment by calmh** [comment]
> So it we decide to get rid of the details, we might as well get rid of the ToTruncated as that's the only place where it's used.

Aye.

> Is there reason for getting rid of it the CamelCase incorrectness, or in general you feel it's not useful?

Easier to get rid of it than fix it, since there's no consumer, and it's more data to serialize for a very high rate event - better performance like this I think.

> We could also include action in the ItemStarted, and the type in ItemFinished, though not sure how useful it is.

Hmm, actually, yes. When I started coding it up I had more action types, and then it wasn't always known when we fired ItemStarted what the action would be. But now we know, so it's silly to separate it like this.

**Comment by AudriusButkevicius** [comment]
That's fine, let's scrap it.

**Comment by calmh** [comment]
@AudriusButkevicius please take another look?

**Pull request merged**
