### PR TITLE
WIP: new fuse-loopback based filesystem type allowing to differenciate between bit-rot and intended changes

### PR DESCRIPTION
**Pull request by cre4ture**
Please refer to #9691 which is the main PR for this feature

### CODE REVIEW

**Comment by calmh** [comment]
So my initial gut reaction is that this is probably a feature we don't want, for most of the reasons brought up in the forum thread about this, but also that this is something I don't want to maintain going forward.

**Comment by cre4ture** [comment]
> So my initial gut reaction is that this is probably a feature we don't want, for most of the reasons brought up in the forum thread about this, but also that this is something I don't want to maintain going forward.

It would not be needed if the other PR is accepted. There the bit-rot can be handled as well. Its kind of a side-effect that comes for free.

**Comment by calmh** [comment]
folder-on-S3 is a reasonable and desirable feature, so then let's concentrate on that one instead.

**Comment by imsodin** [comment]
Disclaimer: Haven't looked at the code, just thinking about the feature overall here:

> folder-on-S3 is a reasonable and desirable feature, so then let's concentrate on that one instead.

What I worry about for this is our extensive metadata access (e.g. scanning, but also during syncing and possibly other places). In my experience S3 is terrible for that. At best extremely slow, at worst slow and expensive. To me it seems like a syncthing/BEP on S3 solution would have to throw out most of our code to optimise for the intricansies of S3, not just pretend it's a normal filesystem and swap it in as such. Maybe it can be handled with extensive caching at the FS layer, potentially even persisting that, but that seems like a can of worms on it's own.

**Comment by cre4ture** [comment]
> folder-on-S3 is a reasonable and desirable feature, so then let's concentrate on that one instead.

That's fine for me. But it was important for me bring in this solution idea as well. I had it implemented anyway.
I guess I can close the PR then?

**Pull request closed without merging**
