### PR TITLE
lib/model: Add option for overwriting names on connect (fixes #2912)

### LINKED ISSUE #2912: Node name propagation
When a node changes its name, paired nodes that left the Machine name field blank won't get it updated.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Overwrites device name on connect.
Perhaps we should make this the default? It would make people more organized with their stuff.

### Testing

Unit tests

### CODE REVIEW

**Comment by calmh** [comment]
As a default, maybe? How would anyone know to set this otherwise?

**Comment by AudriusButkevicius** [comment]
Well it's an option you can enable I guess.

**Comment by calmh** [comment]
@st-review merge this

**Comment by st-review** [comment]
OK, merged as 4389bb037d218abd80168d5acddbbd692fad6c68. Thanks, @AudriusButkevicius!

**Comment by AudriusButkevicius** [comment]
Should we make default to true?

**Comment by calmh** [comment]
UI wise that should then disable the ability to edit the names manually, I guess, otherwise things will be weird?

**Comment by AudriusButkevicius** [comment]
Yeah I guess we could make them read only if the option is enabled

**Pull request closed without merging**
