### PR TITLE
vendor: Move back to upstream KCP (fixes #4407)

### LINKED ISSUE #4407: contribute kcp-go changes/features and/or fix tests
Hello!

Syncthing is now using a fork of [xtaci/kcp-go](https://github.com/xtaci/kcp-go) at [AudriusButkevicius/kcp-go](https://github.com/AudriusButkevicius/kcp-go).

I would have opened the issue on that repository, but issues are disabled. I am sorry if this is the wrong place to discuss my concerns.

Have you tried contributing your changes/features to upstream? Will Syncthing always use the fork?

If you decide to keep using the fork, would you please consider fixing the tests? They won't build:

```
src/github.com/AudriusButkevicius/kcp-go/sess_test.go:473: cannot use fakeaddr (type *net.UDPAddr) as type string in argument to l.closeSession
```

If the plan is that Syncthing keeps using the AudriusButkevicius/kcp-go fork, I will have to package it for Debian.

Cheers,

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 72172d853c093fbf63ef9009ec31a353de4ada3e. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
