### PR TITLE
Add -paths option to print config, key, database paths

### PR DESCRIPTION
**Pull request by calmh**
```
jb@syno:~/s/g/s/syncthing $ syncthing -paths
Configuration file:
	/Users/jb/Library/Application Support/Syncthing/config.xml

Database directory:
	/Users/jb/Library/Application Support/Syncthing/index-v0.13.0.db

Device private key & certificate files:
	/Users/jb/Library/Application Support/Syncthing/key.pem
	/Users/jb/Library/Application Support/Syncthing/cert.pem

HTTPS private key & certificate files:
	/Users/jb/Library/Application Support/Syncthing/https-key.pem
	/Users/jb/Library/Application Support/Syncthing/https-cert.pem

Log file:
	/Users/jb/Library/Application Support/Syncthing/syncthing.log

GUI override directory:
	/Users/jb/Library/Application Support/Syncthing/gui

Default sync folder directory:
	/Users/jb/Sync
```

### CODE REVIEW

**Comment by canton7** [comment]
Nice!

git has `--list`, although that's not quite the same... Personally I'd prefer something a bit more descriptive than `-config`

**Comment by AudriusButkevicius** [comment]
-paths or -locations as this one is definately confusing, and makes me think you can point it at a custom config.

**Comment by calmh** [comment]
Are we OK with `-locations`?

**Comment by calmh** [comment]
Actually no, `-paths` is better I think, "location" is weird terminology.

**Pull request merged**
