### PR TITLE
Copy failed file path

### PR DESCRIPTION
**Pull request by nov1n**
### Purpose

Addresses #3679.

### Testing

Tested on Chrome and Firefox on Windows and Ubuntu.

### Implementation

Files that failed to sync may be clicked to copy the full path to clipboard.
[Clipboard.js](https://clipboardjs.com/) was used.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
There is no indication that it's copyable nor that it was copied.

**Comment by nov1n** [comment]
There is none indeed, that sounds like a good idea. I'll update it tomorrow.

**Comment by calmh** [comment]
More generally, I'm not convinced this is a good idea. Why special case copy behavior for one place a path is shown, and not also do it in the download progress dialog, with the device ID in the device ID dialog, etc?

**Comment by nov1n** [comment]
Issue #3679 raised the issue that there is no way to copy the full file path in the failed files modal. If this is a problem in other places as well, should we add a way to copy there too?

**Comment by calmh** [comment]
Maybe the lack of ability to copy is limited to this case, but adding click-to-copy-automatically seems a bit arbitrary (and hard to discover). Perhaps the real problem is just that the dialog is badly designed to begin with so that the path needs to be hidden in a tooltip, and it should be displayed easier so people can select and Ctrl-C it like anything else?

**Comment by nov1n** [comment]
Okay, I think it was just for convenience purposes as it is a common usecase to copy this path to do investigation. A right aligned icon would make it more easily discoverable, although I agree that it is a arbitrary, especially because it is the only place in the UI where this is possible.

Shall I modify the PR such that the full path is displayed in the dialog (rather than the basepath) such that users may simply Ctrl-C it?

**Comment by nov1n** [comment]
@calmh , see #4023

**Pull request closed without merging**
