### PR TITLE
Do not consider draft releases or releases with emtpy assets

### PR DESCRIPTION
**Pull request by Zillode**
Related to https://github.com/syncthing/syncthing/issues/1285, the Github API allows a [draft option](https://developer.github.com/v3/repos/releases/#input). This patch skips such drafted releases.
Warning: untested!

### CODE REVIEW

**Comment by dzarda** [comment]
Code looks fine.
I'm just assuming the "draft" JSON field is existent. I couldn't find it.
:+1:

**Comment by Zillode** [comment]
https://developer.github.com/v3/repos/releases/#create-a-release
```draft: boolean: true to create a draft (unpublished) release, false to create a published one. Default: false```

**Comment by dzarda** [comment]
Ah yes, I'm just blind, as usual... Now we just need someone to test it.

**Comment by calmh** [comment]
I don't think draft releases are visible unless you're accessing the API from a logged in account with access to the project in question. Skipping releases without assets is valid, but not really a case that should happen with any regularity?

**Comment by calmh** [comment]
Maybe I'm complicating stuff unnecessarily, but when we're anyway in here and rooting around, how about making it return the latest release that is of the right type and has an asset for the current architecture? I.e. we consider each release where we find a matching asset, then check if it matches our prerelease status, and return the first we find?

**Comment by Zillode** [comment]
- Please carefully check lines [1](https://github.com/Zillode/syncthing/blob/d6030b8d68594722b55ddf8c62adf235418e6bb3/cmd/syncthing/gui.go#L638), [2](https://github.com/Zillode/syncthing/blob/d6030b8d68594722b55ddf8c62adf235418e6bb3/cmd/syncthing/main.go#L329) and [3](https://github.com/Zillode/syncthing/blob/d6030b8d68594722b55ddf8c62adf235418e6bb3/cmd/syncthing/main.go#L1063). This means major version upgrades will only happen if ```-upgrade``` is provided. Is this the intended behavior?
- Beta upgrade to newer versions and newer beta versions. Currently v0.11-beta would upgrade to v0.10 because it was released at a later point in time. This PR fixes that as well.

**Comment by calmh** [comment]
> Currently v0.11-beta would upgrade to v0.10 because it was released at a later point in time

Shouldn't the version comparison handle that?

**Comment by calmh** [comment]
I understand what you mean now. Looks good to me!

**Pull request merged**
