### PR TITLE
lib: versioner test is rather a test for simple

### PR DESCRIPTION
**Pull request by lkwg82**
just renamed 

versioner_test.go into simple_test.go

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it

lib/versioner: Rename versioner_test to simple_test

**Comment by st-review** [comment]
@calmh: Clone failed:

```
$ git clone git@github.com:syncthing/syncthing.git syncthing/syncthing
Cloning into 'syncthing/syncthing'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by calmh** [comment]
@lkwg82 sorry, there may be some noise here - using the PR to test the migration of the merge bot to another server

**Comment by calmh** [comment]
@st-review merge it

lib/versioner: Rename versioner_test to simple_test

**Comment by st-review** [comment]
@calmh: Clone failed:

```
$ git clone git@github.com:syncthing/syncthing.git syncthing/syncthing
Cloning into 'syncthing/syncthing'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by calmh** [comment]
@st-review merge it

lib/versioner: Rename versioner_test to simple_test

**Comment by st-review** [comment]
:ok_hand: Merged as 70c5a5dff1083ecf0bb2ee69320d63b67ad3cab9. Thanks, @lkwg82!

**Pull request closed without merging**
