### PR TITLE
test: Fix integration tests choking on event data

### PR DESCRIPTION
**Pull request by acolomb**
### Purpose

As mentioned in https://github.com/syncthing/syncthing/pull/8283#issuecomment-1105836048, the `lib/rc` package will panic because of an invalid typecast for the `FolderSummary` event data, introduced in #8249.  The end goal here is to fix that panic.

Meanwhile, the integration tests no longer even build since #7188, so this is also a stab at making the necessary adjustments.

### CODE REVIEW

**Comment by acolomb** [comment]
In trying to see whether the `FolderSummary` event actually does cause a panic, I was held up trying to fix the tests even building.  Need some help there regarding where to put the `cfg.Serve()` call during tests.

Please review and help fixing these basic issues first, then I'll follow up on fixing the event data type.

**Comment by acolomb** [comment]
Actually I think the original assumption this would panic is a red herring.  The events are parsed from JSON, therefore they are always `map[string]interface{}` and don't carry the original type information anymore.

So we'll retitle this as just fixing integration test building I guess.

**Comment by acolomb** [comment]
Since #6956 the actual `FolderCompletion struct` is used to unmarshal the event during integration tests.  That broke recently because the `remoteFolderState` member type didn't have an `UnmarshalJSON()` or `UnmarshalText()` method.  I now added the latter, but frankly it seems overkill having to write all this manual copy-and-paste boilerplate code for a simple "enum style" value in the event.

I'd very much welcome advice on how to do this more elegantly.

**Comment by st-review** [comment]
:robot: beep boop

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

To permanently exempt this PR from bot nagging, add the `slow-pr` label.

**Pull request closed without merging**
