### PR TITLE
Add dialer.DialTimeout, use that when connecting to relays

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
This is needed for the relaypoolsrv not to hang for 2 minutes when testing a relay we are supposed to add.

### CODE REVIEW

**Comment by calmh** [comment]
That's a rather large diff to add a timeout :) I'll get to it.

**Comment by AudriusButkevicius** [comment]
Again, its splitting and renaming a file, but git is not clever enough.

**Comment by calmh** [comment]
I through the various options on my diff to usually handle that, but it didn't realize the truth. I'll try harder, or just eyeball it :)

**Comment by calmh** [comment]
This also adds fallback stuff, making each failed connection attempt take twice as long in the presence of a proxy, right? I.e. when the device we're trying to connect to is offline, we fail once via proxy then try again direct. Are we sure we want to do direct connection attempts everywhere after being told to use a proxy?

**Comment by AudriusButkevicius** [comment]
Syncthing only works if its connected, hence we try as hard as we can to connect, in order for it to do its job.

**Comment by AudriusButkevicius** [comment]
Also, thr fallback stuff was there before

**Pull request merged**
