### PR TITLE
File conflicts now rename the file to include the local client name

### PR DESCRIPTION
**Pull request by nrm21**
File conflicts now rename the file to include the local client name:

Example old file renamed to:
  New Text Document.sync-conflict-20151206-172713-[NRMLAPTOP-version].txt

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
This doesn't do what you think it does.
It always includes our name, regardless of who caused the conflict.

**Comment by nrm21** [comment]
Yes, I know... it includes the name of the one who lost the conflict (that is the one that will be running the file rename code).

**Comment by AudriusButkevicius** [comment]
I don't think this is right, as every device which will notice a conflict will produce a unique file, causing N'plicate conflicts.

**Comment by nrm21** [comment]
Well conflicts shouldn't happen often but... Can you explain a bit more?

Are you saying that if A = B = C  Then A and B modify a file close enough to simultaneously they will both create a loser?

Because I wasn't seeing that in my testing.

**Comment by canton7** [comment]
1. Should we use device id rather than name? Names probably won't be consistent across the network, and might well contain characters which aren't allowed in filenames. 
2. I don't think putting the name of the device which noticed the conflict into the filename adds anything useful. Think of a case with 3 devices, where your device conflicts with one of the others. You know want to know that you conflicted with another device, and which one you conflicted with. Seeing your own device name on the filename of the conflicted file tells you exactly nothing, but had the potential to add confusion (the file with your name in it probably won't be your copy if the file...)

**Comment by nrm21** [comment]
I can make it either way you guys want.  I just thought friendly name would be more beneficial for userss.

**Comment by canton7** [comment]
Thing is, if we use friendly names, we have to sanitise them to remove all if the character years which aren't allowed in filenames on all of the various filesystems. You also run the risk of creating very long filenames on Windows which exceed the path length limit, which means users have a really hard time deleting or renaminf the files... Which isn't what you want from a file that exists solely to be deleted or renamed.

**Comment by nrm21** [comment]
Not a prob, that's the easy part... fixing that is 30 seconds of code.  It's finding the winner and coding that name/devid in that's would prob take much longer (and likely be harder to know if any code side effects).

**Comment by AudriusButkevicius** [comment]
Imagine the following scenario:

Nodes A-B-C....  up to Z
Initially all in sync.
Z goes offline
At time T1 node A modifies a file, all nodes apart from Z agree with the update, but Z hasn't seen the update as it's offline.
At time T2, node Z modifies the same file, while being offline.

Z comes back online, and there is a conflict, and Z's file wins, because it was modified later than the file modified by A. Suddenly all nodes move the old file they had from A as conflict, adding their own name to it.
Suddenly you have file-A.sync-conflict, file-B.sync-conflict, .. file-Y.sync-conflict, and all of them are generally new files, hence get synced across to all other nodes.

As for which name there should be, I think when we move the file for conflict we have to take the first 5 characters of the device ID who has last modified the file which we are now moving for conflict.
The way you'd get that is check the version which is concurrent and loosing, and then match the first 63 bits of the version ID with the device ID's available in the model.

**Comment by canton7** [comment]
:+1: that's all intuitive to me

**Comment by nrm21** [comment]
Ok I see what you mean.  But if we use winners ID that wouldn't happen right?  Or as you put it "the device ID who has last modified the file" yes?

Just making sure we're on the same page here.

**Comment by AudriusButkevicius** [comment]
Each file version has someone who modified it, when I mean someone who modified it last, I mean someone who last modified the conflicting side, so there is no way you could call that the winner.

**Comment by nrm21** [comment]
I will see what I can do to update the code and re-PR

**Comment by calmh** [comment]
We're probably handling it a bit suboptimally anyway as even without this patch, we'll get all the A..Y sync-conflict files. Not sure if there's a good way around that though.

**Pull request closed without merging**
