### PR TITLE
Add an icon for Safari's pinned tabs

### PR DESCRIPTION
**Pull request by jgke**
Safari has its own standard for handling icons for pinned tabs, which requires a black-and-white .svg and a special tag.

Without this, pinning a tab to localhost will actually just show a blank square instead of the pre-generated letter (I think this is a bug at Safari's end).

Here are some screenshots of the patch in effect:

Active tab with patch:
active w/ patch
Inactive tab with patch:
inactive w/ patch
Without the patch:
w/o patch

The 'documentation' is available at
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

### CODE REVIEW

**Comment by calmh** [comment]
Thanks! This looks like it adds a bitmap-traced svg; is there any advantage of this one over the existing assets/logo-only.svg?

**Comment by jgke** [comment]
Ah, I used some converter that seemingly rasterised the svg and then re-svg'd it. I'll now just cp and edit the logo-only.svg so that the white parts are transparent (or it would render into a circle).

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
(Don't worry about the failing "authors" test; I'll take care of that when merging)

**Comment by calmh** [comment]
Thanks!

**Pull request merged**
