### PR TITLE
all: Use github.com/minio/sha256-simd

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

🚤 🐎 🚀 💯 

### Testing

⁉️

### CODE REVIEW

**Comment by calmh** [comment]
Yeah I know, I just thought looked neater as I dislike when the import path doesn't match the package name.

I was surprised by the manifest changes as well, but those entries are "duplicates" of the repositories already vendored slightly above them in the file, so I guess it's a clean up by gvt for some reason (newer version? older version?)

**Comment by AudriusButkevicius** [comment]
So I think it's actually worse to have the package prefixed, than having a package not match the name of the url.

**Comment by calmh** [comment]
fixd

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 5e99d38412ccd655f64f8f9ba75af2e0c47ad3b7. Thanks, @calmh!

**Comment by xor-gate** [comment]
Hi guys, this is awesome to see it integrated! I posted it some days ago on [the forum](https://forum.syncthing.net/t/faster-hashing-package). It will be appreciated by many.

Keep it up!

**Pull request closed without merging**
