### PR TITLE
lib/ignore: Remove ignore cache

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This removes the caching that we have for ignore results. The rationale
is that it's no longer necessary as the ignore checks are fast enough. I
can back that up with benchmarks.

This is the "BenchmarkManyFiles" test, without ignores, with the list of
ignores in ignore_test.go/BenchmarkMatch, and with the same ignores and no
caching. Note that adding ignores and cache increases the RAM profile
significantly, but adding ignores without cache doesn't have a measureable
impact on CPU usage.

No ignores:

2016/04/03 10:32:23 Result: Wall time: 26.563061423s
2016/04/03 10:32:23 Result: 5.8 MiB/s synced
2016/04/03 10:32:23 Receiver: Utime: 31.461676s
2016/04/03 10:32:23 Receiver: Stime: 20.545401s
2016/04/03 10:32:23 Receiver: MaxRSS: 86764 KiB
2016/04/03 10:32:23 Sender: Utime: 37.289588s
2016/04/03 10:32:23 Sender: Stime: 6.186839s
2016/04/03 10:32:23 Sender: MaxRSS: 88420 KiB

Ignores, with cache:

2016/04/03 10:39:53 Result: Wall time: 25.727279751s
2016/04/03 10:39:53 Result: 6.0 MiB/s synced
2016/04/03 10:39:53 Receiver: Utime: 31.185381s
2016/04/03 10:39:53 Receiver: Stime: 20.443559s
2016/04/03 10:39:53 Receiver: MaxRSS: 95948 KiB
2016/04/03 10:39:53 Sender: Utime: 36.473694s
2016/04/03 10:39:53 Sender: Stime: 6.019724s
2016/04/03 10:39:53 Sender: MaxRSS: 104608 KiB

Ignores, no cache:

2016/04/03 10:38:44 Result: Wall time: 26.349629039s
2016/04/03 10:38:44 Result: 5.9 MiB/s synced
2016/04/03 10:38:44 Receiver: Utime: 31.850223s
2016/04/03 10:38:44 Receiver: Stime: 20.911169s
2016/04/03 10:38:44 Receiver: MaxRSS: 87608 KiB
2016/04/03 10:38:44 Sender: Utime: 36.366089s
2016/04/03 10:38:44 Sender: Stime: 6.233578s
2016/04/03 10:38:44 Sender: MaxRSS: 87724 KiB

### Testing

All ignore tests still pass.

### Documentation

Need to remove the `cacheIgnoredFiles` key from the config examples.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Yeah, on a normal machine it does not have an effect, on an RPI I bet it's different.
I'd like to see this not having an effect on an RPI with 200k files.

**Comment by calmh** [comment]
I think the ratio of CPU work between doing other stuff and handling ignores should be the same regardless, but it would be awesome to get someone with crap hardware run the benchmark. Just toggling `cacheIgnoredFiles` on the master branch is good enough.

I had an alternate pull request prepped that just changed the default config (and migrated existing) to cacheIgnoredFiles=false and didn't remove the code.

**Comment by AudriusButkevicius** [comment]
Nothing is free, but looking at the benchmarks it looks like 20% rather than 100%. Also, cache is fairly linear to the number of files you have, and matching is M*N, where M is number of files, N is number of patterns. I guess I am ok to set cacheDisabled where hasing performance is >100MB.

**Comment by calmh** [comment]
20% overhead is for 50k files, and as you say it scales liberally. I'd like to see some benchmark on a lower powered box because I think the current ignore matching cost is probably just noise compared to the database lookups which do hashing, decompression and so on.

**Comment by calmh** [comment]
Linearly. Autocorrect.

**Comment by calmh** [comment]
We should benchmark just scanning, too. My benchmark above covers a lot more than just the scanning, although scanning is part of it.

**Comment by calmh** [comment]
So... So far, this machine is just too slow for me to have had time to run any useful full scale benchmarks. But I can run the ignore benchmarks and do some extrapolations. This is the pre-glob (i.e. regex based) code:

```
(RaspberryPi2)ubuntu@localhost:~$ ./ignore.test.old -test.run None -test.bench .
BenchmarkMatch-4         	    5000	    275991 ns/op
BenchmarkMatchCached-4   	  500000	      3408 ns/op
PASS
```

That 1/(275991*10^-9) =~ 3600 files per CPU second in ignore matching alone (for the patterns in our benchmark, which I think are a tad pessimistic compared to what most users probably have, but that's just a guess). That's almost 70 seconds of CPU time to just process ignores on 250k files. I can see that being a serious problem, hence the need for the cache.

```
(RaspberryPi2)ubuntu@localhost:~$ ./ignore.test -test.run None -test.bench .
BenchmarkMatch-4         	  100000	     21361 ns/op
BenchmarkMatchCached-4   	  500000	      3615 ns/op
PASS
(RaspberryPi2)ubuntu@localhost:~$ 
```

1/(21361*10^-9) =~ 46000 per second, so about 5 seconds of CPU time for doing lookups on those example 250k files. Given how slow everything else is here I think those 5 seconds will be a negligible fraction of the total amount of work required to do that scan, just based on gut feeling... 

But I'll get to those tests. We have a scan benchmark thing after all. :)

**Comment by AudriusButkevicius** [comment]
I guess the cache is now only 7x improvement versus 70x previously.
I'd still be inclined just to disable it by default and leave it as an option. the code being there doesn't do any harm.

**Comment by calmh** [comment]
Agreed.

**Pull request closed without merging**
