### PR TITLE
Update docs to use https

### PR DESCRIPTION
**Pull request by MikeLund**
Simple change to resolve https://github.com/syncthing/syncthing/issues/3651

### CODE REVIEW

**Comment by wweich** [comment]
@st-review merge it

jenkins: use https when downloading docs (fixes #3651)

**Comment by st-review** [comment]
:ok_hand: Merged as 1e54a3e801b2856e5a17e9e29570a190e3db45a1. Thanks, @MikeLund!

**Comment by fheinle** [comment]
It works. As a side note: passing `-L` to curl will follow HTTP redirects to their new destination, allowing for more flexibility on your webserver's side.

**Comment by wweich** [comment]
As we are all very security conscious, the servers will keep https (as long as there are free certs from Let's Encrypt or an alternative) and using https directly is imho the way to go for now.

**Comment by canton7** [comment]
Sure, but I think that passing `-L` can only do good.

**Pull request closed without merging**
