### PR TITLE
chmod -x on files that shouldn't be executable

### PR DESCRIPTION
**Pull request by aviau**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

all: Remove execute bit for non-executable files

skip-checks: authors

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review merge

all: Remove execute bit for non-executable files

Skip-checks: authors

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review merge

all: Remove execute bit for non-executable files

Skip-check: authors

**Comment by st-review** [comment]
:ok_hand: Merged as ee94d53bda063518d0e163ef3e143c00dd684fe1. Thanks, @aviau!

**Comment by canton7** [comment]
Bots are so fussy....

**Pull request closed without merging**
