### PR TITLE
cmd/syncthing/cli: Add command to show pending devices/folders (fixes #8068)

### LINKED ISSUE #8068: Request: show pending devices/folders in CLI
Currently it is not possible to see pending devices and folders using the CLI, so users have to use the graphical interface.

It is already possible to add new devices and folders using only the CLI, so it would be convenient to add the option to list pending devices and folders in the CLI as well.

Since there is an API endpoint to show pending devices/folders, I see no reason not to have this functionality in the CLI.

Proposed solution: add subcommands
`syncthing cli pending devices`
`syncthing cli pending folders`

### PR DESCRIPTION
**Pull request by ignacy123**
…the CLI (fixes #8068)

Simple wrapper for an API call.

### Purpose

fixes #8068

### Testing

All tests pass.

### CODE REVIEW

**Comment by TobiaszCudnik** [comment]
Ive tested it with a large file and a `watch` (on both sides), unfortunately neither `pending devices` nor `pending folders` ever showed anything. The large file just appeared in the folder after some time.

Am I used it the right way?

**Comment by ignacy123** [comment]
Could you elaborate more on how exactly you are using the command? I am not sure if I understand correctly. The command is supposed to show the devices/folders that have been offered to our Syncthing instance but have not been addressed yet (as in we need to accept/decline them). It is not supposed to do anything with files. 
This is the sample output of `syncthing cli pending folders` when one of my known devices has offered a new folder to my instance:
`{
  "hypcg-uquv5": {
    "offeredBy": {
      "DEVICE-IDXXXX-XXXXX": {
        "label": "label",
        "receiveEncrypted": false,
        "remoteEncrypted": false,
        "time": "2021-12-09T09:30:56Z"
      }
    }
  }
}`

**Comment by imsodin** [comment]
Thanks for your contribution!

This command shouldn't live a the top-level, it fits well with existing commands within `show`.

**Comment by ignacy123** [comment]
That is a valid point. I moved the `pending` group to be a `show` subcommand. New usage is:
`syncthing cli show pending devices`
`syncthing cli show pending folders`

**Comment by TobiaszCudnik** [comment]
> The command is supposed to show the devices/folders that have been offered to our Syncthing instance but have not been addressed yet

Oh sorry, I thought its **pending sync** not **pending acceptance**.

Im trying to work on #7849 and that would help me to easily create a test env, considering the [integration tests are broken](https://github.com/syncthing/syncthing/issues/8071).

**Review by acolomb — APPROVED** [review]
I also like it better as a subcommand to `show`.  Tested and works fine.

**Pull request merged**
