### PR TITLE
gui: Use localised time in duration

### PR DESCRIPTION
**Pull request by tomasz1986**
At the moment, uptime or periodic scanning duration in the Web GUI is
hard-coded to use English shorthand names for time-related data. This
commit allows for translating them into other languages, therefore
making the duration be displayed using the user's local language.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### Screenshots

image
image

### CODE REVIEW

**Comment by tomasz1986** [comment]
This works, but I'm aware that using such short strings for translation may be problematic when shown in Transifex without any context. I've been thinking about using a similar convention to the existing `theme-name-*` strings, but in that case, the names are taken from directly the directory structure, while here this isn't the case. Basically, I'm not sure what would be the best method to use strings like `time-d`, `time-h`, etc. and still make all of this work regarding the Transifex translation.

**Comment by acolomb** [comment]
How about something like `abbrev-hour`, `abbrev-minute` etc?

**Comment by AudriusButkevicius** [comment]
The stuff you pass to .translate are technically keys, so we can just make the keys resolve to d/m/h in the english translation.

**Comment by AudriusButkevicius** [comment]
However, this would be a first and potentially confusing.

**Comment by imsodin** [comment]
While I like not pulling in unnecessary dependencies, handling time and its localization is hardly something we should do ourselves. That's both a universal and not at all trivial problem enough that it is highly reusable. There's moment.js and humanizeduration.js libraries both doing this (localized human friendly times/durations).

**Comment by greatroar** [comment]
moment.js is already checked in. It has a pretty nifty method to format and localize durations, if loss of precision is acceptable:

```
> moment.locale('it');
> moment.duration(10, 'seconds').humanize();
'alcuni secondi'
> moment.duration(100, 'seconds').humanize();
'2 minuti'
> moment.duration(1000, 'seconds').humanize();
'17 minuti'
```

**Comment by tomasz1986** [comment]
> moment.js is already checked in.

It is, but without localisation for some reason 😉. I was going to try to update it to the newest version first, adding the language files in the process, and then give this a shot.

**Comment by tomasz1986** [comment]
I have now done quite a lot of research and testing, and emulating what we've got now (i.e. `20d 5h 10m`, etc.) doesn't seem so easy at all. Moment.js is incapable of using abbreviated time strings, and using `.humanize()` is a no-go for me, because 1) we need to display precise values, e.g. in rescan interval, and 2) it wrongly approximates lower values to higher ones (e.g. "55 minutes" becomes "1 hour"), and 3) the strings quickly get too long to fit in the GUI.

I have also tested https://github.com/EvanHahn/HumanizeDuration.js, which, in contrary to Moment.js, is capable of displaying precise duration, but it also has got no support for abbreviated multilanguage time strings. It does offer a simple way to add them manually, with an example provided in the readme, but everything needs to be done for each language by hand, which is no different from adding translations like the current iteration of this PR already does.

However, I have also found https://github.com/catamphetamine/javascript-time-ago, which does support a so called `mini` format, which seems to do exactly what we want. Unfortunately, its multilanguage support is much weaker than the two previous libraries. For one, it doesn't support many languages that Syncthing is offered in (e.g. Greek, Polish, Japanese). Still, I'm going to give this one a try later on, as in the worst case it should still fall back to English, meaning no difference from the current situation. The project seems quite active, so there is hope that more languages will be added in the future. The recent commit history filled with commits named `.` is kind of a joke though.

I have also tried using native JS with `RelativeTimeFormat`, but this one seems to only be capable of displaying strings like `x minutes ago` without any conversion, which ends up with things like "555 minutes ago", and so on. Being native, it doesn't require any 3rd party multilanguage support, but without the conversion, it doesn't seem very useful here.

**Comment by calmh** [comment]
This is a worthy change and stalled by perhaps unnecessary perfectionism... How about accepting an approximate value as returned by something existing like moment.js `.humanize` and offering the precise timestamp in a tooltip?

**Comment by tomasz1986** [comment]
> How about accepting an approximate value as returned by something existing like moment.js `.humanize` and offering the precise timestamp in a tooltip?

It's an interesting idea, but as a fan of precise time (e.g. hate when a message/email from just a few hours ago is marked "yesterday", etc.), I'd personally prefer to stay with the current English-only implementation :sweat_smile:.

At the moment, https://github.com/catamphetamine/javascript-time-ago seems to still be the only possible solution out of what I've been able to find, yet its limited multilanguage support and ridiculous commit history are problematic.

The multilanguage support is actually a common problem though, because I don't think there exists any library that supports the same languages as Syncthing does, with the exception of the native JS approach, which is however extremely limited and doesn't seem really usable yet.

**Comment by st-review** [comment]
:robot: beep boop

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

To permanently exempt this PR from bot nagging, add the `slow-pr` label.

**Comment by tomasz1986** [comment]
Can I ask to re-open this one (and possibly add a `slow-pr` label)? I'm going to look into this again in the near future 🙂. The issue itself is still present with the shorthand time being English only.

**Comment by acolomb** [comment]
Alternatively, just rebase your branch and open a new PR :-)

**Comment by tomasz1986** [comment]
Closing as superseded by https://github.com/syncthing/syncthing/pull/9552.

**Pull request closed without merging**
