### PR TITLE
Auto accept folders default value #6519

### PR DESCRIPTION
**Pull request by MikolajTwarog**
I added new checkbox in advanced options, that changes the default value, that "Auto accept folders" takes when a new device is introduced.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I am not sure this is a good way forward for this. 

We probably want defaults for devices and defaults for folders, as this options struct will explode from random stuff.

**Comment by MikolajTwarog** [comment]
You don't want this feature at all or do you want some other implementation?

**Comment by AudriusButkevicius** [comment]
Personally, I don't want it at all, but @calmh suggested it's a sensible continuation.

If we do do this, then I definately don't feel like device defaults should live in options, as that's already a massive struct begging to be split up.

**Comment by MikolajTwarog** [comment]
So you want two new tabs in options, where you can set all the default values for devices and folders?

**Comment by imsodin** [comment]
That seems reasonable to me. In config it can literally be a `FolderConfiguration` object, in the UI I'd reuse the folder edit dialogue as far as it makes sense. The main point is that it should also not have the advanced options that are omitted in the folder edit dialogue.

**Comment by MikolajTwarog** [comment]
I can work on that.

**Comment by AudriusButkevicius** [comment]
We probably want a new section in the root config called defaults, which then have one of each, yet I am not sure reusing the same structs will cut it, as there is no way to say there is no default I guess.

**Comment by imsodin** [comment]
Do we need "no default"? I'd say there's always a "default default". Parts of that currently exists in the UI code and other parts as annotations on the go structs.

**Comment by MikolajTwarog** [comment]
I added the structs. Is this ok so far?

**Comment by AudriusButkevicius** [comment]
Did you try reusing the device/folder structs, or does that not make much sense?

**Comment by MikolajTwarog** [comment]
I think that they have too much stuff, that we don't want defaults for, like ID or label.

**Comment by AudriusButkevicius** [comment]
Sounds fair.
In that case, I'd atleast try to populate the defaults from a default folder config using reflection, what I mean is:

````
from := FolderConfiguration{}
util.SetDefaults(&from)
to := FolderConfigurationDefaults{}
util.CopyMatchingFields(&from, &to)
```
So that we don't need to maintain defaults in two places, as it's bound to go out of sync if not done programatically.

**Comment by MikolajTwarog** [comment]
Should the defaults tab be in advanced or settings?

**Comment by AudriusButkevicius** [comment]
Probably advanced, if at all. People who care about this can probably go tweak the xml.

**Comment by imsodin** [comment]
> Should the defaults tab be in advanced or settings?

Regardless of how it's done in the end (I tend to agree with Audrius), as a first step I would not do anything in the web UI and focus on getting the go/config side of things working. The advanced settings part is generated automatically anyway, which gives you the most basic controls in UI without effort.

**Comment by MikolajTwarog** [comment]
Is there anything else needed?

**Comment by MikolajTwarog** [comment]
I don't understand why the TestNewSaveLoad test in config doesn't work.

**Comment by AudriusButkevicius** [comment]
There is a function that we use that initializes empty slices and maps, I suspect you not applying that function on the config after loading.

**Comment by AudriusButkevicius** [comment]
Check `Configuration.clean()`, namely:
```
if cfg.Folders[i].Versioning.Params == nil {
	cfg.Folders[i].Versioning.Params = map[string]string{}
}
```

**Comment by MikolajTwarog** [comment]
Thanks, it was the problem.

**Comment by MikolajTwarog** [comment]
I also don't know why the model test doesn't work on Build (Linux) and Coverage (Syncthing).

**Comment by imsodin** [comment]
Currently the problem of duplicated defaults still applies (https://github.com/syncthing/syncthing/pull/6612#issuecomment-625918837). Wouldn't a simple solution without reflect be to move the user configurable members to the default type, and embed that into the exiting one. Something like

```
type FolderConfiguration struct {
	DefaultFolderConfiguration

	ID                      string                      `xml:"id,attr" json:"id"`
	Label                   string                      `xml:"label,attr" json:"label" restart:"false"`
[...]
}
type DefaultFolderConfiguration struct {
	RescanIntervalS int                     `xml:"rescanIntervalS,attr" json:"rescanIntervalS" default:"3600"`
	Type            FolderType              `xml:"type,attr" json:"type"`
	Versioning      VersioningConfiguration `xml:"versioning" json:"versioning"`
	Order           PullOrder               `xml:"order" json:"order"`
	MinDiskFree     Size                    `xml:"minDiskFree" json:"minDiskFree" default:"1%"`
}
```

**Comment by AudriusButkevicius** [comment]
Sounds good.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
