### PR TITLE
lib/sync: Make some tests not depend on real clock

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

This mocks out the clock on the sync tests that have been failing on the Solaris builder lately. Lets see if it works better.

### CODE REVIEW

**Comment by calmh** [comment]
Different failure, I guess the Solaris builder is just a bit slow at the moment;

```
--- FAIL: TestROScanRecovery (2.67s)
	model_test.go:1077: Timed out waiting for status: folder marker missing, current status: folder path missing
```

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 2ff08e6c84318cd1470b2e779f4b890a13f4c339. Thanks, @calmh!

**Pull request closed without merging**
