### PR TITLE
gui: Disable device removal when we know it will be reintroduced.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
and a cross-out cursor that's not visible.

### CODE REVIEW

**Comment by calmh** [comment]
We don't know that the introducer is still an introducer, or even still present, or that the device is still on the introducer though?

**Comment by calmh** [comment]
Maybe just a note that "was introduced by xxx, may be reintroduced again" instead of trying to be sure?

**Comment by AudriusButkevicius** [comment]
We do know the first two things, as we try to resolve the name which implies he's still there.

**Comment by AudriusButkevicius** [comment]
Also with the new removal logic we know tye device is still there as its not removed by the introducer removing it (or we haven't connected)

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it at your earliest convenience please

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@calmh: Patiently waited 30m0s for the build status to turn green, but enough is enough.

**Comment by calmh** [comment]
@AudriusButkevicius I'll merge this if you help out by fixing or otherwise beating into submissing the fucking Jenkins

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
So I got it to actually build stuff when you ask it to.
Got there by upgrading the plugin to some new version, getting shit totally broken, downgrading back to old version +1 which had the bug fixed, and having to reconfigure most of the jobs as config are not backwards compatible.

Now I can't get it to actually update build status, yet my test PR shows that it knows how to....

https://github.com/syncthing/syncthing/pull/3781
```
Sunshine — Hey this is garbage
```

Ideas?

**Comment by AudriusButkevicius** [comment]
Btw as part of the plugin upgrade had to upgrade Github API plugin, which seems to have failed with random `developer api v3` error (I suspect due to some other plugin trying to use an older API)

I now also fixed jenkins upgrade URL, so we can go for the nuclear option, upgrade everything to latest, and pray.

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it

Skip-check: pr-build-windows

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/3762/head:pr-3762
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   7157917..2fd1dca  master     -> orig/master
   e3cf718..2fd1dca  master     -> origin/master
$ git reset --hard
HEAD is now at e3cf718 lib/ignore: Add central check for internal files, used in scanning, pulling and requests
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git reset --hard orig/master
HEAD is now at 2fd1dca lib/connections: Fix odd logging, forgot to call function
$ git clean -fxd
$ git merge --squash --no-commit pr-3762
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
Commit message subject:

    Skip-check: pr-build-windows

doesn't look like "tag: One sentence description". Specifically, it doesn't
match this pattern:

    ^[\w/,\. ]+: \w

```

**Comment by calmh** [comment]
Right right

**Comment by calmh** [comment]
@st-review merge it

gui: Disable device removal when we know it will be reintroduced

Skip-check: pr-build-windows

**Comment by st-review** [comment]
:ok_hand: Merged as 99922feb3b1bf1afe7a99eab0af082580208077b. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
