### PR TITLE
lib/connections: Use own KCP fork, move listener setup earlier (ref #4446)

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 0d3016635744d79fc9a94bca8aff25e42a7718d8. Thanks, @AudriusButkevicius!

**Comment by AudriusButkevicius** [comment]
@calmh pls take this for a spin and see if you can still repro the issue.

**Comment by calmh** [comment]
I think it mostly works. It takes a while for the connection to time out on the non-restarted side, and in the meantime it drops new attempts as "already connected" which looks like "EOF" to the other side. After about five minutes it connected.

**Comment by AudriusButkevicius** [comment]
Did you pull the extra commit I pushed on master? If not then you are just failing to repro.

**Comment by calmh** [comment]
The blacklist thing? Nope, pulled just before it. So apparently it's not 100% either way. 🤷‍♂️

**Comment by AudriusButkevicius** [comment]
Its definately not 100%, but tye blacklist prevents the symptoms when I see it.

**Comment by AudriusButkevicius** [comment]
Can you with the blacklist and see if it still happens?

**Comment by calmh** [comment]
Not yet, but I think the NAT thing and this is the cause (or, another cause) for reconnects not happening in a timely fashion:

screen shot 2017-10-22 at 23 55 48

Trying and timing out each of those would take a while probably

**Comment by AudriusButkevicius** [comment]
I think we are lacking parallel dials? 😆

**Comment by AudriusButkevicius** [comment]
Technically, with my change, even symmetric NAT shouldn't provide so many addresses.

**Comment by calmh** [comment]
Yes I think this is fixed

**Pull request closed without merging**
