### PR TITLE
Fix for #2026 remove O_EXCL which prevents stale temporary file from …

### PR DESCRIPTION
**Pull request by larroy**
…being used and results in "Out

of Sync"

### CODE REVIEW

**Comment by calmh** [comment]
Hmm, no. There isn't supposed to be a temp file, and the O_EXCL ensures that this assumption is correct. If it's not, there's a bug somewhere else. Specifically, in this case, the temp file should have been [removed here](https://github.com/syncthing/syncthing/blob/master/lib/model/rwfolder.go#L1018) if it exists but has nothing we want to reuse, and if there was something to reuse we should have opened it without O_EXCL. Possibly the issue could be that we get an error [here](https://github.com/syncthing/syncthing/blob/master/lib/model/rwfolder.go#L992) but it's something other than the file not existing - that assumption seems a bit fragile...

**Comment by larroy** [comment]
In my case the (tempporary) file was empty, and syncthing couldn't make any progress. Still what happens if you kill syncthing and the file is left lying there in the filesystem? Then this bug will be triggered.  I'm not sure how the empty file came to be in the first place. But I was syncing from phone to computer and then I walked out of wifi range.

**Comment by calmh** [comment]
> Still what happens if you kill syncthing and the file is left lying there in the filesystem? Then this bug will be triggered.

No, that's the intended use case. Then we hash the file and reuse whatever we might have in it, and no O_EXCL will be set.

I'll double check if there's something weird here with empty temp files specifically...

**Comment by calmh** [comment]
Works fine for me with an empty temporary file in place when pulling starts... Can you reproduce this reliably?

**Comment by larroy** [comment]
I can't reproduce by manually creating a ".syncthing.filename.tmp"

**Comment by calmh** [comment]
I tried that, and it worked for me... Anything other special? I can see os.Remove would fail on windows if the file is read only - but we don't set temp files to read only.

**Comment by larroy** [comment]
I get your point, and sorry I can't reproduce the bug. Tried disconnecting the device on the middle of a sync. I'm not sure how I ended with several empty tempfiles. I was syncthing from the android device to the pc...

shall we close?

**Comment by AudriusButkevicius** [comment]
We can add error handling code at the point we try to check temp file content and remove the file if its not IsNotExists error.

**Comment by larroy** [comment]
Hi
I was hit by this bug again. What I did was:

1- I had a share fully syncrhonized between desktop phone and nas
2- I moved the folder to a nother location in my desktop
3- removed the share in the desktop
4- recreated the share in the desktop with the same ID and different path
5- got a huge amount of these errors on the desktop console

[SBWXE] 14:10:04 INFO: Update for unexpected folder ID "synced" sent from device "TUIQLCU-OIOFVRX-G75OMY7-KF2JWPT-UZPCWNE-WJEOY32-3QWVRVR-MFYLPQP"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.

[SBWXE] 14:11:43 INFO: Completed initial scan (rw) of folder oneplus
[SBWXE] 14:11:43 INFO: Puller (folder "oneplus", file "music/asot/Armin Van Buuren - A State Of Trance 700 (2015-01-29) (Inspiron)/20 W&W - Invasion.mp3"): dst create: open /home/piotr/storage/oneplus/music/asot/Armin Van Buuren - A State Of Trance 700 (2015-01-29) (Inspiron)/.syncthing.20 W&W - Invasion.mp3.tmp: file exists

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/commit/42acf0ed600b4619be75c7769576a11b5b9152f8

**Comment by calmh** [comment]
Doh

**Comment by larroy** [comment]
nice!

**Comment by calmh** [comment]
I forgot to cherry-pick that into the v0.11 branch, so it's not in the .21 release today unfortunately. Sorry. Next one.

**Pull request closed without merging**
