### PR TITLE
lib/model: Fix rescan detection (fixes #4505, fixes #4506)

### LINKED ISSUE #4505: Symlink/file replacement doesn't work properly
```
jb@unu:~/s/g/s/s/test $ go test -v -tags integration -run Symlinks\$
=== RUN   TestSymlinks
2017/11/13 00:26:11 Cleaning...
2017/11/13 00:26:11 Generating files...
2017/11/13 00:26:11 Starting instance 1...
2017/11/13 00:26:13 Starting instance 2...
2017/11/13 00:26:16 Syncing...
2017/11/13 00:26:18 Comparing directories...
2017/11/13 00:26:18 Making some changes...
2017/11/13 00:26:18 Syncing...
2017/11/13 00:26:18 Comparing directories...
--- FAIL: TestSymlinks (7.19s)
	symlink_test.go:260: Mismatch; integration.fileInfo{name:".syncthing.repFileLink.tmp", mode:0x1a4, mod:1510529178000000000, hash:[16]uint8{0xd4, 0x1d, 0x8c, 0xd9, 0x8f, 0x0, 0xb2, 0x4, 0xe9, 0x80, 0x9, 0x98, 0xec, 0xf8, 0x42, 0x7e}, size:0} (s2) != integration.fileInfo{name:"0", mode:0x800001ed, mod:0, hash:[16]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, size:0} (s1)
FAIL
exit status 1
FAIL	github.com/syncthing/syncthing/test	7.251s
```

```
jb@unu:~/s/g/s/s/test $ ls -la s1 s2
s1:
total 32
...
drwxr-xr-x   2 jb  staff    68 Nov 13 00:26 repDirLink/
-rw-r--r--   1 jb  staff     0 Nov 13 00:26 repFileLink

s2:
total 40
...
-rw-r--r--   1 jb  staff     0 Nov 13 00:26 .syncthing.repFileLink.tmp
...
drwxr-xr-x   2 jb  staff    68 Nov 13 00:26 repDirLink/
lrwxr-xr-x   1 jb  staff    14 Nov 13 00:26 repFileLink@ -> does/not/exist
jb@unu:~/s/g/s/s/test $ 
```

```
[MRIW7] 00:26:18 INFO: Puller (folder "default", file "repFileLink"): finisher: file modified but not rescanned; will try again later
[MRIW7] 00:26:18 INFO: Folder default isn't making progress. Pausing puller for 1m0s.
```

### LINKED ISSUE #4506: File/dir replacement doesn't work properly
```
$ go test -v -tags integration -run TestFileTypeChange\$
=== RUN   TestFileTypeChange
2017/11/13 01:01:15 Cleaning...
2017/11/13 01:01:15 Generating files...
2017/11/13 01:01:15 Starting instance 1...
2017/11/13 01:01:17 Starting instance 2...
2017/11/13 01:01:19 Syncing...
2017/11/13 01:01:21 Comparing directories...
2017/11/13 01:01:21 Making some changes...
2017/11/13 01:01:21 Syncing...
2017/11/13 01:01:22 Comparing directories...
--- FAIL: TestFileTypeChange (7.15s)
	filetype_test.go:178: Mismatch; integration.fileInfo{name:".syncthing.dirToReplace.tmp", mode:0x1a4, mod:1510531282000000000, hash:[16]uint8{0xd4, 0x1d, 0x8c, 0xd9, 0x8f, 0x0, 0xb2, 0x4, 0xe9, 0x80, 0x9, 0x98, 0xec, 0xf8, 0x42, 0x7e}, size:0} (s2) != integration.fileInfo{name:"0", mode:0x800001ed, mod:0, hash:[16]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, size:0} (s1)
FAIL
exit status 1
FAIL	github.com/syncthing/syncthing/test	7.217s
```

```
jb@unu:~/s/g/s/s/test $ ls -la s1 s2
s1:
total 0
...
-rw-r--r--   1 jb  staff     0 Nov 13 01:01 dirToReplace
drwxr-xr-x  11 jb  staff   374 Nov 13 01:01 e/
-rw-r--r--   1 jb  staff     0 Nov 13 01:01 emptyDirToReplace
drwxr-xr-x   5 jb  staff   170 Nov 13 01:01 f/
drwxr-xr-x   2 jb  staff    68 Nov 13 01:01 fileToReplace/

s2:
total 0
...
-rw-r--r--   1 jb  staff     0 Nov 13 01:01 .syncthing.dirToReplace.tmp
-rw-r--r--   1 jb  staff     0 Nov 13 01:01 .syncthing.emptyDirToReplace.tmp
...
drwxr-xr-x   2 jb  staff    68 Nov 13 01:01 dirToReplace/
drwxr-xr-x  11 jb  staff   374 Nov 13 01:01 e/
drwxr-xr-x   2 jb  staff    68 Nov 13 01:01 emptyDirToReplace/
drwxr-xr-x   5 jb  staff   170 Nov 13 01:01 f/
drwxr-xr-x   2 jb  staff    68 Nov 13 01:01 fileToReplace/
```

```
[MRIW7] 01:01:22 INFO: Puller (folder "default", file "dirToReplace"): finisher: file modified but not rescanned; will try again later
[MRIW7] 01:01:22 INFO: Puller (folder "default", file "emptyDirToReplace"): finisher: file modified but not rescanned; will try again later
[MRIW7] 01:01:22 INFO: Folder default isn't making progress. Pausing puller for 1m0s.
```

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Diff is large due to comment reformatting and indentation but all it does is wrap the file mtime/size/permissions check in an "if stat.IsRegular()".

### Testing

The corresponding integration tests now pass.

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 2b65e1062ecd002ae79b0cd19c2ed94bd3b817bf. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
This now looses ability to detect rescans when a file gets replaced with a dir midscan?
I think we should check oldStat.regular == newStat.regular, etc?

**Comment by imsodin** [comment]
I don't understand this change either: What is compared there is the file in the db with the currently existing file - this should work regardless whether it is a symlink/dir or a regular file, shouldn't it?

Both before and after this change the pulling related loging concerning one file has a weird error from the hasher before it even begins to pull:

```
[MRIW7] 2017/11/13 10:16:10.141322 blockqueue.go:22: DEBUG: open: open /media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/test/s2/.syncthing.repFileLink.tmp: no such file or directory
[MRIW7] 2017/11/13 10:16:10.141358 rwfolder.go:1104: DEBUG: sendReceiveFolder/default@0xc4200b0480 need file repFileLink; copy 1, reused 0
[MRIW7] 2017/11/13 10:16:10.141470 progressemitter.go:211: DEBUG: progress emitter: registering default repFileLink
[MRIW7] 2017/11/13 10:16:10.141491 rwfolder.go:1187: DEBUG: not weak hashing repFileLink. file did not contain any weak hashes
[MRIW7] 2017/11/13 10:16:10.141559 sharedpullerstate.go:239: DEBUG: sharedPullerState default repFileLink copyNeeded -> 0
[MRIW7] 2017/11/13 10:16:10.158280 rwfolder.go:1474: DEBUG: sendReceiveFolder/default@0xc4200b0480 closing repFileLink
[MRIW7] 2017/11/13 10:16:10.158537 progressemitter.go:225: DEBUG: progress emitter: deregistering default repFileLink
```

And when adding some debug statements to the code before PR like this:
```
@@ -1394,9 +1394,11 @@ func (f *sendReceiveFolder) performFinish(state *sharedPullerState) error {
 		switch {
 		// The file reappeared from nowhere, or mtime/size has changed, fallthrough -> rescan.
 		case !state.hasCurFile || !stat.ModTime().Equal(state.curFile.ModTime()) || stat.Size() != state.curFile.Size:
+			l.Debugln("upper: hascurfile:", state.hasCurFile, "modtime:", state.curFile.ModTime(), stat.ModTime(), "size:", state.curFile.Size, stat.Size())
 			fallthrough
 		// Permissions have changed, means the file has changed, rescan.
 		case !f.ignorePermissions(state.curFile) && state.curFile.HasPermissionBits() && !scanner.PermsEqual(state.curFile.Permissions, curMode):
+			l.Debugln("file modified perm", state.curFile.Permissions, curMode)
 			l.Debugln("file modified but not rescanned; not finishing:", state.curFile.Name)
 			// Scan() is synchronous (i.e. blocks until the scan is
 			// completed and returns an error), but a scan can't happen
```
this is the output
```
[MRIW7] 2017/11/13 10:37:59.294570 rwfolder.go:1397: DEBUG: upper: hascurfile: true modtime: 1970-01-01 01:00:00 +0100 CET 2017-11-13 10:37:55.438167537 +0100 CET size: 0 14
[MRIW7] 2017/11/13 10:37:59.294588 rwfolder.go:1401: DEBUG: file modified perm 0 134218239
```
which suggests that there is no current file in the db when replacing the link with the file, but there should be. To me it seems like there is something more broken in either the integration tests or Syncthing - I just haven't figured out yet what is going on really (or I am off the track entirely).

**Comment by calmh** [comment]
This restores the previous behaviour. The check as written can never work for symlinks or directories because we compare the size and mtime, neither of which makes sense for directories or symlinks.

**Comment by imsodin** [comment]
Ah, I was indeed missing the obvious.
We do sync permissions on dirs/symlinks though, don't we?

**Comment by calmh** [comment]
Yeah that's valid. But it's a nicer bug than not handling change between file and directory. :)

**Comment by AudriusButkevicius** [comment]
But still, if A was a file when we started pulling, and becomes a directory when we finish pulling, we'd blindly replace the directory with a file here without rescanning?

**Pull request closed without merging**
