### PR TITLE
Don't chmod in Atomic on android (fixes  #2472)

### LINKED ISSUE #2472: Cannot write .stignore on Android devices
Syncthing cannot write/update .stignore on Android due to failed chmod operations.
In mode.go we use CreateAtomic that relies on chmod operations which are not permitted on Android. See the following error:

```
[BH4HG] 03:33:26 WARNING: Saving .stignore: chmod /storage/1AF9-2A10/DCIM/.syncthing.tmp.190076736: operation not permitted
```

### PR DESCRIPTION
**Pull request by kluppy**
I haven't touched Go before so though this would be a simple fix.
Turns out I am having trouble getting it to compile and run on android so I thought Zillode  or Nutomic could check if I made a ridiculous mistake.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
@Zillode / @Nutomic we compile with GOOS=android nowadays, so this would match? On x86 and arm?

**Comment by Zillode** [comment]
Correct, arm, x86 and amd64 are compiled with GOOS=android

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
Thanks!

**Pull request merged**
