### PR TITLE
lib/logger: Add date marker

### PR DESCRIPTION
**Pull request by calmh**
With our default time-only log format it's annoying to read logs spanning more than a day because the timestamps become ambiguous, especially when there isn't much output to begin with. This adds a `Day changed to 2022-04-13` type log entry at local midnight.

### CODE REVIEW

**Comment by tomasz1986** [comment]
Just a suggestion, but wouldn't it be preferable to simply change the default format to add both date and time (i.e. `-logflags=3`) to the log? This is what I've been using since forever, as without it I found the logs basically useless for any serious inspection, and doing so would also make it consistent with the logs shown in the Web GUI, which display both time and date by default.

**Comment by AudriusButkevicius** [comment]
Agreed, I prefer having a date over having some obscure line somewhere burried.

**Comment by acolomb** [comment]
Shouldn't this be mentioned in the release notes?  It's missing from -rc.1.

**Comment by calmh** [comment]
This is not in the RC. I added an issue for the change that did happen, though. :+1:

**Pull request closed without merging**
