### PR TITLE
Ship "syncthingw" Windows GUI binary (ref #8046, ref #8248)

### PR DESCRIPTION
**Pull request by calmh**
Add a Windows console-less (GUI) binary that starts Syncthing.

(Annoying build changes in progress.)

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I'm fairly certain you can be console-less, and allocate to a console afterwards?

I guess if you just run it from cmd, it would allocate a new window, but is that a big deal?

**Comment by calmh** [comment]
@AudriusButkevicius I dare you to prove it

**Comment by AudriusButkevicius** [comment]
Sure, I'll give it a go.

**Comment by AudriusButkevicius** [comment]
It's not obvious to less tech savy users what to launch.
Launching w by accident and getting literally nothing is not very "seamless".

On the other hand, I can't find much resources about the current problem in order to fix it, so 🤷

**Comment by Bill-Stewart** [comment]
> It's not obvious to less tech savy users what to launch.

This is a user education issue rather than a technical issue (in my opinion). This nuance needs to be documented, naturally. You could also put some preliminary text in the console that says something such as "On the Windows platform, you can start Syncthing using syncthingw to launch Syncthing in a hidden window."

> I can't find much resources about the current problem in order to fix it

This is unsurprising, because the "solutions" tend to be complex and (in my opinion) probably not worth the effort to "fix" this one use case.

**Comment by st-review** [comment]
:robot: beep boop

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

To permanently exempt this PR from bot nagging, add the `slow-pr` label.

**Comment by calmh** [comment]
Imma offer this one for another round of consideration

**Comment by st-review** [comment]
:robot: beep boop

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

To permanently exempt this PR from bot nagging, add the `slow-pr` label.

**Pull request closed without merging**
