### PR TITLE
style: gofumpt all the things

### PR DESCRIPTION
**Pull request by calmh**
Literally `gofumpt -w .` from the top level dir. Guaranteed to be minor style changes only and nothing else.

@imsodin per request?

### CODE REVIEW

**Review by acolomb — APPROVED** [review]
Yes, please.

**Comment by calmh** [comment]
Okidokie then

**Comment by calmh** [comment]
Overriding policy-bot because `style:` is not one of the approved prefixes, but maybe it should be (or maybe it shouldn't and we shouldn't do more of these...)

**Comment by acolomb** [comment]
> Overriding policy-bot because `style:` is not one of the approved prefixes

The PR content is about code style, but the task itself falls under the "chore" category alright.

**Pull request merged**
