### PR TITLE
Only build ARMv5 (fixes #1218)

### LINKED ISSUE #1218: Auto-update chose wrong architecture
My NAS instance with "ARMv6-compatible processor rev 5 (v6l)" would not come up anymore, because the ARMv5 instance of syncthing apparently auto-upgraded to the ARMv6 version, which does not work on that device because it has no hardware floating point. That was from 0.10.14. Downloaded manually and works now, but I fear next upgrade could break it again.

### PR DESCRIPTION
**Pull request by calmh**
With this change, the build system only builds one ARM variant - ARMv5.
We call the build architecture simply "arm", as this is what
runtime.GOARCH says.

We'll need to publish the same package as syncthing-linux-armv[567]-* as well for a while, to let upgrades from older versions work.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I guess it's enough to publish a single armv{5..7} which then starts using the new convention?
Also, I know there is probably no difference, but I somehow feel sadder that we're not compiling for specific arms.

**Comment by calmh** [comment]
I was thinking there may be manual-only upgraders that may not see the new build for a few weeks, but yeah in principle only long enough for those we care about to do it automatically or click the button. :)

**Comment by AudriusButkevicius** [comment]
But either case, a single release should be enough, as they would upgrade from
armX to armX last
and then armX last starts looking for arm rather than armX for next upgrade?

**Comment by calmh** [comment]
Nope, upgrade code first finds the latest release, then the correct binary within it. No such binary => failure.

**Comment by AudriusButkevicius** [comment]
Oh, I thought it was iterating over the releases as well.
Never mind then.

**Pull request merged**
