### PR TITLE
lib/watchaggregator: Relax test timing requirement for the benefit of macos

### PR DESCRIPTION
**Pull request by imsodin**
Apparently nothing is save.

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review merge

**Comment by st-review** [comment]
@imsodin: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@imsodin: Build status is `failure` -- refusing to merge.

**Comment by imsodin** [comment]
The *irony*: A different flaky test failure on a PR fixing a flaky test...

**Comment by imsodin** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as b999b5804956b7e5469d87d499c881715495d1fc. Thanks, @imsodin!

**Pull request closed without merging**
