### PR TITLE
gui: Add uncamel filter

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
blah

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review lgtm too

**Comment by st-review** [comment]
:ok_hand: Merged as 889814a1af3eb69fe2f1f254365185890c3e0c2a. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
