### PR TITLE
Added colored status indicator for narrow screens. (Fixes #1084)

### LINKED ISSUE #1084: v0.10.9 Status disappears when the window gets smaller
unbenann2t
unbenann3t
unbenannt

With the "Fruit Salad GUI" one still was able to see the current status. Now it is not clear any more.

### PR DESCRIPTION
**Pull request by bigbear2nd**
- Added colored status indicator narrow screens.
- Added section headers

### CODE REVIEW

**Comment by calmh** [comment]
Almost! :) It seems to not work so well with the sync percentage;

screen shot 2015-01-08 at 14 33 14

screen shot 2015-01-08 at 14 33 00

**Comment by bigbear2nd** [comment]
@calmh: Oh, i missed that. Thank you for testing. 
I hope the idea of showing the percentage instead of a blue square is accepted. Otherwise there is no difference between syncing and scanning.

I will update just now.

**Comment by bigbear2nd** [comment]
unbenannt2
unbenannt

**Comment by AudriusButkevicius** [comment]
Can we have a space between the word and the bracket? I am a bit OCD but it just looks odd.

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by AudriusButkevicius** [comment]
LGTM

**Comment by calmh** [comment]
:+1 Thanks

**Pull request merged**
