### PR TITLE
lib/model: Discard download progress upon receiving an index update (fixes #2993)

### LINKED ISSUE #2993: [v0.13-beta] remote completion > 100
the folder is actually 100% in sync (checked in remote gui)
```
curl "127.0.0.1:8384/rest/db/completion?device=AGR6NY2...&folder=go-src"
{"completion":226.55250219942138}
```
Doing the same on other devices that share the same folders leads to similar results. Other folders on the same device, too

a folder that is not up to date shows the correct percentage (not sure if the value is exact but ~99% seems right)
```
curl "127.0.0.1:8384/rest/db/completion?device=AGR6NY2...&folder=bilder"
{"completion":99.64188929950149}
```

other devices show 100% completion on all folders as it should be

as soon as the folder "bilder" is synced completely all folders show 100% in `rest/db/completion`

### Version Information

Syncthing Version: v0.13.0-beta.3, 
OS Version: Linux (64 bit)

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
We still send updates for the same files we've removed.
Reason we need that mechanism is for files that have failed.

### CODE REVIEW

**Comment by calmh** [comment]
Sorry, I don't understand. What do you mean send updates for files we've removed, and why do we want to send a forget for every file we recieve info about?

**Comment by AudriusButkevicius** [comment]
So at the point we get an index update, it's likely that we got the update because the remote device has finished downloading something.

Yet the DownloadProgress messages get sent every 5 seconds, meaning that completion for that file is probably accounted twice (once from the index, once from the deviceDownloadState) until that Forget update arrives 5 seconds later.

**Comment by calmh** [comment]
@st-review merge this please

**Comment by st-review** [comment]
:ok_hand: Merged as 29fa05ae0580e9a707171af7f0b00de6b92a5be8. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
