### PR TITLE
vendor: Update kcp, removes closeConn (fixes #4343)

### LINKED ISSUE #4343: kcp: remove connClose from our fork
Not needed as its not a real connection.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
vendor: Update kcp, removes closeConn (fixes #4343)

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review retest

**Comment by st-review** [comment]
I'm sorry, @AudriusButkevicius. I'm afraid I don't know what you mean. I know how to `don't`, `lgtm`, `merge`, `prevent`, `rebuild`, `squash`, `stop`.

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest

**Comment by AudriusButkevicius** [comment]
some spurious mac blip.

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review rebuild

^ @audrius

**Comment by AudriusButkevicius** [comment]
```
Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.
```

**Comment by AudriusButkevicius** [comment]
@st-review rebuild

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by calmh** [comment]
Yeah I'm upgrading the OS and everything on the Mac build slave today so expect temporary weirdness and don't worry about it for the time being.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: There's already a merge pending for this PR.

**Comment by AudriusButkevicius** [comment]
Sure, so just fucking do it.

**Comment by st-review** [comment]
@AudriusButkevicius: Patiently waited 30m0s for the build status to turn green, but enough is enough.

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by calmh** [comment]
Wat

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/4344/head:pr-4344
From https://github.com/syncthing/syncthing
 * [new ref]           refs/pull/4344/head -> pr-4344
$ git fetch -f origin master:orig/master
From https://github.com/syncthing/syncthing
   55e0ac3e..9e6a1fdc  master     -> orig/master
   49bddfbe..9e6a1fdc  master     -> origin/master
$ git reset --hard
HEAD is now at 49bddfbe cmd/syncthing: Add test for truncate behavior of log file (ref #4255)
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git reset --hard orig/master
HEAD is now at 9e6a1fdc vendor: Update kcp, removes closeConn (fixes #4343)
$ git clean -fxd
$ git merge --squash --no-commit pr-4344
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

```

**Comment by calmh** [comment]
The review bot is drunk and had to go home and lie down for a while. 🤷‍♂️

**Pull request merged**
