### PR TITLE
Add language select menu in webgui (fixes #981)

### LINKED ISSUE #981: Option to change language
Currently Syncthing uses the browser locale settings to detect the correct language (see list at https://github.com/syncthing/syncthing/tree/master/gui/lang). As a workaround you can use https://127.0.0.1:8080/#?lang=fr to override. Please create option to change language from the web GUI for better usability.

### PR DESCRIPTION
**Pull request by ralder**
Issue https://github.com/syncthing/syncthing/issues/981

syn-lang

### CODE REVIEW

**Comment by calmh** [comment]
Neat!

**Comment by calmh** [comment]
Do you have a name for the AUTHORS and in-GUI credits?

**Comment by ralder** [comment]
no. and it's not necessarily for me

**Comment by uok** [comment]
Thanks for implementing this useful feature :+1: 
My personal preference is to have the language selection as a submenu of the settings icon (maybe modal window instead of dropdown?) because you only need it once

**Comment by calmh** [comment]
We need to call you something, for copyright purposes. A pseudonym is acceptable of course, per `CONTRIBUTING`.

**Comment by calmh** [comment]
Needs `(fixes #981)` at the end of commit subject.

**Comment by calmh** [comment]
@st-jenkins test this please

**Comment by calmh** [comment]
@uok I think this is OK as is for now, for a couple of reasons. It's neat to have it clearly visible if you for some reason end up in the wrong language, it simplifies testing of translations, our settings dialog sucks anyway, and I think it's really cool to have it change on the fly. :) It can be revisited in the future.

**Pull request merged**
