### PR TITLE
lib/util: Add secure random numbers source (fixes #3178)

### LINKED ISSUE #3178: Session IDs and CSRF tokens should be cryptographically secure
Currently these are generated using the non-cryptographic RNG, limiting their total entropy to at most 64 bits even though they look longer. That's wrong.

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

The math/rand package contains lots of convenient functions, for example to get an integer in a specified range without running into issues caused by just truncating a number from a different distribution and so on. But it's insecure, and we use if for things that benefit from being more secure like session IDs, CSRF tokens and API keys.

This implements a math/rand.Source that reads from crypto/rand.Reader, this bridging the gap between them. It also updates our RandomString to use the new source, thus giving us secure session IDs and CSRF tokens.

Some future work remains:

 - Fix API keys by making the generation in the UI use this code as well

 - Refactor out these things into an actual random package, and audit our use of randomness everywhere

I'll leave both of those for the future in order to not muddy the waters on this diff...

### Testing

Unit tested as well as I can think of.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 31b515619143e44eadd0b73689d3e5453dd30d36. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Merge failed:

```
$ git fetch -f origin refs/pull/3180/head:pr-3180
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   ebce5d0..31b5156  master     -> orig/master
$ git reset --hard
HEAD is now at 31b5156 lib/util: Add secure random numbers source (fixes #3178)
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 31b5156 lib/util: Add secure random numbers source (fixes #3178)
$ git clean -fxd
Skipping repository syncthing/syncthing
Skipping repository syncthing/syncthing-android
Skipping repository syncthing/docs
Skipping repository syncthing/discosrv
Skipping repository syncthing/syncthing-gtk
Skipping repository syncthing/syncthing-inotify
$ git merge --squash --no-commit pr-3180
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Merge failed:

```
$ git fetch -f origin refs/pull/3180/head:pr-3180
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at 31b5156 lib/util: Add secure random numbers source (fixes #3178)
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 31b5156 lib/util: Add secure random numbers source (fixes #3178)
$ git clean -fxd
Skipping repository syncthing/syncthing
Skipping repository syncthing/syncthing-android
Skipping repository syncthing/docs
Skipping repository syncthing/discosrv
Skipping repository syncthing/syncthing-gtk
Skipping repository syncthing/syncthing-inotify
$ git merge --squash --no-commit pr-3180
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Pull request closed without merging**
