### PR TITLE
lib/model: Release both locks when waiting for services to stop (fixes #5028)

### LINKED ISSUE #5028: RestartFolder deadlock
version commit id 238476bfcd6f052a6d4b77424f3d4429cd102272 

When the folder state is  pulling, if a folder restart occurs, for example, we modify the folder configuration, which will cause a deadlock.

### PR DESCRIPTION
**Pull request by imsodin**
### Purpose

Fixing #5028 as followup to #4982.

### Testing

None due to the racy nature of the issue.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
We should just have one mutex to not have this problem.

**Comment by xjtdy888** [comment]
I think this is not a simple problem of releasing two locks. Even if both pmut and fmut are released, pull will still cause blocking. In the case of pullerRoutine, RequestGlobal will return the time due to network status.
Also affects the handleFile blocking in ```copyChan <- cs```

**Comment by xjtdy888** [comment]
Yes. Release both locks is fixes deadlocking though. 
But restartFolder and CommitConfiguration is abnormal. This will also continue to interfere with subsequent config logic

**Comment by AudriusButkevicius** [comment]
What do you mean by abnormal, please be more specific as it's not obvious what the complaint is about.

**Comment by xjtdy888** [comment]
new stacks and log file, now not deadlocking, but tearDownFolderLocked always blocked
[EODBO.log](https://github.com/syncthing/syncthing/files/2130729/EODBO.log)
[goroutine.log](https://github.com/syncthing/syncthing/files/2130730/goroutine.log)

I'm not sure if I need to open a new isuse to discuss because the deadlock is fixed but new issues are introduced #4982 related

**Comment by AudriusButkevicius** [comment]
> tearDownFolderLocked always blocked

Define always, as in, it never returns or returns after the pull is done, or what?

**Comment by imsodin** [comment]
The logs do look fishy, as in the folder exited, but `StopAndWait` does not return. I am at a loss as to what's happening there.

```
1 @ 0x402f85a 0x403f850 0x443f44d 0x452325d 0x4523609 0x453c948 0x44241c1 0x44279d4 0x405ca61
#	0x443f44c	github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).RemoveAndWait+0x1bc	/usr/local/gopkg/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:654
#	0x452325c	github.com/syncthing/syncthing/lib/model.(*Model).tearDownFolderLocked+0xfc				/usr/local/gopkg/src/github.com/syncthing/syncthing/lib/model/model.go:350
#	0x4523608	github.com/syncthing/syncthing/lib/model.(*Model).RestartFolder+0xc8					/usr/local/gopkg/src/github.com/syncthing/syncthing/lib/model/model.go:379
#	0x453c947	github.com/syncthing/syncthing/lib/model.(*Model).CommitConfiguration+0x9e7				/usr/local/gopkg/src/github.com/syncthing/syncthing/lib/model/model.go:2605
#	0x44241c0	github.com/syncthing/syncthing/lib/config.(*Wrapper).notifyListener+0x140				/usr/local/gopkg/src/github.com/syncthing/syncthing/lib/config/wrapper.go:184
#	0x44279d3	github.com/syncthing/syncthing/lib/config.(*Wrapper).notifyListeners.func1+0x133			/usr/local/gopkg/src/github.com/syncthing/syncthing/lib/config/wrapper.go:175
``` 

but `folder.Stop()` is not running, i.e. it is not blocking on stopping the folder service. The only other folder service/token I am aware of is versioning, but that's not happening either. Generally there is not much happening in the model except tearing down that folder, just the progress emitter, deadlock detector and an idle folder.

There is something weird, but possible unrelated going on in your log:
```
[EODBO] 2018/06/24 19:45:49.534435 service.go:106: INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[EODBO] 2018/06/24 19:45:49.534458 relay_listen.go:65: INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[...]
[EODBO] 2018/06/24 19:45:59.817043 relay_listen.go:72: INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[EODBO] 2018/06/24 19:45:59.817125 service.go:106: INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.788528 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
```

**Comment by AudriusButkevicius** [comment]
I am not sure versioners have a proper shutdown sequence.

**Comment by AudriusButkevicius** [comment]
```
1 @ 0x402f85a 0x402f90e 0x400646b 0x4006205 0x444004b 0x405ca61
#	0x444004a	github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).removeService.func1.1+0x4a	/usr/local/gopkg/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:540
```

It seems it's only given 10s to shutdown.

```
	if spec.Timeout == 0 {
		s.timeout = time.Second * 10
	} else {
		s.timeout = spec.Timeout
	}
```

**Comment by imsodin** [comment]
The thing is the folder service did shutdown, even pretty fast:
```
[EODBO] 2018/06/24 19:46:48.644040 wrapper.go:183: DEBUG: model@0xc420190480 committing configuration
[...]
[EODBO] 2018/06/24 19:47:19.225879 folder.go:113: DEBUG: sendreceive/mmdc7-pdckl@0xc4200e1400 exiting
```

**Comment by AudriusButkevicius** [comment]
pretty fast is 30s, the default timeout is 10s

**Comment by AudriusButkevicius** [comment]
I've raised: https://github.com/thejerf/suture/issues/28

**Comment by AudriusButkevicius** [comment]
Essentially the shutdown time is currently proportional to the file size of what we are downloading, and all the other cruft that happens afterwards.

**Comment by AudriusButkevicius** [comment]
Regardless, this is good to go.

**Comment by imsodin** [comment]
o.O Where has main brain gone

Apart from the suture problem, it's still a valid issue that our puller does not abort in a timely manner and it's still RC material. I'll just drop abort points in all critical puller sections to achieve that.

**Pull request merged**
