### PR TITLE
gui: Disable rescan button while scanning (fixes #4977)

### LINKED ISSUE #4977: Feature request: Set Rescan button to Disabled instead of Hidden while scanning
A few times now, I've clicked the wrong button for a folder because it switched to/from the Scanning/Syncing state, hiding/showing the Rescan button and causing all the buttons to the left to shift over. It feels like a little bit of a dark pattern (though obviously not intentionally malicious). It makes sense to me to set the Disabled attribute on the button rather than hiding it entirely.

rescan-disabled

### PR DESCRIPTION
**Pull request by uok**
Disable (not hide) rescan button while scanning (fixes #4977)

### CODE REVIEW

**Comment by uok** [comment]
You clearly have a simpler solution in mind, but I don't know angular and I don't have time to learn it.

**Comment by imsodin** [comment]
Neither do I, but I copy&pasted angular snippets around a few times such that I remember some of it by now :)

```diff
-                   <button type="button" class="btn btn-sm btn-default" ng-click="rescanFolder(folder.id)" ng-show="['idle', 'stopped', 'unshared', 'outofsync'].indexOf(folderStatus(folder)) > -1">
+                   <button type="button" class="btn btn-sm btn-default" ng-click="rescanFolder(folder.id)" ng-disable="['idle', 'stopped', 'unshared', 'outofsync'].indexOf(folderStatus(folder)) < 0">
                     <span class="fas fa-sync"></span>&nbsp;<span translate>Rescan</span>
                   </button>
```

**Comment by imsodin** [comment]
I hope you tried it out? That was browser-written, untested code and I am prone to making stupid mistakes :)

Not having "paused" in there is correct, because a paused folder can't be scanned (it is scanned on resume).

**Comment by uok** [comment]
yes, it works

**Pull request merged**
