### PR TITLE
all: Add untrusted folders behind feature flag (ref #62)

### PR DESCRIPTION
**Pull request by imsodin**
This is a proposal for adding untrusted folders (encryption) support behind a feature flag, as discussed in https://forum.syncthing.net/t/encryption-merging-scary-changes-feature-flags/15703

The PR branch is an extension of https://github.com/syncthing/syncthing/pull/6727, with the feature flag added and the stdecryptfolder tool removed. That still had outstanding PR reviews and isn't necessary to have in a first iteration for testing this. Other than that I believe I addressed all the PR reviews from there and this should be ready to merge. Of course except for the feature flag code, which no one has reviewed yet.

The feature flag determines which web UI is served: The "traditional" one or the new one with controls for untrusted folders. A missing feature flag does not prevent "manual" config changes that introduce untrusted folders. My reasoning being is that it not being available by default in UI is enough of a barrier to prevent wide adoption. I can add a mechanism in the config layer to prevent untrusted folders without the flag if deemed necessary.

The feature flag itself is just a string, such that it can be reused if we ever want to use a feature flag again, instead of creating ad deprecating a bool every time.

The statics server is adjusted, such that if the feature flag is set, it looks for files in a "untrusted" subdir and serves those instead of the "normal" files if present. Those files are adjusted full copies of the originals, i.e. if other UI changes happen, those need to be kept in sync by hand. That's ugly, but I consider it manageable (thus volunteering xD ).

### CODE REVIEW

**Review by calmh — DISMISSED** [review]
I fixed some things. Merge?

**Comment by calmh** [comment]
@imsodin please sanity check my latest merge commit

**Comment by imsodin** [comment]
The noscript change isn't in the untrusted index.html - taking care of that.

**Comment by imsodin** [comment]
Now the "UI copies" should match again.

> I fixed some things. Merge?

Thanks, that plus fixes look good, Yes :)

**Review by calmh — APPROVED** [review]

**Comment by calmh** [comment]
TestIssue5063 is flaky and times out sometimes, reproducible with -count 100 for example, I didn't investigate yet if it's due to this change or just in general

**Comment by imsodin** [comment]
Seems related, tests time out for me on this branch but not on main. Plus I just realized the recent index sender changes duplicate some encryption code, need to sort that out (as in a merge-leftover). Looking into it.

**Comment by imsodin** [comment]
This PR made it worse, but the problem exists in v1.11.1 too: I messed up locking in the recent index changes. I'll file a separate PR on main and then take care of this PR.

**Review by calmh — APPROVED** [review]

**Pull request merged**
