### PR TITLE
Update Docs URL

### PR DESCRIPTION
**Pull request by elliot-labs**
Update the url to point ot the correct section of the docs.

### Purpose

Update the readme.md file to correctly link to the section it references. Previously brought the web browser to the top of the page. Now it brings the web browser to the right section.

### Testing

Click on the link or copy and paste it in the address bar to see that it is the correct link.

### Authorship

Elliot Huffman, ehuffman@elliot-labs.com, https://elliot-labs.com

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it

etc/linux-systemd: Update docs URL

Skip-check: authors

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/4145/head:pr-4145
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   0b854df..c262f48  master     -> orig/master
   d2699a2..c262f48  master     -> origin/master
$ git reset --hard
HEAD is now at d2699a2 gui: Display global changes timestamps in 24h format
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 7 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git reset --hard orig/master
HEAD is now at c262f48 Merge branch 'release'
$ git clean -fxd
$ git merge --squash --no-commit pr-4145
Updating c262f48..fbb0957
Fast-forward
Squash commit -- not updating HEAD
 etc/linux-systemd/README.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
$ git commit -F -
Commit message subject:

    etc/linux-systemd: Update docs URL

doesn't look like "tag: One sentence description". Specifically, it doesn't
match this pattern:

    ^[\w/,\. ]+: \w

```

**Comment by calmh** [comment]
Thanks!

**Comment by calmh** [comment]
Hah. That pattern is broken, will fix... But for the time being

**Comment by calmh** [comment]
@st-review merge it

etc: Update systemd docs URL

Skip-check: authors

**Comment by st-review** [comment]
:ok_hand: Merged as c9afabf09fc9014cfabd6bd1c9a580c2c2fb542e. Thanks, @elliot-labs!

**Pull request closed without merging**
