### PR TITLE
Remove windows specialisation from osutil.GetLans (fixes #2192)

### LINKED ISSUE #2192: osutil.GetLans() and Go 1.5
Windows specialization can go away, and we can use the same code as other platforms.
Also has v6 support.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by calmh** [comment]
I don't think we want to *require* Go 1.5 yet, though?

**Comment by calmh** [comment]
Closing as I think we'll want to keep that specialization for the foreseeable future - argue with me if you disagree :)

**Comment by AudriusButkevicius** [comment]
Lets keep this open so we don't forget

**Comment by calmh** [comment]
Pull this forward to current master and merge it? As we're building everything with 1.5 nowadays, and can just have that as a req on the Windows build...

**Comment by AudriusButkevicius** [comment]
Sadly https://github.com/golang/go/issues/12551

**Comment by calmh** [comment]
Oh for fucks sake :(

**Comment by calmh** [comment]
That breaks our local discovery v4 broadcasts

**Comment by calmh** [comment]
... I guess? (On mobile, can't edit) Maybe we need to just use our own code there as well and keep it for the foreseeable future?

**Comment by AudriusButkevicius** [comment]
I don't think it breaks discovery, the error is in the code which pulls out the mask only as far as I understood. But there are other issues, such as returning interfaces that are down as being up. Go 1.6 is not that far away I guess, so we can drop this then.

**Comment by calmh** [comment]
I'm thinking we'll randomly get an incorrect netmask in https://github.com/syncthing/syncthing/blob/master/lib/beacon/broadcast.go#L112 and generate a broken broadcast address. It could potentially explain some "v0.12 discovery doesn't work" issues in some setups where v4 broadcasts were the only thing that worked previously?

**Comment by AudriusButkevicius** [comment]
I think it always returns the wrong mask, so it should be permanently broken. Though I am not sure if the broken maso display affects the multicast address. We could build with 1.6 alpha?

**Comment by calmh** [comment]
We could do that actually... Maybe catch some further breakage before it releases. The Windows networking stuff in Go seems like a big bag of lolwtf...

**Comment by AudriusButkevicius** [comment]
Well it was rewritten to support v6, and it's pretty much reimplemented, so it's not a surprise that it takes multiple releases to get it right, especially Windows being a niche platform, stuff we are doing being niche, and there only being a few guys who are actually awesome enough to deliver this.

Let's try making a release with 1.6 alpha, and roll back to 1.5.2 if it breaks.
(Or just use alpha release for Windows)

**Comment by calmh** [comment]
Fair enough :)

**Comment by AudriusButkevicius** [comment]
Rebased. Let's give it a week to see if any issues come up with Windows and 1.6b.

**Comment by calmh** [comment]
This feels good to go to me

**Pull request merged**
