### PR TITLE
Potential race between folder being added and scan (fixes #1986)

### LINKED ISSUE #1986: Mac OSx external HDD issue.
Mac OSx  10.10.3 

The issue reproduction 

1) create a sync folder in external HDD   (  /Volumes/1tb/sync/docs )
2) run Synching 
3) disconnect HDD 
4) run Synching. The application will create the folder with disk name /Volumes/1tb/
5) mount the disk . The disk become mounted to another  /Volumes/1tb 1/  
6) Synching couldn't find the files. 

I solve it by unmounting HDD, deleting /Volumes/1tb/ folder and mounting the HDD. 
It is necessary to do quick. I believe it would create the folder for next directory scan. 

Thank you.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
The only thing that comes to mind, apart from having an empty folder to start with, and then MkdirAll being the culprit.

### CODE REVIEW

**Comment by calmh** [comment]
Looks reasonable, apart from not actually building... ;) Should we maybe make `CurrentLocalVersion(folder string) (ver int64, ok bool)` instead and we could trigger on non-`ok` in this case?

**Comment by AudriusButkevicius** [comment]
Good idea, I'll do that.

**Comment by AudriusButkevicius** [comment]
Redone

**Comment by calmh** [comment]
:+1:

**Pull request merged**
