### PR TITLE
scanner: Allow disabling weak hash in scanning (fixes #3891)

### LINKED ISSUE #3891: There should be a setting to disable the weak hash while scanning
Currently, we can disable weak hash for pulling by setting `weakHashThresholdPct` to 101 (I think).
But there is no way to disable it completely (e.g. for scanning).

There should be an (advanced) option to disable the weak hash.

### Version Information

Syncthing Version: v0.14.19
OS Version: Manjaro / Ubuntu 16.04

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
I know this is ugly, and we should either toss the config itself around, or just restructure this whole thing a bit, but that's more time than I want to spend on this.

### CODE REVIEW

**Comment by calmh** [comment]
I was writing up a whole "not worth it" response here given that I think the weakhash doesn't cost that much now, but added a benchmark and it seems it's still quite a difference;

```
jb@unu:~/s/g/s/s/l/scanner $ go test -bench . -benchtime=5s
BenchmarkHashFile-8         	     100	  60790852 ns/op	 293.23 MB/s	 4505790 B/op	     287 allocs/op
BenchmarkHashFileNoWeak-8   	     100	  52376819 ns/op	 340.34 MB/s	   49176 B/op	     147 allocs/op
PASS
ok  	github.com/syncthing/syncthing/lib/scanner	12.683s
jb@unu:~/s/g/s/s/l/scanner $ 
```

I'd have expected the amount of allocations to not be that heavy. Let me try to fix that first and see if we can bring down the cost of the weakhash enough to not have to worry about this stuff.

**Comment by AudriusButkevicius** [comment]
I personally couldn't immediately find where the allocations are coming from yet bare in mind that my roots are of a python boy who usually rides a single threads across the great plains of unlimited memory.

**Comment by calmh** [comment]
It's the rollinghash adler32 package that does it. I fixed one case earlier today but missed our Reset/Write/Reset/Write usage - it's easily fixed but didn't have as much impact on the rate as I'd hoped:

```
jb@unu:~/s/g/s/s/l/scanner $ go test -bench HashFile -benchtime=5s -memprofile mem.out
BenchmarkHashFile-8         	     100	  62913298 ns/op	 283.34 MB/s	   82090 B/op	     152 allocs/op
BenchmarkHashFileNoWeak-8   	     100	  53847114 ns/op	 331.04 MB/s	   49176 B/op	     147 allocs/op
PASS
ok  	github.com/syncthing/syncthing/lib/scanner	13.065s
jb@unu:~/s/g/s/s/l/scanner $ 
```

The rest of the allocations are mostly from creating the io.LimitReader each iteration. I'll work around that and see if it's worth it. 

If it stays as it is above, is it worth doing this for the 16% performance increase, given that we're preventing the other side from using the weakhash?

**Comment by calmh** [comment]
Oh, and by the way, if it's useful:

```
jb@unu:~/s/g/s/s/l/scanner $ go test -bench HashFile\$ -benchtime=5s -memprofile mem.out -memprofilerate 0
BenchmarkHashFile-8   	     100	  60274768 ns/op	 295.74 MB/s	   82116 B/op	     152 allocs/op
PASS
ok  	github.com/syncthing/syncthing/lib/scanner	7.349s
jb@unu:~/s/g/s/s/l/scanner $ go tool pprof --alloc_objects --lines scanner.test mem.out 
Entering interactive mode (type "help" for commands)
(pprof) top
32985 of 33473 total (98.54%)
Dropped 16 nodes (cum <= 167)
      flat  flat%   sum%        cum   cum%
     32769 97.90% 97.90%      32769 97.90%  github.com/syncthing/syncthing/lib/scanner.Blocks /Users/jb/src/github.com/syncthing/syncthing/lib/scanner/blocks.go:59
       216  0.65% 98.54%        216  0.65%  github.com/syncthing/syncthing/lib/scanner.Blocks /Users/jb/src/github.com/syncthing/syncthing/lib/scanner/blocks.go:51
...
(pprof) 
```

That first line is the io.LimitReader smoking gun, for example.

**Comment by calmh** [comment]
Fixed that:

```
jb@unu:~/s/g/s/s/l/scanner $ go test -bench HashFile -benchtime=5s
BenchmarkHashFile-8         	     100	  61311472 ns/op	 290.74 MB/s	   77772 B/op	      16 allocs/op
BenchmarkHashFileNoWeak-8   	     100	  52725061 ns/op	 338.09 MB/s	   44824 B/op	      11 allocs/op
PASS
ok  	github.com/syncthing/syncthing/lib/scanner	12.774s
jb@unu:~/s/g/s/s/l/scanner $ 
```

Difference is still there, and now I don't think there is any more low hanging fruit on the weakhash side other than parallelizing it...

**Comment by AudriusButkevicius** [comment]
Well petting the GC is a good thing too I guess.

**Comment by calmh** [comment]
Yeah, I've pushed that change and since I did some tweaks with the weakhash testing earlier today you'll need to merge with master and change one of the tests to pass `true` instead of `false` for the weakhash. Otherwise I think this is good to go, might as well do it for the ultimate hashing experience.

**Comment by AudriusButkevicius** [comment]
Rebased.

**Comment by AudriusButkevicius** [comment]
Ah tests.

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as dd78177ae06cef6c115f7f463d81f290e63f58b2. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
