### PR TITLE
Merge RW and RO folders' code

### PR DESCRIPTION
**Pull request by Tracerneo**
Removes separate code for RO folders, reuses code from RW folders

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So I feel this is worse then what it is.

The right way to do this is to extract the scanner into a separate struct, the puller into a separate struct and then do composition by embedding whichever parts your new folder needs into the folder struct.

**Comment by Tracerneo** [comment]
It's up to you. In my opinion it makes future changes easier, because there's only one version of the code. Decision about what to do with the folder depending if it's read-only or not is moved from the main code, directly to the folder logic.

**Comment by calmh** [comment]
The diff has far more `-` lines than `+` lines which ought to mean it's a net positive, so to speak. It might be a step in the right direction. Let me stare at it for a while. :)

**Comment by calmh** [comment]
*Well actually*, the main problem is a bunch of the relevant code lives in `Model` and that the dependency graph between the things here looks like a spider web... Sigh.

**Comment by calmh** [comment]
Yeah, I've changed my mind. The current situation with the `roFolder` being a rather small and obvious type is preferable to the merged version, as it makes it clearer what code is actually in motion in the "read only" case. What should probably happen is that the `roFolder` should gain more of the scanning code from `model`, and `rwFolder` should embed an `roFolder` and then decorate it with the pulling stuff on top.

**Pull request closed without merging**
