### PR TITLE
Add remaining scanning time (fixes #2484)

### LINKED ISSUE #2484: Show ETA while scanning
As suggested in #2481 an ETA info while scanning would improve usability

### PR DESCRIPTION
**Pull request by calmh**
screen shot 2015-11-18 at 10 56 23

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Done in is a bad wording.

We should call it Estimated scan time: 2m 10ss, no need for leading zeros.

**Comment by uok** [comment]
sweet, thanks for implementing! My suggestion: "remaining scan time" on the left and just time on the right. I think the scan speed remains more or less static (unless you upgrade your hardware)

**Comment by calmh** [comment]
Changed (approximately) per suggestions. I'm keeping the zero padding on the seconds field as that makes it not jump about as much.

screen shot 2015-11-18 at 11 59 35

**Comment by AudriusButkevicius** [comment]
I'd add the word estimate

**Comment by calmh** [comment]
Can I just use a `~` on the right, as for the states above it? A longer label pretty much wont fit as the table is split 50/50 between the two columns.

**Comment by uok** [comment]
I think the "~" is a good idea or move the time info to the header. IMHO the user knows that this can only be an estimated but is thankful about the info that e.g. scanning will take roughly another 30min

**Comment by calmh** [comment]
Tilde added. And yeah, as long as it's not a report sent back in time from a future Syncthing it's going to be an estimate :D

**Comment by calmh** [comment]
We can put times in the header once we have this for the other relevant states - syncing, primarily.

**Comment by uok** [comment]
sounds good

**Comment by calmh** [comment]
screen shot 2015-11-18 at 12 12 14

**Pull request merged**
