### PR TITLE
Update docs to https URLs.

### PR DESCRIPTION
**Pull request by MikeLund**
Simple sed to update all docs.syncthing.net URL:s in the project to use https. The docs server will always redirect to https anyways, so no point making insecure request in first place. Thanks!

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins add to white list

**Comment by calmh** [comment]
@st-review merge it

all: Update docs.s.n links to use https

Skip-check: authors

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by calmh** [comment]
@MikeLund Thanks!

**Comment by st-review** [comment]
:ok_hand: Merged as 74dd051d5192741e6d44f4ffa00a697b0c304ee5. Thanks, @MikeLund!

**Pull request closed without merging**
