### PR TITLE
lib/config: Apply defaults to folders/devices on config load (ref #6748)

### PR DESCRIPTION
**Pull request by calmh**
This makes it so that `default:"..."` struct tags on devices and folders actually take effect during JSON/XML loading, like it does for general and GUI options.

This means we can add a field to a device/folder and have it take its default value on config load without writing a config migration. (I suspect we've missed this in the past because the current
behavior is unintuitive...)

### CODE REVIEW

**Comment by imsodin** [comment]
Having the magic default application on folders and devices only feels like potential for future mistakes/confusion. It's clear why it's only necessary for those (slice vs non-slice), but maybe it's worth doing this for all the config elements with defaults instead of setting defaults in the `config.Read...` methods. And it may even be possible to create a utility function for it (untested, and anyway optional):

```golang
func (cfg *DeviceConfiguration) UnmarshalJSON(data []byte) error {
	return util.UnmarshalJSONWithDefaults(cfg, data)
}

func UnmarshalJSONWithDefaults(target interface{}, data []byte) error {
	SetDefaults(target)
	type noCustomUnmarshal reflect.TypeOf(target)
	ptr := (*noCustomUnmarshal)(target)
	return json.Unmarshal(data, ptr)
}
```

**Comment by calmh** [comment]
Unsure about the possibility to generalize, but to be clear this is not something that now applies to folders and devices *only*. The situation currently is that defaults-on-deserialize applies to everything *but* devices and folders -- that is, the main config, GUI config and options config all get defaults as expected. Devices and folders were the exception because way back when it happened we didn't sort out the unmarshal magic I just did. This change makes the behavior the same for all the types.

**Comment by imsodin** [comment]
I am aware of that, I am only talking about where the defaults are applied: For folders and devices it's now on unmarshalling, for everything else it's on a dedicated config reading function (`json.Unmarshal(&OptionsConfiguration{}, bs)` has no defaults). I don't think we ever do (un)marshal options and gui separately from the entire config, but if we added an api for doing just that in the future, we'd have to think about doing the same unmarshalling magic for those too, and that's where my proposition to apply defaults on unmarshal for everything comes in.

**Comment by calmh** [comment]
Right, okay. Let me look into that.

**Comment by calmh** [comment]
Not for merging, need to consider the details a bit

**Comment by AudriusButkevicius** [comment]
Looks good, yet I am a bit puzzled how we manage to hide the marshalling methods via a type alias, presumably the underlying method still resolves to the type behind the alias?

**Comment by calmh** [comment]
Declaring a new type drops the methods. But this solution is ugly. I was thinking today that I might as well fork encoding/json+encoding/xml to add support for a method `{Un}MarshalContext()` that would take a context and pass it to new `MarshalJSONContext()` etc methods, which would help with keeping track of things during unmarshal -- like unmarshal could then know what `myID` is and be able to do related cleanup directly. Similarly one could support `PreUnmarshal(ctx)` and `PostUnmarshal(ctx)` hooks for things like setting defaults prior to unmarshal and doing validation post unmarshal without having to do ugly conversions to temporary types and stuff.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
