### PR TITLE
gui: Vertically center identicons in panel titles

### PR DESCRIPTION
**Pull request by norgeous**
before:
before

after:
after

### CODE REVIEW

**Comment by norgeous** [comment]
hopefully perfect this time

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 855a1bef895464ca0f87a9bd9ccccc07a815a622. Thanks, @norgeous!

**Pull request closed without merging**
