### PR TITLE
lib/model: Properly schedule pull on reconnect (fixes #4504)

### LINKED ISSUE #4504: Pulls not triggered correctly on reconnection
Since f6ea2a7f there is an issue where a disconnect during sync, which causes "peer went away" errors, does not get resolved on reconnect.

Reproducer:

```
jb@unu:~/s/g/s/s/test $ go test -v -tags integration -run Reconnect
=== RUN   TestReconnectReceiverDuringTransfer
2017/11/13 00:35:23 Cleaning...
2017/11/13 00:35:24 Generating files...
2017/11/13 00:35:24 Starting up...
2017/11/13 00:35:24 Starting instance 1...
2017/11/13 00:35:27 Starting instance 2...
2017/11/13 00:35:31 Pausing receiver...
2017/11/13 00:35:31 Resuming receiver...
2017/11/13 00:35:32 Pausing receiver...
2017/11/13 00:35:32 Resuming receiver...
(hangs here, s2 is out of sync, connected, and not pulling)
```

To be resolved before 0.14.41-rc.1

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

We need to reset prevSeq so that we force a full check when someone reconnects - the sequence number may not have changed due to the reconnect. (This is a regression; we did this before f6ea2a7.)

Also add an optimization: we schedule a pull after scanning, but there is no need to do so if no changes were detected. This matters now because the scheduled pull actually traverses the database which is expensive.

This, however, makes the pull not happen on initial scan if there were no changes during the initial scan. Compensate by always scheduling a pull after initial scan in the rwfolder itself.

### Testing

Previously failing integration test now passes

### CODE REVIEW

**Comment by imsodin** [comment]
I think this makes `prevSeq` completely moot, as it will always be zero (except for failed pulls, but there it will always be different from the remote sequence, otherwise the pull wouldn't fail in the first place). This is actually just a consequence of https://github.com/syncthing/syncthing/commit/f6ea2a7f8e5077b7b279cd680400509bccbf557e that I missed together with the connection case that you fix here.

**Comment by imsodin** [comment]
Actually, the integration test in the issue works on my machine and I don't understand the issue conceptually: When pulling does not succeed, `prevSeq` is not updated, so the remote sequence should be higher and thus a pull should happen after reconnect.

**Comment by AudriusButkevicius** [comment]
So, wazzup with zis?

**Comment by imsodin** [comment]
As a pull is now only scheduled when really necessary, the `prevSeq` is not needed any more and can be disposed of. It is set to 0 on every pull anyway.

**Comment by calmh** [comment]
I've incorporated that commit

**Comment by imsodin** [comment]
I haven't really looked at the integration test changes - they run on my machine, that's good enough for me.

**Comment by imsodin** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@imsodin: Noted! Need another LGTM or explicit merge command.

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 5f4ed66aa1b0cd22f96503cf91279b64f9f9ffdc. Thanks, @calmh!

**Pull request closed without merging**
