### PR TITLE
Remove -reset option

### PR DESCRIPTION
**Pull request by calmh**
Is there an actual reason for this flag+REST URL to exist?

### CODE REVIEW

**Comment by Zillode** [comment]
Clearing the index on an android device is not easily possible (but it could still be implemented in the android app itself).

**Comment by AudriusButkevicius** [comment]
We should have a reset which just clears the index.

**Comment by calmh** [comment]
This reminds me that we probably need better handling of trivial conflicts, as removing the indexing and doing a rescan will cause a conflict for every file in the folder even though they might be identical.

**Comment by Zillode** [comment]
Given @calmh's question, is it ok if I change the behaviour of ```-reset``` to clear the index but not rename the folders?

**Comment by AudriusButkevicius** [comment]
Yeah, that's what I'd prefer, and keeping the API call.
Perhaps even taking an optional argument to specify which directory/device, so that we could eventually have the reset button for each folder in the UI.

**Pull request closed without merging**
