### PR TITLE
sync percentage process max is 100%

### PR DESCRIPTION
**Pull request by SCys**
### Purpose

sync percentage process max is 100%.

### CODE REVIEW

**Comment by calmh** [comment]
I'd rather we found and fixed the cases where we report that we have more data in sync than actually exists...

**Comment by AudriusButkevicius** [comment]
Agree

**Comment by SCys** [comment]
i will try other way change the ui show progress percentage.
origin code show large than 231%.

**Comment by calmh** [comment]
If you can reproduce this, please file the issue with the steps and we can fix that instead.

**Pull request closed without merging**
