### PR TITLE
Added the link to the site in navbar-brand

### PR DESCRIPTION
**Pull request by nervgh**

### CODE REVIEW

**Comment by calmh** [comment]
I'm not super keen on this. It seem to make sense at first glance, but... The upper-left logo is usually a kind of home button. I'd be annoyed if I pressed it by reflex or to refresh or something and ended up on a marketing site for the thing I'd obviously already installed.

**Comment by AudriusButkevicius** [comment]
Agree with @calmh on this one

**Comment by nervgh** [comment]
@calmh I agree with you. I can add `target="_blank"` or you could close this PR. The choice is yours :blush:

**Comment by calmh** [comment]
Leaving as is for the moment. Thanks for the improvement suggestion anyhow. :)

**Pull request closed without merging**
