### PR TITLE
Use RemoveAll for (?d) prefixed paths (fixes #3164)

### LINKED ISSUE #3164: The (?d) prefix on an ignored directory should delete directory contents
Follow-up to [this](https://forum.syncthing.net/t/ignoring-d-prefix-eadir-folder/7437), have been asked by @AudriusButkevicius to raise an issue

---

Devices : 3 Synology NAS DS215j
Running Syncthing v0.13.2
Sharing a big folder of media files

Each subfolder containing one or more media files contains one hidden folder `@eaDir` containing subfolders and temporary files.

    BIGFOLDER\
    BIGFOLDER\SOME_MEDIA\
    BIGFOLDER\SOME_MEDIA\MEDIA_FILE.EXT
    BIGFOLDER\SOME_MEDIA\@eaDir\Random_temp_file.ext
    BIGFOLDER\SOME_MEDIA\@eaDir\Random_temp_subfolder\
    BIGFOLDER\SOME_MEDIA\@eaDir\Randem_temp_subfolder\Random_temp_file.ext

At the moment, .stignore contains on each node :
 
    (?d)@eaDir 

If I remove the `SOME_MEDIA` folder on one node, the other nodes display :

`[REDACTED] 10:52:45 INFO: Puller (folder "BIGFOLDER", dir "SOME_MEDIA"): delete: remove /volume/BIGFOLDER/SOME_MEDIA: directory not empty`

I thought that prefixing `@eaDir` with `(?d)` would allow deletion, but it doesn't seem to work.

I tried the `(?d)@eaDir/**` pattern too, but it doesn't seem to work too.

Any ideas on how to handle deletion of those ignored `@eaDir` subdirectories and their respective content when deleting directories ?

I can provide much more details if needed.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Test actually touching the filesystem seem incredibly flaky (if the test fails, and forgets to unset readonly flags etc), but let me know if you want me to add some.

### CODE REVIEW

**Comment by calmh** [comment]
LGTM

**Comment by calmh** [comment]
@st-review merge it

lib/model: Handle (?d) deletes of directories (fixes #3164)

**Comment by st-review** [comment]
:ok_hand: Merged as 915e1ac7def2603bac81c1e6b9ce7f07032bf148. Thanks, @AudriusButkevicius!

**Comment by Tstassin** [comment]
Thanks @AudriusButkevicius for being so fast at fixing this.
Hope this will make it very soon to v0.13.3

**Comment by AudriusButkevicius** [comment]
@calmh, this is a bit dangerous as it ignores `!` stuff. Should we be concerned?

**Comment by calmh** [comment]
@AudriusButkevicius explain

**Comment by AudriusButkevicius** [comment]
(?d)temp
!temp/myimportantfile

This will nuke the important file, although you might expect it to be excluded.

**Comment by calmh** [comment]
Right, yes. I think that's fine. Dangerous config to start with, temp would only be deleted because some other device has deleted all of it anyway so effect is similar to not ignoring temp or temp/myimportantfile.

Doesn't hurt to document it I guess

**Pull request closed without merging**
