### PR TITLE
genassets.go: Use SOURCE_DATE_EPOCH when available

### PR DESCRIPTION
**Pull request by aviau**
Debian bug: [#828994](https://bugs.debian.org/828994)

Original patch author: Eduard Sanou <dhole@openmailbox.org>

### CODE REVIEW

**Comment by calmh** [comment]
Simpler suggestion: remove the BuildDate handling completely in genassets. It is not used anywhere currently. If it were used, it should inherit main.BuildDate instead which does get set correctly from the commit date.

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by aviau** [comment]
@calmh I have updated the patch to remove BuildDate.

**Comment by calmh** [comment]
Also the template around line 33 and the field at line 89

**Comment by calmh** [comment]
And the resulting import changes for the compile errors :)

**Comment by calmh** [comment]
@st-review merge it!

script: Remove build date in genassets.go

The build date prevented the builds from being reproducible.

Debian bug: https://bugs.debian.org/828994

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 3cbe7d40d1d452c7b956d36a80febb3b3e03d090. Thanks, @aviau!

**Comment by AudriusButkevicius** [comment]
This was used for asset caching though...

**Comment by calmh** [comment]
Yeah but we've all but completely removed that now. If we think that's a good idea we can revive it, but then I think we should use the main build stamp instead.

**Pull request closed without merging**
