### PR TITLE
Audit logins with new Login event (fixes #2377)

### LINKED ISSUE #2377: Log or audit gui login failures
I'd like to have syncthing listening on 0.0.0.0 on my VPS and it would be nice to know if somebody is trying to get in. I'd be willing to work on this but I don't know if this should be an auditable event or just logged to stdout?

### PR DESCRIPTION
**Pull request by tylerbrazier**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So I'd call it LoginAttempt, and I would declare audit at the module scope, and call it emitLoginAttempt(username, success)

**Comment by calmh** [comment]
Also needs handling in verbose.go to print correctly when running with `-verbose`, otherwise LGTM

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
@canton7 Can we add events in patch releases nowadays, or do you need more heads up? I forget.

**Comment by canton7** [comment]
You should be fine to add in events

**Comment by calmh** [comment]
:+1:

**Comment by AudriusButkevicius** [comment]
@tylerbrazier can you add yourself to authors, and lets get this merged.

**Comment by calmh** [comment]
I think a worthy followup here would be to log the IP the login attempt came from as well.

**Comment by rumpelsepp** [comment]
> I think a worthy followup here would be to log the IP the login attempt came from as well.

That would be cool, as we could then contribute an appropriate regex to fail2ban for automatic firewall rules.

**Pull request merged**
