### PR TITLE
vendor: Update everything

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Update dependencies.

@aviau is going to hate this one. Or maybe not care at all since it doesn't change our external dependencies.

### CODE REVIEW

**Comment by calmh** [comment]
`github.com/xtaci/smux/session.go:121: undefined: time.Until`

That's a Go 1.8-ism, rejected by our current Go 1.7 check. We can go to 1.8 now though.

**Comment by AudriusButkevicius** [comment]
Lets do that

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as c24bf7ea55c1bc75043fe50a5adec4da9b9941da. Thanks, @calmh!

**Comment by aviau** [comment]
Haha. Well, I don't care :o)

Sometimes, Debian libs are ahead of Syncthing, sometimes they are behind.

If you want to be 100% sure that one library is updated because of a known issue, the best is to add a test in Syncthing that checks for this specific bug. Otherwise I try to read the Syncthing changelogs.

I recently (today) updated 110+ Go libs, so I think we are up-to-date for the most of it...

**Pull request closed without merging**
