### PR TITLE
Syncthing resume

### PR DESCRIPTION
**Pull request by calmh**
@rumpelsepp to merge if this is the correct path etc and makes sense

### Testing

None whatsoever, I don't do systemd.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by rumpelsepp** [comment]
@st-review Merge this, please.

**Comment by rumpelsepp** [comment]
Hmm, seems I am blacklisted or something.

**Comment by calmh** [comment]
No it just doesn't like the capital M I think

**Comment by calmh** [comment]
I should probably make it case insensitive

**Comment by rumpelsepp** [comment]
@st-review merge this, please!

**Comment by st-review** [comment]
OK, merged as d37ed65f42baa6a46e0f04fa048889a8ad0626a9.

**Comment by rumpelsepp** [comment]
This bot is awesome. No more silly merge commits for one line patches.

**Comment by calmh** [comment]
(There are now reactions on comments? Wow... Ah well.)

**Comment by rumpelsepp** [comment]
Just saw the new button and couldn't resist clicking some icons... :D

**Pull request closed without merging**
