### PR TITLE
lib/model: Don't deadlock when returning temp index block counts

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Don't deadlock.

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it when it passes

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by AudriusButkevicius** [comment]
Muhah.

**Comment by st-review** [comment]
:ok_hand: Merged as 9bb5988b4ed726a7eb7662dce01580b0e82dab02. Thanks, @calmh!

**Pull request closed without merging**
