### PR TITLE
Add missing licenses fixes #3100

### LINKED ISSUE #3100: Missing license notices
Hello,

The following files are missing a copyright notice and this makes distributing them illegal.

Just including the full license in the file headers would be perfect (and make me a very happy Debian Developer).
 
**MIT:**

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software

- [x] gui/default/vendor/angular/angular-dirPagination.js
- [x] gui/default/vendor/angular/angular-translate-loader-static-files.js
- [x] gui/default/vendor/angular/angular-translate.js
- [x] gui/default/vendor/angular/angular.js

**BSD-3-Clause:**
> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

- [x] lib/osutil/mkdirall_windows.go
- [x] lib/upnp/igd_service.go
- [x] lib/upnp/igd.go
- [x] lib/upnp/upnp.go

I haven't looked at the whole repo yet (because I am sleepy!), so I'll update this issue as I go. Feel free to check check the boxes as the licenses are fixed.

### PR DESCRIPTION
**Pull request by aviau**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
LGTM, tho I'll leave it to @calmh to merge, given it's legal business.

**Comment by lkwg82** [comment]
please add a line with your email in the AUTHORS file

**Comment by aviau** [comment]
Added myself to AUTHORS in #3109

**Comment by AudriusButkevicius** [comment]
Authors is not mandatory for comment checks, but given it's not the first PR, it's probably easier for you to be there.

You should also add yourself to NICKS I think.

**Comment by aviau** [comment]
> You should also add yourself to NICKS I think.

Okay, just did that too in #3109

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it

gui, lib: Add missing licenses (fixes #3100)

**Comment by st-review** [comment]
:ok_hand: Merged as 6e07742fe95f2d1e9b460d57b3bb02d9babadf1a. Thanks, @aviau!

**Comment by calmh** [comment]
There's a risk we'll screw this up when we next update the Angular stuff, as we'll probably just copy over the files. At that point I'll try to remember that we should also copy the relevant LICENSE files which should be the permanent solution. The inclusion of the licenses into the Go source code files doesn't suffer from that so I'm not worried.

**Pull request closed without merging**
