### PR TITLE
gui: Sort folder by label, devices by name (fixes #3310)

### LINKED ISSUE #3310: Folders should be sorted by label, not ID
Is it possible to sort the folder by label instead of by ID?

I'm using 0.13.7 on Linux (AMD64 & ARM), Windows and OS X.

### PR DESCRIPTION
**Pull request by norgeous**

### CODE REVIEW

**Comment by calmh** [comment]
95% - there should be some support for "legacy" folders that have an ID but no label, so we show and sort by the ID. That is, the logic for what we sort on should be the same as what we display - label if nonblank, otherwise ID.

**Comment by norgeous** [comment]
yes. i did not think of that. well played sir.
Lucky for us `orderBy` supports arrays...
`| orderBy : ['group','sub']`
will test and add shortly

**Comment by norgeous** [comment]
woops, looks like i screwed it up trying to rebase. my bad. closing to open another clean one.

**Comment by calmh** [comment]
You can just force push to the same branch as well to clear out old crap, after fixing it locally :)

**Comment by norgeous** [comment]
I tend to only use
`git pull --rebase syncthing master`
as I am stupid :S

One day I will master git.

**Pull request closed without merging**
