### PR TITLE
gui: Remove "é"

### PR DESCRIPTION
**Pull request by polyfloyd**
### Purpose

To remove "é".

### Screenshots

screen shot 2018-01-09 at 20 36 53

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
Another PR succeeded a sec ago that fixes the same issue. Thanks for your effort.

**Pull request closed without merging**
