### PR TITLE
Prevent negative values for number inputs

### PR DESCRIPTION
**Pull request by uok**
- settings: incoming/outgoing rate limit
- folder: maximum age (staggered file versioning)

### CODE REVIEW

**Comment by calmh** [comment]
This needs corresponding `<span translate ng-if="folderEditor.staggeredMaxAge.$error.min ...` messages and so on?

**Comment by uok** [comment]
What do you mean by that? The `min` attributes are for browser validation (if you click the tiny down arrow in a number field, you cannot go below 0). This attribute has been used on other input fields (e.g. rescan interval) so I just added them where they were missing

**Comment by calmh** [comment]
Yes. But the spans in question are shown when the corresponding validation fails, to tell the user what they need to fix.

**Comment by uok** [comment]
Thanks, found it - and it works! :tada: sometimes I surprise myself :smile:

**Comment by AudriusButkevicius** [comment]
Rebase please

**Comment by uok** [comment]
done :checkered_flag:

**Comment by AudriusButkevicius** [comment]
Nope

**Comment by uok** [comment]
yeah it is, but somehow the checks consider the whole master and not just this commit to recommend rebase. I am working on the other commit/rebase for the icons

**Pull request merged**
