### PR TITLE
lib/model: Correctly detect deleted but previously ignored files as deleted

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

When an existing file becomes ignored we set the invalid bit on it. If we then unignore it, the scanner will clear the invalid bit when it sees it again. But if we delete the file, then unignore it, it stays marked as invalid and not-deleted. With this change it correctly transitions to deleted and not-invalid.

### Testing

It helped me resolve my way out of https://forum.syncthing.net/t/what-to-do-with-files-when-they-become-ignored/7111 but these parts are a bit murky...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Shouldn't we not set the invalid bit in the first place?

**Comment by calmh** [comment]
Yeah I'm a bit confused about why we do that, to be honest.

- For incoming index updates we accept all entries, even ignored ones, and handle this by filtering out ignored entries in the withNeed loop.

- For outgoing index updates we filter out all ignored entries, so they never get sent at all.

- For existing files that are in the index when they become ignored, we ... erm ... skip them entirely in the scanner, then set the invalid bit in the scan-for-deleted files step.

This keeps the ignored files around in the index, but the invalid bit prevents them from entering the "global" list. I'm not sure what the point is. Maybe to keep the version vector around for the time when they become unignored again? Otherwise it could be cleaner to just remove the file from the index, but I don't think we have a method for doing that currently.

**Comment by AudriusButkevicius** [comment]
Don't the versions at that point go complete wacko, and potentially cause conflicts?

**Comment by calmh** [comment]
At what point? :)

**Comment by AudriusButkevicius** [comment]
Ignore me, its ignored it can't cause conflicts.

**Pull request merged**
