### PR TITLE
cleanup, unused code

### PR DESCRIPTION
**Pull request by lkwg82**
### Purpose

cleanup, remove unused code while reading the source

### Testing

compile

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:no_entry: Merge failed:

```
$ git fetch -f origin refs/pull/3004/head:pr-3004
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at 4aa6ecb lib/model: Do not use WRONLY (ref #2584)
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 4aa6ecb lib/model: Do not use WRONLY (ref #2584)
$ git clean -fxd
Skipping repository syncthing/syncthing
$ git merge --squash --no-commit pr-3004
Updating 4aa6ecb..98bfd31
Fast-forward
Squash commit -- not updating HEAD
 lib/config/wrapper.go | 5 -----
 1 file changed, 5 deletions(-)
$ git commit -F -
******************************************************
* Commit message does not match the expected format: *
*                                                    *
*   some/tag: A longer description (fixes #1234)     *
*                                                    *
******************************************************

```

**Comment by AudriusButkevicius** [comment]
@st-review merge

lib/config: Remove dead code

**Comment by st-review** [comment]
:ok_hand: Merged as dffc34559b215120ffaad7b1dcf5e290deb3b750. Thanks, @lkwg82!

**Pull request closed without merging**
