### PR TITLE
lib/connections Fix Did not complete all the connection attempt

### PR DESCRIPTION
**Pull request by xjtdy888**
fixed Did not complete all the connection attempt, 
the first attempt if the priority fails, premature return

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it

lib/connections: Actually make connection attempts for lower priority addresses as well

Skip-check: authors

**Comment by st-review** [comment]
:ok_hand: Merged as a17d953334a8361197f5b0801caaa0be5953170e. Thanks, @xjtdy888!

**Comment by calmh** [comment]
@xjtdy888 Thanks

**Comment by calmh** [comment]
Actually no this is still completely broken, dammit...

**Comment by calmh** [comment]
I posted a comment here previous saying this PR was broken. It's not, I was aiming for another PR. Leaving this comment here in case the previous one went out by email, sorry.

**Pull request closed without merging**
