### PR TITLE
vendor: Revert to github.com/jackpal/gateway instead of fork

### PR DESCRIPTION
**Pull request by calmh**
It now includes all the fixes.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

I'm fighting with the "purego" tag that's needed by discosrv dependencies...

**Comment by calmh** [comment]
I think this one is good to go, as it's an all new all better gateway package.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 6a67921e40d92052385b96375a3c7c256eef7156. Thanks, @calmh!

**Pull request closed without merging**
