### PR TITLE
cmd/ursrv: Support new android build user

### LINKED ISSUE #9140: Usage reporting should include Google Play as a distribution channel
Android accounts for 15% of our reported platforms:

image

Google Play is the biggest distribution channel for it, but is completely missing from our stats:

image

### PR DESCRIPTION
**Pull request by bt90**
### Purpose

Fixes #9140

## Authorship

Your name and email will be added automatically to the AUTHORS file
based on the commit metadata.

### CODE REVIEW

**Review by calmh — APPROVED** [review]

**Comment by bt90** [comment]
@calmh while the new android-builder shows up in the stats, it's not attributed to Google Play. Is the new ursrv version already deployed?

**Comment by calmh** [comment]
It is, it auto-deploys weekly, but the problem is that there is another regexp higher up in the list that matches it before...

**Comment by calmh** [comment]
There.

**Comment by bt90** [comment]
> but the problem is that there is another regexp higher up in the list that matches it before...

Oh my...i'm stupid.

**Comment by calmh** [comment]
Took me a good long while of staring at it to figure out what was going as well :D

**Pull request merged**
