### PR TITLE
gui: better info for stalled and lengthy scans (fixes #5627)

### LINKED ISSUE #5627: Stalled scans need better UI representation
Currently, a stalled scan keeps increasing Remaining Time on a folder, which leads to ridiculous amounts displayed: 

Should be `Unknown (stalled)` instead.

Also, for scans not completely stalled but really too slow `> 1 year` should suffice. Suggested in [this forum thread](https://forum.syncthing.net/t/remaining-time-ui/13086/5).

### PR DESCRIPTION
**Pull request by nekr0z**
Fixes #5627 

### Testing

Not really.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I'd drop it to 1 month cap rather than 1 year, otherwise it looks ok to me.

I don't think anyone will use software if it takes more than a month to be ready.

**Comment by nekr0z** [comment]
> I'd drop it to 1 month cap

I was basing on what @calmh said on the forum thread, and he mentioned a year. If a month is more sutable, I'm all for it.

**Comment by AudriusButkevicius** [comment]
@calmh ?

**Comment by calmh** [comment]
Arbitrary time interval is arbitrary, no big deal.

**Pull request merged**
