### PR TITLE
Hide .stignore files

### LINKED ISSUE #2114: Set “hidden” property on .stfolder and .stignore on Windows
To hide it from users and prevent accidental deletion.

### PR DESCRIPTION
**Pull request by Aeyoun**
Resolves #2114.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So probably you need to add yourself to AUTHORS.

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
:+1:

Needs the commit message to actually include the issue number though; `Hide .stignore files (fixes #2114)`

**Comment by calmh** [comment]
While you're at it, the author adding commit should be titled "Add Aeyoun" as others are.

**Comment by Aeyoun** [comment]
Oh, sorry for not following up. I missed the email notifications about this one.

**Pull request closed without merging**
