### PR TITLE
test: Reduce test coverage

### PR DESCRIPTION
**Pull request by calmh**
This is a test pr to experiment with measuring test coverage differences

### CODE REVIEW

**Comment by calmh** [comment]
dem worms

glowworms

**Comment by calmh** [comment]
@st-jenkins retest this

**Comment by calmh** [comment]
@st-jenkins retest this

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please again with sugar on top

**Comment by calmh** [comment]
@st-jenkins retest this please once more

**Comment by canton7** [comment]
That's a very very accurate metric...

**Comment by calmh** [comment]
Indeed it is

**Comment by calmh** [comment]
Ehm.

**Comment by calmh** [comment]
@st-jenkins retest this please with new jenkins

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
fuck it

**Pull request closed without merging**
