### PR TITLE
lib/protocol: Hide repeated data blocks in a given file

### PR DESCRIPTION
**Pull request by calmh**
Adds the block offset as additional data into the AES-SIV encryption of the block hash, thus making it not possible to correlate blocks at different offsets within a file. (These are never decrypted so there is no "other side" to this change.)

### CODE REVIEW

**Comment by imsodin** [comment]
> (These are never decrypted so there is no "other side" to this change.)

Why actually? We could send and then decrypt the hash in requests from untrusted to trusted, thus being able to check the data. Maybe that doesn't happen to save a bit of overhead?

**Comment by calmh** [comment]
In theory we probably could, yes. Maybe we already do send it and just lack the verification, I'm not sure.

**Comment by calmh** [comment]
I think we do, let me add that.

**Comment by calmh** [comment]
There, now we actually decrypt the hash as well.

**Review by imsodin — COMMENTED** [review]
In the `copierRoutine` in the puller we already skip searching by weak hash for receive-encrypted folders. ~~Now we can also skip searching by hash.~~ We can't - we still want to reuse unchanged blocks.

**Review by imsodin — APPROVED** [review]

**Pull request merged**
