### PR TITLE
lib/{nat,pmp}: Fix shadowing and nil IPs

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Self explanatory

### CODE REVIEW

**Comment by calmh** [comment]
I see no shadowing here? (I don't see anything wrong with the change either, I just don't see why it's necessary.)

**Comment by AudriusButkevicius** [comment]
So I am not sure how it works, but if you look at: 
http://alex-graf.de/public/st/sttrace_upnp_pmp_nat.txt

It seems that the `err :=` is not the same err outside the if?

**Comment by calmh** [comment]
Ah, yes of course

**Comment by calmh** [comment]
@st-review merge this please

**Comment by st-review** [comment]
:no_entry: Merge failed:

```
$ git fetch -f origin refs/pull/2979/head:pr-2979
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   0155b6f..fa1cfd9  master     -> orig/master
$ git reset --hard
HEAD is now at fa1cfd9 lib/versioner: Refactor for testing, speed up test
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at fa1cfd9 lib/versioner: Refactor for testing, speed up test
$ git clean -fxd
$ git merge --squash --no-commit pr-2979
Updating fa1cfd9..8562cc9
Fast-forward
Squash commit -- not updating HEAD
 lib/nat/service.go | 5 +++--
 lib/pmp/pmp.go     | 3 +++
 2 files changed, 6 insertions(+), 2 deletions(-)
$ git commit -F -
******************************************************
* Commit message does not match the expected format: *
*                                                    *
*   some/tag: A longer description (fixes #1234)     *
*                                                    *
******************************************************

```

**Comment by calmh** [comment]
@st-review merge this please, while accepting {} as valid parts of a tag

**Comment by st-review** [comment]
:ok_hand: Merged as e61f424ade1a8cfb24667a9478f032f1103cc83a. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
