### PR TITLE
Correctly set default logfile location on Windows (fixes #2608)

### LINKED ISSUE #2608: Version 0.12.9 Windows: panic: runtime error: invalid memory address or nil pointer dereference
Hi,
after the automatic update I cannot start syncthing anymore.
On my Win7 64Bit Machine, on the CMD.EXE it type:
`C:\syncthing-windows-amd64>syncthing.exe`
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal 0xc0000005 code=0x0 addr=0x30 pc=0x42467a]`

`goroutine 1 [running]:`
`main.ensureDir(0xc0820578c0, 0x25, 0x1c0)`
`        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:1040 +0x15a`
`main.main()`
`        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:318 +0x41c`

I downloaded the 0.12.9 from github manually, with the same result.
I tried the 32Bit version too (copied to the 64bit folder out of lazyness...) :
`C:\syncthing-windows-amd64>syncthing.exe`
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1c pc=0x41e868]`

`goroutine 1 [running]:`
`main.ensureDir(0x11862090, 0x25, 0x1c0)
        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:1040 +0x108`
`main.main()
        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:318 +0x369`

the log shows nothing interesting. Last lines:
`[FNH3H] 07:22:45 WARNING: Automatically upgraded to version "v0.12.9". Restarting in 1 minute.
[FNH3H] 07:22:45 INFO: New UPnP port mapping: external port 42177 to local port 22000.
[FNH3H] 07:23:45 OK: Exiting`

### PR DESCRIPTION
**Pull request by calmh**
*Not actually tested on Windows*

The usual chicken-and-egg about having the command line option for logFile depend on the other command line options and having expanded the locations... I think this is the correct behavior again, but hey who knows. I can't be bothered to get a Windows running and the binary over there, but if someone happen to run Windows and wants to check that this fixes the "Log output saved to ${config}" crap that'd be awesome

### CODE REVIEW

**Comment by canton7** [comment]
I'll test. Waiting for a build...

**Comment by canton7** [comment]
I don't get any "Log output saved to file ... " line: the first line of output is "INFO: Starting syncthing". Is that expected?

Actually, it doesn't log to `%LOCALAPPDATA%\syncthing\syncthing.log` either.

**Comment by calmh** [comment]
That's unexpected.

**Comment by calmh** [comment]
Missed one thing, try again with that new build...

**Comment by canton7** [comment]
:+1: all worky now

**Pull request merged**
