### PR TITLE
Put temporary files in the OS temp directory (fixes #1239)

### LINKED ISSUE #1239: upgrading: rename syncthing.exe -> syncthing.exe.old
Hi,

after clicking on the blue button on Windows 7 64bit I got this error-message:

"23:13:54: upgrading: rename C:\Program Files\syncthing\syncthing.exe C:\Program Files\syncthing\syncthing.exe.old: Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist."

Manually renaming solved the problem.

Greetings,

Uwe

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Since we might not always have a chance to clean up, hence
let's leave it to the OS.

Furthermore, try to clean up as much as we can.

### CODE REVIEW

**Comment by kozec** [comment]
Hmmm.. Let's say, for example, that I want to synchronize 20GB file from PC A to PC B. Wouldn't this create 20GB file in my /tmp directory? Because that would be bad for really lot of reasons...

**Comment by AudriusButkevicius** [comment]
Yes, this is for basic stuff, not for files.

**Comment by AudriusButkevicius** [comment]
Not sure why the tests are failing: `invalid cross-device link`
Why does rename try to do hard-linking?

**Comment by Zillode** [comment]
I also stumbled upon on this problem before. Go (or the OS) does not allow renaming across 'devices', so you need to copy the file from the temp dir to the actual dir instead of renaming it.

**Comment by kozec** [comment]
@AudriusButkevicius 
> Why does rename try to do hard-linking?

Because that's how renaming works. You create hardlink to file and then remove original. Rename syscall throws EXDEV when it's asked to move across devices and it's up to application to solve problem by copying.

**Comment by AudriusButkevicius** [comment]
So I've now reverted the fix which saved files in /tmp, due to the fact that Go's rename doesn't allow moving files cross devices.

Instead it now tries to remove any remaining temp files.

**Pull request merged**
