### PR TITLE
gui: "Syncing" favicon is no longer animated (fixes #3267)

### LINKED ISSUE #3267: Favicon should not be animated
Static syncing symbol is fine.

### PR DESCRIPTION
**Pull request by calmh**
Resaved with just first frame in Photoshop, ran pngcrush on it.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 06e63aedea18ef4c73944acfd8da416f1d4543b3. Thanks, @calmh!

**Comment by norgeous** [comment]
Do you think its worth adding something _like_ [this](https://github.com/Bahlaouane-Hamza/I-Miss-You) also, to override to default favicon on unfocussed tabs?

**Comment by AudriusButkevicius** [comment]
I don't think the animation adds any value, just a distraction, even if its on the active tab only.

**Comment by norgeous** [comment]
no, i actually agree with you - yes, remove the animation. Static is best.
but would it be a good idea to hide all (notify, sync and pause) icons unless the tab is focussed?
so that the unfocussed tab always just shows the normal (unmodified) logo
i can make an additional PR... but just wanted to check this was a wanted feature

**Comment by AudriusButkevicius** [comment]
I think thats worse, just like gmail tells you how many emails you have, regardless which tab you are looking at.

**Comment by norgeous** [comment]
cool fair point

**Pull request closed without merging**
