### PR TITLE
Remove an unwanted right parenthesis

### PR DESCRIPTION
**Pull request by GodUseVPN**
Which cause a javascript error.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by canton7** [comment]
@st-review merge it

gui: Remove erroneous right parenthesis

Skip-check: authors

**Comment by st-review** [comment]
:ok_hand: Merged as c08fe4e2c5b853f3cf5eac951bde3defe8367124. Thanks, @GodUseVPN!

**Pull request closed without merging**
