### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by HairyFotr**
### Purpose

Fixed a few typos.

### Testing

None required.

### CODE REVIEW

**Comment by calmh** [comment]
@st-review 

all: Typos

Skip-check: authors

**Comment by st-review** [comment]
I'm sorry, @calmh. I'm afraid I don't know what you mean. I know how to `don't`, `lgtm`, `merge`, `prevent`, `squash`, `stop`.

**Comment by calmh** [comment]
@st-review merge it...

all: Typos

Skip-check: authors

**Comment by st-review** [comment]
:ok_hand: Merged as 0ad10b0feeb8a035bd140613ee6226b05d70424d. Thanks, @HairyFotr!

**Pull request closed without merging**
