### PR TITLE
Don't forget some files when scanning (fixes #1780)

### LINKED ISSUE #1780: Big file broken
I am using v0.11.2 on OSX. I was transferring a file of 25GB size, and the transfer had started during the creation of the file. The file size of the original file as well of the transferred file are identical, but the content has another md5 sum. How can this happen? Is there any way of how to prevent this?
Thanks!

### PR DESCRIPTION
**Pull request by calmh**
We were not putting the last batch, or a small batch, of scanned files
into the index...

### CODE REVIEW

**Comment by calmh** [comment]
what the hell?

**Comment by calmh** [comment]
So I added 053690d in response to http://build.syncthing.net/job/syncthing-pr/550/console and now this...? /me puts down the keyboard and backs away slowly...

**Comment by Zillode** [comment]
build server needs a clean/reboot?
`14:13:50 WARNING: Stopping folder "default" - folder marker missing`
works for me

**Comment by Zillode** [comment]
@st-jenkins please run integration tests for windows

**Comment by calmh** [comment]
No this actually seems related to the change, although I'm leaning towards the test being the bad code...

**Comment by calmh** [comment]
Although it does work on my machine, too...

**Comment by calmh** [comment]
It also passes on a normal Ubuntu vm...

**Comment by calmh** [comment]
Ok, so that was a test issue, probably related to ordering that for some reason differs on the build server...

However, this bug was a misunderstanding. It doesn't exist. :) It's just that the event wasn't sent. I was wondering why this wasn't caught by the integrration tests...

**Pull request closed without merging**
