### PR TITLE
Corrected spelling in GUI message

### PR DESCRIPTION
**Pull request by brbecker**
Corrects typo of "underscode" to "underscore" in index.html and lang-tr.*

### CODE REVIEW

**Comment by calmh** [comment]
Hi! Thanks. All of the `lang-*.json` are auto generated though, so changing it in index.html is enough.

**Comment by Zillode** [comment]
@brbecker, please update your PR such that only ```gui/index.html``` is committed, thanks

**Comment by brbecker** [comment]
@Zillode, Thanks for the note. I have now done this.

**Comment by AudriusButkevicius** [comment]
You should probably add yourself to authors and squash into a single commit.

**Comment by brbecker** [comment]
@AudriusButkevicius, I think I've done this. Learning git as I go. :)

**Comment by calmh** [comment]
Merged in bb438bf

**Pull request closed without merging**
