### PR TITLE
cleanup: removed deadcode in test/util.go

### PR DESCRIPTION
**Pull request by lkwg82**
### Purpose

cleanup

### Testing

clean test suite run

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
These are probably still used if you run integration tests (rather than unit tests), yet we don't run them as they are super flaky.

**Comment by lkwg82** [comment]
I'll check.

**Comment by lkwg82** [comment]
Where can I find the integration test setup?

**Comment by AudriusButkevicius** [comment]
./build.sh docker-test

or 
```
                               ./build.sh clean \
                                && go run build.go -race \
                                && export GOPATH=$(pwd)/Godeps/_workspace:$GOPATH \
                                && cd test \
                                && go test -tags integration -v -timeout 90m -short \
                                && git clean -fxd .
```

**Comment by calmh** [comment]
```
cd test
go test -v -tags "integration benchmark"
```

many will fail, for reasons of upkeep, but lets not break compiling them :)

**Comment by AudriusButkevicius** [comment]
Can we close this now?

**Pull request closed without merging**
