### PR TITLE
[WIP] Refactor API/GUI code for testing

### PR DESCRIPTION
**Pull request by calmh**
I converted a number of concrete types to interfaces (events.BufferedSubscription, discover.CachingMux, relay.Service, logger.Recorder). These are the ones passed into the apiService constructor, so having them be interfaces mean they can be mocked out when testing. That part is fairly clean I think.

Then I extracted a Config interface (*config.Wrapper) and a Model interface (from *model.Model). These are quite large, specifically the Model interface is fucking huuuge. Of course this is an effect of the Model type itself being too large. But there are a few distinct categories of methods on it - ones related to quering sizes and statistics, ones related to connection management, ones related to scanning, etc. Potentially these could be broken out into smaller interfaces, all of which could be fulfilled by an actual *model.Model today, but could potentially be separated out later. I haven't fully thought that through yet...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Looks good, not sure why wip

**Comment by calmh** [comment]
Mostly because this

```diff
 +type Model interface {
 +	GlobalDirectoryTree(folder, prefix string, levels int, dirsonly bool) map[string]interface{}
 +	Completion(device protocol.DeviceID, folder string) float64
 +	Override(folder string)
 +	NeedFolderFiles(folder string, page, perpage int) ([]db.FileInfoTruncated, []db.FileInfoTruncated, []db.FileInfoTruncated, int)
 +	NeedSize(folder string) (nfiles int, bytes int64)
 +	ConnectionStats() map[string]interface{}
 +	DeviceStatistics() map[string]stats.DeviceStatistics
 +	FolderStatistics() map[string]stats.FolderStatistics
 +	CurrentFolderFile(folder string, file string) (protocol.FileInfo, bool)
 +	CurrentGlobalFile(folder string, file string) (protocol.FileInfo, bool)
 +	ResetFolder(folder string)
 +	Availability(folder, file string) []protocol.DeviceID
 +	GetIgnores(folder string) ([]string, []string, error)
 +	SetIgnores(folder string, content []string) error
 +	PauseDevice(device protocol.DeviceID)
 +	ResumeDevice(device protocol.DeviceID)
 +	DelayScan(folder string, next time.Duration)
 +	ScanFolder(folder string) error
 +	ScanFolders() map[string]error
 +	ScanFolderSubs(folder string, subs []string) error
 +	BringToFront(folder, file string)
 +	ConnectedTo(deviceID protocol.DeviceID) bool
 +	GlobalSize(folder string) (nfiles, deleted int, bytes int64)
 +	LocalSize(folder string) (nfiles, deleted int, bytes int64)
 +	CurrentLocalVersion(folder string) (int64, bool)
 +	RemoteLocalVersion(folder string) (int64, bool)
 +	State(folder string) (string, time.Time, error)
 +}
```

is :scream: 

But maybe that's just the way it is until we maybe, hopefully, at some point refactor that a bit.

**Comment by AudriusButkevicius** [comment]
Atleast to reduce the model.go, we could split definitions into separate files model_conns.go model_stats.go if goes permits that.

**Comment by AudriusButkevicius** [comment]
Thougj yeah, having smaller interfaces would be nicer.

**Comment by calmh** [comment]
So I don't want to export the interfaces, I can't call them `model` and `config` because that conflicts with the package names, and `modelIntf`, `configIntf` works but feels like Java. Other opinions? Otherwise I think this is mergeable and I'll start looking at tests down the line, but it'll be a smaller diff on that day.

**Comment by AudriusButkevicius** [comment]
Looks good, feel free to merge.

**Comment by calmh** [comment]
@st-review merge this please

cmd/syncthing: Extract interfaces for things the API depends on

Enables testing of the API service, in the long run.

**Comment by st-review** [comment]
OK, merged as a492cfba13db36fae86b118eea4fb1d231eb9f13. Thanks, @calmh!

**Pull request closed without merging**
