### PR TITLE
cmd/strelaypoolsrv: Show popup on row hover

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Shows map popup as you hover on the table row

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

skip-check: authors

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Couldn't retrieve your user information - not merging.

**Comment by AudriusButkevicius** [comment]
@st-review merge

skip-check: authors

**Comment by st-review** [comment]
@AudriusButkevicius: Couldn't retrieve your user information - not merging.

**Comment by AudriusButkevicius** [comment]
@st-review merge

skip-check: authors

**Comment by st-review** [comment]
@AudriusButkevicius: Merge failed:

```
$ git fetch -f origin refs/pull/4201/head:pr-4201
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   7a15fef..3395992  master     -> orig/master
$ git reset --hard
HEAD is now at 3395992 gui: Make icons and directory information in local device summary consistent with folders (fixes #4100)
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 3395992 gui: Make icons and directory information in local device summary consistent with folders (fixes #4100)
$ git clean -fxd
$ git merge --squash --no-commit pr-4201
Updating 3395992..ad6f0ef
Fast-forward
Squash commit -- not updating HEAD
 cmd/strelaypoolsrv/gui/index.html | 13 ++++++++-----
 1 file changed, 8 insertions(+), 5 deletions(-)
$ git commit -F -
Commit message subject:

    skip-check: authors

doesn't look like "tag: One sentence description". Specifically, it doesn't
match this pattern:

    ^[\w/,\. ]+: \w

```

**Comment by AudriusButkevicius** [comment]
@st-review merge

skip-checks: authors

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
@st-review retest

**Comment by st-review** [comment]
I'm sorry, @AudriusButkevicius. I'm afraid I don't know what you mean. I know how to `don't`, `lgtm`, `merge`, `prevent`, `squash`, `stop`.

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest

**Comment by AudriusButkevicius** [comment]
@st-jenkins test this please helooo?

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
this is the future, talking to robots on a wednesday evening.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as d637148ccae04b59bf096c1aa59f80bed8f7373e. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
