### PR TITLE
Change remote device table column proportions

### LINKED ISSUE #4531: GUI folder/device status rows should handle longer values nicer
Hi,
in the WebGui, can we have the full view on IPV6 adresses?

They are unreadable because of the "..." at the end of each adress.

Steps to reproduce:

Open the WebGUI and open Remote Devices to see some IPs

 - what you expected to happen instead

The whole IP Adress, so I can compare or textcopy them.

Versions:
Syncthing Version: v0.14.40, 64Bit on Mac/Linux/Windows
OS Version: Windows 7 / Mac OSX Sierra
Browser Version: FireFox / Safari 

Screenshots:
bildschirmfoto 2017-11-19 um 21 19 43

bildschirmfoto 2017-11-19 um 21 30 30

### PR DESCRIPTION
**Pull request by otbutz**
### Purpose

Fixes #4531

### Screenshots

Large:
grafik

Medium:
grafik

Small:
grafik

### CODE REVIEW

**Comment by calmh** [comment]
You're making the label column rather narrow. What happens in translations with longer labels? It looks like the IPv6 address flows nicely under the label, but it also happens to already be on a lower line - what happens if it's on the same line as the label?

**Comment by otbutz** [comment]
grafik

Better?

The table-layout is now `auto` and the `th` column scales based on its content using `width: 1px;`. The `td` claims only the remaining space with `max-width: 0px;`

https://github.com/otbutz/syncthing/tree/fit-to-content

**Comment by otbutz** [comment]
@calmh should I open a second pull request for my first commit? I think that it's fix for a regression in the current master branch: https://github.com/syncthing/syncthing/pull/5565/commits/321e3c0b9e1bee573dc3b37e9aa8998907245f62

**Comment by otbutz** [comment]
I haven't tested it but it seems reasonable to use it for them as well.

**Comment by otbutz** [comment]
@calmh Give it a spin ;)

**Comment by calmh** [comment]
👌

**Pull request merged**
