### PR TITLE
Change Bottom Bar links to a new tab/window

### PR DESCRIPTION
**Pull request by Rewt0r**
Was getting kinda annoying clicking links in the footer and it navigating away from the page, I've added "_blank" as the target to those links.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Same as #1240 though...

**Comment by Rewt0r** [comment]
Whoops! Apologies..

**Comment by calmh** [comment]
@st-jenkins add to white list

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
Yeah, but this one is mergeable...

**Pull request merged**
