### PR TITLE
fix(gui): apply small screen CSS changes earlier (fixes #9590)

### LINKED ISSUE #9590: WebUI table column widths broken on iPhone 12 Pro Max and wider
### What happened?

On more recent iPhones with larger screens, including:
- iPhone 12 Pro Max
- iPhone 13 Pro Max
- iPhone 14 Plus
- iPhone 14 Pro Max
- iPhone 15 Plus
- iPhone 15 Pro Max

the pixel width is greater than the 419px max-width threshold for triggering the narrow-screen configuration, so some WebUI elements display incorrectly, i.e. truncating long strings and wrapping rows of buttons without proper vertical spacing, as shown in this screenshot:

IMG_7110

The pixel widths for these devices is 428 or 430 pixels.

This is seen on Firefox on iOS (connecting a Synology version of Syncthing), but should be browser-independent.

I will provide a PR.

### Syncthing version

v1.27.8

### Platform & operating system

Linux (64-bit Intel/AMD)

### Browser version

iOS Firefox v127.0

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by imsodin**
These CSS overrides address issues that are already present on wider screens, so apply it there. Some experiments show we might even want to up the limit more, but I am chicken and lazy, so I propose to use the existing 470px media block.

Supersedes another PR after not getting any reaction to feedback there: https://github.com/syncthing/syncthing/pull/9591#issuecomment-2212586134

### CODE REVIEW

**Comment by imsodin** [comment]
@tomasz1986 and @acolomb - you meddle with this CSS every now and then, so you may have opinions/input. This change is just me doing something that seems sensible, and has the desired effects on the issues pointed out in #9590 - I have no idea what other effects it might have :)

**Comment by tomasz1986** [comment]
Thanks, I will try to test this, as I've also seen those issues a long time ago already, but I didn't feel like touching anything in the existing code too much in fear of breaking something else.

For the record, I also saw https://github.com/syncthing/syncthing/pull/9591, however those breakpoints, or at least some of them, come from Bootstrap, so I think it would be better to leave the specific `px` values as is.

I also wonder why the `420px` breakpoint was added there originally, as there must have been a valid reason for that (since this code is in the overrides file).

**Comment by imsodin** [comment]
This is the original issue and PR related to this code:

https://github.com/syncthing/syncthing/issues/5774
https://github.com/syncthing/syncthing/pull/5787

There's some talk there about "bootstrap xs breakpoint", so I assume that's the same/something similar as you are referencing. If those values come from there, it would be great to have comments saying that. Such that no-context noobs like myself don't come in messing things up :)

I really have no clue what I am doing, I just saw a reasonable problem description and possible solution in that PR (as in I played around with my desktop browser and it seemed to make sense - though I can't promise that was representative/correct), and just wanted to get that to a point where it's mergeable. If you believe there are dragons here, just tell me to stop meddling with things I don't understand and I'll close this PR - I have no appetite to learn the ins and outs of this :)

**Comment by tomasz1986** [comment]
> There's some talk there about "bootstrap xs breakpoint", so I assume that's the same/something similar as you are referencing. If those values come from there, it would be great to have comments saying that. Such that no-context noobs like myself don't come in messing things up :)

They are the same thing, and the actual points are as follows:

```
/* Extra small devices (phones, up to 480px) */
/* No media query since this is the default in Bootstrap */

/* Small devices (tablets, 768px and up) */
@media (min-width: @screen-sm) { ... }

/* Medium devices (desktops, 992px and up) */
@media (min-width: @screen-md) { ... }

/* Large devices (large desktops, 1200px and up) */
@media (min-width: @screen-lg) { ... }
```

Our code uses `max-width`, so the pixel values should be `479px`, `767px`, `991px`, and `1199px` (which is currently the case in the overrides code). However, there doesn't seem to be any basis for `420px` (or `419px`) in Bootstrap itself. Because of this, I think your change to merge the code into the existing `479px` breakpoint makes perfect sense, but I will try testing it in real life and come back with my observations 🙂.

Just for the record, I'm only talking about Bootstrap 3 here.

**Comment by tomasz1986** [comment]
I've just tested the code. I think it is sensible to merge everything into the `479px` breakpoint, as the PR does. I've also checked what happens if you merged all this into the next upper breakpoint, but then the GUI looked off, as there was plenty of space and really no need to move the right table column below.

On a side note, strictly speaking, following Bootstrap, the line below should use `767px` instead of `768px`, but I'm not sure if the fix fits into this PR?

https://github.com/syncthing/syncthing/blob/6d64daaba326ba8378c700e00a31e425c7c90579/gui/default/assets/css/overrides.css#L404

**Comment by acolomb** [comment]
Sorry I'm also no good at web design and such.  Starting to feel dizzy already when reading about these pixel-width based responsive design classes...  I guess there are many people researching this and putting their optimizations into Bootstrap, so let's leave it them as far as possible.  Are we like up-to-date on that library at all?

**Comment by tomasz1986** [comment]
> Are we like up-to-date on that library at all?

No, our Bootstrap version is long obsolete. The newer ones aren't a drop-in replacement though. In the past, I've tried switching to Bootstrap 4 locally, but it changes the GUI quite dramatically, so a lot of tweaks would be required to make it work. Even more for Bootstrap 5.

**Review by calmh — APPROVED** [review]

**Comment by imsodin** [comment]
@tomasz1986 

> On a side note, strictly speaking, following Bootstrap, the line below should use `767px` instead of `768px`, but I'm not sure if the fix fits into this PR?

Yep, I'd rather not - that's unrelated to this change. If you could do that in a separate PR together with adding comments to existing media blocks like in your comment above, that would be great (https://github.com/syncthing/syncthing/pull/9756#issuecomment-2395138782).

**Comment by imsodin** [comment]
Policybot thinks no contributor has approved - somehow it doesn't see Jakobs approval?! Anyway, I am force merging.

**Pull request merged**
