### PR TITLE
cmd/syncthing: Add fswatcher and remove useAPIKey stats

### PR DESCRIPTION
**Pull request by imsodin**
This adds usage reporting for the filesystem notification feature and removes the useAPIKey field as requested by @AudriusButkevicius.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
You'll have to fix your own tests :)

**Comment by imsodin** [comment]
(◣_(◣_(◣_◢)_◢)_◢)

**Comment by imsodin** [comment]
Fixed by rerun. I will commit a "permanentish fix" (=make this less likely to happen).

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 55b63941b86ca745ff84783b596449f76db7b44d. Thanks, @imsodin!

**Pull request closed without merging**
