### PR TITLE
systemd units for system/user

### PR DESCRIPTION
**Pull request by peterhoeg**
@encbladexp - any comments?

I added a configuration file for both system and user sessions so people can choose how to run it.

I changed the Restart= to on-failure as you will otherwise not be able to exit syncthing from inside the application.

### CODE REVIEW

**Comment by xuhdev** [comment]
Any progress to merge this?

**Comment by rumpelsepp** [comment]
Just forgot to post this. Arch Linux provides systemd service files for syncthing as well. They can be used for some ideas, references, ...

https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/syncthing

**Comment by calmh** [comment]
This just needs a README and a rename of the directory and we're good to merge.

**Comment by peterhoeg** [comment]
@calmh There you go.

**Comment by calmh** [comment]
Perfect, thanks!

**Comment by calmh** [comment]
Can I also ask you to rebase this onto the current master, since it's currently otherwise a merge from *way* back?

**Comment by peterhoeg** [comment]
@calmh Here you go.

**Comment by calmh** [comment]
Merged, thanks for the patience! :)

**Pull request closed without merging**
