### PR TITLE
cmd/syncthing: Implement "release candidate" logic

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Implement the upgrade and usage reporting things for release candidates.

### Testing

I tagged it and ran a couple of local tests, looked good to me...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 1c9361a8188351ea52f68c4204ca24d4677e4fc7. Thanks, @calmh!

**Pull request closed without merging**
