### PR TITLE
Updates for Go 1.5

### PR DESCRIPTION
**Pull request by calmh**
- Use different style linker arguments if Go > 1.4 is detected.
- Darwin/386 and Dragonfly/386 are deprecated. These guys can build for themselves, or a separate build job can do it with the older compiler/runtime.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
This will also need some shifting in packages, to allow cli and others to work

**Comment by calmh** [comment]
(Needs corresponding updates in cli, discosrv and so on of course)

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests

**Comment by AudriusButkevicius** [comment]
Can you rebase and lets merge

**Comment by uok** [comment]
official release of Go 1.5 - https://blog.golang.org/go1.5

**Pull request merged**
