### PR TITLE
gui: Add Docs help links to each setting in Advanced Configuration

### PR DESCRIPTION
**Pull request by tomasz1986**
Add a link next to each setting's label to its explanation in the Docs.
This way, it is easy to quickly check what the setting is about without
going to the Docs site separately and searching for it manually.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### CODE REVIEW

**Comment by tomasz1986** [comment]
This is how it looks like.



WIP, as this will only work if 

1. https://github.com/syncthing/docs/pull/607 is implemented.

2. all settings are actually documented. Right now, a few are still missing from the Docs.

**Comment by imsodin** [comment]
This is likely to generate links pointing at nothing. In my opinion a link to https://docs.syncthing.net/users/config.html at the top would have the same gain with less fragility/busy-work (adding the config titles).

**Comment by tomasz1986** [comment]
> This is likely to generate links pointing at nothing.

Hmm, I would not really say so. There are some missing entries, but the vast majority of the options are actually present in the Docs.

> In my opinion a link to [docs.syncthing.net/users/config.html](https://docs.syncthing.net/users/config.html) at the top would have the same gain with less fragility/busy-work (adding the config titles).

Accessing the Docs is not a big deal. The problem is that searching through that page is a major pain. I am just speaking from my own experience, but especially on touch screen devices, looking for individual entries is a nightmare.

**Comment by imsodin** [comment]
Right, and it's only a missing anchor - leaves the user still on the right page.

(We should just move the docs repo into the main one and add a lint step to ensure all options are present. Or even better autogenerate from a proto comment or something. Anyway, I am digressing :) ).

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Comment by acolomb** [comment]
I would like to see this happen as a very useful addition.  To avoid the burden of having to maintain sync between the anchor links into the docs repo, how about just using the Sphinx-generated search facility, e.g.:

https://docs.syncthing.net/search.html?q=CaseSensitiveFS

That at least gives clickable results and is not even limited to the `*.rst` files in `config/` and `advanced/`.  Maybe there is also a way to make Sphinx highlight a certain search term within a specific target page through a URL parameter?

**Comment by tomasz1986** [comment]
I personally prefer direct links, as the search may return too many results for some of the options, with the actual configuration page listed somewhere down below the less relevant ones. The links here use the same IDs as are used in `config.xml`, so as long as the Docs follow the convention (which they should, for the sake of consistency), I don't think there would be any real burden when it comes to maintenance. It was mentioned before, but even if an ID link becomes broken for some reason, it will still redirect to the configuration page, which I would say is acceptable.

What I would like to do in addition to this one though would to be have some highlighting in CSS for `:target` in the Docs, so that the linked option with its description gets automatically highlighted in yellow or something, for better visibility.

**Comment by acolomb** [comment]
Reopening as this will be very useful once https://github.com/syncthing/docs/pull/710 is merged.

**Comment by acolomb** [comment]
Please migrate to the versioned links once https://github.com/syncthing/syncthing/pull/8108 is merged.

**Comment by tomasz1986** [comment]
> Please migrate to the versioned links once #8108 is merged.

I've migrated the links 🙂.

**Comment by acolomb** [comment]
We removed the .html extension on all links, please do the same here.

**Comment by tomasz1986** [comment]
> We removed the .html extension on all links, please do the same here.

Done.

**Comment by acolomb** [comment]
Some don't work:

https://docs.syncthing.net/users/config#config-option-device.addresses
https://docs.syncthing.net/users/config#config-option-device.allowednetworks
https://docs.syncthing.net/users/config#config-option-device.deviceid
https://docs.syncthing.net/users/config#config-option-device.ignoredfolders
https://docs.syncthing.net/users/config#config-option-folder.devices
https://docs.syncthing.net/users/config#config-option-gui.usetls
https://docs.syncthing.net/users/config#config-option-options.alwayslocalnets
https://docs.syncthing.net/users/config#config-option-options.crurl
https://docs.syncthing.net/users/config#config-option-options.featureflags
https://docs.syncthing.net/users/config#config-option-options.globalannounceservers
https://docs.syncthing.net/users/config#config-option-options.listenaddresses
https://docs.syncthing.net/users/config#config-option-options.stunservers
https://docs.syncthing.net/users/config#config-option-options.unackednotificationids

The links are generated based on the JSON names used in the GUI.  The documentation is written for the XML representation.  Sometimes they use different name tags, or the plural / singular form differs (e.g. multiple `<address>` elements vs. one `addresses: [ ... ]` array).

**Comment by acolomb** [comment]
I think we can handle that gracefully by defining aliases on the individual `option` directives in the docs.  That's a manual process, but only few options to touch overall.

**Comment by acolomb** [comment]
It was actually easy to solve:  https://github.com/syncthing/docs/pull/724

**Review by calmh — APPROVED** [review]
Seems fine to me. Leaving unmerged in case I missed something that should be tweaked what with the ongoing docs changes, otherwise merge at will.

**Comment by acolomb** [comment]
Yeah it doesn't really depend on the docs changes (https://github.com/syncthing/docs/pull/724).  Until that one is merged, some generated links here will just point at the config page in general.  No big deal.

**Pull request merged**
