### PR TITLE
Use different session cookies per device

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Doesn't work. yet.

**Comment by AudriusButkevicius** [comment]
This probably works better. But for @Zillode to approve.

**Comment by Zillode** [comment]
:+1: awesome!

**Comment by calmh** [comment]
Ah. This fixes the two-guis-on-localhost thing?

**Comment by AudriusButkevicius** [comment]
Yeah

**Comment by calmh** [comment]
Neat

**Pull request merged**
