### PR TITLE
Allow limiting max conflicts (fixes #2282)

### LINKED ISSUE #2282: *.sync-conflict-*.* files growing in numbers, uncontrollably
Not sure why, but all my synced folders using syncthing show a never-ending (and only growing) number of \*sync-conflict\* files, taking up gigabytes in minutes of having syncthing running.
This 'feature' is killing one of my syncs, since it has a limited volume size of 30GB.
When I try and delete them, they just come back. I don't really understand the use of this. How do I control the number of these files, or avoid ever having more than one per file? I prefer the newest version of any file everywhere, no exceptions. And/or if the conflict disappears, or grows older than x time, have the sync-conflict files deleted automatically.
Can someone please either make this optional, or copy how btsync does this (because I never had it using that). By the way, I have versioning switched off entirely, still the same issue.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Heads up to @kozec and @canton7, as default value will be 0, means disabled conflicts.
As usual, keeping the trend, completely untested.

### CODE REVIEW

**Comment by canton7** [comment]
Cheers for the heads-up!

**Comment by calmh** [comment]
Wouldn't it be simpler to keep maxConflicts as an attribute rather than the closure business on moveForConflict?

**Comment by AudriusButkevicius** [comment]
:dizzy_face: obviously that's the right thing...

**Comment by calmh** [comment]
:+1:

**Comment by calmh** [comment]
Maybe we should have a non-unlimited default here. Five? Ten?

**Comment by polyzen** [comment]
I've only had 2 or 3 at once, but 5 feels a bit low

**Pull request merged**
