### PR TITLE
ticker test (want windows build)

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by canton7** [comment]
My current best guess is that the ticker is firing twice in succession after some time. That is, you might want a test that runs the ticker every few hundred ms for a few minutes, checking that it never fires twice in quick succession.

**Comment by calmh** [comment]
That would be a serious Windows or Go bug.

**Comment by canton7** [comment]
Or a misunderstanding of how some Windows timer works at the Go level? That would surprise me the least, I think.

I don't think clocks moving around is likely: some people see this quite repeatably when Syncthing starts up - it would be too large a coincidence if their clock happened to move around at that point.

**Comment by calmh** [comment]
Yeah. No clue.

**Pull request closed without merging**
