### PR TITLE
lib/api: extend `db/browse` to filter filename

### PR DESCRIPTION
**Pull request by cjc7373**
### Purpose
relates to #8114

This is a naive idea to make the API to provide the conflicted file list. I added a simple dfs to truncate all empty dirs in the result. This truncation is applied only when we want to filter files.

IMHO, WebUI cannot use this method to show conflict files as this API can be expensive. But this is enough for GUI wrappers like [syncthingtray](https://github.com/Martchus/syncthingtray) to combine this API and `LocalChangeDetected`, `RemoteChangeDetected` events to provide such info.

### Documentation

I'll update doc if needed.

### CODE REVIEW

**Comment by acolomb** [comment]
I only glanced at the diff to see what approach is taken.  And I don't think it's really an adequate solution for tracking creation of conflict files.  That should be handled using its own event type when the file is created.  And building a list of currently existing conflict files should probably happen during scanning, yielding a separate data structure.  In short, scanning for these on-demand doesn't feel like a clean solution to me.

But maybe other @syncthing/maintainers can chime in on whether this is an acceptable addition?

**Comment by cjc7373** [comment]
So what you mean is to have a dedicated API to search existing conflicting file list, and maintain some state in the database to track this list?

**Comment by acolomb** [comment]
Yes, except we don't need to keep it in the database IMHO, just a list in RAM. Arguably if it gets too big, we need a strategy to limit memory usage, but the API response for getting the whole list needs pagination anyway.

**Review by ufkhan4385 — APPROVED** [review]

**Comment by imsodin** [comment]
Agreed - this should either be a general purpose "glob" parameter (because that's what we already use for ignore patterns) or new funcitonality specific to conflicts.

**Comment by cjc7373** [comment]
I'll try to make a new PR

**Pull request closed without merging**
