### PR TITLE
gui: Add identicons to 'Add / Edit Folder' modal

### PR DESCRIPTION
**Pull request by norgeous**
before:
untitled

---

after:
untitled
untitled

### CODE REVIEW

**Comment by norgeous** [comment]
It doesn't look as great as I thought it would =[
maybe I should add a 'box' around / grouping the identicon and device name
or another idea, I add the identicon to bootstrap tooltip?

**Comment by norgeous** [comment]
maybe something like this:
untitled
or
untitled

comments please!

**Comment by wweich** [comment]
I like the second one (checkbox inside the "button"). But the OS checkbox looks off.
I would suggest replacing it with `glyphicon-unchecked` and `glyphicon-check` or perhaps use another way to indicate in-/active. But that will break the screen reader compatibility :(.

**Comment by uok** [comment]
Please do not add additional identicons. In my opinion they should be removed from the GUI completely as they do not help at all.

**Comment by calmh** [comment]
I could go either way with this. Like say merge this and then in another step allow a user selectable (uploadable?) avatar per device which would then take the identicons place everywhere. Yes, it's "unnecessary fluff" to some extent but it can make things more friendly and memorable. 

A device could even announce an avatar image for itself in the connection handshake.

**Comment by norgeous** [comment]
closing until we know what to do

**Comment by calmh** [comment]
I don't think this should be closed based on uoks comments above. Uok might have a point, but that point would be to use something other than identicons. This work might still be valid and would just use another icon, come that dayö

**Comment by calmh** [comment]
Any interest in finishing this off?

**Comment by norgeous** [comment]
Yes, I can do... how do you want it to look?

**Comment by calmh** [comment]
The original screen shot looked ok to me

**Comment by AudriusButkevicius** [comment]
I assume this is dead, we should close this?

**Comment by calmh** [comment]
I'd still like this, but it needs to be taken all the way.

**Pull request closed without merging**
