### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Fixes some stuff.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

vendor: Update pfilter and go-stun (fixes #4561)

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by AudriusButkevicius** [comment]
Liar liar pants on fire.

**Comment by AudriusButkevicius** [comment]
@st-review merge

vendor: Update pfilter and go-stun (fixes #4561)

**Comment by st-review** [comment]
:ok_hand: Merged as b9ed6c4c2ca7ea729c9288c5b1d61dd5b795b1a9. Thanks, @AudriusButkevicius!

**Comment by imsodin** [comment]
I need to defend the little robot: The actual reason is sneaky imsodin manually retesting to mask yet another of "his" testing failures.

**Comment by AudriusButkevicius** [comment]
You broke it, you bought it. Make sure you are around to always do that.

**Pull request closed without merging**
