### PR TITLE
gui: Some browsers force lowercase attributes

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Breaks on Chrome on Windows

### CODE REVIEW

**Comment by calmh** [comment]
`go run build.go translate` as well to update the master lang-en.json. I wonder if there is something smart we could do to with Transifex avoid having to retranslate this in all languages...

**Comment by AudriusButkevicius** [comment]
So sadly translate likes to fail on windows

**Comment by calmh** [comment]
@st-review merge this stuff, please

**Comment by st-review** [comment]
OK, merged as 490464e170759dc9d917c1d4a8df640ccd6a4d73. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
