### PR TITLE
Edit device after accepting new connection (fixes #1929)

### LINKED ISSUE #1929: Could the "add node X" to syncthing? prompt ask for a name too?
It would remove an extra step from the process. Maybe the remote host could suggest a name in its config.

### PR DESCRIPTION
**Pull request by andersonvom**
This will open the "edit device" dialogue after accepting a new device
connection. This will allow the user to specify the name of the device
or leave it blank in case they want to accept whatever the device
advertises once it connects.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
LGTM, leaving for @calmh to merge. I guess the only downside it having a one click option.

**Comment by calmh** [comment]
Sounds reasonable but I need to test. Does this mean that when a connection is accepted we just open the add-device dialog properly pre filled, or we add the device and then open the edit dialogue which can just be cancelled? The first would make sense to me, the second would feel like an extra step

**Comment by AudriusButkevicius** [comment]
I was suggesting to add a second button `Add and edit`, rather tham as replacement.

**Comment by uok** [comment]
@andersonvom thanks for contributing! I think this is a good improvement for device adding, as most people name their computers like "MyPC" and you need to change it anyways. Also you can add address and additional shares in one go.

**Comment by calmh** [comment]
OK I looked at this and it does what I hoped it did. I don't think we need this as a second button, one way to do it is plenty. However I disagree with renaming the button "Add and Edit" for the only reason that we don't have that string anywhere else and it's an unnecessary burden on all our translators when we already have "Add" and "Add Device" as alternatives. So unless someone wants to argue strongly for that, I'd merge this when that was changed.

**Comment by AudriusButkevicius** [comment]
If clicking add adds it without a name, then I am fine with Add or whatever we have now.

**Comment by AudriusButkevicius** [comment]
Needs a rebase though

**Comment by calmh** [comment]
It'd be the same effect as the current "Add Device" at the bottom right, except the device ID is already filled in, basically...

@andersonvom when you do rebase, don't attempt to merge the autogenerated crap, just regenerate it with the asset script and add that as the conflict "resolution".

**Comment by andersonvom** [comment]
I changed the button text and icon to keep the experience consistent with the existing button (+ Add Device)

**Comment by AudriusButkevicius** [comment]
One more thing, moving the date to the header, does that match the `Add/Share folder` prompt?

**Comment by calmh** [comment]
This looks good to me. I patched up the event time for share folder as well.

**Pull request merged**
