### PR TITLE
Leaflet map fix definitive: Remove circle on map

### PR DESCRIPTION
**Pull request by keevBush**
I removed circle on the map relays stats

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Why?

**Comment by keevBush** [comment]
radius change every time with Leaflet and @calmh had made a suggestion to remove it.

**Comment by calmh** [comment]
needs cleanup of random whitespace (blank lines) added here and there, otherwise lgtm. I don't know what the problem is with the circles, but they don't add much value imho

**Comment by AudriusButkevicius** [comment]
They could be made to add value, we just need to adjust the size and make them logarithmic scale.

**Comment by calmh** [comment]
At that point it might as well be a heatmap? I mean, that's what we're simulating right?

**Comment by AudriusButkevicius** [comment]
Sure, but I guess it would have to be logarithmic as well.
The idea is that we want to see where most bandwidth is being used up.

**Comment by calmh** [comment]
Okay, so we leave the broken stuff in place until someone feels like fixing it.

**Pull request closed without merging**
