### PR TITLE
Additional cases for detecting folders disappearing

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
Almost feels like panic/recover would make the code cleaner.

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests on windows

**Comment by calmh** [comment]
Sorry, I just skimmed this and though it was adding failing test cases... I realize now it's actually a bugfix, as labeled. :)

**Pull request merged**
