### PR TITLE
jenkins: Build natively on Solaris

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Allow cgo to happen on Solaris as well.

### Testing

Lets see what the builders say.

### CODE REVIEW

**Comment by calmh** [comment]
So far so good

**Comment by calmh** [comment]
@st-review merge it please

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as a72f5379fb2cfad7b9f4527f8bf4058dfe6b8d0b. Thanks, @calmh!

**Pull request closed without merging**
