### PR TITLE
Fix capitalization in HTTP-header in SOAP request (fixes #1696)

### LINKED ISSUE #1696: upnp port mapping failed 0.11.0
Hello,

I am running syncthing 0.11.0 on "Debian 3.2.63-2+deb7u1 armv5tel" and get "Failed to create UPnP port mapping" in the web interface. My router is identical to the router in #1187 and the SOAP response is the same (501 not implemented) as that issue, but my SOAP Request URL appears valid. Running STTRACE=upnp ./syncthing 2>&1 | tee ~/upnplog.txt gives me the following log. I have increased the time-out with the upnpTimeoutSeconds in .config/syncthing/config.xml.  Any further suggestion on how to troubleshoot it? 

Thanks!

upnplog.txt: 
~~~ 
[monitor] 2015/04/25 14:59:40.758906 monitor.go:94: INFO: Starting syncthing
[LZZ6Y] 2015/04/25 14:59:52.133109 main.go:399: INFO: syncthing v0.11.0 (go1.4.2 linux-arm default) unknown-user@syncthing-builder 2015-04-22 00:37:18 UTC
[LZZ6Y] 2015/04/25 14:59:52.136784 main.go:400: INFO: My ID: *************
[LZZ6Y] 2015/04/25 14:59:52.198793 main.go:673: INFO: Starting web GUI on http://127.0.0.1:8384/
[LZZ6Y] 2015/04/25 15:00:02.625250 upnp.go:97: INFO: Starting UPnP discovery...
[LZZ6Y] 2015/04/25 15:00:02.632074 upnp.go:173: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on lo
[LZZ6Y] 2015/04/25 15:00:02.636094 upnp.go:173: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on lo
[LZZ6Y] 2015/04/25 15:00:02.638029 upnp.go:173: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on eth0
[LZZ6Y] 2015/04/25 15:00:02.641520 upnp.go:192: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on eth0
[LZZ6Y] 2015/04/25 15:00:02.643145 upnp.go:198: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on eth0
[LZZ6Y] 2015/04/25 15:00:02.644560 upnp.go:173: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on eth1
[LZZ6Y] 2015/04/25 15:00:02.646669 upnp.go:192: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on eth1
[LZZ6Y] 2015/04/25 15:00:02.648284 upnp.go:197: INFO: write udp4: network is unreachable
[LZZ6Y] 2015/04/25 15:00:02.649571 upnp.go:173: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on eth0
[LZZ6Y] 2015/04/25 15:00:02.651601 upnp.go:192: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on eth0
[LZZ6Y] 2015/04/25 15:00:02.653047 upnp.go:198: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on eth0
[LZZ6Y] 2015/04/25 15:00:02.654386 upnp.go:192: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on lo
[LZZ6Y] 2015/04/25 15:00:02.655763 upnp.go:198: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on lo
[LZZ6Y] 2015/04/25 15:00:02.656994 upnp.go:192: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on lo
[LZZ6Y] 2015/04/25 15:00:02.658452 upnp.go:173: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on eth1
[LZZ6Y] 2015/04/25 15:00:02.658985 upnp.go:192: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on eth1
[LZZ6Y] 2015/04/25 15:00:02.659133 upnp.go:197: INFO: write udp4: network is unreachable
[LZZ6Y] 2015/04/25 15:00:02.660418 upnp.go:198: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on lo
[LZZ6Y] 2015/04/25 15:00:03.040224 upnp.go:229: DEBUG: Handling UPnP response:

HTTP/1.1 200 OK
ST:urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN:uuid:00000000-0000-0001-0000-687f7481bd8f::urn:schemas-upnp-org:device:InternetGatewayDevice:1
Location:http://192.168.1.1:80/igd.xml
Server: WRT120N/1.0 UPnP/1.0 UPnP-Device-Host/1.0
EXT:
Cache-Control:max-age=60
Date: Sat, 25 Apr 2015 13:03:06 GMT


[LZZ6Y] 2015/04/25 15:00:03.058012 upnp.go:401: DEBUG: [http://192.168.1.1:80/igd.xml] Found urn:schemas-upnp-org:service:WANIPConnection:1 with URL http://192.168.1.1:80/upnp/control?WANIPConnection
[LZZ6Y] 2015/04/25 15:00:03.059240 upnp.go:401: DEBUG: [http://192.168.1.1:80/igd.xml] Found urn:schemas-upnp-org:service:WANPPPConnection:1 with URL http://192.168.1.1:80/upnp/control?WANPPPConnection
[LZZ6Y] 2015/04/25 15:00:03.160065 upnp.go:124: DEBUG: UPnP discovery result 00000000-0000-0001-0000-687f7481bd8f with services:
[LZZ6Y] 2015/04/25 15:00:03.161615 upnp.go:126: DEBUG: * [urn:upnp-org:serviceId:WANIPConn1] http://192.168.1.1:80/upnp/control?WANIPConnection
[LZZ6Y] 2015/04/25 15:00:03.163115 upnp.go:126: DEBUG: * [urn:upnp-org:serviceId:WANPPPConn1] http://192.168.1.1:80/upnp/control?WANPPPConnection
[LZZ6Y] 2015/04/25 15:00:22.640762 upnp.go:198: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on lo finished.
[LZZ6Y] 2015/04/25 15:00:22.640980 upnp.go:198: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on lo finished.
[LZZ6Y] 2015/04/25 15:00:22.642752 upnp.go:198: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on eth0 finished.
[LZZ6Y] 2015/04/25 15:00:22.651846 upnp.go:198: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on eth0 finished.
[LZZ6Y] 2015/04/25 15:00:22.652054 upnp.go:151: INFO: UPnP discovery complete (found 1 device).
[LZZ6Y] 2015/04/25 15:00:22.652466 upnp.go:462: DEBUG: SOAP Request URL: http://192.168.1.1:80/upnp/control?WANIPConnection
[LZZ6Y] 2015/04/25 15:00:22.652567 upnp.go:463: DEBUG: SOAP Action: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"
[LZZ6Y] 2015/04/25 15:00:22.652657 upnp.go:464: DEBUG: SOAP Request:

<?xml version="1.0" ?>
	<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
	<s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
	<NewRemoteHost></NewRemoteHost>
	<NewExternalPort>51063</NewExternalPort>
	<NewProtocol>TCP</NewProtocol>
	<NewInternalPort>22000</NewInternalPort>
	<NewInternalClient>192.168.1.105</NewInternalClient>
	<NewEnabled>1</NewEnabled>
	<NewPortMappingDescription>syncthing-51063</NewPortMappingDescription>
	<NewLeaseDuration>0</NewLeaseDuration>
	</u:AddPortMapping></s:Body>
	</s:Envelope>

[LZZ6Y] 2015/04/25 15:00:22.885172 upnp.go:469: DEBUG: SOAP Response:

<HEAD><TITLE>501 Not Implemented</TITLE></HEAD>
<BODY><H1>501 Not Implemented</H1>
We are sorry to be unable to perform the method POST to non-script at this time.<P>
If you would like to see this capability in future
releases, send the method which failed, why you
would like to have it, and the server version Apache
to <ADDRESS>http://www.apache.org/</ADDRESS><P>
</BODY>


[LZZ6Y] 2015/04/25 15:00:22.885599 upnp.go:462: DEBUG: SOAP Request URL: http://192.168.1.1:80/upnp/control?WANIPConnection
[LZZ6Y] 2015/04/25 15:00:22.885701 upnp.go:463: DEBUG: SOAP Action: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"
~~~

wget http://192.168.1.1/igd.xml

~~~
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">

<specVersion>
	<major>1</major>
	<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.1</URLBase>

<device>
	<deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType>
	<friendlyName>Linksys WRT120N</friendlyName>
	<manufacturer>Linksys Inc.</manufacturer>
	<manufacturerURL>http://www.linksysbycisco.com/</manufacturerURL>
	<modelDescription>Internet Access Server</modelDescription>
	<modelName>WRT120N</modelName>
	<modelNumber>v1.0.01</modelNumber>
	<modelURL>http://www.linksysbycisco.com/international/</modelURL>
	<serialNumber>JUT00K503200</serialNumber>
	<UDN>uuid:00000000-0000-0001-0000-687f7481bd8f</UDN>
	<UPC>494125014380</UPC>

	<serviceList>
	<service>








		<serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType>
		<serviceId>urn:upnp-org:serviceId:L3Forwarding1</serviceId>
		<SCPDURL>/igd_l3f.xml</SCPDURL>
		<controlURL>http://192.168.1.1:80/upnp/control?Layer3Forwarding</controlURL>
		<eventSubURL>http://192.168.1.1:80/upnp/event?Layer3Forwarding</eventSubURL>
	</service>
	</serviceList>

	<deviceList>
	<device>
		<deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType>
		<friendlyName>Linksys WRT120N (WAN)</friendlyName>
		<manufacturer>Linksys Inc.</manufacturer>
		<manufacturerURL>http://www.linksysbycisco.com/</manufacturerURL>
		<modelDescription>Internet Access Server (WAN Interface Device)</modelDescription>
		<modelName>WRT120N WAN Interface</modelName>
		<modelNumber>v1.0.01</modelNumber>
		<modelURL>http://www.linksysbycisco.com/international/</modelURL>
		<serialNumber>JUT00K503200</serialNumber>
    	<UDN>uuid:00000000-0000-0001-0001-687f7481bd8f</UDN>
    	<UPC>494125014380</UPC>
		<serviceList>
		<service>
			<serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType>
			<serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId>
			<SCPDURL>/igd_wcic.xml</SCPDURL>
			<controlURL>http://192.168.1.1:80/upnp/control?WANCommonInterfaceConfig</controlURL>
			<eventSubURL>http://192.168.1.1:80/upnp/event?WANCommonInterfaceConfig</eventSubURL>
		</service>
		</serviceList>

		<deviceList>
		<device>
			<deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType>
			<friendlyName>Linksys WRT120N (WAN Con)</friendlyName>
			<manufacturer>Linksys Inc.</manufacturer>
			<manufacturerURL>http://www.linksysbycisco.com/</manufacturerURL>
			<modelDescription>Internet Access Server (WAN Connection Device)</modelDescription>
			<modelName>WRT120N WAN Connector</modelName>
			<modelNumber>v1.0.01</modelNumber>
			<modelURL>http://www.linksysbycisco.com/international/</modelURL>
			<serialNumber>JUT00K503200</serialNumber>
        	<UDN>uuid:00000000-0000-0001-0002-687f7481bd8f</UDN>
        	<UPC>494125014380</UPC>

			<serviceList>
			<service>
				<serviceType>urn:schemas-upnp-org:service:WANEthernetLinkConfig:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:WANEthLinkC1</serviceId>
				<SCPDURL>/igd_wec.xml</SCPDURL>
				<controlURL>http://192.168.1.1:80/upnp/control?WANEthernetLinkConfig</controlURL>
				<eventSubURL>http://192.168.1.1:80/upnp/event?WANEthernetLinkConfig</eventSubURL>
			</service>

			<service>
				<serviceType>urn:schemas-upnp-org:service:WANPPPConnection:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:WANPPPConn1</serviceId>
				<SCPDURL>/igd_wpc.xml</SCPDURL>
				<controlURL>http://192.168.1.1:80/upnp/control?WANPPPConnection</controlURL>
				<eventSubURL>http://192.168.1.1:80/upnp/event?WANPPPConnection</eventSubURL>
			</service>

			<service>
				<serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
				<serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>
				<SCPDURL>/igd_wic.xml</SCPDURL>
				<controlURL>http://192.168.1.1:80/upnp/control?WANIPConnection</controlURL>
				<eventSubURL>http://192.168.1.1:80/upnp/event?WANIPConnection</eventSubURL>
			</service>
			</serviceList>

		</device>
		</deviceList>

	</device>

		<device>
			   <deviceType>urn:schemas-wifialliance-org:device:WFADevice:1</deviceType>
			  <friendlyName>Linksys WRT120N (WFA)</friendlyName>
				<manufacturer>Linksys Inc.</manufacturer>
				<manufacturerURL>http://www.linksysbycisco.com/</manufacturerURL>
				<modelDescription>Internet Access Server</modelDescription>
				<modelName>WRT120N</modelName>
				<modelNumber>v1.0.01</modelNumber>
				<modelURL>http://www.linksysbycisco.com/international/</modelURL>
				<serialNumber>JUT00K503200</serialNumber>
				<UDN>uuid:00000000-0000-0001-1000-687f7481bd8f</UDN>
        			<UPC>494125014380</UPC>
			  <serviceList>
			    <service>
			      <serviceType>urn:schemas-wifialliance-org:service:WFAWLANConfig:1</serviceType>
			      <serviceId>urn:wifialliance-org:serviceId:WFAWLANConfig1</serviceId>
			      <SCPDURL>/igd_WSC_UPnP.xml</SCPDURL>
						<controlURL>/upnp/control?WFAWLANConfig</controlURL>
						<eventSubURL>/upnp/event?WFAWLANConfig</eventSubURL>
			    </service>
			  </serviceList>
		</device>
	</deviceList>

	<presentationURL>/</presentationURL>
</device>
</root>

<!--
	File		: igd.xml
	Descripte	: internet gateway device description page
	Copyright	:
	Authors		: Pert
	Date		: 03/12/2002
	Last Date	: 03/??/2002
	Version		: v1.0
-->
~~~

### PR DESCRIPTION
**Pull request by jarlebring**
Some routers are sensitive to the capitalization in  "SOAPAction" in the HTTP-header in SOAP request. See issue #1696. This modification follows the recommendation of preserving caps in HTTP-headers in go described on http://stackoverflow.com/questions/26351716/how-to-keep-key-case-sensitive-in-request-header-using-golang?lq=1

### CODE REVIEW

**Comment by calmh** [comment]
:+1: Make the commit subject `Fix capitalization in HTTP-header in SOAP request (fixes #1696)` to comply with the custom and appear in release notes, please?

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
Also, `gofmt` the file please. :)

**Comment by jarlebring** [comment]
I'm a github newbie. Do I have to add myself to AUTHORS?

**Comment by calmh** [comment]
Nope, I've done that. Thanks. For the future, amending the commit so it's correctly formatted (or whatever the review issue was) is preferred to adding extra commits for it. :)

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by jarlebring** [comment]
Ok. :+1:

**Pull request merged**
