### PR TITLE
lib/model: Fixed adding empty items to device list (fixes #8646)

### LINKED ISSUE #8646: Perhaps the list of devices contains empty elements
https://github.com/syncthing/syncthing/blob/main/lib/model/model.go#L1279

### PR DESCRIPTION
**Pull request by Ratio2**
### Purpose

Fixed an obvious typo that resulted in empty entries in the device list.

### Testing

Didn't do any testing.

For testing, you need to create 3 devices, connect 1 and 2, make 1 introducer for 2, connect 1 and 3, make sure that device 3 automatically appears on 2.

### Documentation

No need to change documentation.

## Authorship

Your name and email will be added automatically to the AUTHORS file
based on the commit metadata.

### CODE REVIEW

**Review by calmh — COMMENTED** [review]
Honestly I'm not sure what's going on here to begin with, with the copying, but assuming that it's necessary for a good reason, the whole

```
cfg.Folders = make([]config.FolderConfiguration, 0, len(folders))
for _, fcfg := range folders {
    cfg.Folders = append(cfg.Folders, fcfg)
}
```

can be replaced with the somewhat shorter

```
cfg.Folders = append([]config.FolderConfiguration{}, 0folders...)
```

and the same for devices...

**Comment by calmh** [comment]
(Fixed since)

**Comment by rasa** [comment]
@calmh Fixed how?
https://github.com/Ratio2/syncthing/blob/09e4b0108397e6b682ef7ce12ae788fc0f8d65b9/lib/model/model.go#L1275-L1282 still shows:
```go
			cfg.Folders = make([]config.FolderConfiguration, 0, len(folders))
			for _, fcfg := range folders {
				cfg.Folders = append(cfg.Folders, fcfg)
			}
			cfg.Devices = make([]config.DeviceConfiguration, len(devices))
			for _, dcfg := range devices {
				cfg.Devices = append(cfg.Devices, dcfg)
			}
```

**Comment by calmh** [comment]
Ah, it hasn't, I fooled myself by being on the PR branch when looking at it 🤦  Thanks for catching that.

**Pull request merged**
