### PR TITLE
cmd/syncthing: Correctly set, parse and compare modified time HTTP headers (fixes #3165)

### LINKED ISSUE #3165: Syncthing uses incorrect timezone for Last-Modified header
Syncthing sets the Last-Modified header on static assets to the time at which the config was last committed. However, it sets a local time, whereas the docs for `http.TimeFormat` specify that the time must be UTC.

This can result in a Last-Modified time in the future for timezones ahead of GMT, or a time before the config was committed for timezones behind GMT.

This is probably partially responsible for the reports of the UI showing "Unknown Device" with an empty folder list when people upgrade to 0.13. I say "partially" because I know there have been reports from people ahead of GMT, so something else is at play as well here....

See [here](https://github.com/syncthing/syncthing/blob/4bc2b3f3690c755a8ffb22862915e286bdc24702/cmd/syncthing/gui.go#L1257), [here](https://github.com/syncthing/syncthing/blob/4bc2b3f3690c755a8ffb22862915e286bdc24702/cmd/syncthing/gui.go#L1300), and [here](https://github.com/syncthing/syncthing/blob/4bc2b3f3690c755a8ffb22862915e286bdc24702/cmd/syncthing/gui.go#L301).

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Don't respond with NotModified when that is a lie.

### Testing

Tricky! The mock HTTP server serves assets from disk which doesn't suffer from this.

@canton7 to test the build and verify :)

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Can I just merge?

**Comment by calmh** [comment]
No, hang on

**Comment by calmh** [comment]
It was wrong on the first attempt so it might well be now. canton7 is testing on irc

**Comment by canton7** [comment]
@st-jenkins merge it please!

**Comment by st-review** [comment]
:ok_hand: Merged as 98734375f2e410c49969704fde13b13ffbac063b. Thanks, @calmh!

**Pull request closed without merging**
