### PR TITLE
cmd/strelaysrv: Fix a few connection and routine leaks (fixes #4245)

### LINKED ISSUE #4245: relay server eats ram
Hi, 

continuing https://forum.syncthing.net/t/relay-server-ram-memory-usage/10086/6 here.

I stopped the relay server with -SIGQUIT and here is the log file:
https://163.172.132.71/strelaysrv.log

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
...

### CODE REVIEW

**Comment by calmh** [comment]
Ok apart from not actually building and stuff. Maybe set timeouts on the http server, like we do on the api server in Syncthing iirc

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 94acc20dd63488d7b735339da3efa80f5d1df7ba. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
