### PR TITLE
Remove KCP (fixes #4737)

### LINKED ISSUE #4737: Remove KCP
The KCP implementation didn't live up to our expectations and should be removed. We will aim to add TCP hole punching when the required support in standard library is available, and monitor for other suitable technologies in the meantime.

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Less KCP.

### Testing

Uhm.

### CODE REVIEW

**Comment by calmh** [comment]
@canton7 @Nutomic @kozec This outright removes fields from the config. We'll still accept (and ignore) them when posted, but they'll be missing in the JSON we produce. Problem?

**Comment by AudriusButkevicius** [comment]
We should make sure we don't complain about unknown addresses.

**Comment by calmh** [comment]
Ah, good point

**Comment by Nutomic** [comment]
The only fields that change are DefaultKCPPort and DefaultStunServers, right? I've never used them so it will be fine.

**Comment by canton7** [comment]
Nope, doesn't affect me.

**Comment by AudriusButkevicius** [comment]
So having checked lib/connections, this probably needs a new error type errDeprecated in getDialerFactory that does not cause a l.Info.

**Comment by AudriusButkevicius** [comment]
Otherwise this looks good.

**Pull request merged**
