### PR TITLE
lib/nat, lib/connections: Fix a few issues with NAT traversal

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Can't really test this as my router is now in such a broken state that I can't even log in to enable UPnP.
Yet I refuse to pay 30GBP to the ISP for a new one as I hope to move houses soon.

This is coming from here:

https://forum.syncthing.net/t/upnp-not-working-since-upgrade-to-0-13/7475/12

### CODE REVIEW

**Comment by calmh** [comment]
Space at the end of a comment triggering fmt, I think. Otherwise LGTM

**Comment by AudriusButkevicius** [comment]
Github editor sucks

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 87701339fee7324c90c975b947fef2a5dafa0b0c. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
