### PR TITLE
Cleanup markdown inline link mess

### PR DESCRIPTION
**Pull request by rumpelsepp**
I just wanted to add the freenode webchat link, because people who are
not used to irc can join the chatroom instantly. I tried to clean up the
markdown file a bit and moved the links to the footer; that makes the
"source code" less ugly.

In the end I am not sure what's nicer; either having these ugly inline links or shifting link id numbers when inserting a new link in the middle... I just leave this worldshaking work here, because it is better than reverting everything again and just add the freenode link. :dancer:

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I guess I prefer it the old way.

**Comment by rumpelsepp** [comment]
> I guess I prefer it the old way. Leaving it to @calmh

Me too, I think... I'm fine with reverting that mess I have created. :dancers:

**Comment by calmh** [comment]
Actually I think rumpelsepps way is neater. :) Can you fix the build status badges crap while you're anyway at it?

**Comment by rumpelsepp** [comment]
> Can you fix the build status badges crap while you're anyway at it?

Sure. What's better? numeric ids or keywords?

```
[awesome link][1]

[1]: http://foo.bar
```

or

```
[awesome link][awesome_id]

[awesome_id]: http://foo.bar
```

**Comment by calmh** [comment]
Numerics look more like a footnote to me, which is nice. Ids don't require renumbering, which is nice. (I guess numerics technically don't either, but tidyness would require it anyway.)

**Comment by rumpelsepp** [comment]
> Can you fix the build status badges crap while you're anyway at it?

Tried to fix it. It looks better now, but still ugly. :/

**Comment by AudriusButkevicius** [comment]
I think you can use [#] without having to type numbers.

**Comment by calmh** [comment]
LGTM. What do you mean who has problems with the links?

**Comment by rumpelsepp** [comment]
screenshot from 2015-09-14 23-06-42

> I think you can use [#] without having to type numbers. 

Ahh. Will have a look at this and fix it. :+1:

**Comment by calmh** [comment]
I think the shields.io thing serving that badge is just crap now and then and you get the alt text instead. Automatic numbering sounds scary, and annoying to keep track of when adding a link somewhere in the middle?

**Comment by AudriusButkevicius** [comment]
Agree, screw the numbering :D

**Comment by rumpelsepp** [comment]
I have updated this PR. I have omitted the badge crap, because it does not look better at all and it is more confusing than just copy & paste from the badge homepage.

**Pull request merged**
