### PR TITLE
lib/model: Fix lock order

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
generateClusterConfig acquires fmut :(

### CODE REVIEW

**Comment by calmh** [comment]
But I wonder, was there a good reason we were holding pmut while sending the clusterconfig?

**Comment by AudriusButkevicius** [comment]
I can't see one.

**Comment by calmh** [comment]
The "clusterconfig on closed connection" thing comes to mind, if a connection is closed or switched between pmut is released and clusterconfig is called.

**Comment by AudriusButkevicius** [comment]
Yeah but this is the generation part, and the error happens on receive

**Comment by calmh** [comment]
Lets try I guess

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as aa3ef49dd7f632d8aae62dd26cf424915e3806bd. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
