### PR TITLE
cleanup: removed deadcode in connection/tcp_listen.go

### PR DESCRIPTION
**Pull request by lkwg82**
### Purpose

cleanup

### Testing

run test suite

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 935c273c8f9905e46fe65a0c7524248a1d0ff4a2. Thanks, @lkwg82!

**Comment by AudriusButkevicius** [comment]
We should add these scans of yours as part of the github checks.

**Comment by lkwg82** [comment]
yes ... I'll prepare PRs for `build.go`

**Comment by AudriusButkevicius** [comment]
I don't think it's in build.go. I think it's somewhere in jenkins.

**Comment by lkwg82** [comment]
mhm, I thought these checks will be *called* in jenkins and declared in `build.go`?

**Comment by AudriusButkevicius** [comment]
Currently we just have
```
#!/bin/bash
set -euo pipefail

# Check for incorrectly formatted code
unformatted=$(gofmt -l $(find cmd/ lib/ -name \*.go))
if [ -z "$unformatted" ] ; then
    echo "Files formatted correctly"
    exit 0
else
    echo Files need gofmt:
    echo "$unformatted"
    exit 1
fi
```

which publishes stuff back into github.

**Comment by lkwg82** [comment]
lets continue in #3085

**Comment by calmh** [comment]
This should have been `lib/connection: Remove dead code` or similar, not `cleanup: `.

**Comment by lkwg82** [comment]
as this was reintroduced, it will be with the correct comment ;)

**Pull request closed without merging**
