### PR TITLE
Update lang-ko-KR.json

### PR DESCRIPTION
**Pull request by dcyang**
changed the possibly misleading Korean translation of "Out of Sync"
"동기화 실패" (literally "sync failed") -> "미동기화" ("unsynchronized" or "yet to be synchronized")

### Purpose

a better translation of "Out of Sync" to Korean

### Testing

Try the above 2 Korean expressions in Google translate.
(in addition to my claim of being a native Korean speaker)

## Authorship

Your name and email will be added automatically to the AUTHORS file
based on the commit metadata.

### CODE REVIEW

**Comment by tomasz1986** [comment]
Translations are handled at https://transifex.com/syncthing, so you would need to register there and apply to become a translator for Korean first if you want to submit the changes yourself. With this particular translation, I see what you mean, and I will add the fix today. Thanks for noticing the problem! If you find any other examples that could be improved, please use Transifex (or you could also drop a comment on the forum at https://forum.syncthing.net).

**Comment by joe128** [comment]
Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: David 창모 Yang ***@***.***> Datum: 07.10.22  11:33  (GMT+01:00) An: syncthing/syncthing ***@***.***> Cc: Subscribed ***@***.***> Betreff: [syncthing/syncthing] Update lang-ko-KR.json (PR #8588) changed the possibly misleading Korean translation of "Out of Sync"

"동기화 실패" (literally "sync failed") -> "미동기화" ("unsynchronized" or "yet to be synchronized")

Purpose

a better translation of "Out of Sync" to Korean

Testing

Try the above 2 Korean expressions in Google translate.

(in addition to my claim of being a native Korean speaker)

Authorship

Your name and email will be added automatically to the AUTHORS file

based on the commit metadata.







You can view, comment on, or merge this pull request online at:

  https://github.com/syncthing/syncthing/pull/8588



Commit Summary



  3c9489b  Update lang-ko-KR.json





File Changes  (1 file)



  

    M

    gui/default/assets/lang/lang-ko-KR.json

    (6)

  





Patch Links:



  https://github.com/syncthing/syncthing/pull/8588.patch

  https://github.com/syncthing/syncthing/pull/8588.diff

**Comment by joe128** [comment]
dyVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: David 창모 Yang ***@***.***> Datum: 07.10.22  11:33  (GMT+01:00) An: syncthing/syncthing ***@***.***> Cc: Subscribed ***@***.***> Betreff: [syncthing/syncthing] Update lang-ko-KR.json (PR #8588) changed the possibly misleading Korean translation of "Out of Sync"

"동기화 실패" (literally "sync failed") -> "미동기화" ("unsynchronized" or "yet to be synchronized")

Purpose

a better translation of "Out of Sync" to Korean

Testing

Try the above 2 Korean expressions in Google translate.

(in addition to my claim of being a native Korean speaker)

Authorship

Your name and email will be added automatically to the AUTHORS file

based on the commit metadata.







You can view, comment on, or merge this pull request online at:

  https://github.com/syncthing/syncthing/pull/8588



Commit Summary



  3c9489b  Update lang-ko-KR.json





File Changes  (1 file)



  

    M

    gui/default/assets/lang/lang-ko-KR.json

    (6)

  





Patch Links:



  https://github.com/syncthing/syncthing/pull/8588.patch

  https://github.com/syncthing/syncthing/pull/8588.diff

**Comment by joe128** [comment]
::YY::::::::YVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: David 창모 Yang ***@***.***> Datum: 07.10.22  11:33  (GMT+01:00) An: syncthing/syncthing ***@***.***> Cc: Subscribed ***@***.***> Betreff: [syncthing/syncthing] Update lang-ko-KR.json (PR #8588) changed the possibly misleading Korean translation of "Out of Sync"

"동기화 실패" (literally "sync failed") -> "미동기화" ("unsynchronized" or "yet to be synchronized")

Purpose

a better translation of "Out of Sync" to Korean

Testing

Try the above 2 Korean expressions in Google translate.

(in addition to my claim of being a native Korean speaker)

Authorship

Your name and email will be added automatically to the AUTHORS file

based on the commit metadata.







You can view, comment on, or merge this pull request online at:

  https://github.com/syncthing/syncthing/pull/8588



Commit Summary



  3c9489b  Update lang-ko-KR.json





File Changes  (1 file)



  

    M

    gui/default/assets/lang/lang-ko-KR.json

    (6)

  





Patch Links:



  https://github.com/syncthing/syncthing/pull/8588.patch

  https://github.com/syncthing/syncthing/pull/8588.diff

**Pull request closed without merging**
