### PR TITLE
gui: Improved header nav for mobile (fixes #3218)

### LINKED ISSUE #3218: gui: Mobile top bar is (still) crap
screen shot 2016-05-30 at 10 18 59

1000 yard stare tom lea

### PR DESCRIPTION
**Pull request by norgeous**
untitled

#3218

### CODE REVIEW

**Comment by norgeous** [comment]
good to go. please check it

**Comment by calmh** [comment]
:+1:

**Comment by calmh** [comment]
@st-review merge it

gui: Improve navigation header layout on mobile

**Comment by st-review** [comment]
:ok_hand: Merged as 36c6a1955f47530604355bc4d39b1104e0b1db92. Thanks, @norgeous!

**Comment by calmh** [comment]
Forgot the fixes... Ah well.

**Pull request closed without merging**
