### PR TITLE
Relicense to MPLv2

### PR DESCRIPTION
**Pull request by calmh**
This pull request updates the license on all existing code to MPLv2, replacing GPLv3. This pull request is for approval by all existing contributors.

Discussion of this change is not to happen on this PR - there is a discussion thread here that's free for all: https://discourse.syncthing.net/t/syncthing-is-going-to-be-relicensed-as-mplv2/2006. Comments on this PR that are not approval/disapproval from contributors or technical issues with the proposal (files missed in the update, etc) will be deleted.

### CODE REVIEW

**Comment by calmh** [comment]
For approval by:

@AudriusButkevicius
@cqcallaw
@KayoticSully
@filoozoom
@uok
@jedie
@pluby
@krozycki
@tojrobinson
@seehuhn
@pyfisch
@jpjp
@alex2108
@Zillode
@snnd
@rumpelsepp
@peterhoeg
@marclaporte
@frioux
@bigbear2nd
@veeti
@qbit
@marcindziadus
@kozec
@bsidhom
@Cathryne
@tnn2
@timabell
@piobpl
@philips
@mvdan
@gillisig
@facastagnini
@ceh
@cdata
@brendanlong
@asdil12
@andrew-d
@Vilbrekin
@Rewt0r
@Nutomic

**Comment by rumpelsepp** [comment]
:+1:

**Comment by veeti** [comment]
:+1:

**Comment by AudriusButkevicius** [comment]
:+1:

**Comment by tojrobinson** [comment]
:+1:

**Comment by piobpl** [comment]
:+1:

**Comment by ceh** [comment]
:+1:

**Comment by pyfisch** [comment]
:+1:

**Comment by Zillode** [comment]
:+1:

**Comment by uok** [comment]
:+1:

**Comment by gillisig** [comment]
:+1:

**Comment by qbit** [comment]
:+1:

**Comment by filoozom** [comment]
:+1:

**Comment by asdil12** [comment]
:+1:

**Comment by Cathryne** [comment]
:+1:

**Comment by frioux** [comment]
++

-- 
sent from a rotary phone, pardon my brevity

**Comment by tnn2** [comment]
ok

**Comment by marcindziadus** [comment]
+1

**Comment by mvdan** [comment]
:+1:

**Comment by pluby** [comment]
:+1:

**Comment by alex2108** [comment]
:+1:

**Comment by timabell** [comment]
:+1:

**Comment by brendanlong** [comment]
:+1:

**Comment by Vilbrekin** [comment]
:+1:

**Comment by bsidhom** [comment]
:+1:

**Comment by kozec** [comment]
+1 for every from those 4 lines of mine :-)

**Comment by philips** [comment]
+1

**Comment by cqcallaw** [comment]
I personally dislike re-licensing to a license that does less to protect and promote user freedom, but I'm definitely in the minority here, so I'll reluctantly give my :+1:

**Comment by seehuhn** [comment]
ok with me

**Comment by andrew-d** [comment]
:+1: from me :smile:

**Comment by cdata** [comment]
:+1:

**Comment by Nutomic** [comment]
:+1:

**Comment by Rewt0r** [comment]
:+1:

**Comment by marclaporte** [comment]
+1

**Comment by peterhoeg** [comment]
:+1:

**Comment by bencurthoys** [comment]
+1

**Comment by bigbear2nd** [comment]
:+1:

**Comment by jpjp** [comment]
:+1:

**Comment by snnd** [comment]
:+1:

**Comment by moshen** [comment]
:+1:

**Comment by calmh** [comment]
Currently missing:

@KayoticSully
@jedie
@krozycki
@facastagnini

Are you guys there? :)

**Comment by jedie** [comment]
I see it as https://github.com/syncthing/syncthing/pull/1421#issuecomment-77762754 but ok: :+1: ;-/

**Comment by calmh** [comment]
@jedie Understood, and with thanks.

**Comment by kilburn** [comment]
:+1:

**Comment by facastagnini** [comment]
:+1:

**Comment by kamadak** [comment]
:+1:

**Comment by pascalj** [comment]
:+1:

**Comment by krozycki** [comment]
:+1:

**Comment by dzarda** [comment]
:heavy_check_mark:

**Comment by sciurius** [comment]
+1

**Comment by KayoticSully** [comment]
:+1:

**Comment by calmh** [comment]
\o/

**Pull request merged**
