### PR TITLE
Walk ignored directories

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Because content inside the directories might be excluded from ignores

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
This is actually not enough as the tree of directories we need will not exist.

**Comment by calmh** [comment]
A *really* neat extension of this would be for the ignore matcher to be aware of the exclusions and return that information in the `Match(...)` call somehow. Then we could prune ignore directories that don't have any excludes, and only descend into directories where something deeper is excluded. Not necessarily needed in step one, though.

**Comment by AudriusButkevicius** [comment]
Another possible way (not sure, is this possible?) would be to translate:
```
!please/exclude/this/file
*
```
to:
```
!please/exclude/this/file
!please/exclude/this
!please/exclude
!please
*
````

This way `matcher.Match("please") == false`, and so on, still allowing us to skip directories which are ignored.

**Comment by AudriusButkevicius** [comment]
Can you see any reason why my above idea wouldn't work?
We could also prioritize exclusions over inclusions (potentially traversing the whole pattern set for each file)

**Comment by calmh** [comment]
Sounds like it ought to work... That way is just a change to the pattern matcher then, which is nice.

**Comment by AudriusButkevicius** [comment]
Hmm, how do we handle:
`!exclude/**/this` and `!and/exclude/*/that`

**Comment by calmh** [comment]
Tricky. I'm looking around for what other things do, but can't find a good example of something else that supports doing this. It feels like we should maybe stick to something simpler, i.e. copy the behavior of something existing exactly...

**Comment by AudriusButkevicius** [comment]
Or just skip supporting the two cases...

**Comment by calmh** [comment]
Yes.

(I'm *this* close to just saying fuck it to all the magic patterns, going with plain regexps, first match wins, and saying that we don't descend into directories only if we can prove everything below them are ignored...)

**Comment by AudriusButkevicius** [comment]
Well you cannot prove that...
As the exclusion patterns (or even worse regexps) might be totally obscure...
Plus, you'll have to ship a book with syncthing to explain how to setup ignores.

Looking at how it's done today in other software (both OneDrive and Dropbox), you have either sync everything, or selective sync, and I think selective sync is sort of solved if we invert ignore mechanism and drop exclude ignore.

No per-file bullshit, but at the same time, they probably don't rely on some other mechanism for building the directory tree for them, and probably deal with files only, and then just do `mkdir -p`.

**Comment by AudriusButkevicius** [comment]
Plus, dropbox doesn't even allow you to include some deep directory if the parent is not included.
So you

**Comment by calmh** [comment]
Yes, maybe. It would simplify life for us and for users. But there'll always be a desire to at least ignore certain file types (temp files etc).

**Comment by AudriusButkevicius** [comment]
This ain't gonna cut it.

**Pull request closed without merging**
