### PR TITLE
Fix #2662 update Edit menu to Action

### LINKED ISSUE #2662: Old wording in Add Device -> Device ID
When clicking the "add device" button in the web ui, the Device ID section says the following:
The device ID to enter here can be found in the "Edit > Show ID" dialog on the other device. 
add device

However, there is no "Edit" menu, only an action menu. Perhaps this needs to be updated in the translations as well.

### PR DESCRIPTION
**Pull request by kluppy**
OK,
So where does Transifex pull it's list of strings from?
Changing the html template is easy but what do I have to do next.

### CODE REVIEW

**Comment by calmh** [comment]
Thanks! After changing the strings in the html, run "go run build.go translate". This updates lang-en.json which is the master that Transifex bases of.

**Comment by kluppy** [comment]
I am sorry, this is probably a complete noob problem but I get an error when trying to translate.

    kluppy@XPS:~/Development/go/src/github.com/syncthing/syncthing$ ./build.sh translate
    GOPATH is /home/kluppy/Development/go
    go run ../../../script/translate.go lang-en.json ../../ > lang-en-new.json
    stat ../../../script/translate.go: no such file or directory
    exit status 1
    exit status 1

I can build fine with my GOPATH etc but when I try `./build translate` or `go run build.go translate` I get the error above. Is there a silly mistake I am making?

Thanks

**Comment by AudriusButkevicius** [comment]
I probably broke it. It needs am extra ../ these days.

**Comment by kluppy** [comment]
That was it, thanks.

**Comment by kluppy** [comment]
I am interested now in why it added a new and kept the old one?

**Comment by calmh** [comment]
We don't throw away old translations automatically. If we did, and we made an error, it would be annoying for the translators as their translated versions would also have disappeared and they'd have to retranslate it when it came back. This way, Transifex will also suggest the old string+translation as a "similar phrase" or something.

**Comment by AudriusButkevicius** [comment]
So we're missing a fix adding the ../ somewhere

**Comment by kluppy** [comment]
Sorry, I was too tired to be working last night, was making silly mistakes.
The build script should be fixed now and the translations updated. Is there anything else you are worried about?

**Comment by AudriusButkevicius** [comment]
Last thiing, squash into a single ir two commits and rebase. Sorry to be annoying.

**Comment by kluppy** [comment]
What? You didn't like 11 commits to change a total of 6 lines in 3 files.
Maybe your just a little picky.

That should have cleaned it up.

**Comment by AudriusButkevicius** [comment]
Tyvm

**Pull request merged**
