### PR TITLE
Fixes restart during transfer integration tests

### PR DESCRIPTION
**Pull request by Zillode**
(Do not merge) Could not reproduce failing TestRestartSenderDuringTransfer and TestRestartSenderAndReceiverDuringTransfer on windows. Experimenting via Jenkins now...

### CODE REVIEW

**Comment by Zillode** [comment]
@st-jenkins run on windows

**Comment by Zillode** [comment]
@st-jenkins run on windows

**Comment by Zillode** [comment]
```
=== RUN TestRestartReceiverDuringTransfer
2015/07/31 00:26:45 Cleaning...
2015/07/31 00:26:54 Generating files...
2015/07/31 00:26:57 Starting up...
2015/07/31 00:26:57 Starting instance 1...
2015/07/31 00:26:59 Starting instance 2...
2015/07/31 00:27:05 Stopping receiver...
2015/07/31 00:27:05 Starting instance 2...
2015/07/31 00:27:17 Comparing directories...
--- PASS: TestRestartReceiverDuringTransfer (32.92s)
=== RUN TestRestartSenderDuringTransfer
2015/07/31 00:27:18 Cleaning...
2015/07/31 00:27:19 Generating files...
2015/07/31 00:27:22 Starting up...
2015/07/31 00:27:22 Starting instance 1...
2015/07/31 00:27:25 Starting instance 2...
2015/07/31 00:27:31 Stopping sender...
2015/07/31 00:27:31 Starting instance 1...
2015/07/31 00:27:38 Stopping sender...
2015/07/31 00:27:38 Starting instance 1...
2015/07/31 00:27:46 Stopping sender...
2015/07/31 00:27:47 Starting instance 1...
2015/07/31 00:27:55 Comparing directories...
--- PASS: TestRestartSenderDuringTransfer (37.87s)
=== RUN TestRestartSenderAndReceiverDuringTransfer
2015/07/31 00:27:56 Cleaning...
2015/07/31 00:27:57 Generating files...
2015/07/31 00:28:00 Starting up...
2015/07/31 00:28:00 Starting instance 1...
2015/07/31 00:28:02 Starting instance 2...
2015/07/31 00:28:08 Stopping receiver...
2015/07/31 00:28:08 Stopping sender...
2015/07/31 00:28:09 Starting instance 2...
2015/07/31 00:28:19 Starting instance 1...
2015/07/31 00:28:31 Comparing directories...
--- PASS: TestRestartSenderAndReceiverDuringTransfer (36.17s)
```
:+1:

**Comment by calmh** [comment]
Hmm. What was the original error fixed by this? AwaitSync with just one device should be a no-op I think?

**Comment by Zillode** [comment]
I think it waits until the node is fully restarted, then 250ms is enough to get both instances connected and exchange the index

**Comment by Zillode** [comment]
so the original problem was that dev2 disconnects, then dev1 thinks it is ready, and then the test fails because the directories do not contain the same files. Might only happen on slower machines

**Comment by calmh** [comment]
The integration tests need serious cleanup (or killing off, to a large extent).

**Pull request closed without merging**
