### PR TITLE
cmd/stcrashreceiver: Group issues with varying traces

### PR DESCRIPTION
**Pull request by imsodin**
All these "out of memory" issues are just in the way of recognizing anything relevant and multiply all the time, as their stacktraces are all over the place. I added a list of strings to check the panic messages against, and if any match, use that string as an identifier for event/issue grouping instead of the stacktrace (https://docs.sentry.io/data-management/rollups/?platform=go#custom-grouping).

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I guess this just like the relaypoolsrv is not autodeployed, so needs upgrading.

**Comment by calmh** [comment]
Fwiw I’ve been adding filters in sentry to simply reject all these messages. But there are apparently lots of different fatal errors, and our users experience all of them...

**Comment by imsodin** [comment]
I didn't find any pointer to that functionality - I don't care about stats so this filtering in sentry is good enough for me.

Another thought: Would it be worthwhile to do filtering on the receiving side, such that the traces don't get stored (disk space)?

**Comment by calmh** [comment]
Yeah, it would save some space. As is they are stored uselessly for the retention period, but 🤷‍♂

**Comment by imsodin** [comment]
I take that as a "who cares" ;)

**Pull request closed without merging**
