### PR TITLE
lib/connections: Fix race condition in parallel dial, minor cleanups

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Classic go-in-for race in the dialler.

Because I already made the changes while troubleshooting something else, a couple of style cleanups and log tweaks as well.

### Testing

None whatsoever. But I'm pretty sure this is the right thing.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 72d645865e309d6fec78b96bf1139d747a27c27b. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
Classic.

**Pull request closed without merging**
