### PR TITLE
Spelling fix

### PR DESCRIPTION
**Pull request by ka7**
### Purpose
some trivial spelling-fixes, as found by this tool: https://github.com/ka7/misspell_fixer
( there are some more, but in 3rd party stuff )
( this is 2nd try,  a41a5c4 had some issues, removed the man-pages from request. )

### Testing
no testing done. affects just man-pages, and comments.

### Screenshots
--

### Documentation
no changes

### Authorship
just some trivial spelling fixes, add me or not, I don't care :)

### CODE REVIEW

**Comment by calmh** [comment]
Thanks, looks good

**Comment by calmh** [comment]
@st-jenkins test this please

**Comment by calmh** [comment]
@st-review merge this please

all: Correct spelling in comments

Skip-check: authors

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@calmh: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
Spurious failure is spurious

**Comment by calmh** [comment]
@st-review merge this please

all: Correct spelling in comments

Skip-check: authors pr-build-mac

**Comment by st-review** [comment]
:ok_hand: Merged as bd41e21c26186ca7577f426dab16e99cb71f01cb. Thanks, @ka7!

**Pull request closed without merging**
