### PR TITLE
lib/connections: Fix rate limiting on arm64 (fixes #3921)

### LINKED ISSUE #3921: Rate limiting is broken on ARM64
Apparently the default rate limit of zero (no limit) breaks on arm64. The cause chain seems to be:

- [we create a zero rate limiter](https://github.com/syncthing/syncthing/blob/master/lib/connections/limiter.go#L68) (that `<` should be a `<=`, thanks to @AudriusButkevicius for noticing)
- [the zero rate is documented to drop all events](https://godoc.org/golang.org/x/time/rate#Limit)
- there is a bug (???) in the rate limiter package that makes this not actually happen, instead a zero rate limiter allows all events
- except, apparently on arm64 (???)

Last point to be confirmed, but seems to be the case...

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Blah

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it

lib/connections: Fix rate limiting on arm64 (fixes #3921)

Skip-check: metalint

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by calmh** [comment]
(Updated stuff on the build servers to apparently metalint got smarter or more stupid, will fix...)

**Comment by st-review** [comment]
:ok_hand: Merged as 2c4b92d410d33f848e46d2b7373f7aa1222ea1db. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
