### PR TITLE
Add `org.opencontainers.image.source` to Dockerfiles

### PR DESCRIPTION
**Pull request by DerRockWolf**
### Purpose

The OCI image spec specifies well-defined [annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) that can be added to images.
Theses annotations can then be used by other tools to gather more information of an image.

This PR adds the `org.opencontainers.image.source` to allow tools such as [renovate](https://github.com/renovatebot/renovate) to find the release notes of a give version.

~~I've only done this change for `Dockerfile`. Should I also add the label to the other dockerfiles?~~
I've now added the source annotations to all `Dockerfile`s & action workflows.

### Testing

None, change was done by following the [renovate documentation](https://docs.renovatebot.com/modules/datasource/docker/).

## Authorship

Your name and email will be added automatically to the AUTHORS file
based on the commit metadata.

### CODE REVIEW

**Comment by calmh** [comment]
Nice. I think we could do this for the others as well. There are other annotations we could do as well, some static and some as part of the build (version)...

**Comment by DerRockWolf** [comment]
> Nice. I think we could do this for the others as well. There are other annotations we could do as well, some static and some as part of the build (version)...

Perfect, then I'll also add the source annotations to the other dockerfiles.
If you let me know which other annotations you want I can also add them :)

**Comment by reneleonhardt** [comment]
Good idea, but why change and synchronize 6 Dockerfiles if not needed? ;)
Just add all labels to the 2 actions: https://github.com/docker/build-push-action#inputs
Or much easier add all labels automatically https://github.com/docker/metadata-action :)

**Comment by DerRockWolf** [comment]
> Good idea, but why change and synchronize 6 Dockerfiles if not needed? ;) Just add all labels to the 2 actions: https://github.com/docker/build-push-action#inputs Or much easier add all labels automatically https://github.com/docker/metadata-action :)

I haven't looked at how the images are built, until now, so this was the most obvious place to add them.
I can also do it like you've suggested, but @calmh or other maintainers should decide how they want it.

**Comment by calmh** [comment]
I think static labels should go in the dockerfiles themselves. Looking quickly at the list, I think that would be

- org.opencontainers.image.authors `The Syncthing Project`
- org.opencontainers.image.url `https://syncthing.net/`
- org.opencontainers.image.documentation `https://docs.syncthing.net/`
- org.opencontainers.image.source as mentioned
- org.opencontainers.image.vendor `The Syncthing Project`
- org.opencontainers.image.licenses `MPL-2.0`
- org.opencontainers.image.title `Syncthing` (or `Syncthing Discovery Server` etc)

Then the build scripts can set org.opencontainers.image.version and org.opencontainers.image.revision appropriately...

**Comment by DerRockWolf** [comment]
> I think static labels should go in the dockerfiles themselves. Looking quickly at the list, I think that would be
> 
>     * org.opencontainers.image.authors `The Syncthing Project`
> 
>     * org.opencontainers.image.url `https://syncthing.net/`
> 
>     * org.opencontainers.image.documentation `https://docs.syncthing.net/`
> 
>     * org.opencontainers.image.source as mentioned
> 
>     * org.opencontainers.image.vendor `The Syncthing Project`
> 
>     * org.opencontainers.image.licenses `MPL-2.0`
> 
>     * org.opencontainers.image.title `Syncthing` (or `Syncthing Discovery Server` etc)
> 
> 
> Then the build scripts can set org.opencontainers.image.version and org.opencontainers.image.revision appropriately...

I've added all annotations :slightly_smiling_face: 

For the infrastructure images I didn't include the `version` annotations because from what I can tell the images only are tagged with `latest` and the current git sha.

**Review by calmh — APPROVED** [review]

**Pull request merged**
