### PR TITLE
lib/api: Skip an IPv6 specific test inside Docker (fixes #5991)

### LINKED ISSUE #5991: lib/api: TestHostCheck never finishes with Go 1.13rc2 under Docker
`go test -v -race -short ./lib/api`

Go 1.12:

```
=== RUN   TestHostCheck
22:17:37 INFO: GUI and API listening on 127.0.0.1:49708
22:17:37 INFO: Access the GUI via the following URL: http://127.0.0.1:0/
22:17:37 INFO: GUI and API listening on 127.0.0.1:49713
22:17:37 INFO: Access the GUI via the following URL: http://127.0.0.1:0/
22:17:37 INFO: GUI and API listening on [::]:49715
22:17:37 INFO: Access the GUI via the following URL: http://127.0.0.1:0/
22:17:37 INFO: GUI and API listening on [::1]:49717
22:17:37 INFO: Access the GUI via the following URL: http://[::1]:0/
--- PASS: TestHostCheck (0.21s)
```

Go 1.13rc2:

```
=== RUN   TestHostCheck
20:15:27 INFO: GUI and API listening on 127.0.0.1:34355
20:15:27 INFO: Access the GUI via the following URL: http://127.0.0.1:0/
20:15:27 INFO: GUI and API listening on 127.0.0.1:42867
20:15:27 INFO: Access the GUI via the following URL: http://127.0.0.1:0/
20:15:27 INFO: GUI and API listening on [::]:36807
20:15:27 INFO: Access the GUI via the following URL: http://127.0.0.1:0/
(panics after x minutes)
```

Seems to *only* be under Docker, so probably some sort of IPv6 badness there that triggers it...

### PR DESCRIPTION
**Pull request by calmh**
Isn't this just the most beautiful thing you've ever seen?

### Testing

```
docker run -it --rm -v $(pwd):/foo -w /foo -e GOPROXY=direct \
  golang:1.13rc2 go test -v -race -short ./lib/... ./cmd/...
```

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Why don't we check that the ipv6 stuff is supported instead?

**Comment by AudriusButkevicius** [comment]
Checking half of those things does not mean docker, it just means cgroups or lxc, which could just be systemd.

**Comment by calmh** [comment]
That's not what my Googling told me, but if you have a better test in mind please don't hesitate to show it :)

**Comment by imsodin** [comment]
An ugly, lazy method would be to introduce a `STTESTSSKIPIPV6` env var.

**Pull request merged**
