### PR TITLE
lib/osutil: Add test for IsDeleted (ref #4925)

### PR DESCRIPTION
**Pull request by imsodin**
Trying to reproduce #4925.

### CODE REVIEW

**Comment by imsodin** [comment]
@calmh Is the linux build run as root and thus not failing to stat `inacc/file` where `inacc` has `000` perms?

**Comment by imsodin** [comment]
@AudriusButkevicius Yes, apart from the minor issue mentioned above (that scenario is now just skipped on the linux build server).

**Comment by calmh** [comment]
No, no root, but I don't think 000 will prevent a stat (didn't look at the code)

**Comment by imsodin** [comment]
@calmh Any ideas why it doesn't prevent it on the build server (it does on my pc)?

**Comment by imsodin** [comment]
I (too hastily) updated the test to just skip that part if it fails. See the ["old test"](https://github.com/syncthing/syncthing/pull/4936/files/da08b34979d5680df6f24f9845c24dcd346289f7#diff-bc0d4ee330436348056e2922eb8f814aR252) and resulting [test failure](https://build.syncthing.net/viewLog.html?buildId=20589&buildTypeId=Syncthing_BuildLinuxCross&tab=buildLog&_focus=1082&state=1082#_state=1082)

**Comment by calmh** [comment]
Right, so the Linux build agent *does* in fact run as root in it's litter docker world. Sorry about that misinformation. I think that's pretty broken but probably the alternative is a mess of permission problems instead. Maybe we can run with your later root-avoiding version of the test and be happy that it succeeds as non-root on for example mac instead. :/

**Comment by imsodin** [comment]
Totally. It will also work whenever anyone runs tests locally.

**Comment by calmh** [comment]
At least you're not here yet: https://github.com/kubernetes/kubernetes/commit/eace2d08d0b3d5b493eefec9f8532ef2980617ac

**Pull request merged**
