### PR TITLE
Test ignoredeletes

### PR DESCRIPTION
**Pull request by Zillode**
Both sides 'up to date', however the master has one file more than the remote.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Was this fixed? Because I though it exposes a bug?

**Comment by calmh** [comment]
I didn't see the bug in that case... The two devices are out of sync, with one having one more file than the other, as the delete is ignored...

**Comment by AudriusButkevicius** [comment]
@Zillode any comments?

**Comment by Zillode** [comment]
Well, I think this is still a bug. Both devices claim to be 'up to date' (local and remotely), until you restart Syncthing (or maybe if another file gets synced, but I did not test that).

**Comment by calmh** [comment]
The bug may be that we don't show the other side as out of sync when they are missing a delete. I'll have to look closer, but I suspect we only compare byte sizes that don't take deletes into account. So we get the following sequence:

1. Both sides are in sync, each have one file
2. Alice deletes the file. Bob ignores the delete. Alice thinks Bob is up to date, because she doesn't care about the missing delete (bug from above). Bob thinks Alice is up to date, because the index update saying otherwise was ignored.
3. Connection is restarted for whatever reason.
4. Alice sees Bob as up to date, because above. Bob thinks Alice is out of date, because she should be announcing the file we have but don't (because it was deleted, and we ignored that update).

**Pull request closed without merging**
