### PR TITLE
Fix debian control

### PR DESCRIPTION
**Pull request by spk**
This is a first step to fix https://github.com/syncthing/syncthing/issues/2441
Cheers

### CODE REVIEW

**Comment by calmh** [comment]
The description seems a little long winded and markety for the context, but if this is indeed proper in the Debian package context then it all LGTM.

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
Right, the build server is offline. Anyway I should fix the author check script to only audit commits to cmd/ and lib/ so this is in principle fine to merge, but I'd like to wait until I'm back or someone does that script fix or it'll break the build.

**Comment by spk** [comment]
Rebased

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
Merged, thanks!

**Comment by spk** [comment]
\o/

**Pull request closed without merging**
