### PR TITLE
Add missing parameter in disk space warning

### PR DESCRIPTION
**Pull request by simplypeachy**
Plus copyright bump, minor grammatical fix.

### CODE REVIEW

**Comment by calmh** [comment]
Change itself looks fine, but the copyright notice is fine as is (year is creation year, grammar is per the license itself) so please leave that alone. :)

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
Hi! Do you have an email address that you are reachable on for the authors list, please?

**Comment by simplypeachy** [comment]
aD@simplypeachy.co.uk

**Comment by calmh** [comment]
Thanks. What do you want us to use for name?

**Comment by simplypeachy** [comment]
Adam Piggott. Cheers!

**Comment by calmh** [comment]
@st-jenkins test this please

**Pull request merged**
