### PR TITLE
readme: Add bountysource badge

### PR DESCRIPTION
**Pull request by bt90**

### CODE REVIEW

**Comment by imsodin** [comment]
Do we want to promote them? I haven't heard anything from them lately, don't find any news online and they do still exist (same poor UX as back in the day :) ) - I guess no news is good news. Last thing I remember is them trying t pull a super-shady trick after it was taken over by that cryptocurrency (they wanted to confiscate bounties that weren't claimed/addressed within a timeframe, then backtracked after too much outrage). Basically the combination of crypto-takeover and then clearly malicious actor basically poisened them for me, as in I can't see how that was an accident. So yeah basically I need convincing bountysource is a good thing at this point to feature it/approve this PR.

**Comment by bt90** [comment]
Wasn't aware of that. Do you know any alternative platforms which provide something similar?

**Comment by imsodin** [comment]
Nothing that does the same thing - various platforms to fund projects, but not for people to put money on tickets.

**Comment by bt90** [comment]
Bummer. I'll still keep my bounties up as long as  they pay them out accordingly. But we shouldn't promote them.

**Pull request closed without merging**
