### PR TITLE
snapcraft.yaml.template: use environment stanza

### PR DESCRIPTION
**Pull request by 3v1n0**
Update snapcraft syntax

### CODE REVIEW

**Comment by calmh** [comment]
Note that this doesn't build, at least not with the snapcraft version of the build server which may not be the latest and greatest...

**Comment by 3v1n0** [comment]
Weird is that so old? What version is it running?

**Comment by calmh** [comment]
```
root@66ecfa6af56b:/# cat /etc/debian_version 
stretch/sid
root@66ecfa6af56b:/# snapcraft --version
snapcraft, version 2.40
root@66ecfa6af56b:/# 
```

**Comment by 3v1n0** [comment]
Weird that should work. It does to me at least.

What error are you getting?

**Comment by calmh** [comment]
Cool. Have you tested that this works as expected in the produced snap?

**Comment by xordspar0** [comment]
It looks like this change has already been made in 95eb81467c76a380dcebe68c7502cf56fa2ce3c5. We can probably close this now.

**Comment by st-review** [comment]
:robot: *beep boop*

I'm going to close this pull request as it has been idle for more than 90 days.

This is not a rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
