### PR TITLE
gui: Fix usage statistics URL in report usage preview (fixes #3397)

### LINKED ISSUE #3397: Formatting issue in Anonymous Usage Reporting Preview
This is a trivial GUI issue.
In `Settings` -> `Preview`, the _Anonymous Usage Reporting_ modal view has a slight issue with not interpreting the `<a>` intended to show the link. The `<a href=...` construct is left visible and no clickable link is present.
The `<p>` in question is shown here.

`<p translate="" translate-value-url="<a href=&quot;https://data.syncthing.net&quot; target=&quot;_blank&quot;>https://data.syncthing.net</a>" class="ng-scope">The aggregated statistics are publicly available at &lt;a href="https://data.syncthing.net" target="_blank"&gt;https://data.syncthing.net&lt;/a&gt;.</p>`

It seems that the inner text content escapes the `<>` into `&lt;&gt;`

Syncthing Version: v0.13.10
OS Version: Debian stretch/sid
Browser Version: Both Chromium 51 and Firefox 45

### PR DESCRIPTION
**Pull request by xduugu**
### Purpose

This applies the fix from 9d75652 to the usage report preview. It also removes the now obsolete language string from all language files. I was not sure if the removal of language strings is also managed by transifex. If that's the case, please ignore the second commit.

### Testing

Local testing with STGUIASSETS variable was performed.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
No need to modify the translation files, these get updated automatically.

**Comment by xduugu** [comment]
Should I remove the second commit (the one that changes the language files) then?

**Comment by AudriusButkevicius** [comment]
Yes, I think so.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as e3ccc45d196a46d8f3fdd51397a561f175398ae4. Thanks, @xduugu!

**Pull request closed without merging**
