### PR TITLE
gui: Add QR code and copy modal for folder IDs (fixes #9055)

### LINKED ISSUE #9055: Proposal gui: add qr-code to folder id textfield analog to device-id
## The Idea
The "This Device" section on the right side of the dashboard has a link / on click feature on the device id field in the "Identification Column".

grafik

This shows the QR code of this device, which is convenient for the setup of mobile devices (for example).

At the moment the setup  for already available folders on android devices is a bit fuzzy if you want a dedicated folder.
You need to create a folder with the folder-id of the remote folder that you want to add / sync with.
Then the folders will match and everything works fine.
The folder-id is a bit difficult to read with the default fonts. You can easily mix 'l' (L) and 'I' (I) there.

This was the origin of the idea of my proposal.  Syncthing has already the ability that the device id can be shown as a qr code 
(And the android-version can import the qr code there).

So it would be great if this feature would not be limited to the device id. 
So a folder match can be easily made on the remote device.

PS: I have several mobile devices which are connected to 3 syncthing nodes. So for me, it would be a great feature, making the setup process  easier. But I can totally see, that this feature can also help users in general setting up a remote folder that they want to sync with.

## Code

I already looked at the code. Unfortunately it is written in angular and I am not familiar with this framework.
But there is already a template  ''gui/default/syncthing/device/idqrModalView.html" and a call in 
gui/default/syncthing/core/syncthingController.js:
```js
        $scope.showDeviceIdentification = function (deviceCfg) {
            $scope.currentDevice = deviceCfg;
            $('#idqr').modal();
        };
```
From my understanding it should be relatively easy adding this feature analog to the already existing model and template.
But this is just a humble guess from my side.

## Draft

grafik

### PR DESCRIPTION
**Pull request by tomasz1986**
gui: Add QR code and copy modal for folder IDs (fixes #9055)

Allow to easily copy folder IDs by a button click or through a QR code.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### Screenshots

image
image

### CODE REVIEW

**Comment by calmh** [comment]
Who is the consumer of this QR code?

**Comment by tomasz1986** [comment]
> Who is the consumer of this QR code?

For now, it can be decoded with QR code scanning apps as explained in https://github.com/syncthing/syncthing/issues/9055#issuecomment-1694756642. Just for the record, I don't need this personally, but the feature request has been kept open, hence the PR.

**Comment by calmh** [comment]
I ask about the consumer for two reasons... to begin with I'm unconvinced about the utility of it as I think folders are generally propagated via Syncthing itself instead of manually, and if the scenario calls for manually - is that a scenario where we expect the user had the two devices in front of them and wants to use a QR scanner to copy/paste a short string? It seems a bit contrived. 

The other is about the format. Assuming there were a consumer, would it be more useful to have more data in the string, maybe `//deviceID/folderID` like a host-path URL, so that the folder QR could be used in a useful manner to add a device plus folder share relationship?

**Comment by calmh** [comment]
I don't see this being merged as-is and I think the underlying use case/assumptions require discussion. 👍

**Pull request closed without merging**
