### PR TITLE
Extract session store

### PR DESCRIPTION
**Pull request by emlun**
### Purpose

This is an extract from PR #9175, which can be reviewed in isolation to reduce the volume of changes to review all at once in #9175. There are about to be several services and API handlers that read and set cookies and session state, so this abstraction will prove helpful.

In particular a motivating cause for this is that with the current architecture in PR #9175, in `api.go` the [`webauthnService` needs to access the session](https://github.com/syncthing/syncthing/pull/9175/files#diff-e2e14f22d818b8e635572ef0ee7718dee875c365e07225d760a6faae8be7772dR309-R310) for authentication purposes but needs to be instantiated before the `configMuxBuilder` for config purposes, because the WebAuthn additions to config management need to perform WebAuthn registration ceremonies, but currently the session management is embedded in the `basicAuthAndSessionMiddleware` which is [instantiated much later](https://github.com/syncthing/syncthing/pull/9175/files#diff-e2e14f22d818b8e635572ef0ee7718dee875c365e07225d760a6faae8be7772dL371-R380) and only if authentication is enabled in `guiCfg`. This refactorization extracts the session management out from `basicAuthAndSessionMiddleware` so that `basicAuthAndSessionMiddleware` and `webauthnService` can both use the same shared session management service to perform session management logic.

### Testing

This is a refactorization intended to not change any externally observable behaviour, so existing tests (e.g., `api_auth_test.go`) should cover this where appropriate. I have manually verified that:

- Appending `+ "foo"` to the cookie name in `createSession` causes `TestHtmlFormLogin/invalid_URL_returns_403_before_auth_and_404_after_auth` and `TestHtmlFormLogin/UTF-8_auth_works` to fail
- Inverting the return value of `hasValidSession` cases a whole bunch of tests in `TestHTTPLogin` and `TestHtmlFormLogin` to fail
- (Fixed) Changing the cookie to `MaxAge: 1000` in `destroySession` does NOT cause any tests to fail!
  - Added tests `TestHtmlFormLogin/Logout_removes_the_session_cookie`, `TestHTTPLogin/*/Logout_removes_the_session_cookie`, `TestHtmlFormLogin/Session_cookie_is_invalid_after_logout` and `TestHTTPLogin/200_path#01/Session_cookie_is_invalid_after_logout` to cover this.
  - Manually verified that these tests pass both before and after the changes in this PR, and that changing the cookie to `MaxAge: 1000` or not calling `m.tokens.Delete(cookie.Value)` in `destroySession` makes the respective pair of tests fail.

### CODE REVIEW

**Review by calmh — COMMENTED** [review]
In principle seems fine. Some high level thoughts before looking at any details:

- The new tokenStore seems like an extension of the tokenManager, maybe it should live in the same file or a separate one beside tokenManager. (Unless the whole tokenManager is just a pair of create/destroy methods that could be added to the tokenManager in order to keep it in one place?)
- I'm not sure about the difference in behavior between creating and destroying a session; creating a session takes the response writer as a parameter and does the cookie juggling, destroying a session does not and returns something that it expects the caller to do cookie juggling on. Probably better to keep this symmetrical?

**Comment by emlun** [comment]
>The new tokenStore seems like an extension of the tokenManager, maybe it should live in the same file or a separate one beside tokenManager. (Unless the whole tokenManager is just a pair of create/destroy methods that could be added to the tokenManager in order to keep it in one place?)

By `tokenStore` do you mean `sessionStore`? If so, yes, we can certainly move it to `tokenmanager.go` if you prefer.

And in "tokenManager is just a pair of create/destroy methods" do you also mean `sessionStore` rather than `tokenManager`? If so, probably - `sessionStore` has three methods: `createSession`, `hasValidSession([]*http.Cookie) bool` and `destroySession([]*http.Cookie)`. So yes, we could easily merge `sessionStore` into `tokenManager` if you prefer that.

The argument against would be that right now `tokenManager` doesn't have anything to do with the HTTP layer, so I think it makes sense to keep that decoupled from HTTP and model the `sessionStore` by composition rather than merging them. But we can go either way if you prefer merging. I'm also happy to rename `sessionStore` to something more obviously related to `tokenManager` if you want to keep them separate.

>creating a session takes the response writer as a parameter and does the cookie juggling, destroying a session does not and returns something that it expects the caller to do cookie juggling on. Probably better to keep this symmetrical?

Very good point! Probably best to take the `http.ResponseWriter` in `destroySession` too, then, since `createSession` is already a bit entangled with the `Request` for the TLS detection logic which doesn't look like it would make much sense to move out.

> Perhaps the sessionStore, from the point of view of the API, could be boiled down to an interface

That abstraction certainly makes sense if we do want to merge `sessionStore` into `tokenManager`.

**Comment by emlun** [comment]
I have moved `sessionStore` to `tokenmanager.go`, harmonized the signatures of its methods, and renamed `sessionStore` to `tokenCookieManager`. Let me know if you'd like me to also merge it into `tokenManager`.

**Review by calmh — APPROVED** [review]
LGTM!

**Pull request merged**
