### PR TITLE
cmd/stvanity: Use Go 1.3 compatible interface

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Actually fix the build on Go 1.3 for reals

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge this when it passes

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 4eb23a38b1ceb2c522cb589db2b6e987fd9e915c. Thanks, @calmh!

**Comment by AudriusButkevicius** [comment]
Why do we care about go 1.3?

**Comment by calmh** [comment]
Because we have no compelling reason not to.

**Comment by lkwg82** [comment]
Do we have a test for this specific compiler compatibility? Actually having compiler versions x ... 1.6 to successfull compile the code seems to be sufficient.

**Comment by calmh** [comment]
Yes. https://build.syncthing.net/job/syncthing-go13-386/

**Pull request closed without merging**
