### PR TITLE
vendor: Update github.com/zillode/notify

### PR DESCRIPTION
**Pull request by imsodin**

### CODE REVIEW

**Comment by imsodin** [comment]
@st-review don't

This diff looks wrong (there were other changes).

**Comment by st-review** [comment]
@imsodin: Preventing merge for the time being. Push a new revision to reset!

**Comment by imsodin** [comment]
False alarm, the "other changes" were dot-files and thus pruned - sorry.

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by calmh** [comment]
Huh?

**Comment by imsodin** [comment]
Bot is confused, me too: The flaky test failures on our mac builder have become significantly worse. Upstream removed a one second sleep, maybe that's enough... (https://github.com/rjeczalik/notify/pull/141/files)

**Comment by calmh** [comment]
Yeah, I know where the flakyness comes from, will fix it.

**Comment by calmh** [comment]
@st-review rebuild

**Comment by calmh** [comment]
Ugh, rebuild also doesn't work any more

**Pull request merged**
