### PR TITLE
Always exit via error select, making sure reader routine is exits (fi…

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
…xes #2547)

Written but not tested. Someone needs to verify my thinking.

### CODE REVIEW

**Comment by calmh** [comment]
I'll give this a spin

**Comment by calmh** [comment]
I'm suspicious (without having tested it). We call `c.disconnect()` in a bunch of places to bail out, but `disconnect()` just sets a bool which doesn't obviously cause us to receive anything from the `err` channel? Should it in fact close the connection instead?

**Comment by AudriusButkevicius** [comment]
It sets a bool, and closes the connection (not visible in the diff), which should make the reader routine exit with an error.

**Comment by calmh** [comment]
Ah, sorry, I missed the close as it was outside off the diff and I must have imagined a `}` there. Then it *looks* sane but I can still give it a test. :)

**Comment by AudriusButkevicius** [comment]
I guess you can only test it using iptables or something?

**Comment by calmh** [comment]
LGTM. Tested by running a local relaysrv and stopping it with ^Z to force a timeout.

```
[I6KAH] 2015/12/20 10:00:02.537856 gui.go:236: INFO: API listening on 127.0.0.1:8081
[I6KAH] 2015/12/20 10:00:02.537869 gui.go:237: INFO: GUI URL is http://127.0.0.1:8081/
[I6KAH] 2015/12/20 10:00:02.551994 static.go:75: DEBUG: StaticClient:0xc8200638f0@relay://localhost:22067 connected [::1]:22067
[I6KAH] 2015/12/20 10:00:02.552157 static.go:89: DEBUG: StaticClient:0xc8200638f0@relay://localhost:22067 joined [::1]:22067 via [::1]:50879
[I6KAH] 2015/12/20 10:00:12.527305 upnpsvc.go:58: INFO: No UPnP device detected
[I6KAH] 2015/12/20 10:02:02.553032 static.go:156: DEBUG: StaticClient:0xc8200638f0@relay://localhost:22067 timed out
[I6KAH] 2015/12/20 10:02:02.553073 static.go:232: DEBUG: StaticClient:0xc8200638f0@relay://localhost:22067 disconnecting
[I6KAH] 2015/12/20 10:02:02.553254 relay.go:47: DEBUG: Svc: Failed service 'StaticClient:0xc8200638f0@relay://localhost:22067' (1.000000 failures of 5.000000), restarting: true, error: "StaticClient:0xc8200638f0@relay://localhost:22067 returned unexpectedly", stacktrace: [unknown stack trace]
[I6KAH] 2015/12/20 10:02:12.555005 static.go:71: DEBUG: Relay connect: read tcp [::1]:51013->[::1]:22067: i/o timeout
[I6KAH] 2015/12/20 10:02:12.555116 relay.go:47: DEBUG: Svc: Failed service 'StaticClient:0xc8200638f0@relay://localhost:22067' (1.988512 failures of 5.000000), restarting: true, error: "StaticClient:0xc8200638f0@relay://localhost:22067 returned unexpectedly", stacktrace: [unknown stack trace]
[I6KAH] 2015/12/20 10:02:22.560201 static.go:71: DEBUG: Relay connect: read tcp [::1]:51025->[::1]:22067: i/o timeout
[I6KAH] 2015/12/20 10:02:22.560302 relay.go:47: DEBUG: Svc: Failed service 'StaticClient:0xc8200638f0@relay://localhost:22067' (2.965660 failures of 5.000000), restarting: true, error: "StaticClient:0xc8200638f0@relay://localhost:22067 returned unexpectedly", stacktrace: [unknown stack trace]
[I6KAH] 2015/12/20 10:02:25.838979 static.go:75: DEBUG: StaticClient:0xc8200638f0@relay://localhost:22067 connected [::1]:22067
[I6KAH] 2015/12/20 10:02:25.839200 static.go:89: DEBUG: StaticClient:0xc8200638f0@relay://localhost:22067 joined [::1]:22067 via [::1]:51037

```

**Pull request merged**
