### PR TITLE
Support multiple API keys (command-line and config) (fixed #2747)

### LINKED ISSUE #2747: Use both the API keys specified on the command line and in config
Syncthing should accept both the API key specified on the command-line, and the one set in Syncthing's config.

This means that users don't run into a case where they attempt to use the API key from Syncthing's Config page, and get confused because someone else has overridden it from the command line.

I remember we discussed this a while back.

### PR DESCRIPTION
**Pull request by canton7**
No idea whether this is idiomatic Go, or even the best way of solving this - please push back if not.

### CODE REVIEW

**Comment by calmh** [comment]
LGTM. Wording wise IsValidAPIKey sounds more natural to me than IsAPIKeyValid, but it's not like I didn't understand it anyway.

**Comment by calmh** [comment]
Actually, with this change you could also remove the APIKey() method and rename RawAPIKey back to just APIKey I think.

**Comment by canton7** [comment]
Yeah, I wasn't sure whether there was a data encapsulation argument here, so left it in to be safe. I'll remove and update this PR.

**Comment by canton7** [comment]
Anything else you want me to do to this?

**Comment by canton7** [comment]
Thanks!

**Pull request merged**
