### PR TITLE
lib/model: Don't close file early (fixes #6875)

### LINKED ISSUE #6875: Copy range method "all" prevents sync
Tested setting the "all" method on a folder on Mac to see what happens. I'm not sure if any of our advanced methods are supported, but then I'd expect a fallback to standard? Actual results:

```
[MRIW7] 09:36:21 INFO: Puller (folder default, item "whatever"): dst write: read /Users/jb/dev/syncthing/syncthing/test/s2/whatever: file already closed
[MRIW7] 09:36:21 INFO: default: Failed to sync 1 items
[MRIW7] 09:36:21 INFO: Folder default isn't making sync progress - retrying in 1m0s.
[MRIW7] 09:37:22 INFO: default: Failed to sync 1 items
[MRIW7] 09:37:22 INFO: Folder default isn't making sync progress - retrying in 1m0s.
[MRIW7] 09:38:22 INFO: default: Failed to sync 1 items
[MRIW7] 09:38:22 INFO: Folder default isn't making sync progress - retrying in 2m0s.
...
```

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
I guess this might explain why this doesn't actually work.

### CODE REVIEW

**Comment by calmh** [comment]
Now I'm confused how there were positive user results on this.

**Comment by calmh** [comment]
So with this the fallback to `standard` works, but apparently none of my systems (macOS/APFS, FreeBSD/ZFS, Linux/ext4) support any of the fancy methods... (I added some debug prints) 🤷

**Comment by AudriusButkevicius** [comment]
I'm surprised because sendfile should work.

If you run the tests for copy range stuff in fs package, does it also not work?

**Comment by AudriusButkevicius** [comment]
Seems to fail for me as well. Looking.

**Comment by calmh** [comment]
The tests say `PASS`, only `ioctl` says `SKIP`. But that's also the case for the things that as I understand it should not pass...

**Comment by calmh** [comment]
On freebsd the ioctl and sendfile tests fail:

```
--- FAIL: TestCopyRange (0.57s)
    --- FAIL: TestCopyRange/ioctl (0.13s)
        --- FAIL: TestCopyRange/ioctl/append_to_end (0.02s)
        --- FAIL: TestCopyRange/ioctl/append_to_end,_offsets_at_start (0.02s)
        --- FAIL: TestCopyRange/ioctl/overwrite_part_of_destination_region (0.01s)
        --- FAIL: TestCopyRange/ioctl/overwrite_all_of_destination (0.01s)
        --- FAIL: TestCopyRange/ioctl/overwrite_part_of_destination (0.01s)
        --- FAIL: TestCopyRange/ioctl/destination_gets_expanded_as_it_is_being_written_to (0.01s)
        --- FAIL: TestCopyRange/ioctl/source_file_too_small (0.01s)
        --- FAIL: TestCopyRange/ioctl/not_block_aligned_write (0.01s)
        --- FAIL: TestCopyRange/ioctl/last_block (0.01s)
        --- FAIL: TestCopyRange/ioctl/whole_file_copy_block_aligned (0.01s)
        --- FAIL: TestCopyRange/ioctl/whole_file_copy_not_block_aligned (0.01s)
    --- FAIL: TestCopyRange/sendfile (0.12s)
        --- FAIL: TestCopyRange/sendfile/append_to_end (0.01s)
        --- FAIL: TestCopyRange/sendfile/append_to_end,_offsets_at_start (0.01s)
        --- FAIL: TestCopyRange/sendfile/overwrite_part_of_destination_region (0.01s)
        --- FAIL: TestCopyRange/sendfile/overwrite_all_of_destination (0.01s)
        --- FAIL: TestCopyRange/sendfile/overwrite_part_of_destination (0.01s)
        --- FAIL: TestCopyRange/sendfile/destination_gets_expanded_as_it_is_being_written_to (0.01s)
        --- FAIL: TestCopyRange/sendfile/source_file_too_small (0.01s)
        --- FAIL: TestCopyRange/sendfile/not_block_aligned_write (0.01s)
        --- FAIL: TestCopyRange/sendfile/last_block (0.01s)
        --- FAIL: TestCopyRange/sendfile/whole_file_copy_block_aligned (0.01s)
        --- FAIL: TestCopyRange/sendfile/whole_file_copy_not_block_aligned (0.01s)
    --- PASS: TestCopyRange/all (0.16s)
        --- PASS: TestCopyRange/all/append_to_end (0.02s)
        --- PASS: TestCopyRange/all/append_to_end,_offsets_at_start (0.02s)
        --- PASS: TestCopyRange/all/overwrite_part_of_destination_region (0.02s)
        --- PASS: TestCopyRange/all/overwrite_all_of_destination (0.02s)
        --- PASS: TestCopyRange/all/overwrite_part_of_destination (0.02s)
        --- PASS: TestCopyRange/all/destination_gets_expanded_as_it_is_being_written_to (0.02s)
        --- PASS: TestCopyRange/all/source_file_too_small (0.02s)
        --- PASS: TestCopyRange/all/not_block_aligned_write (0.01s)
        --- PASS: TestCopyRange/all/last_block (0.01s)
        --- PASS: TestCopyRange/all/whole_file_copy_block_aligned (0.01s)
        --- PASS: TestCopyRange/all/whole_file_copy_not_block_aligned (0.01s)
    --- PASS: TestCopyRange/standard (0.15s)
        --- PASS: TestCopyRange/standard/append_to_end (0.02s)
        --- PASS: TestCopyRange/standard/append_to_end,_offsets_at_start (0.02s)
        --- PASS: TestCopyRange/standard/overwrite_part_of_destination_region (0.02s)
        --- PASS: TestCopyRange/standard/overwrite_all_of_destination (0.02s)
        --- PASS: TestCopyRange/standard/overwrite_part_of_destination (0.02s)
        --- PASS: TestCopyRange/standard/destination_gets_expanded_as_it_is_being_written_to (0.02s)
        --- PASS: TestCopyRange/standard/source_file_too_small (0.02s)
        --- PASS: TestCopyRange/standard/not_block_aligned_write (0.01s)
        --- PASS: TestCopyRange/standard/last_block (0.01s)
        --- PASS: TestCopyRange/standard/whole_file_copy_block_aligned (0.01s)
        --- PASS: TestCopyRange/standard/whole_file_copy_not_block_aligned (0.01s)
```

**Comment by calmh** [comment]
Maybe I should deploy a FreeBSD builder.

**Comment by AudriusButkevicius** [comment]
So it seems it's the mtimefs that's getting in the way.

I also noticed https://github.com/golang/go/issues/24331

Not sure we'd have any use for any of these cool poller features tho.

**Pull request merged**
