### PR TITLE
Folder information icons and tooltip (fixes #3710)

### LINKED ISSUE #3710: Folder information is too long for the label
Hey,

my folders have a lot of files and directories in it and so the label is too short to display the storage size information. Caused by too long strings like "directions", please short it to "dirs" or whatever.
Increasing the width of the label would fix it too, but i do not know if the place to the left is needed otherwise.

folder information

### Version Information

Syncthing Version: v0.14.10
OS Version: Windows 10
Browser Version: Firefox ESR 45.4.0
Screen Resolution: 1920x1080
Language: German

### PR DESCRIPTION
**Pull request by uok**
add icons and tooltip to folder information to save space

### CODE REVIEW

**Comment by calmh** [comment]
screen shot 2016-11-13 at 14 54 36

**Comment by calmh** [comment]
@st-review merge it

gui: Use icons and tooltips for folder size info (fixes #3710)

**Comment by st-review** [comment]
:ok_hand: Merged as ba6aff4a1b34df8dd670ea3f353fb353d902ba24. Thanks, @uok!

**Comment by calmh** [comment]
Thank uok!

**Pull request closed without merging**
