### PR TITLE
README.md: Spelling

### PR DESCRIPTION
**Pull request by RichiH**
### Purpose

Fix typo.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge this please

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2821/head:pr-2821
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
 * [new branch]      master     -> orig/master
   9259425..b8c72ad  master     -> origin/master
$ git reset --hard
HEAD is now at 9259425 Add priority,section and homepage to debian/control
$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 5 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
$ git reset --hard orig/master
HEAD is now at b8c72ad Default to modern -ldflags syntax for unknown Go version
$ git clean -fxd
$ git merge --squash --no-commit pr-2821
Updating b8c72ad..9bf84e5
Fast-forward
Squash commit -- not updating HEAD
 README.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
$ git commit -F -
[master 57b5da8] README.md: Spelling
 Author: Richard Hartmann <RichiH@users.noreply.github.com>
 1 file changed, 1 insertion(+), 1 deletion(-)
$ git rev-parse HEAD
57b5da800e76116b9a24d740bc43b33d5b36cb5a
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 3 of 3 required status checks are expected        
To git@github.com:syncthing/syncthing.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:syncthing/syncthing.git'

```

**Comment by RichiH** [comment]
Anything I can do to help pass the tests?

**Comment by AudriusButkevicius** [comment]
Nah, we'll sort it out, I am just testing the bot ;)

**Comment by RichiH** [comment]
K, have fun, then :)

**Comment by calmh** [comment]
Right, the bot isn't exempt from the required checks...

**Comment by calmh** [comment]
Merged manually (no author addition necessary for one bit changes in README ;)

**Comment by RichiH** [comment]
Fine by me either way; thanks for merging :)

**Pull request closed without merging**
