### PR TITLE
gui: Various improvments

### PR DESCRIPTION
**Pull request by norgeous**
before:
untitled

after:
untitled

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Feels like a childrens game, `find X differences`, where X is undefined.
So far my calculations say that X is 1.

**Comment by norgeous** [comment]
sorry my bad. to elaborate...
1. fixed logo placement under 768 width. now aligned to 'left margin' and vertically centred in the header bar.
2. gap between icon and title fixed - as i believe i have broken this previously
3. added `.panel-icon` class to all accordion and modals - this allows for those `h3`s and `h4`s to be spread out onto multiline (which i believe is prefered)

**Comment by norgeous** [comment]
clarification:
- css file changes: points 1 and 2 above
- html file changes: all the html files i have changed, i have just added `<div class="panel-icon">` and multilined

**Comment by AudriusButkevicius** [comment]
@st-review merge

gui: CSS tweaks for mobile views

**Comment by st-review** [comment]
:ok_hand: Merged as 3795a786c9482ba58d9c4eb556dad8e0dec2b710. Thanks, @norgeous!

**Pull request closed without merging**
