### PR TITLE
lib/model: Test should pass go vet inspections

### PR DESCRIPTION
**Pull request by calmh**
Because this check was introduced after the previous commit was tested...

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge this if it passes, please...

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by calmh** [comment]
CAN YOU BE ANY SLOWER, APPVEYOR? Don't worry, I've got all week.

**Comment by st-review** [comment]
:ok_hand: Merged as f6953624dd98e1da62a61db97d0a9442ce85d181. Thanks, @calmh!

**Pull request closed without merging**
