### PR TITLE
Fix integration rename windows

### PR DESCRIPTION
**Pull request by Zillode**

### CODE REVIEW

**Comment by Zillode** [comment]
@st-jenkins run integration tests for linux and windows please

**Comment by Zillode** [comment]
```
=== RUN TestSyncClusterWithoutVersioning
2015/07/30 20:15:00 Testing with numFiles=100, fileSizeExp=20, timeLimit=45s
2015/07/30 20:15:00 Cleaning...
2015/07/30 20:15:00 Generating files...
2015/07/30 20:15:06 Starting Syncthing...
2015/07/30 20:15:06 Starting instance 1...
2015/07/30 20:15:09 Starting instance 2...
2015/07/30 20:15:11 Starting instance 3...
2015/07/30 20:15:15 Iteration 1
2015/07/30 20:15:15 Forcing rescan...
2015/07/30 20:16:25 Syncing...
2015/07/30 20:16:29 Checking...
2015/07/30 20:16:31 Altering...
--- PASS: TestSyncClusterWithoutVersioning (96.17s)
=== RUN TestSyncClusterSimpleVersioning
2015/07/30 20:16:36 Testing with numFiles=100, fileSizeExp=20, timeLimit=45s
2015/07/30 20:16:36 Cleaning...
2015/07/30 20:16:41 Generating files...
2015/07/30 20:16:47 Starting Syncthing...
2015/07/30 20:16:47 Starting instance 1...
2015/07/30 20:16:49 Starting instance 2...
2015/07/30 20:16:52 Starting instance 3...
2015/07/30 20:16:55 Iteration 1
2015/07/30 20:16:55 Forcing rescan...
2015/07/30 20:18:08 Syncing...
2015/07/30 20:18:12 Checking...
2015/07/30 20:18:13 Altering...
--- PASS: TestSyncClusterSimpleVersioning (101.44s)
=== RUN TestSyncClusterTrashcanVersioning
2015/07/30 20:18:17 Testing with numFiles=100, fileSizeExp=20, timeLimit=45s
2015/07/30 20:18:17 Cleaning...
2015/07/30 20:18:22 Generating files...
2015/07/30 20:18:28 Starting Syncthing...
2015/07/30 20:18:28 Starting instance 1...
2015/07/30 20:18:31 Starting instance 2...
2015/07/30 20:18:33 Starting instance 3...
2015/07/30 20:18:36 Iteration 1
2015/07/30 20:18:36 Forcing rescan...
2015/07/30 20:19:41 Syncing...
2015/07/30 20:19:44 Checking...
2015/07/30 20:19:46 Altering...
--- PASS: TestSyncClusterTrashcanVersioning (92.65s)
=== RUN TestSyncClusterStaggeredVersioning
2015/07/30 20:19:50 Testing with numFiles=100, fileSizeExp=20, timeLimit=45s
2015/07/30 20:19:50 Cleaning...
2015/07/30 20:19:55 Generating files...
2015/07/30 20:20:01 Starting Syncthing...
2015/07/30 20:20:01 Starting instance 1...
2015/07/30 20:20:03 Starting instance 2...
2015/07/30 20:20:06 Starting instance 3...
2015/07/30 20:20:10 Iteration 1
2015/07/30 20:20:10 Forcing rescan...
2015/07/30 20:21:15 Syncing...
2015/07/30 20:21:20 Checking...
2015/07/30 20:21:22 Altering...
--- PASS: TestSyncClusterStaggeredVersioning (96.99s)
=== RUN TestSyncClusterForcedRescan
2015/07/30 20:21:27 Cleaning...
2015/07/30 20:21:31 Generating files...
2015/07/30 20:21:38 Starting instance 1...
2015/07/30 20:21:41 Starting instance 2...
2015/07/30 20:21:43 Starting instance 3...
2015/07/30 20:21:46 Forcing rescan...
2015/07/30 20:23:11 Syncing...
2015/07/30 20:23:15 Checking...
2015/07/30 20:23:17 Altering...
--- PASS: TestSyncClusterForcedRescan (474.14s)
```
:+1:

**Comment by calmh** [comment]
So I know I'm annoying now but even I get confused by the two defers right next to each other in the intuitively wrong order. How about just deferring osutil.Rename instead which does this correctly out of the box?

**Comment by Zillode** [comment]
Good idea, much better now:)

**Comment by calmh** [comment]
@st-jenkins run integration tests, yo

**Comment by calmh** [comment]
Needs import statements, then merge. :)

**Comment by Zillode** [comment]
@st-jenkins run integration tests for linux and windows please

**Pull request merged**
