### PR TITLE
Add proxy support (fixes #271)

### LINKED ISSUE #271: Add support for proxy configuration
As far as I can tell, sync is done via TCP, so adding support for proxied connections should be on the table, both HTTP and SOCKS.

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Just because how easy it is.

Not tested at all though, as I have no proxy at hand, so someone from #271@juliohm1978 @s200999900 @pysiak @histrio @nottinhill @dboonz need to verify that it works before we merge this.

This does not use it for TCPPing, because we don't have access to the underlying dialer.

### CODE REVIEW

**Comment by calmh** [comment]
Neat!

> This does not use it for TCPPing, because we don't have access to the underlying dialer.

Does that mean no relaying from behind proxy?

**Comment by AudriusButkevicius** [comment]
No, relaying will work, but the latency for all relays will be 1H, unless we manage to connect to them not via the proxy.

**Comment by calmh** [comment]
Ah, I'd though we discarded relays where the ping failed, but no worries. As it happens I'll be behind a SOCKS proxy at work today, so can take this for a quick spin there as well maybe.

**Comment by AudriusButkevicius** [comment]
It takes `all_proxy=socks5://user:password@host:port` and `no_proxy=host1,host2,host` env vars.

**Comment by calmh** [comment]
Yep. Hopefully that'll even get set automatically when I configure my computer for proxying. If not, it's easy to do manually. I'm guessing Windows doesn't do this though? If this works nicely, perhaps there's another way to detect the necessary proxy setup on Windows.

**Comment by calmh** [comment]
No go on first attempt, looks like discovery does not use the proxy.

**Comment by AudriusButkevicius** [comment]
If you STTRACE=dialer, does it use the right thing for dialing discovery?

**Comment by calmh** [comment]
No, the discovery uses a bog standard dialer as far as I can tell. You probably need to override the dialer in the http clients that are constructed in discovery.NewGlobal

**Comment by AudriusButkevicius** [comment]
I think we should keep this as least intrusive as possible, not adding any ifs for checking if we are behind a proxy etc.

**Comment by calmh** [comment]
Ideally, yes. So we announce the proxy's address, no-one dies.

**Comment by AudriusButkevicius** [comment]
I won't be able to make a fix until later this evening, so hoepfully you'll still be around a socks5 proxy :dancer:

**Comment by calmh** [comment]
I'll be back in the locked datacenter with the proxy between ~03:00 and ~12:00 CET, should be able to fit in some quick testing then. :)

**Comment by dcarosone** [comment]
If you need a socks proxy for testing, ssh -D (plus something to block
direct access, like having the target listen on a private address)

**Comment by AudriusButkevicius** [comment]
This also should support $HTTP_PROXY apparently.

**Comment by calmh** [comment]
Almost, but not quite. It gets stuck dialing the proxy via the proxy dialer recursively. I thought the problem might be

 - setting both Dial and Proxy on the DefaultHTTPTransport, but removing either of those made no difference
 - changing the DefaultHTTPTransport at all (maybe proxy.Direct uses that internally), but removing that entirely made no difference

What I get is:

```
[7DDRT] 2015/10/14 10:46:00.242684 main.go:812: INFO: No automatic upgrades; v0.12.0-beta3+5-g5580cf1-dirty is not a release version.
[7DDRT] 2015/10/14 10:46:00.242811 usage_report.go:281: INFO: Starting usage reporting
[7DDRT] 2015/10/14 10:46:00.247960 logger.go:304: DEBUG: Dialing tcp address 10.24.8.191:8080 success, 192.168.11.3:58546 -> 10.24.8.191:8080
[7DDRT] 2015/10/14 10:46:00.248444 logger.go:304: DEBUG: Dialing tcp address 10.24.8.191:8080 success, 192.168.11.3:58547 -> 10.24.8.191:8080
[7DDRT] 2015/10/14 10:46:00.248792 logger.go:304: DEBUG: Dialing tcp address 10.24.8.191:8080 success, 192.168.11.3:58548 -> 10.24.8.191:8080
[7DDRT] 2015/10/14 10:46:00.249562 logger.go:304: DEBUG: Dialing tcp address 10.24.8.191:8080 success, 192.168.11.3:58549 -> 10.24.8.191:8080
[7DDRT] 2015/10/14 10:46:00.249894 logger.go:304: DEBUG: Dialing tcp address 10.24.8.191:8080 success, 192.168.11.3:58550 -> 10.24.8.191:8080
[7DDRT] 2015/10/14 10:46:00.250274 logger.go:304: DEBUG: Dialing tcp address 10.24.8.191:8080 success, 192.168.11.3:58551 -> 10.24.8.191:8080
```

(10.24.8.191 is the proxy, 192.168.11.3 is me)

**Comment by calmh** [comment]
I also *don't* get the expected "Proxy settings detected" info line, not sure why. No time to look closer atm :/

**Comment by AudriusButkevicius** [comment]
The line is hard to spot as its in the first large batch of messages.
Also, this does not look wrong, it seems you are just dialing multiple times?

**Comment by AudriusButkevicius** [comment]
Works for me:

image

**Comment by calmh** [comment]
But it has the proxy address in the destination field in the "Dialed" log lines, implying it uses the proxy to dial the proxy.

**Comment by AudriusButkevicius** [comment]
Maybe thats us contacting discovery via $HTTP_PROXY, via socks proxy? Are you sure that is not defined? I tested with ssh -D and that worked?

Also, worst case we should probably also fallback to the direct dialer, for things like locally discovered nodes.

**Comment by calmh** [comment]
So setting http_proxy=something and/or https_proxy=soemthing results in the above; no "Proxy settings detected", but discovery seems to work through the proxy. Regular dialing does not use the proxy. Looking at the code, it seems to expect all_proxy, and setting all_proxy=socks5://something actually works (where "something" is a SOCKS proxy). Setting all_proxy=http://my-http-proxy does nothing, or so it seems.

So it's a success for a SOCKS proxy at least.

**Comment by calmh** [comment]
GUI shows the proxy address as the device address, not sure if desired.

screen shot 2015-10-15 at 10 44 25

**Comment by calmh** [comment]
This is awesome! :dancers:

**Comment by AudriusButkevicius** [comment]
I said from the beginning that you need to use all_proxy not http_proxy. I'll fix the remote address issue, amd add fallback to non-proxy connections if proxy fails.

**Comment by calmh** [comment]
Right, I focused on the http proxy part because that's what I was behind. But I could break out from that with an ssh -D with an appropriate ProxyCommand, and then run syncthing on top of that. So BEP over TLS over SOCKS over SSH over "HTTP" over TCP :)

**Comment by AudriusButkevicius** [comment]
Falls back to direct dialing if the proxy is down, and returns the "right" remote address.

**Comment by calmh** [comment]
@st-jenkins run integration tests please

**Comment by calmh** [comment]
Jenkins test reporting seems to have changed after I upgraded it the other day. Will look into that.

**Comment by calmh** [comment]
```
2015/10/16 11:30:51 Supervisor connectionSvc: connectionSvc: Failed service '(connections.serviceFunc)(0x304a40)' (4.927683 failures of 5.000000), restarting: true, error: interface conversion: net.Conn is dialer.dialerConn, not *net.TCPConn, stacktrace: goroutine 58 [running]:
github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc82816b860, 0xaa9088e00000000)
	/Users/jb/src/github.com/thejerf/suture/suture.go:550 +0xaf
github.com/syncthing/syncthing/lib/connections.tcpDialer(0xc827028a00, 0xc8200a8f00, 0x3, 0x0, 0x0)
	/Users/jb/src/github.com/syncthing/syncthing/lib/connections/connections_tcp.go:47 +0x7f4
github.com/syncthing/syncthing/lib/connections.(*connectionSvc).connect(0xc823a9e1c0)
	/Users/jb/src/github.com/syncthing/syncthing/lib/connections/connections.go:313 +0x272a
github.com/syncthing/syncthing/lib/connections.(*connectionSvc).(github.com/syncthing/syncthing/lib/connections.connect)-fm()
	/Users/jb/src/github.com/syncthing/syncthing/lib/connections/connections.go:110 +0x20
github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0xc8240dd160)
	/Users/jb/src/github.com/syncthing/syncthing/lib/connections/connections.go:460 +0x19
github.com/thejerf/suture.(*Supervisor).runService.func1(0xc82816b860, 0x0, 0x1b6e6b8, 0xc8240dd160)
	/Users/jb/src/github.com/thejerf/suture/suture.go:556 +0x5e
created by github.com/thejerf/suture.(*Supervisor).runService
	/Users/jb/src/github.com/thejerf/suture/suture.go:559 +0x51
2015/10/16 11:30:51 Supervisor connectionSvc: Entering the backoff state.
```

**Comment by Linuturk** [comment]
Did this make it into the v0.12.x releases? I've tried setting the env variable `all_proxy` before running the syncthing daemon from the same terminal and I'm not seeing the `Proxy settings detected` line mentioned above.

Is that the right way to test this out or am I missing something? Is there documentation anywhere on how this is supposed to work?

Thanks for the work on this feature. Really appreciated.

**Comment by chucic** [comment]
@Linuturk according to https://forum.syncthing.net/t/syncthing-v0-12-0-beryllium-bedbug/6026 it's there. I didn't found any other info on it in http://docs.syncthing.net/index.html.

**Comment by Linuturk** [comment]
Now I feel silly because I left off the `export` piece. Seems to be working now. Thanks!

**Comment by rumpelsepp** [comment]
You can omit the export when you put the assignment into the same line :)

```
$ all_proxy=... syncthing
```

**Pull request merged**
