### PR TITLE
lib/connections: Try not to deadlock (fixes #2987)

### LINKED ISSUE #2987: lib/connections, lib/model: Deadlock on new connection when it tries to set the name
Since some recent change I think. lib/connections calls model.AddConnection with a lock held, AddConnection updates the config by setting the device name, that calls CommitConfiguration which calls into lib/connections where it tries to acquire the same lock again.

```
goroutine 28 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0x11d1dac0)
        /usr/local/go/src/runtime/sema.go:47 +0x24
sync.(*Mutex).Lock(0x11d1dabc)
        /usr/local/go/src/sync/mutex.go:83 +0x1fc
sync.(*RWMutex).Lock(0x11d1dabc)
        /usr/local/go/src/sync/rwmutex.go:83 +0x28
github.com/syncthing/syncthing/lib/connections.(*Service).CommitConfiguration(0x11d1da40, 0xd, 0x10df8400, 0x1, 0x4, 0x10d7b0e0, 0x2, 0x4, 0x1, 0x110adf70, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/connections/connections.go:481 +0x50
github.com/syncthing/syncthing/lib/config.(*Wrapper).replaceLocked(0x10d77760, 0xd, 0x10da0280, 0x1, 0x1, 0x114c83f0, 0x2, 0x2, 0x1, 0x110adf70, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/config/wrapper.go:158 +0x584
github.com/syncthing/syncthing/lib/config.(*Wrapper).SetDevice(0x10d77760, 0x59131419, 0x3350f81, 0x79b51e71, 0x8c0ca4c, 0x3acfa84c, 0x15a32e9f, 0xa767b41c, 0x74e36e68, 0x1142c150, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/config/wrapper.go:207 +0x258
github.com/syncthing/syncthing/lib/model.(*Model).AddConnection(0x10d86000, 0x76f27590, 0x12aca0c0, 0x76f276c8, 0x12aca060, 0x1, 0x1142c150, 0x9, 0x1142c160, 0x9, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:1046 +0xcf4
github.com/syncthing/syncthing/lib/connections.(*Service).handle(0x11d1da40)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/connections/connections.go:274 +0x16d4
github.com/syncthing/syncthing/lib/connections.(*Service).(github.com/syncthing/syncthing/lib/connections.handle)-fm()
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/connections/connections.go:138 +0x1c
github.com/syncthing/syncthing/lib/connections.serviceFunc.Serve(0x12a23470)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/connections/connections.go:644 +0x1c
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0x112c6990, 0x2, 0x76ef0e68, 0x12a23470)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/suture.go:556 +0x5c
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/suture.go:559 +0x44
```

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Cleans up a bunch of structs which don't really need to be there as well.

### Testing

None at all

### CODE REVIEW

**Comment by calmh** [comment]
Can't be any worse than existing. ;)
(LGTM)

**Comment by calmh** [comment]
@st-review merge, please

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as ea54525a33e4d59be1025d740da6c23c069913ea. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
