### PR TITLE
Simplify FileInfoTruncated

### PR DESCRIPTION
**Pull request by calmh**
Here's a different approach to simplifying the FileInfoTruncated stuff. It retains the type safety of the existing solution, while letting the truncated version contain the correct file size.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins run integration tests, please

**Comment by AudriusButkevicius** [comment]
I've cancelled the tests, as the code is broken until we sort out the flag business which is breaking the build.

**Comment by AudriusButkevicius** [comment]
Looks good, as well, though I am torn between the two versions.

**Comment by Zillode** [comment]
+1

**Comment by AudriusButkevicius** [comment]
@st-jenkins run integration tests please

**Comment by AudriusButkevicius** [comment]
@calmh is this good to merge from your POV?

**Comment by calmh** [comment]
Yeah

**Pull request merged**
