### PR TITLE
lib: Use bytes.Equal instead of bytes.Compare where possible

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Simpler, faster, cleaner.

Done by machine:

```
gofmt -w -l -r 'bytes.Compare(a, b) == 0 -> bytes.Equal(a,b)' lib/*/*.go
gofmt -w -l -r 'bytes.Compare(a, b) != 0 -> !bytes.Equal(a,b)' lib/*/*.go

```

### Testing

Can't fail?

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review wait until all checks pass then do your thing.

**Comment by st-review** [comment]
I'm sorry, @AudriusButkevicius. I'm afraid I don't know what you mean. I know how to `merge`, `squash`.

**Comment by calmh** [comment]
:D

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
OK, merged as f5f0e460166d1011947a2e91fca7fec367a4a99c. Thanks, @calmh!

**Pull request closed without merging**
