### PR TITLE
Don't leak sendIndexes on disconnect (fixes #2589)

### LINKED ISSUE #2589: Disconnects leak goroutines (sendIndexes)
I've been running SyncThing in a small (4 node) cluster. Total about 4000 files at 5...6GB disk.

On my VPS (which is one of the few with all 4 folder shares) I regularly see a slow memory leak when doing synchronization among clients and when doing scans. SyncThing starts at 40MB memory usage and soon finds itself in the 120MB range.  The VPS it's living on only has 256MB of RAM and I have other services (namely, httpd) competing for time/memory there. 

Top shows SyncThing at 20ish percent of my memory load

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
20492 indrora   20   0   60732  55796   8884 S  0.0 21.3   0:05.73 syncthing
```

This just goes up as SyncThing scans folders or synchronizes with devices. I use SyncThing on my phone to back up photos, and a few large photos can churn SyncThing into eating several tens-of-megs of RAM.

### PR DESCRIPTION
**Pull request by calmh**
Adds a Closed() method on protocol.Connection and clears up
wireformatConnection a little too.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I have a bigger rework of that in my temp index PR

**Comment by AudriusButkevicius** [comment]
The tests failed.

**Comment by calmh** [comment]
unborkd

**Comment by calmh** [comment]
This seems to have broken the tests so the protocol tests deadlock, sometimes... Weird. Can't look into it right now but will.

**Pull request merged**
