### PR TITLE
build, lib: Correct total test coverage calculation

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

High numbers are nice, but truthful ones are more useful.

### Testing

Lets see if this builds.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as a4ed50ca85e670a5f0ff064e220915f310ddb553. Thanks, @calmh!

**Comment by calmh** [comment]
This will, if I can hack it, result in st-review saying things like

---

This PR increases test coverage by 0.001 percentage points! Good work @AudriusButkevicius!

---

when it does change. With some suitable polite wording when the coverage goes down...

**Comment by calmh** [comment]
Hah. Made complicated by the fact that the test coverage varies randomly from run to run...

**Pull request closed without merging**
