### PR TITLE
gui: remove blank meta tags

### PR DESCRIPTION
**Pull request by lsmithx2**
remove blank meta tags

### Purpose

Remove blank meta tags in header.

### Testing

None needed

### Screenshots

N/A

### Documentation

Remove blank meta tags from header.

## Authorship

Your name and email will be added automatically to the AUTHORS file
based on the commit metadata.

### CODE REVIEW

**Comment by tomasz1986** [comment]
The empty tags are indeed not required in HTML5, but what's up with the jQuery update? As a matter of fact, adding the file like that doesn't actually do anything, because `jquery-2.2.2.js` is hard-coded in the HTML.

**Comment by lsmithx2** [comment]
> The empty tags are indeed not required in HTML5, but what's up with the jQuery update? As a matter of fact, adding the file like that doesn't actually do anything, because `jquery-2.2.2.js` is hard-coded in the HTML.

I was testing that in my branch I did not mean to commit that.

**Comment by tomasz1986** [comment]
> I was testing that in my branch I did not mean to commit that.

Please remove the file then, if it's not a problem for you 🙂. I'd also like to ask to change the PR title from `remove blank meta tags` to `gui: remove blank meta tags` to match the overall convention.

Other than that, everything looks fine to me, unless there's a plan to fill in the two tags with some actual useful information.

**Comment by lsmithx2** [comment]
> > I was testing that in my branch I did not mean to commit that.
> 
> Please remove the file then, if it's not a problem for you 🙂. I'd also like to ask to change the PR title from `remove blank meta tags` to `gui: remove blank meta tags` to match the overall convention.
> 
> Other than that, everything looks fine to me, unless there's a plan to fill the two tags with some actual useful information.

No problem I have completed these changes.

**Review by calmh — APPROVED** [review]

**Pull request merged**
