### PR TITLE
all: Even more boring linter fixes

### PR DESCRIPTION
**Pull request by calmh**
More of same, except there was an actual error checking bug in this one. :)

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
This is seriously non-sense. If you expect people to write code like this, I suspect we won't get anything done most of the time.

**Comment by calmh** [comment]
It would be nonsense if there weren't also actual bugs sprinkled among these things.

**Comment by calmh** [comment]
Honestly we can probably revert the underscores crap later. We'll get linter warnings on new code, but that's kinda fine as it's just a note that the error checking requires a though.

**Comment by calmh** [comment]
I removed the underscoryness again

**Pull request merged**
