### PR TITLE
gui: Display rescan button when out of sync and remove deprecated folder state

### PR DESCRIPTION
**Pull request by imsodin**
It should be possible to trigger a scan on an out of sync folder, i.e. in case a problem was resolved manually on disk. I reversed the condition from displaying rescan for some specific folder states to all states except unknown and paused.

The invalid parameter on the folder summary is deprecated as per comment in gui.go -> removed.

### CODE REVIEW

**Comment by calmh** [comment]
> all states except unknown and paused

Do we really want to allow rescan while syncing? That won't actually *work*, will it?

**Comment by imsodin** [comment]
It will schedule a blocking scan, i.e. the scan will happen after syncing finished - but that wasn't a conscious choice on my part, simply a mistake. State "scanning" was allowed too, which we don't want either I would say. I went back to explicitly allowing states, which is a bit less prone to such stupid mistakes.

**Comment by AudriusButkevicius** [comment]
Lgtm

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as ae760798e1d53c3a89dfb52dceccd534c475a397. Thanks, @imsodin!

**Pull request closed without merging**
