### PR TITLE
lib/model: Don't update ignore hash when pull fails

### PR DESCRIPTION
**Pull request by imsodin**
While reviewing the PR about pull scheduling on reconnect I realized that the ignores hash is incorrectly updated even if a pull fails. This means on a subsequent pull, ignored files aren't included anymore, which is relevant due to #4460, and should thus also be in v0.14.41.

### CODE REVIEW

**Comment by calmh** [comment]
Won't we have set the correct bits on all the ignored files as part of the pulling, even if some other files fail to pull for whatever reason?

**Comment by imsodin** [comment]
Yes, that case is fine, the problem is the other way round: If a file got un-ignored and fails to be pulled, it won't get queried again.

**Comment by calmh** [comment]
Ah

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 6cf01c1d30ad4d74ca4ecb3ccf34716cca9b93db. Thanks, @imsodin!

**Pull request closed without merging**
