### PR TITLE
All folder panels collapsed, fixes #1034

### LINKED ISSUE #1034: Keep all folder panels collapsed
What was the initial idea behind the first folder panel that is always expanded? Would it be ok to remove this property so that all folder panels are collapsed on startup?

### PR DESCRIPTION
**Pull request by krozycki**
All folder panels collapsed by default, icon with arrow shows on mouseover and the tooltip appears.

### CODE REVIEW

**Comment by calmh** [comment]
Can has screenshots? :)

**Comment by krozycki** [comment]
screenshot - 19 02 2015 - 14 19 54
screenshot - 19 02 2015 - 14 20 29
screenshot - 19 02 2015 - 14 20 46
screenshot - 19 02 2015 - 14 21 12

Hmm, there is no mouse pointer on the screenshots, two of them have it over the panel heading so there is an icon and the others don't.

**Comment by calmh** [comment]
Ah, right. This is somewhat into bikeshed territory (sorry), but how does it look if you instead replace the existing "disk" icon with a down arrow or so to indicate the possible expansion? I'm not sure I like the status text jumping to the left...

**Comment by uok** [comment]
please keep things tidy and just collapse all panels - no indicator, mouseover, tooltip necessary
I simply closed all panels and tested this with my parents (once a week computer users :smile: ), who have never used Syncthing and it took them ~1 second to figure out where to click to open the panel. And the other 99,999999% of the Syncthing community will also figure that out :wink:

**Comment by krozycki** [comment]
Changed to just collapsing all panels.

**Comment by uok** [comment]
Thanks! (if there are really complaints about this we can always change it back or come up with something better during a future GUI redesign)

**Comment by calmh** [comment]
Works for me. :+1:

**Pull request merged**
