### PR TITLE
lib/model: Some platforms do not support usage checks (fixes #4321)

### LINKED ISSUE #4321: syncthing v0.14.37-rc.2: folder error: failed to check available storage space
- what happened,

Upon startup syncthing pauses shares with the above error message which can also be found in the logs (one is attached). Resuming is not possible as they will get stopped again with the same error message. Storage space is plenty on this device and on the other nodes which are running the same version albeit on other Oses.

 - what you expected to happen instead, and

Normal starup.

 - any steps to reproduce the problem.

I am not sure whether this is easily reproducable or whether it is the specific version or OS combination. I am willing to debug this further with directions.

The log file has been edited so that keys and share names have been renamed/removed. Otherwise it is provided as is.

### Version Information

Syncthing Version: v0.14.37-rc.2
OS Version: OpenBSD 6.1-current
Browser Version: N/A

### Logfile

[NPNSQ] 18:51:53 INFO: syncthing v0.14.37-rc.2 "Dysprosium Dragonfly" (go1.9rc2 openbsd-amd64) teamcity@build.syncthing.net 2017-08-22 06:48:25 UTC
[NPNSQ] 18:51:53 INFO: My ID: xxxxxxxx
[NPNSQ] 18:51:54 INFO: Single thread SHA256 performance is 47 MB/s using minio/sha256-simd (41 MB/s using crypto/sha256).
[NPNSQ] 18:51:55 INFO: Hashing performance with weak hash is 40.15 MB/s
[NPNSQ] 18:51:55 INFO: Hashing performance without weak hash is 45.48 MB/s
[NPNSQ] 18:51:55 INFO: Weak hash enabled, as it has an acceptable performance impact.
[NPNSQ] 18:51:55 VERBOSE: Starting up (/home/ckeen/.config/syncthing)
[NPNSQ] 18:51:56 INFO: Starting deadlock detector with 20m0s timeout
[NPNSQ] 18:51:56 INFO: Ready to synchronize "foo" (readwrite)
[NPNSQ] 18:51:56 INFO: Ready to synchronize default (readwrite)
[NPNSQ] 18:51:56 INFO: Ready to synchronize bar (readwrite)
[NPNSQ] 18:51:56 WARNING: Stopping folder "foo" - failed to check available storage space
[NPNSQ] 18:51:56 INFO: Stopping folder "foo" due to error: failed to check available storage space
[NPNSQ] 18:51:56 INFO: Failed initial scan (rw) of "foo"
[NPNSQ] 18:51:56 VERBOSE: Folder "foo" is now error
[NPNSQ] 18:51:56 WARNING: Stopping folder default - failed to check available storage space
[NPNSQ] 18:51:56 INFO: Stopping folder default due to error: failed to check available storage space
[NPNSQ] 18:51:56 INFO: Failed initial scan (rw) of default
[NPNSQ] 18:51:56 VERBOSE: Folder "default" is now error
[NPNSQ] 18:51:56 WARNING: Stopping folder bar - failed to check available storage space
[NPNSQ] 18:51:56 INFO: Stopping folder bar due to error: failed to check available storage space
[NPNSQ] 18:51:56 INFO: Failed initial scan (rw) of bar
[NPNSQ] 18:51:56 VERBOSE: Folder "bar" is now error
[NPNSQ] 18:51:56 INFO: Send rate is unlimited, receive rate is unlimited
[NPNSQ] 18:51:56 INFO: Rate limits do not apply to LAN connections
[NPNSQ] 18:51:56 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=xxx
[NPNSQ] 18:51:56 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=xxx
[NPNSQ] 18:51:56 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=xxx
[NPNSQ] 18:51:56 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=xxx
[NPNSQ] 18:51:56 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=xxx
[NPNSQ] 18:51:56 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=xxx
[NPNSQ] 18:51:56 INFO: TCP listener (0.0.0.0:22000) starting
[NPNSQ] 18:51:56 VERBOSE: Discovered device XXX at [tcp://192.168.178.20:22000]
[NPNSQ] 18:51:56 INFO: GUI and API listening on 127.0.0.1:8384
[NPNSQ] 18:51:56 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[NPNSQ] 18:51:56 INFO: Device XXX is "baz" at [dynamic]
[NPNSQ] 18:51:56 INFO: Device XXX is "quux" at [dynamic]
[NPNSQ] 18:51:56 INFO: Device XXX is "localhost" at [dynamic]
[NPNSQ] 18:51:56 INFO: Device XXX is "bar" at [dynamic]
[NPNSQ] 18:51:56 INFO: Device XXX is "me" at [dynamic]
[NPNSQ] 18:51:56 INFO: Anonymous usage reporting is always enabled for candidate releases.
[NPNSQ] 18:51:56 INFO: Automatic upgrade is always enabled for candidate releases.
[NPNSQ] 18:51:56 VERBOSE: Startup complete
[NPNSQ] 18:51:56 INFO: Starting usage reporting
[NPNSQ] 18:51:57 INFO: Skipping pull of "foo" due to folder error: failed to check available storage space
[NPNSQ] 18:51:57 INFO: Skipping pull of bar due to folder error: failed to check available storage space
[NPNSQ] 18:51:57 INFO: Skipping pull of default due to folder error: failed to check available storage space
[NPNSQ] 18:52:07 INFO: Skipping pull of "foo" due to folder error: failed to check available storage space
[NPNSQ] 18:52:07 INFO: Joined relay relay://51.15.52.244:22067
[NPNSQ] 18:52:07 INFO: Skipping pull of default due to folder error: failed to check available storage space
[NPNSQ] 18:52:07 INFO: Skipping pull of bar due to folder error: failed to check available storage space
[NPNSQ] 18:52:07 INFO: Detected 0 NAT devices
[NPNSQ] 18:52:10 INFO: set tcp 192.168.178.24:46700->192.168.178.20:22000: protocol not available
[NPNSQ] 18:52:11 INFO: Established secure connection to XXX at 192.168.178.24:46700-192.168.178.20:22000 (tcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[NPNSQ] 18:52:11 INFO: Device XXX client is "syncthing v0.14.37-rc.2" named "quux"
[NPNSQ] 18:52:11 INFO: Skipping pull of bar due to folder error: failed to check available storage space
[NPNSQ] 18:52:11 INFO: Skipping pull of default due to folder error: failed to check available storage space
[NPNSQ] 18:52:11 INFO: Skipping pull of "foo" due to folder error: failed to check available storage space
[NPNSQ] 18:52:13 VERBOSE: Summary for folder "default" is map[globalFiles:3604 needDirectories:1136 inSyncFiles:0 needFiles:3604 sequence:10598 needSymlinks:1 localDirectories:0 localSymlinks:0 globalBytes:2002212482 localBytes:0 state:error globalDirectories:1136 inSyncBytes:0 version:10598 localFiles:0 needBytes:2002212482 localDeleted:0 error:failed to check available storage space globalSymlinks:1 needDeletes:0 globalDeleted:1552]
[NPNSQ] 18:52:13 VERBOSE: Completion for folder "default" on device XXX is 100%
[NPNSQ] 18:52:13 VERBOSE: Summary for folder "bar" is map[localSymlinks:0 localBytes:0 globalFiles:56 globalSymlinks:0 globalBytes:357916046 needBytes:357916046 state:error globalDirectories:4 needDirectories:4 sequence:104 needFiles:56 error:failed to check available storage space localDeleted:0 globalDeleted:16 needDeletes:0 localFiles:0 localDirectories:0 needSymlinks:0 inSyncBytes:0 inSyncFiles:0 version:104]
[NPNSQ] 18:52:13 VERBOSE: Completion for folder "bar" on device XXX is 100%
[NPNSQ] 18:52:13 VERBOSE: Summary for folder "m59k9-mvdrj" is map[globalBytes:14863233 globalDirectories:0 localDeleted:0 inSyncBytes:0 localBytes:0 localFiles:0 globalSymlinks:0 localSymlinks:0 version:47 needDeletes:0 globalDeleted:11 needSymlinks:0 globalFiles:1 needBytes:14863233 inSyncFiles:0 error:failed to check available storage space localDirectories:0 needDirectories:0 sequence:47 needFiles:1 state:error]
[NPNSQ] 18:52:13 VERBOSE: Completion for folder "m59k9-mvdrj" on device XXX is 100%
[NPNSQ] 18:52:16 VERBOSE: Listen address dynamic+https://relays.syncthing.net/endpoint resolution has changed: lan addresses: [relay://51.15.52.244:22067/?id=XXX&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=] wan addresses: [relay://51.15.52.244:22067/?id=XXX&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=]
[NPNSQ] 18:52:21 INFO: Skipping pull of "foo" due to folder error: failed to check available storage space
[NPNSQ] 18:52:21 INFO: Skipping pull of default due to folder error: failed to check available storage space
[NPNSQ] 18:52:21 INFO: Skipping pull of bar due to folder error: failed to check available storage space
[NPNSQ] 18:52:31 INFO: Skipping pull of "foo" due to folder error: failed to check available storage space
[NPNSQ] 18:52:31 INFO: Skipping pull of bar due to folder error: failed to check available storage space
[NPNSQ] 18:52:31 INFO: Skipping pull of default due to folder error: failed to check available storage space
[NPNSQ] 18:52:41 INFO: Skipping pull of default due to folder error: failed to check available storage space
[NPNSQ] 18:52:41 INFO: Skipping pull of "foo" due to folder error: failed to check available storage space
[NPNSQ] 18:52:41 INFO: Skipping pull of bar due to folder error: failed to check available storage space

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by calmh** [comment]
We should only look at the result if err == nil

**Comment by AudriusButkevicius** [comment]
That's already done in the lines below.

**Comment by calmh** [comment]
Only after it calculates stuff on `usage.Free` etc and `usage` might be nil (if it's a pointer type, I didn't look)

**Comment by st-review** [comment]
:ok_hand: Merged as a69ba18f62d13a12b8e8344ac37025e62e8d649d. Thanks, @AudriusButkevicius!

**Comment by AudriusButkevicius** [comment]
It's not a pointer, but it will be zero floats, which doesn't seem to panic.

**Comment by calmh** [comment]
No that's fine then, if slightly odd

**Pull request closed without merging**
