### PR TITLE
Display Local State Summary (All Folders)

### PR DESCRIPTION
**Pull request by fti7**
Simple State Summary of all local Folders

### CODE REVIEW

**Comment by Zillode** [comment]
:+1: 
Maybe use 'Total Local State' as a caption? Not sure, wait for confirmation before changing.
Also adding a screenshot is useful for this kind of prs.

screen shot 2015-06-19 at 22 52 05

**Comment by uok** [comment]
other ideas (easier to translate): "space used", "total size"

**Comment by fti7** [comment]
Or "Shared Data"? ;-) idk
I thought it would be good to have almost the same Caption as on the Folder Entries. So Users know from where this Value come from

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
Nice. I agree about "local state" not being an optimal label, but this should use the same as that's what we call it elsewhere. Perhaps we can reformulate that in the future.

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
(Merge conflict on index.html due to adding to authors, merging manually)

**Pull request merged**
