### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by marclaporte**

### CODE REVIEW

**Comment by calmh** [comment]
I'm a little torn on this one. The changes are valid as such, but the cost of fixing them is high (they'll need re-translating into 20 languages by at least 20 other people. Probably this should be refactored at some point so that a different key than the English string is used...

**Comment by calmh** [comment]
It could be a worthy endeavour to replace all original strings in the HTML source with more neutral keys and perform the same replacement on the lang-xx.json files. We could then bulk re-upload it into transifex to make it a seamless change for the translators and have more freedom in changing the English strings without breaking stuff.

**Comment by marclaporte** [comment]
Agreed.

I am not a fan of short system keys because the code becomes less readable. And it's nice to grep for an interface message.

In Tiki, we use full text messages as strings, but we have an English translation file, so this permits us to adjust visible results for a small number of strings, without breaking translations. And at every major release, a cleanup / swap can be made.

These typo fixes to the original do not invalidate the translations in reality. So even if I don't speak the twenty languages, I could fix the 20 translations, which is less work now, before we get to 100 :-)  Because of http://docs.transifex.com/faq/#what-happens-when-i-update-my-source-files, I guess I would add a new entry and copy the current translation.

Even if I didn't do so, translators would likely be suggested these translations by the translation memory: http://docs.transifex.com/guides/tm

If you are up for the bulk re-import, I would then review all the strings for spelling, grammar and consistency of terms (ex.: always use "folders" and not "directories"). Your call on how to proceed. This is very low priority and we can come back to it later. 

Thanks!

**Comment by marclaporte** [comment]
"Old translations are compared to the new strings. If there is a high-enough similarity between the old and new strings, Transifex doesn't delete the old string. Instead, it with update to a new version of it. As a result your Translation Memory will find the existing translations and presents them as suggestions in the Web Editor."
Source: http://docs.transifex.com/faq/index#what-happens-when-i-update-my-source-files

**Comment by calmh** [comment]
Still sounds to me like the old string will just be presented as a suggestion and still require manual handling, but this should be tested at some point.

**Comment by calmh** [comment]
(Unintentional close)

**Comment by calmh** [comment]
Merged

**Pull request closed without merging**
