### PR TITLE
Code formatting on README.md

### PR DESCRIPTION
**Pull request by halfninja**

### CODE REVIEW

**Comment by rumpelsepp** [comment]
**I would suggest to add even more information here, I have attached my thoughts below**

# Systemd Services

This directory contains configuration files for running syncthing under the **systemd** service manager on Linux both as either a system service or a user service.

## How to use the system instance 

Running synchting as a system service ensures that syncthing is run at startup even if the syncthing user has no active session.

1. Create the user who should run the service, or choose an existing one.
2. Copy the `syncthing@.service` files into the [load path of the system instance](http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20Load%20Path).
3. Enable and start the service. Append the syncthing user after the `@`: `systemctl enable syncthing@myuser.service` and `systemctl start syncthing@myuser.service`.

## How to use the user instance

Running synchting as a user service ensures that syncthing is run after the syncthing user has created a session. This could be used e.g. on a multiuser desktop computer when you want to avoid unnecessarly running syncthing instances.

1. Create the user who should run the service, or choose an existing one.
2. Copy the `syncthing@.service` files into the [load path of the user instance](http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20Load%20Path). To do this without root privileges you can use `~/.config/systemd/user/`.
3. Enable and start the service: `systemctl --user enable syncthing.service` and `systemctl --user start syncthing.service`.

To check if syncthing runs properly you can use the `status` subcommand: `systemctl status syncthing@myuser.service` alternatively `systemctl --user status syncthing.service`

## Using the journal

Systemd logs everything into the journal. You can easily acces syncthing log messages (`-e` lets the pager jump to the very end):

```
journalctl -e -u syncthing@myuser.service
journalctl -e --user-unit=syncthing
```

## Debugging

If you are asked on the bugtracker to start syncthing with specific environment variables it will not work the easy way. Systemd isolates each service and it cannot access global environment variables. The solution is to add this variables to the service file instead. Just use `systemctl edit syncthing@myuser.service` or `systemctl --user edit syncthing.service`. This will add a configuration file automatically and you can add service parameters like e.g. `Environment=STTRACE=model`.

**Comment by kozec** [comment]
Shouldn't this be part of _systemd_ documentation?

**Comment by rumpelsepp** [comment]
> Shouldn't this be part of systemd documentation?

Saw this in the stream, but now it seems to be gone? Anyway, I agree with you. But I think you can otherwise neglect this README completly. Currently there are too little information for "systemd noobs" who just want to start syncthing and who don't really know what is a "system" or a "user" instance.

**Comment by kozec** [comment]
Sorry, I was under impression that you are proposing change to main readme, not systemd specific one. I deleted my question as soon as I realized my mistake, but not fast enough :-D

**Comment by rumpelsepp** [comment]
> I deleted my question as soon as I realized my mistake, but not fast enough :-D

It is still in the rss stream on my dashboard. :D Seems to be a github issue.

**Comment by lunemec** [comment]
https://github.com/syncthing/syncthing/wiki/Autostart-syncthing
systemd section

**Pull request closed without merging**
