### PR TITLE
Tidy up the REST interface URLs (fixes #1593)

### LINKED ISSUE #1593: Tidy up the REST interface
The URL:s are somewhat of a mess and don't follow a pattern or system where we could. Take the time to rethink it and make a breaking change some time before v1.0.

### PR DESCRIPTION
**Pull request by calmh**
This is a proposal for discussion on changing the REST URL:s. It's been nagging on me for a while that they are a blob of randomness, where we could add some structure. Obviously this breaks everyone using the API, so probably it's something we should do *once* and in a major(minor)-version change...

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
LGTM

**Comment by calmh** [comment]
https://github.com/syncthing/syncthing/wiki/REST-Changes-in-v0.11

**Comment by canton7** [comment]
It's slightly evil that `/rest/version` - the resource you need in order to determine what API to use - changed ;) Otherwise, looks nice to me!

**Comment by kozec** [comment]
> It's slightly evil that /rest/version - the resource you need in order to determine what API to use - changed ;) Otherwise, looks nice to me!

I'd say that 404 from it means that you are using wrong one :p
But I do not intend to support older API, and do hope that's not expected...

**Comment by canton7** [comment]
It's true - I can work with a 404 :stuck_out_tongue_closed_eyes: 

I let Syncthing auto-upgrade, so I need to be able to handle that moment when 0.10.x upgrades to 0.11.0. It looks like you control Syncthing's version more tightly? If so, you don't have my problems...

**Comment by calmh** [comment]
Currently v0.10 doesn't actually auto-upgrade to v0.11. The user might still press the button though...

**Comment by AudriusButkevicius** [comment]
Should we just merge this?

**Pull request merged**
