### PR TITLE
lib/upnp: Fix port order

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

I've got the order wrong.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge this please

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by AudriusButkevicius** [comment]
@st-review merge this please

**Comment by st-review** [comment]
:ok_hand: Merged as 1c7af1a72e5ee1fefb501f10ddcfc49a0bda608c. Thanks, @AudriusButkevicius!

**Comment by st-review** [comment]
:no_entry: Merge failed:

```
$ git fetch -f origin refs/pull/2980/head:pr-2980
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   e61f424..1c7af1a  master     -> orig/master
$ git reset --hard
HEAD is now at 1c7af1a lib/upnp: Fix port order
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 1c7af1a lib/upnp: Fix port order
$ git clean -fxd
$ git merge --squash --no-commit pr-2980
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Comment by AudriusButkevicius** [comment]
Yeah, because I tricked you!

**Pull request closed without merging**
