### PR TITLE
Average bps

### PR DESCRIPTION
**Pull request by benshep**
Calculate average bps using a FIFO buffer instead of just basing it on the last two byte counts. Use this to show an esimate of the ETA for syncing folders.

### CODE REVIEW

**Comment by benshep** [comment]
Oops, sorry - that's more commits than I was expecting to see.

**Comment by calmh** [comment]
Better, I think, to do the calculation on the "server" side using the `EWMA` we have in use in other places and exposing it in the connection stats struct.

**Comment by benshep** [comment]
Hmm, OK. So you would replace AddInt64 in the countingReader and countingWriter objects with a byteCounter object? Seems sensible.

**Comment by calmh** [comment]
That sounds reasonable. Might need some scaffolding or moving a type or two or something, not sure, but it's an approach I would 👍 at this point

**Pull request closed without merging**
