### PR TITLE
Fix mobile responsive css

### PR DESCRIPTION
**Pull request by lkwg82**
### Purpose

This fixes the responsive design on phones. Broken menu at the top and left aligned list at the bottom.

### Testing

manual
### Screenshots

screenshot

### CODE REVIEW

**Comment by calmh** [comment]
I agree this needs fixing, but I'm not sure this is the best fix. :) In keeping in line with "hamburger" menus and so on, would it make sense to just drop the text (language name and "Actions") and keep the icons, thus making it fit on a single line? Or the logo could go - the user knows what they're looking it, probably.

The bottom meny is a matter of taste I guess - for me it looks cleaner left-aligned.

**Comment by lkwg82** [comment]
Reducing to icons sounds better.

Left aligned looks on mobile weird, with icons centered too. 

I'll make another iteration.

**Comment by lkwg82** [comment]
xs

**Comment by norgeous** [comment]
i think:
1. keep the branding as the full logo (with 'Syncthing' word)
2. get rid of the word 'English', so its just a globe with arrow (as @calmh previously said)
3. right align the globe and cog icons

**Comment by lkwg82** [comment]
agree with 2+3
1 needs to stay, else with iphone5 it gets to narrow

sync

**Comment by calmh** [comment]
This is a vast improvement and I'm sorely tempted to merge it as is, however;

screen shot 2016-04-01 at 07 45 31

(Language, Help, Settings)

screen shot 2016-04-01 at 07 46 18

(Settings, Help, Language)

Due to the float right I imagine. I don't particularly care which order it is, but we should not change it when resizing. :)

**Comment by norgeous** [comment]
CSS _is_ hard, but it's getting better for layouts... I used css' [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) on my last project and it was amazing. Way better than floats. @lkwg82 if you haven't used `flexbox` before, It might be worth considering as I believe it could solve some issues with the layout (maybe here, but especially elsewhere).

[Compatability](http://caniuse.com/#feat=flexbox) should be considered before adding any ```flexbox```. For me adding `-webkit-` and `-ms-` prefixes (and variants) was enough. Also, not too familiar with bootstrap, but it [supports](http://v4-alpha.getbootstrap.com/getting-started/flexbox/)?

I think just merge this as it for now (no `flexbox`), although I'm not in a position to comment =]

Does anyone know of a problem with using `flexbox`?

**Comment by lkwg82** [comment]
@calmh the resizing issue directs to some maybe problem, I'll turn another iteration.

@norgeous Sry, I'm not a css pro and it is always close to feel a pain. Please take this over in another PR. For your concerns, just test!

**Comment by calmh** [comment]
@lkwg82 Only blocker I see is the reordering of buttons between the two layouts, otherwise I'm happy. The resizing thing, the logo thing and the flexbox thing can all be left for our future selfs to sort out.

**Comment by lkwg82** [comment]
the reorder thing is because of floating left or right. I did this, because I dont know how to solve the situation that sth in the middle need to use the maximum space. The space between the logo and the icons.

Currently I can not solve this blocker. :|

**Comment by calmh** [comment]
Fair enough! I'll take to as is and we can touch it up as we go along.

**Pull request merged**
