### PR TITLE
all: Don't let Suture capture panics (fixes #4758)

### LINKED ISSUE #4758: Suture services should not survive panics
We use `suture.Service`s in a lot of places and I like the interface, and that we get restarts on error returns etc. I'm not fond of the fact that it transparently swallows panics.

For example, a `panic("bug: foo")` in the database layer that we expect should be loud and fatal currently goes silently unnoticed if it's called from a folder runner, as that is a suture.Service and it just gets automatically restarted. Apart from the obvious issues, this leaves us with deadlocks if the panic happened inside a lock that wasn't defer-unlocked. 

I suggest we add a `PanicsPanic` options to the package, and see if we can get it accepted upstream. If not, I can live with a fork (it's a very stable package, seldom updated).

### PR DESCRIPTION
**Pull request by calmh**
Fork with new option. Default behavior stays unchanged, because I'm lazy and don't want to rewrite all the tests in the forked package.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I think this should go back upstream?

**Comment by calmh** [comment]
It's counter to the philosophy of capturing all the things, so it's not welcome upstream.  I have an old issue on it there.

**Comment by AudriusButkevicius** [comment]
It didn't look like it was a hard no on the old issue, more like how about this, you saying sounds good and closing it.

**Comment by calmh** [comment]
Maybe I misremember. I’ll file a PR.

**Pull request merged**
