### PR TITLE
Git-ignore VIM swap files

### PR DESCRIPTION
**Pull request by cdhowie**
Tiny patch for `.gitignore` to prevent adding VIM swap files to the repo.  (This already happened once as I found when trying to edit a file, so this request also deletes that swap file from the repo.)

### CODE REVIEW

**Comment by jkufner** [comment]
Btw, what about (optionaly) honoring .gitignore files?

**Comment by cdhowie** [comment]
> It should be `.*.sw[ponmlkjihgfedcba]`

I'm interested in hitting the common case here, not necessarily all of them.

> Btw, what about (optionaly) honoring .gitignore files?

I have no idea what you mean by this.

**Comment by Ichimonji10** [comment]
Nack. I don't think that this patch is appropriate. Files that are generated by user-specific tools such as vim, emacs, eclipse, nano, or whatever should be ignored by user-specific configuratino files such as [`.gitconfig`](https://github.com/Ichimonji10/impedimenta/blob/master/useful_things/configs/gitconfig#L10-L11) and [`.gitignore_global`](https://github.com/Ichimonji10/impedimenta/blob/master/useful_things/configs/gitignore_global). The `.gitignore` file that ships with a project is best suited to ignoring files that are generated by the project itself, not by an individual user's tools.

**Comment by canton7** [comment]
There's `.git/info/exclude` for project-specific, non-tracked ignores, as well.

**Comment by jkufner** [comment]
Oh, I see... Yes, this should be in user's global configuration.

I thought that this is part of syncthing default configuration -- the
files to not sync. I missed the name of the file changed by this commit.

By "honoring .gitignore" I meant to respect .gitignore files, so for
example object files in compiled project would not be synced, saving
bandwidth on expendable files. On the other side, syncthing could not be
used to sync compiled project from powerful computer to small laptop
before continuing work on large project (and benefiting from partial
compilation). So this feature must be optional.

**Comment by Ichimonji10** [comment]
@canton7, thanks for the info. I had no idea that was possible.

**Comment by Ichimonji10** [comment]
Also, in case it is decided that this patch is approprate - what's with the binary `internal/model/.model.go.swp` file?

**Comment by cdhowie** [comment]
> IMO, I don't think that this patch is appropriate. Files generated by user-specific tools such as vim, emacs, eclipse, nano, sublime text or whatever should be ignored by user-specific configuration files ...

If that is the stance of the project then that is fine, though it conflicts with the presence of the `*.sublime*` pattern already being in the root `.gitignore`.

**Comment by cdhowie** [comment]
> Also, in case it is decided that this patch is approprate - what's with the binary `internal/model/.model.go.swp` file?

...

Quoting my own pull request:

> (This already happened once as I found when trying to edit a file, **so this request also deletes that swap file from the repo**.)

**Comment by Ichimonji10** [comment]
> Um... quoting my own pull request:
>> (This already happened once as I found when trying to edit a file, so this request also deletes that swap file from the repo.)

/me facepalms

> If that is the stance of the project then that is fine, though it conflicts with the presence of the *.sublime* pattern already being in the root .gitignore.

That is true. I would contend that its presence is also inappropriate.

**Comment by cdhowie** [comment]
Very well, I will close this request and open a new one to only remove the stray swap file.

**Comment by calmh** [comment]
Hello bikeshedders! :) You have a point though, I've removed the system and user specific ignores that snuck in over time.

**Pull request closed without merging**
