### PR TITLE
Connection refactor

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

1. Removes separate relay lists and relay clients/services, just makes it a listen address
2. Easier plugging-in of other transports
3. Allows "hot" disabling and enabling NAT services
4. Allows "hot" listen address changes
5. Changes listen address list with a preferable "default" value just like for discovery
6. Debounces global discovery announcements as external addresses change (which it might a lot upon starting)
7. Stops this whole "pick other peers relay by latency". This information is no longer available,
   but I don't think it matters as most of the time other peer only has one relay.
8. Rename ListenAddress to ListenAddresses, as well as in javascript land.
9. Stop serializing deprecated values to JSON

Funky bits:

1. The UI is still shit
2. It's now non-fatal not to have a listen address, or to have an invalid listen address (will probably just flag up as 0/1)

### Testing

So it starts, didn't try to connect to anyone yet, probably needs a review before I do.
Also, all the tests are failing, but haven't spent time trying to fix them since the code is not wrapped up yet.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
We need a create template for suture Serve() Stop() that we could reuse for every service we have that supports failures and restarts. Everytime I need to implement one, I end up doing it differently.

**Comment by calmh** [comment]
https://reviews.syncthing.net/cru/CR-12

**Comment by AudriusButkevicius** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
No clue why the main build is failing.

**Comment by AudriusButkevicius** [comment]
Punches through NAT

```
[BKD5O] 2016/04/25 21:37:34.786065 utp_listen.go:164: INFO: utp://0.0.0.0:22020 detected NAT type: Full cone NAT, external address: utp://46.XXX.XXX.62:60530
[BKD5O] 2016/04/25 21:37:52.687242 utp_listen.go:78: DEBUG: connect from 178.XXX.XXX.157:50963
[BKD5O] 2016/04/25 21:37:52.822262 service.go:222: INFO: Established secure connection to F72F5AO-37T2W7K-XXXXXX-ZDMWZF6-KR7SSHD-O6YQ7GM-CR2XWJG-UOTCTA5 at [::]:22020-178.XXX.XXX.157:50963 (UTP (Server))
```

**Comment by AudriusButkevicius** [comment]
There, UTP removed, only refactor. 
UTP will follow once this is merged I guess.

**Comment by calmh** [comment]
screen shot 2016-04-27 at 14 39 43

I think the two identical icons there looks ugly. Could you find another one for one of them, or merge the type info into the address line perhaps?

**Comment by canton7** [comment]
http://fortawesome.github.io/Font-Awesome/icon/plug/ :smile:

**Comment by calmh** [comment]
When running, at least with the configs in test/h1 and test/h2, this runs a tight loop in the connection service using 100% CPU. Profile: https://nym.se/t/pprof001.svg

**Comment by AudriusButkevicius** [comment]
Addressed everything I think.

**Comment by AudriusButkevicius** [comment]
Right, hours later, I think I addressed everything :D

**Comment by calmh** [comment]
Needs some love to be mergeable into master again

```
jb@syno:~/s/g/s/syncthing $ git merge pr-2982
Removing lib/relay/relay.go
Removing lib/relay/debug.go
Auto-merging lib/model/model.go
Removing lib/model/connection.go
Removing lib/connections/connections_tcp.go
CONFLICT (modify/delete): lib/connections/connections.go deleted in pr-2982 and modified in HEAD. Version HEAD of lib/connections/connections.go left in tree.
Removing cmd/syncthing/mocked_relay_test.go
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 674fc566bb1bb8a7223ac242151594c18f9079e2. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
