### PR TITLE
Don't check interface flags on Windows

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Fixes UPnP failures on Windows.

### CODE REVIEW

**Comment by calmh** [comment]
Can this result in weird errors from other parts of the code (in the style of "netlink: rib: blah blah whatever") that we should suppress equally?

**Comment by AudriusButkevicius** [comment]
Potentially, but that's not as bad as no upnp

**Comment by tjldtf** [comment]
With the latest version 0.11.6, I still get "No UPnP device detected".

**Comment by AudriusButkevicius** [comment]
Please provide the logs with STTRACE=upnp environment variable set.

**Comment by tjldtf** [comment]
The log file is

[YLOIO] 2015/05/25 15:18:47.323643 main.go:466: INFO: syncthing v0.11.6 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-05-23 23:58:46 UTC
[YLOIO] 2015/05/25 15:18:47.324643 main.go:467: INFO: My ID: ...
[YLOIO] 2015/05/25 15:18:47.324643 main.go:738: INFO: Database block cache capacity 65536 KiB
[YLOIO] 2015/05/25 15:18:47.337644 main.go:793: INFO: Starting web GUI on http://127.0.0.1:8384/
[YLOIO] 2015/05/25 15:18:47.640661 main.go:868: INFO: Starting local discovery announcements
[YLOIO] 2015/05/25 15:18:47.645661 discover.go:133: INFO: Local discovery over IPv6 unavailable
[YLOIO] 2015/05/25 15:18:47.645661 main.go:873: INFO: Starting global discovery announcements
[YLOIO] 2015/05/25 15:18:47.647662 main.go:646: OK: Ready to synchronize default (read-write)
[YLOIO] 2015/05/25 15:18:47.647662 main.go:662: INFO: Device ... is "yyy" at [dynamic]
[YLOIO] 2015/05/25 15:18:47.647662 main.go:662: INFO: Device ... is "xxx" at [dynamic]
[YLOIO] 2015/05/25 15:18:47.650662 upnp.go:171: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {6353A798-2F58-4C3C-943D-20961D5425AC}
[YLOIO] 2015/05/25 15:18:47.650662 upnp.go:171: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {F1129CA2-6C1B-4766-875A-D6CE26830666}
[YLOIO] 2015/05/25 15:18:47.650662 rwfolder.go:275: INFO: Completed initial scan (rw) of folder default
[YLOIO] 2015/05/25 15:18:47.650662 upnp.go:171: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {0D64FE81-9B56-4EE3-A655-17375AA283AD}
[YLOIO] 2015/05/25 15:18:47.651662 upnp.go:171: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {6353A798-2F58-4C3C-943D-20961D5425AC}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:190: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {F1129CA2-6C1B-4766-875A-D6CE26830666}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:171: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {F1129CA2-6C1B-4766-875A-D6CE26830666}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:190: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {6353A798-2F58-4C3C-943D-20961D5425AC}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:200: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {6353A798-2F58-4C3C-943D-20961D5425AC}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:200: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {F1129CA2-6C1B-4766-875A-D6CE26830666}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:171: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {0D64FE81-9B56-4EE3-A655-17375AA283AD}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:190: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {0D64FE81-9B56-4EE3-A655-17375AA283AD}
[YLOIO] 2015/05/25 15:18:47.654662 upnp.go:200: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {0D64FE81-9B56-4EE3-A655-17375AA283AD}
[YLOIO] 2015/05/25 15:18:47.655662 upnp.go:190: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {6353A798-2F58-4C3C-943D-20961D5425AC}
[YLOIO] 2015/05/25 15:18:47.656662 upnp.go:200: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {6353A798-2F58-4C3C-943D-20961D5425AC}
[YLOIO] 2015/05/25 15:18:47.657662 upnp.go:190: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {F1129CA2-6C1B-4766-875A-D6CE26830666}
[YLOIO] 2015/05/25 15:18:47.657662 upnp.go:190: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {0D64FE81-9B56-4EE3-A655-17375AA283AD}
[YLOIO] 2015/05/25 15:18:47.657662 upnp.go:200: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {F1129CA2-6C1B-4766-875A-D6CE26830666}
[YLOIO] 2015/05/25 15:18:47.657662 upnp.go:200: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {0D64FE81-9B56-4EE3-A655-17375AA283AD}
[YLOIO] 2015/05/25 15:18:57.655234 upnp.go:221: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {6353A798-2F58-4C3C-943D-20961D5425AC} finished.
[YLOIO] 2015/05/25 15:18:57.655234 upnp.go:221: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {0D64FE81-9B56-4EE3-A655-17375AA283AD} finished.
[YLOIO] 2015/05/25 15:18:57.655234 upnp.go:221: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {F1129CA2-6C1B-4766-875A-D6CE26830666} finished.
[YLOIO] 2015/05/25 15:18:57.656234 upnp.go:221: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on {6353A798-2F58-4C3C-943D-20961D5425AC} finished.
[YLOIO] 2015/05/25 15:18:57.658234 upnp.go:221: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {F1129CA2-6C1B-4766-875A-D6CE26830666} finished.
[YLOIO] 2015/05/25 15:18:57.658234 upnp.go:221: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on {0D64FE81-9B56-4EE3-A655-17375AA283AD} finished.
[YLOIO] 2015/05/25 15:18:57.658234 upnpsvc.go:46: INFO: No UPnP device detected

**Comment by AudriusButkevicius** [comment]
It seems that there genuinely is no UPnP device on the network.

**Comment by tjldtf** [comment]
Thanks, I tested now with two devices in the same subnet watching with Wireshark, filtering for udp.port==1900 and the ip address of the other device. I attached the output of Wireshark when I start syncthing on the other device.
screen shot

**Comment by AudriusButkevicius** [comment]
This is the outgoing request, you should filter source port 1900 too, to see if any responses come back.

**Comment by tjldtf** [comment]
Thanks, I filtered for udp.port==1900 and the ip.addr of both devices. First starting syncthing on the device on which Whireshark is running and then start it on the other device. Beside above package of both devices, packages from other device arrives:
screenshot

**Comment by AudriusButkevicius** [comment]
Sorry, what are we debugging?
I am talking about UPnP, not local discovery, local discovery does not use SSDP, hence not sure why you are starting stuff on two devices.
Also, this response does not seem to be related to UPnP, the response should come from Src port 1900.

**Comment by tjldtf** [comment]
Ok, I've two devices on a subnet running syncthing and on one of them Whireshark filtering for udp.port==1900 and the ip addresses of these devices. The only packages Whireshark shows are these two I posted. If I misunderstand it completely, can you please give me some advice? Thank you in advance.

**Comment by tjldtf** [comment]
I filtered now for udp.srcport==1900 || udp.dstport==1900, but the result remains the same.

**Comment by AudriusButkevicius** [comment]
Well, your router is not responding to UPnP requests it seems then.

**Comment by tjldtf** [comment]
Mmh, I downloaded "UPnP Tester" and run it. It detects some devices.

**Comment by AudriusButkevicius** [comment]
Sorry, I'll have to get home to get the sample response we are looking for.
You can probably capture it using wireshark with src port 1900...

**Comment by tjldtf** [comment]
Thanks so far for your help. I've seen and read the issue "Another "No UPnP device detected" #1873" which seems to be the same. Both devices here are W7. I'll try to find out more.

**Comment by AudriusButkevicius** [comment]
Yeah let's keep the discussion there.

**Pull request merged**
