### PR TITLE
lib/model: Incremental block stats usage reporting

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
...

### CODE REVIEW

**Comment by imsodin** [comment]
What is the plan to account for the difference if the folder was restarted since the last report or not?
I don't know exactly what you do when analyzing the data, but you could record the folder start time/block stat reset time to get information about the duration in which this data was accumulated.

**Comment by AudriusButkevicius** [comment]
Probably the stats need to live somewhere outside of the folder, and the sharedPullerState should just increment some global.

**Comment by calmh** [comment]
Since we only care about the ratio between the numbers I don't think it's a big deal. This is probably sane anyway, we'll get less but fresher data and if we want more aggregation we can do it over several days server side.

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by imsodin** [comment]
Sure, for the important metrics this makes sense. I was bringing this up because Audrius already added this nice new "Totals to date" statistics, which is obviously not very important, but flashy, and this particular metric will be hampered by this. So I guess lgtm from my side unless @AudriusButkevicius rather wants to implement his "outside of folder" proposal?

**Comment by AudriusButkevicius** [comment]
Moved the stats to the global variable.

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 386cb274bdd3bbf53662420c0eebdd16a5ee9abc. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
