### PR TITLE
lib/upnp: Each service is it's own NAT device

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Don't merge this yet.

### CODE REVIEW

**Comment by calmh** [comment]
screen shot 2017-12-30 at 19 54 49

I love it already

**Comment by AudriusButkevicius** [comment]
Good to be merged now.

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as c7f136c2b8400fc2e972a9be52d44db9452cf717. Thanks, @AudriusButkevicius!

**Comment by calmh** [comment]
*its own

ah well :)

**Comment by calmh** [comment]
Should've had a bug ticket too for the release notes. Never mind.

**Comment by kewlfft** [comment]
Very well done thanks for this smart solution, that's fixing the issue with the BTHub router (British Telecom router)  which has 2 IGD services PPP and IP. The previous implementation was failing and creating 10*NumberOfNodes unused port mappings.

**Pull request closed without merging**
