### PR TITLE
lib/beacon: Check interface flags

### PR DESCRIPTION
**Pull request by bt90**
### Purpose

Check if the interface allows to receive multicast traffic.

## Authorship

Your name and email will be added automatically to the AUTHORS file
based on the commit metadata.

### CODE REVIEW

**Comment by calmh** [comment]
What advantages does this bring? Might it have disadvantages?

**Comment by calmh** [comment]
Does it fail to do so? What if the interface is down when we do this, but comes up a minute later?

**Comment by bt90** [comment]
I'll test tonight but the join should result in an error as it can't send the MLD message.

The interesting thing is that interface discovery and joining happens outside the `for { }` block:

https://github.com/syncthing/syncthing/blob/541572781b1b089ad7fb5cac124858166410d5c7/lib/beacon/multicast.go#L126-L164

The broadcast code is different in that regard. I'm focusing on the writer as broadcast listening handles interface and address changes transparently:

https://github.com/syncthing/syncthing/blob/541572781b1b089ad7fb5cac124858166410d5c7/lib/beacon/broadcast.go#L26-L71

**Comment by bt90** [comment]
Joining a group doesn't throw an error: https://go.dev/play/p/qwdjdSrU7WN

Note that the playground doesn't even provide an IPv6 address for its loopback interface. Maybe we should move at least the `JoinGroup` calls into the loop?

I need to investigate further using Wireshark but my suspicion is that `JoinGroup` sends the MLD message and the our multicast listener won't rejoin after network interface changes later on.

**Pull request closed without merging**
