### PR TITLE
Clarify and correct handling of existing files/directories when pulling

### PR DESCRIPTION
**Pull request by calmh**
This fixes a corner case I discovered in the symlink branch, where we
unexpectedly succeed in "replacing" an entire non-empty directory tree
with a file or symlink. This happens when archiving is in use, as we
then just move the entire tree away into the archive. This is wrong as
we should just archive files and fail on non-empty dirs in all cases.

New handling first checks what the (old) thing is, and if it's a
directory or symlink just does the delete, otherwise does conflict
handling or archiving as appropriate.

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins run integration tests please

**Comment by Zillode** [comment]
& windows

**Comment by calmh** [comment]
@st-jenkins test this please

**Comment by calmh** [comment]
@st-jenkins run integration tests, for windows and stuff

**Comment by Zillode** [comment]
:+1:

**Comment by Zillode** [comment]
This fixes https://github.com/Zillode/syncthing/commit/32df24146a1927dd07010f5bda09c813430f7f89 ?

**Comment by calmh** [comment]
Any complaints on this one?

**Pull request merged**
