### PR TITLE
all: Dead code cleanup

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
### Purpose

Remove dead code

### Testing

Builds

### CODE REVIEW

**Comment by calmh** [comment]
No it doesnt

**Comment by AudriusButkevicius** [comment]
2nd attempt.

**Comment by calmh** [comment]
@st-review merge this please

**Comment by st-review** [comment]
OK, merged as 2eb8a9ef5676f745fbac9dca45ee86f7b389e37f. Thanks, @AudriusButkevicius!

**Pull request closed without merging**
