### PR TITLE
added documentation key to syncthing-resume.service

### PR DESCRIPTION
**Pull request by aviau**
this fixes lintian warning:
```
systemd-service-file-missing-documentation-key lib/systemd/system/syncthing-resume.service
```

### CODE REVIEW

**Comment by lkwg82** [comment]
please add a line with your email in the AUTHORS file

**Comment by aviau** [comment]
@lkwg82 done

**Comment by AudriusButkevicius** [comment]
@rumpelsepp I have no idea if this is correct. Mind confirming?

**Comment by rumpelsepp** [comment]
@st-review Merge this please.

**Comment by st-review** [comment]
@rumpelsepp: Merge failed:

```
$ git fetch -f origin refs/pull/3109/head:pr-3109
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   ee94d53..cd05282  master     -> orig/master
$ git reset --hard
HEAD is now at cd05282 lib/connection: Remove unused functions
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at cd05282 lib/connection: Remove unused functions
$ git clean -fxd
Skipping repository syncthing/syncthing
Skipping repository syncthing/syncthing-android
Skipping repository syncthing/docs
Skipping repository syncthing/discosrv
Skipping repository syncthing/syncthing-gtk
Skipping repository syncthing/syncthing-inotify
$ git merge --squash --no-commit pr-3109
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
******************************************************
* Commit message does not match the expected format: *
*                                                    *
*   some/tag: A longer description (fixes #1234)     *
*                                                    *
******************************************************

```

**Comment by rumpelsepp** [comment]
@st-review Merge this please.

etc/linux-systemd: Add documentation key to syncthing-resume.service

**Comment by st-review** [comment]
@rumpelsepp: Merge failed:

```
$ git fetch -f origin refs/pull/3109/head:pr-3109
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at cd05282 lib/connection: Remove unused functions
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at cd05282 lib/connection: Remove unused functions
$ git clean -fxd
Skipping repository syncthing/syncthing
Skipping repository syncthing/syncthing-android
Skipping repository syncthing/docs
Skipping repository syncthing/discosrv
Skipping repository syncthing/syncthing-gtk
Skipping repository syncthing/syncthing-inotify
$ git merge --squash --no-commit pr-3109
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
******************************************************
* Commit message does not match the expected format: *
*                                                    *
*   some/tag: A longer description (fixes #1234)     *
*                                                    *
******************************************************

```

**Comment by rumpelsepp** [comment]
Holy cow, what am I doing wrong? A `(fixes #FOO)' thing doesn't make sense here...

**Comment by AudriusButkevicius** [comment]
@st-review merge

etc: Add documentation key to syncthing-resume.service

**Comment by st-review** [comment]
:ok_hand: Merged as 73ae87fad1678bc84eeeb7366751e537958ad1e7. Thanks, @aviau!

**Comment by rumpelsepp** [comment]
Fail.

**Comment by AudriusButkevicius** [comment]
It doesn't like dashes I guess.

**Pull request closed without merging**
