### PR TITLE
lib/config: Bump config version to 14

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Because one part of this was taken already in v0.12.24 as v13

### CODE REVIEW

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@AudriusButkevicius you suck at reviewing about as much as suck at writing code

**Comment by AudriusButkevicius** [comment]
The screen is too small for this triviallity, and the bot is the clever one this time.

**Comment by calmh** [comment]
Oh for fucks sake, clever to the point that I can't even :D

**Comment by AudriusButkevicius** [comment]
Yeah, not having xunit output pisses me off too

**Comment by calmh** [comment]
It's actually there, if you click through to details a few times; https://build.syncthing.net/job/syncthing-pr/2075/testReport/

**Comment by calmh** [comment]
@st-review merge later

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 5d2414dfa92cdcbcb55acb8b5d238482af964ec8. Thanks, @calmh!

**Comment by alex2108** [comment]
If I understand this correctly this will not result in a correct config for users of beta-4 as that already has config version 13 (actually the previous PR resulted in that I think...)

**Comment by calmh** [comment]
Correct. That's a bit unfortunate but has been the case in essentially all betas - as we change the migration steps along the way, weird things happen for those that are already half converted in the wrong way.

**Pull request closed without merging**
