### PR TITLE
Replace reflect with messagediff (fixes #2159)

### LINKED ISSUE #2159: Consider changing test struct diffing tool
Looks cool: https://github.com/d4l3k/messagediff

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
godep can't vendor test dependencies.

### CODE REVIEW

**Comment by calmh** [comment]
We need to handle that somehow though. Perhaps add a `go get -t -d ./...` before the build step; this then requires internet access when building though. I've been thinking of ways to improve the whole dependencies situation, as it's a a bit annoying currently...

**Comment by calmh** [comment]
I've been considering changing the build process to use gb (getgb.io), which would allow us to simply vendor the required test stuff and so on.

**Comment by calmh** [comment]
Do you want to finish this one off? We could tweak the vendoring mechanism to be more manual - just copy in the vendored packages instead of using godeps, or using some other tool.

**Comment by AudriusButkevicius** [comment]
We should move to the normal go vendoring mechanism perfhaps.

**Comment by calmh** [comment]
We could do that, yes. It would be cleaner, and it would mean you need to build with Go 1.5+ to get our dependencies, but that's sort of fine. And there are some tools around to manage the vendor directory fairly cleanly.

**Comment by AudriusButkevicius** [comment]
Rebased, plus fixed some broken tests on Windows.

**Comment by calmh** [comment]
@st-jenkins retest this please, are you asleep?

**Comment by calmh** [comment]
@st-review merge it!

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2213/head:pr-2213
$ git fetch -f origin master:orig/master
From github.com:syncthing/syncthing
   b8c72ad..dd9a4e0  master     -> orig/master
   b8c72ad..dd9a4e0  master     -> origin/master
$ git reset --hard
HEAD is now at 57b5da8 README.md: Spelling
$ git checkout master
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
$ git reset --hard orig/master
HEAD is now at dd9a4e0 README.md: Spelling
$ git clean -fxd
$ git merge --squash --no-commit pr-2213
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
[master fde026a] Add deps
 Author: Audrius Butkevicius <audrius.butkevicius@gmail.com>
 12 files changed, 641 insertions(+), 51 deletions(-)
 create mode 100644 vendor/github.com/d4l3k/messagediff/LICENSE
 create mode 100644 vendor/github.com/d4l3k/messagediff/README.md
 create mode 100644 vendor/github.com/d4l3k/messagediff/bypass.go
 create mode 100644 vendor/github.com/d4l3k/messagediff/bypasssafe.go
 create mode 100644 vendor/github.com/d4l3k/messagediff/messagediff.go
 create mode 100644 vendor/github.com/d4l3k/messagediff/messagediff_test.go
$ git rev-parse HEAD
fde026a1818a01e8100312822db780b49e23fed3
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 3 of 3 required status checks are expected        
To git@github.com:syncthing/syncthing.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:syncthing/syncthing.git'

```

**Comment by calmh** [comment]
@st-review merge it!

**Comment by st-review** [comment]
OK, merged as a8ffde6f21e04047ef87741421370323c86427c5.

**Comment by calmh** [comment]
So st-review couldn't push despite the tests passing, as what it pushes has a different SHA1 and thus hasn't been tested. I made the bot owner so it can do so anyway. I also see it took the *last* commit message instead of the *first* as it was supposed to and didn't close the PR for some reason. Investigating, sorry about the crappage :D

**Comment by calmh** [comment]
At, it was already closed before.

**Comment by calmh** [comment]
It should now correctly find and use the first commit...

**Pull request closed without merging**
