### PR TITLE
lib/versioner: Hack to make test coverage stable from run to run

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Sometimes clean would run, sometimes not.

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
@calmh: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
@st-review retest this please, that looks very spurious

**Comment by st-review** [comment]
I'm sorry, @calmh. I'm afraid I don't know what you mean. I know how to `don't`, `lgtm`, `merge`, `prevent`, `squash`, `stop`.

**Comment by calmh** [comment]
I mean Jenkins... but it understood

**Comment by calmh** [comment]
@st-review merge it nao

**Comment by st-review** [comment]
:ok_hand: Merged as dcbf68e104928235eb90cd3d6f955036cc7c0126. Thanks, @calmh!

**Pull request closed without merging**
