### PR TITLE
Added select ID text on click to gui

### PR DESCRIPTION
**Pull request by brgmnn**
I added an angular directive to select the entire ID when clicking in the div in the "Show ID" modal drop down. Seems like a useful (if small) usability feature.

I wasn't sure if I should commit the `internal/auto/gui.files.go` file but as it's in the repo I thought I should include it.

### CODE REVIEW

**Comment by calmh** [comment]
:+1: LGTM

**Comment by calmh** [comment]
@st-jenkins add to white list

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
Do you have an actual email address for the AUTHORS file?

**Comment by brgmnn** [comment]
I have amended my pull request to include myself in the AUTHORS, NICK and GUI code with a contact email as well as the Github no reply email address (so I don't have to switch emails across git repos). Hopefully I've amended all the right places!

**Comment by calmh** [comment]
:+1:

**Pull request merged**
