### PR TITLE
Lots of tiny changes for Dutch language.

### PR DESCRIPTION
**Pull request by erikvanoosten**
### Purpose

For Dutch translation: corrected spelling mistakes, more consistent use of the word 'scan', simplified some translations, use same punctuations as in English (e.g. trailing spaces ` ` or period `.`).

### Testing

None at all.

### Documentation

Documentation does not seem to be available in Dutch, so no changes.

### Authorship

No contribution is needed. If you insist, my name is 'Erik van Oosten' (lower case `v` please).

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Read the readme-first file in the language directory

**Comment by erikvanoosten** [comment]
Sorry I didn't see that one.
Anyway, I looked at the transifex stuff and noticed that its useless. There are really good suggestions there that are a year old and were not picked up.

**Comment by calmh** [comment]
@erikvanoosten it should only be a matter of signing up and editing the phrases, is it not?

**Comment by calmh** [comment]
Ah, it might be that the phrases are "reviewed" and thus only editable by "coordinators". That's a really annoying part of transifex, I should set up a script to auto-upgrade everyone to coordinator daily...

**Comment by erikvanoosten** [comment]
That would be really nice. Thanks!

**Comment by calmh** [comment]
I've scripted something to promote everyone to coordinators. The Transifex API is really ... 😱 though

**Pull request closed without merging**
