### PR TITLE
gui: resurrect old dark theme as black theme

### PR DESCRIPTION
**Pull request by wweich**
### Purpose

Add a new theme "black" which is a copy of the old dark theme before the "lightening".

As suggested by @AudriusButkevicius in syncthing/syncthing-android#764.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@calmh I suggest we do this as this is causing too much noise

**Comment by calmh** [comment]
Sure whatever

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by AudriusButkevicius** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@AudriusButkevicius: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by st-review** [comment]
:ok_hand: Merged as 81248c3f56acf77e52bd18b2175eccd1f80cf2d9. Thanks, @wweich!

**Pull request closed without merging**
