### PR TITLE
Show help link, add icons, tweak icon spacing

### PR DESCRIPTION
**Pull request by calmh**
screen shot 2015-05-27 at 21 54 24

That's a link to http://docs.syncthing.net/intro/gui.html, which needs some sprucing up but still answers some common questions... Open for suggestions about calling the menu "Tools", but we need to call it something if there's a "Help" button next to it.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Options?

**Comment by calmh** [comment]
Maybe. Shutdown and stuff isn't really an Option. Hardly a Tool either, but meh... If we didn't already have the logo in the upper left I'd just stick "Syncthing" there or something and call it the app menu or whatever.

**Comment by AudriusButkevicius** [comment]
Well a shutdown is an optional action someone can invoke? Tools makes me expect a merge tool, version restore tool, etc.

**Comment by Zillode** [comment]
menu? This is how its called in firefox. However, ff shows just the icon and not the text unless you hover over it

**Comment by AudriusButkevicius** [comment]
Yeah menu works too

**Comment by calmh** [comment]
A menu called "menu" right beside another menu doesn't sit well with me. `Operations` then?

**Comment by AudriusButkevicius** [comment]
Or we could rename Settings option to Options and then Have Settings -> Options :dancers:

**Comment by calmh** [comment]
But Shutdown still isn't a Setting. `Actions`?

I'm hitting Merge soon inb4 further bikeshed :expressionless:

**Comment by AudriusButkevicius** [comment]
Let's go with actions

**Comment by calmh** [comment]
Merging with `Actions`

**Pull request merged**
