### PR TITLE
cmd/syncthing: Accept ISO-8859-1 and UTF-8 in HTTP BasicAuth header (…

### PR DESCRIPTION
**Pull request by calmh**
### Purpose

Decrease user pain by trying to interpret given username and password as both UTF-8 and ISO-8859-1 as this seems to be the most common variants. 

### Testing

Actually verified by a unit test.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@st-review merge

**Comment by st-review** [comment]
:no_good: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
Huh?

**Comment by calmh** [comment]
@st-jenkins retest this please

**Comment by calmh** [comment]
@st-review merge this as well, Audrius OK'd it

**Comment by st-review** [comment]
:ok_hand: Merged as 893cc025f985a698888ec90eb5adf68570af5b81. Thanks, @calmh!

**Pull request closed without merging**
